use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "extend_native_false_0",
        steps: 54,
        effects: &[("snapshot", 28), ("done", 52)],
        holes: &[],
    },
    Baseline {
        name: "extend_proxy_false_0",
        steps: 72,
        effects: &[("iter", 14), ("snapshot", 46), ("done", 70)],
        holes: &[],
    },
    Baseline {
        name: "extend_generic_false_0",
        steps: 59,
        effects: &[("snapshot", 33), ("done", 57)],
        holes: &[],
    },
    Baseline {
        name: "extend_dynamic_false_0",
        steps: 79,
        effects: &[("iter", 20), ("snapshot", 53), ("done", 77)],
        holes: &[],
    },
    Baseline {
        name: "extend_self_false_0",
        steps: 53,
        effects: &[("snapshot", 27), ("done", 51)],
        holes: &[],
    },
    Baseline {
        name: "extend_native_true_0",
        steps: 56,
        effects: &[("snapshot", 29), ("done", 54)],
        holes: &[],
    },
    Baseline {
        name: "extend_proxy_true_0",
        steps: 74,
        effects: &[("iter", 15), ("snapshot", 47), ("done", 72)],
        holes: &[],
    },
    Baseline {
        name: "extend_generic_true_0",
        steps: 61,
        effects: &[("snapshot", 34), ("done", 59)],
        holes: &[],
    },
    Baseline {
        name: "extend_dynamic_true_0",
        steps: 81,
        effects: &[("iter", 21), ("snapshot", 54), ("done", 79)],
        holes: &[],
    },
    Baseline {
        name: "extend_self_true_0",
        steps: 54,
        effects: &[("snapshot", 27), ("done", 52)],
        holes: &[],
    },
    Baseline {
        name: "extend_native_false_1",
        steps: 80,
        effects: &[("snapshot", 36), ("done", 78)],
        holes: &[],
    },
    Baseline {
        name: "extend_proxy_false_1",
        steps: 111,
        effects: &[("iter", 15), ("next", 40), ("snapshot", 67), ("done", 109)],
        holes: &[],
    },
    Baseline {
        name: "extend_generic_false_1",
        steps: 85,
        effects: &[("snapshot", 41), ("done", 83)],
        holes: &[],
    },
    Baseline {
        name: "extend_dynamic_false_1",
        steps: 118,
        effects: &[("iter", 21), ("next", 46), ("snapshot", 74), ("done", 116)],
        holes: &[],
    },
    Baseline {
        name: "extend_self_false_1",
        steps: 79,
        effects: &[("snapshot", 35), ("done", 77)],
        holes: &[],
    },
    Baseline {
        name: "extend_native_true_1",
        steps: 97,
        effects: &[("snapshot", 38), ("done", 95)],
        holes: &[],
    },
    Baseline {
        name: "extend_proxy_true_1",
        steps: 128,
        effects: &[("iter", 17), ("next", 42), ("snapshot", 69), ("done", 126)],
        holes: &[],
    },
    Baseline {
        name: "extend_generic_true_1",
        steps: 102,
        effects: &[("snapshot", 43), ("done", 100)],
        holes: &[],
    },
    Baseline {
        name: "extend_dynamic_true_1",
        steps: 135,
        effects: &[("iter", 23), ("next", 48), ("snapshot", 76), ("done", 133)],
        holes: &[],
    },
    Baseline {
        name: "extend_self_true_1",
        steps: 95,
        effects: &[("snapshot", 36), ("done", 93)],
        holes: &[],
    },
    Baseline {
        name: "extend_native_false_3",
        steps: 132,
        effects: &[("snapshot", 52), ("done", 130)],
        holes: &[(48, 47), (49, 47)],
    },
    Baseline {
        name: "extend_proxy_false_3",
        steps: 189,
        effects: &[
            ("iter", 17),
            ("next", 42),
            ("next", 61),
            ("next", 80),
            ("snapshot", 109),
            ("done", 187),
        ],
        holes: &[(105, 104), (106, 104)],
    },
    Baseline {
        name: "extend_generic_false_3",
        steps: 137,
        effects: &[("snapshot", 57), ("done", 135)],
        holes: &[(51, 50), (52, 50)],
    },
    Baseline {
        name: "extend_dynamic_false_3",
        steps: 196,
        effects: &[
            ("iter", 23),
            ("next", 48),
            ("next", 67),
            ("next", 86),
            ("snapshot", 116),
            ("done", 194),
        ],
        holes: &[(111, 110), (112, 110)],
    },
    Baseline {
        name: "extend_self_false_3",
        steps: 131,
        effects: &[("snapshot", 51), ("done", 129)],
        holes: &[(47, 46), (48, 46)],
    },
    Baseline {
        name: "extend_native_true_3",
        steps: 153,
        effects: &[("snapshot", 56), ("done", 151)],
        holes: &[(52, 51), (53, 51)],
    },
    Baseline {
        name: "extend_proxy_true_3",
        steps: 210,
        effects: &[
            ("iter", 21),
            ("next", 46),
            ("next", 65),
            ("next", 84),
            ("snapshot", 113),
            ("done", 208),
        ],
        holes: &[(109, 108), (110, 108)],
    },
    Baseline {
        name: "extend_generic_true_3",
        steps: 158,
        effects: &[("snapshot", 61), ("done", 156)],
        holes: &[(55, 54), (56, 54)],
    },
    Baseline {
        name: "extend_dynamic_true_3",
        steps: 217,
        effects: &[
            ("iter", 27),
            ("next", 52),
            ("next", 71),
            ("next", 90),
            ("snapshot", 120),
            ("done", 215),
        ],
        holes: &[(115, 114), (116, 114)],
    },
    Baseline {
        name: "extend_self_true_3",
        steps: 151,
        effects: &[("snapshot", 54), ("done", 149)],
        holes: &[(50, 49), (51, 49)],
    },
];
