use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "from_iter_array_false_0",
        steps: 49,
        effects: &[("snapshot", 23), ("done", 47)],
        holes: &[],
    },
    Baseline {
        name: "from_iter_iter_false_0",
        steps: 49,
        effects: &[("snapshot", 23), ("done", 47)],
        holes: &[],
    },
    Baseline {
        name: "from_iter_proxy_false_0",
        steps: 70,
        effects: &[("iter", 11), ("snapshot", 44), ("done", 68)],
        holes: &[],
    },
    Baseline {
        name: "from_iter_custom_iter_false_0",
        steps: 67,
        effects: &[("iter", 11), ("next", 21), ("snapshot", 41), ("done", 65)],
        holes: &[],
    },
    Baseline {
        name: "from_iter_dynamic_false_0",
        steps: 71,
        effects: &[("iter", 12), ("snapshot", 45), ("done", 69)],
        holes: &[],
    },
    Baseline {
        name: "from_iter_array_true_0",
        steps: 50,
        effects: &[("snapshot", 23), ("done", 48)],
        holes: &[],
    },
    Baseline {
        name: "from_iter_iter_true_0",
        steps: 50,
        effects: &[("snapshot", 23), ("done", 48)],
        holes: &[],
    },
    Baseline {
        name: "from_iter_proxy_true_0",
        steps: 71,
        effects: &[("iter", 11), ("snapshot", 44), ("done", 69)],
        holes: &[],
    },
    Baseline {
        name: "from_iter_custom_iter_true_0",
        steps: 68,
        effects: &[("iter", 11), ("next", 21), ("snapshot", 41), ("done", 66)],
        holes: &[],
    },
    Baseline {
        name: "from_iter_dynamic_true_0",
        steps: 72,
        effects: &[("iter", 12), ("snapshot", 45), ("done", 70)],
        holes: &[],
    },
    Baseline {
        name: "from_iter_array_false_1",
        steps: 85,
        effects: &[("snapshot", 30), ("done", 83)],
        holes: &[],
    },
    Baseline {
        name: "from_iter_iter_false_1",
        steps: 85,
        effects: &[("snapshot", 30), ("done", 83)],
        holes: &[],
    },
    Baseline {
        name: "from_iter_proxy_false_1",
        steps: 119,
        effects: &[("iter", 12), ("next", 37), ("snapshot", 64), ("done", 117)],
        holes: &[],
    },
    Baseline {
        name: "from_iter_custom_iter_false_1",
        steps: 118,
        effects: &[
            ("iter", 12),
            ("next", 22),
            ("next", 43),
            ("snapshot", 63),
            ("done", 116),
        ],
        holes: &[],
    },
    Baseline {
        name: "from_iter_dynamic_false_1",
        steps: 120,
        effects: &[("iter", 13), ("next", 38), ("snapshot", 65), ("done", 118)],
        holes: &[],
    },
    Baseline {
        name: "from_iter_array_true_1",
        steps: 90,
        effects: &[("snapshot", 31), ("done", 88)],
        holes: &[],
    },
    Baseline {
        name: "from_iter_iter_true_1",
        steps: 90,
        effects: &[("snapshot", 31), ("done", 88)],
        holes: &[],
    },
    Baseline {
        name: "from_iter_proxy_true_1",
        steps: 124,
        effects: &[("iter", 13), ("next", 38), ("snapshot", 65), ("done", 122)],
        holes: &[],
    },
    Baseline {
        name: "from_iter_custom_iter_true_1",
        steps: 123,
        effects: &[
            ("iter", 13),
            ("next", 23),
            ("next", 44),
            ("snapshot", 64),
            ("done", 121),
        ],
        holes: &[],
    },
    Baseline {
        name: "from_iter_dynamic_true_1",
        steps: 125,
        effects: &[("iter", 14), ("next", 39), ("snapshot", 66), ("done", 123)],
        holes: &[],
    },
    Baseline {
        name: "from_iter_array_false_3",
        steps: 135,
        effects: &[("snapshot", 44), ("done", 133)],
        holes: &[],
    },
    Baseline {
        name: "from_iter_iter_false_3",
        steps: 135,
        effects: &[("snapshot", 44), ("done", 133)],
        holes: &[],
    },
    Baseline {
        name: "from_iter_proxy_false_3",
        steps: 195,
        effects: &[
            ("iter", 14),
            ("next", 39),
            ("next", 58),
            ("next", 77),
            ("snapshot", 104),
            ("done", 193),
        ],
        holes: &[],
    },
    Baseline {
        name: "from_iter_custom_iter_false_3",
        steps: 198,
        effects: &[
            ("iter", 14),
            ("next", 24),
            ("next", 45),
            ("next", 66),
            ("next", 87),
            ("snapshot", 107),
            ("done", 196),
        ],
        holes: &[],
    },
    Baseline {
        name: "from_iter_dynamic_false_3",
        steps: 196,
        effects: &[
            ("iter", 15),
            ("next", 40),
            ("next", 59),
            ("next", 78),
            ("snapshot", 105),
            ("done", 194),
        ],
        holes: &[],
    },
    Baseline {
        name: "from_iter_array_true_3",
        steps: 144,
        effects: &[("snapshot", 47), ("done", 142)],
        holes: &[],
    },
    Baseline {
        name: "from_iter_iter_true_3",
        steps: 144,
        effects: &[("snapshot", 47), ("done", 142)],
        holes: &[],
    },
    Baseline {
        name: "from_iter_proxy_true_3",
        steps: 204,
        effects: &[
            ("iter", 17),
            ("next", 42),
            ("next", 61),
            ("next", 80),
            ("snapshot", 107),
            ("done", 202),
        ],
        holes: &[],
    },
    Baseline {
        name: "from_iter_custom_iter_true_3",
        steps: 207,
        effects: &[
            ("iter", 17),
            ("next", 27),
            ("next", 48),
            ("next", 69),
            ("next", 90),
            ("snapshot", 110),
            ("done", 205),
        ],
        holes: &[],
    },
    Baseline {
        name: "from_iter_dynamic_true_3",
        steps: 205,
        effects: &[
            ("iter", 18),
            ("next", 43),
            ("next", 62),
            ("next", 81),
            ("snapshot", 108),
            ("done", 203),
        ],
        holes: &[],
    },
];
