use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "copy_native_false_0",
        steps: 53,
        effects: &[("snapshot", 27), ("done", 51)],
        holes: &[],
    },
    Baseline {
        name: "copy_proxy_false_0",
        steps: 71,
        effects: &[("iter", 13), ("snapshot", 45), ("done", 69)],
        holes: &[],
    },
    Baseline {
        name: "copy_generic_false_0",
        steps: 58,
        effects: &[("snapshot", 32), ("done", 56)],
        holes: &[],
    },
    Baseline {
        name: "copy_dynamic_false_0",
        steps: 71,
        effects: &[("iter", 13), ("snapshot", 45), ("done", 69)],
        holes: &[],
    },
    Baseline {
        name: "copy_self_false_0",
        steps: 53,
        effects: &[("snapshot", 27), ("done", 51)],
        holes: &[],
    },
    Baseline {
        name: "copy_native_true_0",
        steps: 54,
        effects: &[("snapshot", 27), ("done", 52)],
        holes: &[],
    },
    Baseline {
        name: "copy_proxy_true_0",
        steps: 72,
        effects: &[("iter", 13), ("snapshot", 45), ("done", 70)],
        holes: &[],
    },
    Baseline {
        name: "copy_generic_true_0",
        steps: 59,
        effects: &[("snapshot", 32), ("done", 57)],
        holes: &[],
    },
    Baseline {
        name: "copy_dynamic_true_0",
        steps: 72,
        effects: &[("iter", 13), ("snapshot", 45), ("done", 70)],
        holes: &[],
    },
    Baseline {
        name: "copy_self_true_0",
        steps: 54,
        effects: &[("snapshot", 27), ("done", 52)],
        holes: &[],
    },
    Baseline {
        name: "copy_native_false_1",
        steps: 80,
        effects: &[("snapshot", 36), ("done", 78)],
        holes: &[],
    },
    Baseline {
        name: "copy_proxy_false_1",
        steps: 111,
        effects: &[("iter", 15), ("next", 40), ("snapshot", 67), ("done", 109)],
        holes: &[],
    },
    Baseline {
        name: "copy_generic_false_1",
        steps: 85,
        effects: &[("snapshot", 41), ("done", 83)],
        holes: &[],
    },
    Baseline {
        name: "copy_dynamic_false_1",
        steps: 111,
        effects: &[("iter", 15), ("next", 40), ("snapshot", 67), ("done", 109)],
        holes: &[],
    },
    Baseline {
        name: "copy_self_false_1",
        steps: 79,
        effects: &[("snapshot", 35), ("done", 77)],
        holes: &[],
    },
    Baseline {
        name: "copy_native_true_1",
        steps: 97,
        effects: &[("snapshot", 38), ("done", 95)],
        holes: &[],
    },
    Baseline {
        name: "copy_proxy_true_1",
        steps: 128,
        effects: &[("iter", 17), ("next", 42), ("snapshot", 69), ("done", 126)],
        holes: &[],
    },
    Baseline {
        name: "copy_generic_true_1",
        steps: 102,
        effects: &[("snapshot", 43), ("done", 100)],
        holes: &[],
    },
    Baseline {
        name: "copy_dynamic_true_1",
        steps: 128,
        effects: &[("iter", 17), ("next", 42), ("snapshot", 69), ("done", 126)],
        holes: &[],
    },
    Baseline {
        name: "copy_self_true_1",
        steps: 95,
        effects: &[("snapshot", 36), ("done", 93)],
        holes: &[],
    },
    Baseline {
        name: "copy_native_false_3",
        steps: 134,
        effects: &[("snapshot", 54), ("done", 132)],
        holes: &[(50, 49), (51, 49)],
    },
    Baseline {
        name: "copy_proxy_false_3",
        steps: 191,
        effects: &[
            ("iter", 19),
            ("next", 44),
            ("next", 63),
            ("next", 82),
            ("snapshot", 111),
            ("done", 189),
        ],
        holes: &[(107, 106), (108, 106)],
    },
    Baseline {
        name: "copy_generic_false_3",
        steps: 139,
        effects: &[("snapshot", 59), ("done", 137)],
        holes: &[(53, 52), (54, 52)],
    },
    Baseline {
        name: "copy_dynamic_false_3",
        steps: 191,
        effects: &[
            ("iter", 19),
            ("next", 44),
            ("next", 63),
            ("next", 82),
            ("snapshot", 111),
            ("done", 189),
        ],
        holes: &[(107, 106), (108, 106)],
    },
    Baseline {
        name: "copy_self_false_3",
        steps: 131,
        effects: &[("snapshot", 51), ("done", 129)],
        holes: &[(47, 46), (48, 46)],
    },
    Baseline {
        name: "copy_native_true_3",
        steps: 157,
        effects: &[("snapshot", 60), ("done", 155)],
        holes: &[(56, 55), (57, 55)],
    },
    Baseline {
        name: "copy_proxy_true_3",
        steps: 214,
        effects: &[
            ("iter", 25),
            ("next", 50),
            ("next", 69),
            ("next", 88),
            ("snapshot", 117),
            ("done", 212),
        ],
        holes: &[(113, 112), (114, 112)],
    },
    Baseline {
        name: "copy_generic_true_3",
        steps: 162,
        effects: &[("snapshot", 65), ("done", 160)],
        holes: &[(59, 58), (60, 58)],
    },
    Baseline {
        name: "copy_dynamic_true_3",
        steps: 214,
        effects: &[
            ("iter", 25),
            ("next", 50),
            ("next", 69),
            ("next", 88),
            ("snapshot", 117),
            ("done", 212),
        ],
        holes: &[(113, 112), (114, 112)],
    },
    Baseline {
        name: "copy_self_true_3",
        steps: 151,
        effects: &[("snapshot", 54), ("done", 149)],
        holes: &[(50, 49), (51, 49)],
    },
];
