use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "from_native_false_0",
        steps: 50,
        effects: &[("snapshot", 24), ("done", 48)],
        holes: &[],
    },
    Baseline {
        name: "from_proxy_false_0",
        steps: 68,
        effects: &[("iter", 10), ("snapshot", 42), ("done", 66)],
        holes: &[],
    },
    Baseline {
        name: "from_generic_false_0",
        steps: 53,
        effects: &[("snapshot", 27), ("done", 51)],
        holes: &[],
    },
    Baseline {
        name: "from_dynamic_false_0",
        steps: 68,
        effects: &[("iter", 10), ("snapshot", 42), ("done", 66)],
        holes: &[],
    },
    Baseline {
        name: "from_self_false_0",
        steps: 50,
        effects: &[("snapshot", 24), ("done", 48)],
        holes: &[],
    },
    Baseline {
        name: "from_native_true_0",
        steps: 51,
        effects: &[("snapshot", 24), ("done", 49)],
        holes: &[],
    },
    Baseline {
        name: "from_proxy_true_0",
        steps: 69,
        effects: &[("iter", 10), ("snapshot", 42), ("done", 67)],
        holes: &[],
    },
    Baseline {
        name: "from_generic_true_0",
        steps: 54,
        effects: &[("snapshot", 27), ("done", 52)],
        holes: &[],
    },
    Baseline {
        name: "from_dynamic_true_0",
        steps: 69,
        effects: &[("iter", 10), ("snapshot", 42), ("done", 67)],
        holes: &[],
    },
    Baseline {
        name: "from_self_true_0",
        steps: 51,
        effects: &[("snapshot", 24), ("done", 49)],
        holes: &[],
    },
    Baseline {
        name: "from_native_false_1",
        steps: 86,
        effects: &[("snapshot", 31), ("done", 84)],
        holes: &[],
    },
    Baseline {
        name: "from_proxy_false_1",
        steps: 117,
        effects: &[("iter", 11), ("next", 36), ("snapshot", 62), ("done", 115)],
        holes: &[],
    },
    Baseline {
        name: "from_generic_false_1",
        steps: 89,
        effects: &[("snapshot", 34), ("done", 87)],
        holes: &[],
    },
    Baseline {
        name: "from_dynamic_false_1",
        steps: 117,
        effects: &[("iter", 11), ("next", 36), ("snapshot", 62), ("done", 115)],
        holes: &[],
    },
    Baseline {
        name: "from_self_false_1",
        steps: 86,
        effects: &[("snapshot", 31), ("done", 84)],
        holes: &[],
    },
    Baseline {
        name: "from_native_true_1",
        steps: 91,
        effects: &[("snapshot", 32), ("done", 89)],
        holes: &[],
    },
    Baseline {
        name: "from_proxy_true_1",
        steps: 122,
        effects: &[("iter", 12), ("next", 37), ("snapshot", 63), ("done", 120)],
        holes: &[],
    },
    Baseline {
        name: "from_generic_true_1",
        steps: 94,
        effects: &[("snapshot", 35), ("done", 92)],
        holes: &[],
    },
    Baseline {
        name: "from_dynamic_true_1",
        steps: 122,
        effects: &[("iter", 12), ("next", 37), ("snapshot", 63), ("done", 120)],
        holes: &[],
    },
    Baseline {
        name: "from_self_true_1",
        steps: 91,
        effects: &[("snapshot", 32), ("done", 89)],
        holes: &[],
    },
    Baseline {
        name: "from_native_false_3",
        steps: 136,
        effects: &[("snapshot", 45), ("done", 134)],
        holes: &[],
    },
    Baseline {
        name: "from_proxy_false_3",
        steps: 193,
        effects: &[
            ("iter", 13),
            ("next", 38),
            ("next", 57),
            ("next", 76),
            ("snapshot", 102),
            ("done", 191),
        ],
        holes: &[],
    },
    Baseline {
        name: "from_generic_false_3",
        steps: 139,
        effects: &[("snapshot", 48), ("done", 137)],
        holes: &[],
    },
    Baseline {
        name: "from_dynamic_false_3",
        steps: 193,
        effects: &[
            ("iter", 13),
            ("next", 38),
            ("next", 57),
            ("next", 76),
            ("snapshot", 102),
            ("done", 191),
        ],
        holes: &[],
    },
    Baseline {
        name: "from_self_false_3",
        steps: 136,
        effects: &[("snapshot", 45), ("done", 134)],
        holes: &[],
    },
    Baseline {
        name: "from_native_true_3",
        steps: 145,
        effects: &[("snapshot", 48), ("done", 143)],
        holes: &[],
    },
    Baseline {
        name: "from_proxy_true_3",
        steps: 202,
        effects: &[
            ("iter", 16),
            ("next", 41),
            ("next", 60),
            ("next", 79),
            ("snapshot", 105),
            ("done", 200),
        ],
        holes: &[],
    },
    Baseline {
        name: "from_generic_true_3",
        steps: 148,
        effects: &[("snapshot", 51), ("done", 146)],
        holes: &[],
    },
    Baseline {
        name: "from_dynamic_true_3",
        steps: 202,
        effects: &[
            ("iter", 16),
            ("next", 41),
            ("next", 60),
            ("next", 79),
            ("snapshot", 105),
            ("done", 200),
        ],
        holes: &[],
    },
    Baseline {
        name: "from_self_true_3",
        steps: 145,
        effects: &[("snapshot", 48), ("done", 143)],
        holes: &[],
    },
];
