[package]
name = "kagari-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
jit = []

[dependencies]
kagari-types.workspace = true
bincode.workspace = true
kagari-abi.workspace = true
kagari-contract.workspace = true
thiserror.workspace = true
kagari-common.workspace = true
kagari-bytecode.workspace = true

[dev-dependencies]
kagari-hir.workspace = true
kagari-compiler = { workspace = true, features = ["source"] }
kagari-mir.workspace = true
