[package]
name = "kagari-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
jit = []

[dependencies]
kagari-abi.workspace = true
thiserror.workspace = true
kagari-common.workspace = true
kagari-bytecode.workspace = true
indexmap.workspace = true

[dev-dependencies]
kagari-compiler.workspace = true
kagari-mir.workspace = true
