pub mod application;
pub mod bindings;
pub(crate) mod contracts;
pub mod implementation;
pub mod intrinsic;
pub(crate) mod native;
mod operands;
mod resolve;
pub mod surface;
pub mod traits;
use crate::scalar::BuiltinType;
use kagari_common::integer::IntegerMethod;
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum StandardIntrinsic {
    ArrayWithCapacity,
    ArrayCapacity,
    ArrayReserve,
    MapWithCapacity,
    MapCapacity,
    MapReserve,
    SetWithCapacity,
    SetCapacity,
    SetReserve,

    StringParse,
    ParseNumber(BuiltinType),
    ParseRadix(BuiltinType),
    Integer(IntegerMethod, BuiltinType),
    ArrayRetain,
    MapRetain,
    SetRetain,
    ArraySort,
    ArraySortBy,
    ArraySortByKey,
    ArrayDedup,
    ArrayReplaceStorage,
    CollectionRetainStorage,
    IterResume,
    CollectionMutationBegin,
    CollectionMutationEnd,
    MapGetOrInsertWith,
    MapUpdate,
    KeyLookupBegin,
    KeyCandidates,
    KeyMapGet,
    KeyMapInsert,
    KeyMapRemove,
    KeySetContains,
    KeySetInsert,
    KeySetRemove,
    ValuePartialCmp,
    ValueCmp,
    ValueEq,
    ValueHash,
    ValueDebug,
    ValueDisplay,
    ArrayListNew,
    ArrayListFrom,
    ArrayListFromFn,
    LinkedHashMapNew,
    LinkedHashMapFrom,
    LinkedHashSetNew,
    LinkedHashSetFrom,
    ArrayLen,
    ArrayIsEmpty,
    ArrayGet,
    ArrayPush,
    ArrayPop,
    ArrayInsert,
    ArrayRemove,
    ArrayExtendStorage,
    ArraySwap,
    ArrayReverse,
    ArrayTruncate,
    ArrayExtend,
    ArraySwapRemove,

    ArrayClear,
    ArrayFill,
    ArrayCopyFrom,
    ArrayCopyFromStorage,
    ArrayRemoveRange,
    ArrayRemoveRangePrepare,
    ArrayCopyWithin,
    ArrayCopyWithinBounds,
    ArrayJoin,
    MapLen,
    MapIsEmpty,
    MapContainsKey,
    MapGet,
    MapInsert,
    MapRemove,
    MapClear,
    MapKeys,
    MapValues,
    MapEntries,
    MapKeysStorage,
    MapValuesStorage,
    MapEntriesStorage,
    SetLen,
    SetIsEmpty,
    SetContains,
    SetInsert,
    SetRemove,
    SetClear,
    SetToArray,
    StringLenBytes,
    StringLenChars,
    StringIsEmpty,
    StringConcat,
    StringContains,
    StringStartsWith,
    StringEndsWith,
    StringSlice,
    StringReplace,
    StringReplaceN,
    StringRepeat,
    StringIsAscii,
    StringEqIgnoreAsciiCase,
    StringToAsciiLowercase,
    StringToAsciiUppercase,
    StringToLowercase,
    StringToUppercase,
    StringBytes,
    StringCharIndices,
    StringIsCharBoundary,

    StringSplit,
    StringSplitN,
    StringSplitOnce,
    StringRsplitOnce,
    StringSplitWhitespace,
    StringLines,

    StringTrim,
    StringTrimStart,
    StringTrimEnd,
    StringFind,
    StringRfind,
    StringStripPrefix,
    StringStripSuffix,

    OptionUnwrapOrElse,
    OptionOrElse,
    OptionMapOr,
    OptionMapOrElse,
    OptionFilter,
    OptionIsSomeAnd,
    OptionZip,
    OptionFlatten,
    OptionTranspose,
    ResultUnwrapOrElse,
    ResultOrElse,
    ResultMapOr,
    ResultMapOrElse,
    ResultOk,
    ResultErr,
    ResultIsOkAnd,
    ResultIsErrAnd,
    ResultFlatten,
    ResultTranspose,
    OptionIsSome,
    OptionIsNone,
    OptionUnwrapOr,
    OptionMap,
    OptionAndThen,
    OptionOkOr,
    OptionOkOrElse,
    ResultIsOk,
    ResultIsErr,
    ResultUnwrapOr,
    ResultMap,
    ResultMapErr,
    ResultAndThen,
    MathMin,
    MathMax,
    MathClamp,
    MathAbs,
    MathFloor,
    MathCeil,
    MathRound,
    MathSqrt,
    MathSin,
    MathCos,
    MathTan,
    DebugPrint,
    DebugAssert,
    DebugAssertEq,
    DebugPanic,
}
