[workspace]
members = [
    "crates/kagari-cli",
    "crates/kagari-common",
    "crates/kagari-embed",
    "crates/kagari-hir",
    "crates/kagari-ir",
    "crates/kagari-jit-cranelift",
    "crates/kagari-runtime",
    "crates/kagari-syntax",
    "crates/kagari-vm",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
kagari-common = { path = "crates/kagari-common" }
kagari-embed = { path = "crates/kagari-embed" }
kagari-hir = { path = "crates/kagari-hir" }
kagari-ir = { path = "crates/kagari-ir" }
kagari-jit-cranelift = { path = "crates/kagari-jit-cranelift" }
kagari-runtime = { path = "crates/kagari-runtime" }
kagari-syntax = { path = "crates/kagari-syntax" }
kagari-vm = { path = "crates/kagari-vm" }
cranelift-codegen = "0.132.0"
cranelift-frontend = "0.132.0"
cranelift-jit = "0.133.2"
cranelift-module = "0.132.0"
cranelift-native = "0.132.0"
smallvec = "1.15.1"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
indexmap = "2.14.0"
