[workspace]
members = [
    "benchmarks/lua-comparison",
    "crates/kagari-codegen",
    "crates/kagari-abi",
    "crates/kagari-contract",
    "crates/kagari-types",
    "crates/kagari-stdlib",
    "crates/kagari-cli",
    "crates/kagari-common",
    "crates/kagari-source",
    "crates/kagari-embed",
    "crates/kagari-hir",
    "crates/kagari-mir",
    "crates/kagari-bytecode",
    "crates/kagari-compiler",
    "crates/kagari-codegen-cranelift",
    "crates/kagari-runtime",
    "crates/kagari-syntax",
    "crates/kagari-vm",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
kagari-codegen = { path = "crates/kagari-codegen" }
kagari-abi = { path = "crates/kagari-abi" }
kagari-contract = { path = "crates/kagari-contract" }
kagari-types = { path = "crates/kagari-types" }
kagari-stdlib = { path = "crates/kagari-stdlib" }
kagari-common = { path = "crates/kagari-common" }
kagari-source = { path = "crates/kagari-source" }
kagari-embed = { path = "crates/kagari-embed", default-features = false }
kagari-hir = { path = "crates/kagari-hir" }
kagari-mir = { path = "crates/kagari-mir" }
kagari-bytecode = { path = "crates/kagari-bytecode" }
kagari-compiler = { path = "crates/kagari-compiler", default-features = false }
kagari-codegen-cranelift = { path = "crates/kagari-codegen-cranelift" }
kagari-runtime = { path = "crates/kagari-runtime" }
kagari-syntax = { path = "crates/kagari-syntax" }
kagari-vm = { path = "crates/kagari-vm" }
cranelift-codegen = "0.132.0"
cranelift-frontend = "0.132.0"
cranelift-jit = "0.132.0"
cranelift-module = "0.132.0"
cranelift-native = "0.132.0"
smallvec = "1.15.1"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
thiserror = "2"

[profile.dev]
opt-level = 1
