[package]
name = "kagari-bytecode"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kagari-types.workspace = true
kagari-abi.workspace = true
kagari-contract.workspace = true
kagari-common.workspace = true
serde.workspace = true
smallvec.workspace = true
bincode.workspace = true
thiserror.workspace = true
