// Recorded at 8e5df0d0 before native lazy constructors/steps.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "chain_native_false",
        steps: 421,
        allocations: 92,
        depth: 3,
        effects: &[
            ("input", 8),
            ("other", 17),
            ("iter", 22),
            ("constructed", 35),
            ("next", 128),
            ("next", 165),
            ("next", 202),
            ("done", 419),
        ],
        holes: &[],
    },
    Baseline {
        name: "chain_native_true",
        steps: 274,
        allocations: 59,
        depth: 3,
        effects: &[
            ("input", 5),
            ("other", 14),
            ("iter", 19),
            ("constructed", 32),
            ("next", 68),
            ("next", 105),
            ("next", 142),
            ("done", 272),
        ],
        holes: &[],
    },
    Baseline {
        name: "chain_script_false",
        steps: 478,
        allocations: 93,
        depth: 3,
        effects: &[
            ("input", 9),
            ("other", 18),
            ("iter", 23),
            ("constructed", 36),
            ("next", 54),
            ("next", 88),
            ("next", 122),
            ("next", 156),
            ("next", 186),
            ("next", 223),
            ("next", 260),
            ("done", 476),
        ],
        holes: &[],
    },
    Baseline {
        name: "chain_script_true",
        steps: 286,
        allocations: 60,
        depth: 3,
        effects: &[
            ("input", 6),
            ("other", 15),
            ("iter", 20),
            ("constructed", 33),
            ("next", 51),
            ("next", 81),
            ("next", 118),
            ("next", 155),
            ("done", 284),
        ],
        holes: &[],
    },
    Baseline {
        name: "chain_lazy_false",
        steps: 477,
        allocations: 107,
        depth: 4,
        effects: &[
            ("input", 12),
            ("other", 21),
            ("iter", 26),
            ("constructed", 39),
            ("upstream", 68),
            ("upstream", 101),
            ("upstream", 134),
            ("next", 184),
            ("next", 221),
            ("next", 258),
            ("done", 475),
        ],
        holes: &[],
    },
    Baseline {
        name: "chain_lazy_true",
        steps: 288,
        allocations: 68,
        depth: 3,
        effects: &[
            ("input", 9),
            ("other", 18),
            ("iter", 23),
            ("constructed", 36),
            ("next", 82),
            ("next", 119),
            ("next", 156),
            ("done", 286),
        ],
        holes: &[],
    },
];
