// Recorded at 8e5df0d0 before native lazy constructors/steps.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "chunks_array_0_2",
        steps: 114,
        allocations: 35,
        depth: 3,
        effects: &[
            ("input", 8),
            ("other", 14),
            ("constructed", 29),
            ("done", 111),
        ],
        holes: &[],
    },
    Baseline {
        name: "chunks_array_2_2",
        steps: 339,
        allocations: 111,
        depth: 4,
        effects: &[
            ("input", 11),
            ("other", 17),
            ("constructed", 32),
            ("done", 336),
        ],
        holes: &[],
    },
    Baseline {
        name: "chunks_array_1_5",
        steps: 277,
        allocations: 82,
        depth: 4,
        effects: &[
            ("input", 11),
            ("other", 17),
            ("constructed", 32),
            ("done", 274),
        ],
        holes: &[],
    },
    Baseline {
        name: "chunks_script_0_2",
        steps: 127,
        allocations: 37,
        depth: 3,
        effects: &[
            ("input", 9),
            ("other", 15),
            ("list iter", 24),
            ("len", 31),
            ("constructed", 42),
            ("done", 124),
        ],
        holes: &[],
    },
    Baseline {
        name: "chunks_script_2_2",
        steps: 373,
        allocations: 113,
        depth: 4,
        effects: &[
            ("input", 12),
            ("other", 18),
            ("list iter", 27),
            ("len", 34),
            ("constructed", 45),
            ("get", 81),
            ("get", 98),
            ("get", 148),
            ("done", 370),
        ],
        holes: &[],
    },
    Baseline {
        name: "chunks_script_1_5",
        steps: 311,
        allocations: 84,
        depth: 4,
        effects: &[
            ("input", 12),
            ("other", 18),
            ("list iter", 27),
            ("len", 34),
            ("constructed", 45),
            ("get", 80),
            ("get", 97),
            ("get", 114),
            ("done", 308),
        ],
        holes: &[],
    },
    Baseline {
        name: "chunks_dynamic_0_2",
        steps: 128,
        allocations: 54,
        depth: 3,
        effects: &[
            ("input", 10),
            ("other", 16),
            ("list iter", 25),
            ("len", 32),
            ("constructed", 43),
            ("done", 125),
        ],
        holes: &[],
    },
    Baseline {
        name: "chunks_dynamic_2_2",
        steps: 374,
        allocations: 130,
        depth: 4,
        effects: &[
            ("input", 13),
            ("other", 19),
            ("list iter", 28),
            ("len", 35),
            ("constructed", 46),
            ("get", 82),
            ("get", 99),
            ("get", 149),
            ("done", 371),
        ],
        holes: &[],
    },
    Baseline {
        name: "chunks_dynamic_1_5",
        steps: 312,
        allocations: 101,
        depth: 4,
        effects: &[
            ("input", 13),
            ("other", 19),
            ("list iter", 28),
            ("len", 35),
            ("constructed", 46),
            ("get", 81),
            ("get", 98),
            ("get", 115),
            ("done", 309),
        ],
        holes: &[],
    },
    Baseline {
        name: "chunks_view_0_2",
        steps: 121,
        allocations: 52,
        depth: 3,
        effects: &[
            ("input", 9),
            ("other", 15),
            ("constructed", 36),
            ("done", 118),
        ],
        holes: &[],
    },
    Baseline {
        name: "chunks_view_2_2",
        steps: 358,
        allocations: 128,
        depth: 4,
        effects: &[
            ("input", 12),
            ("other", 18),
            ("constructed", 39),
            ("done", 355),
        ],
        holes: &[],
    },
    Baseline {
        name: "chunks_view_1_5",
        steps: 296,
        allocations: 99,
        depth: 4,
        effects: &[
            ("input", 12),
            ("other", 18),
            ("constructed", 39),
            ("done", 293),
        ],
        holes: &[],
    },
];
