// Recorded at 8e5df0d0 before native lazy constructors/steps.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "enumerate_native_false",
        steps: 247,
        allocations: 68,
        depth: 2,
        effects: &[("input", 8), ("constructed", 18), ("done", 245)],
        holes: &[],
    },
    Baseline {
        name: "enumerate_native_true",
        steps: 85,
        allocations: 29,
        depth: 2,
        effects: &[("input", 5), ("constructed", 15), ("done", 83)],
        holes: &[],
    },
    Baseline {
        name: "enumerate_script_false",
        steps: 305,
        allocations: 69,
        depth: 3,
        effects: &[
            ("input", 9),
            ("constructed", 19),
            ("next", 31),
            ("next", 68),
            ("next", 105),
            ("next", 142),
            ("done", 303),
        ],
        holes: &[],
    },
    Baseline {
        name: "enumerate_script_true",
        steps: 98,
        allocations: 30,
        depth: 3,
        effects: &[
            ("input", 6),
            ("constructed", 16),
            ("next", 28),
            ("done", 96),
        ],
        holes: &[],
    },
    Baseline {
        name: "enumerate_lazy_false",
        steps: 303,
        allocations: 83,
        depth: 4,
        effects: &[
            ("input", 12),
            ("constructed", 22),
            ("upstream", 45),
            ("upstream", 81),
            ("upstream", 117),
            ("done", 301),
        ],
        holes: &[],
    },
    Baseline {
        name: "enumerate_lazy_true",
        steps: 99,
        allocations: 38,
        depth: 3,
        effects: &[("input", 9), ("constructed", 19), ("done", 97)],
        holes: &[],
    },
];
