// Recorded at 8e5df0d0 before native lazy constructors/steps.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "filter_native_false",
        steps: 214,
        allocations: 58,
        depth: 3,
        effects: &[
            ("input", 8),
            ("callback", 14),
            ("constructed", 22),
            ("visit", 40),
            ("visit", 65),
            ("visit", 79),
            ("done", 212),
        ],
        holes: &[],
    },
    Baseline {
        name: "filter_native_true",
        steps: 89,
        allocations: 29,
        depth: 2,
        effects: &[
            ("input", 5),
            ("callback", 11),
            ("constructed", 19),
            ("done", 87),
        ],
        holes: &[],
    },
    Baseline {
        name: "filter_script_false",
        steps: 272,
        allocations: 59,
        depth: 3,
        effects: &[
            ("input", 9),
            ("callback", 15),
            ("constructed", 23),
            ("next", 35),
            ("visit", 54),
            ("next", 75),
            ("visit", 94),
            ("next", 104),
            ("visit", 123),
            ("next", 144),
            ("done", 270),
        ],
        holes: &[],
    },
    Baseline {
        name: "filter_script_true",
        steps: 102,
        allocations: 30,
        depth: 3,
        effects: &[
            ("input", 6),
            ("callback", 12),
            ("constructed", 20),
            ("next", 32),
            ("done", 100),
        ],
        holes: &[],
    },
    Baseline {
        name: "filter_lazy_false",
        steps: 270,
        allocations: 73,
        depth: 4,
        effects: &[
            ("input", 12),
            ("callback", 18),
            ("constructed", 26),
            ("upstream", 49),
            ("visit", 59),
            ("upstream", 88),
            ("visit", 98),
            ("upstream", 116),
            ("visit", 126),
            ("done", 268),
        ],
        holes: &[],
    },
    Baseline {
        name: "filter_lazy_true",
        steps: 103,
        allocations: 38,
        depth: 3,
        effects: &[
            ("input", 9),
            ("callback", 15),
            ("constructed", 23),
            ("done", 101),
        ],
        holes: &[],
    },
];
