// Recorded at 8e5df0d0 before native lazy constructors/steps.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "filter_map_native_false",
        steps: 227,
        allocations: 59,
        depth: 3,
        effects: &[
            ("input", 8),
            ("callback", 14),
            ("constructed", 22),
            ("visit", 40),
            ("visit", 70),
            ("visit", 87),
            ("done", 225),
        ],
        holes: &[],
    },
    Baseline {
        name: "filter_map_native_true",
        steps: 89,
        allocations: 29,
        depth: 2,
        effects: &[
            ("input", 5),
            ("callback", 11),
            ("constructed", 19),
            ("done", 87),
        ],
        holes: &[],
    },
    Baseline {
        name: "filter_map_script_false",
        steps: 285,
        allocations: 60,
        depth: 3,
        effects: &[
            ("input", 9),
            ("callback", 15),
            ("constructed", 23),
            ("next", 35),
            ("visit", 54),
            ("next", 80),
            ("visit", 99),
            ("next", 112),
            ("visit", 131),
            ("next", 157),
            ("done", 283),
        ],
        holes: &[],
    },
    Baseline {
        name: "filter_map_script_true",
        steps: 102,
        allocations: 30,
        depth: 3,
        effects: &[
            ("input", 6),
            ("callback", 12),
            ("constructed", 20),
            ("next", 32),
            ("done", 100),
        ],
        holes: &[],
    },
    Baseline {
        name: "filter_map_lazy_false",
        steps: 283,
        allocations: 74,
        depth: 4,
        effects: &[
            ("input", 12),
            ("callback", 18),
            ("constructed", 26),
            ("upstream", 49),
            ("visit", 59),
            ("upstream", 93),
            ("visit", 103),
            ("upstream", 124),
            ("visit", 134),
            ("done", 281),
        ],
        holes: &[],
    },
    Baseline {
        name: "filter_map_lazy_true",
        steps: 103,
        allocations: 38,
        depth: 3,
        effects: &[
            ("input", 9),
            ("callback", 15),
            ("constructed", 23),
            ("done", 101),
        ],
        holes: &[],
    },
];
