// Recorded at 8e5df0d0 before native lazy constructors/steps.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "flat_map_native_false",
        steps: 506,
        allocations: 132,
        depth: 3,
        effects: &[
            ("input", 8),
            ("callback", 14),
            ("constructed", 26),
            ("visit", 52),
            ("visit", 127),
            ("visit", 202),
            ("done", 504),
        ],
        holes: &[],
    },
    Baseline {
        name: "flat_map_custom_native_false",
        steps: 406,
        allocations: 97,
        depth: 3,
        effects: &[
            ("input", 8),
            ("callback", 14),
            ("constructed", 26),
            ("visit", 52),
            ("iter", 65),
            ("next", 82),
            ("next", 119),
            ("visit", 145),
            ("iter", 157),
            ("next", 174),
            ("visit", 200),
            ("iter", 213),
            ("next", 230),
            ("next", 267),
            ("done", 404),
        ],
        holes: &[],
    },
    Baseline {
        name: "flat_map_native_true",
        steps: 104,
        allocations: 36,
        depth: 2,
        effects: &[
            ("input", 5),
            ("callback", 11),
            ("constructed", 23),
            ("done", 102),
        ],
        holes: &[],
    },
    Baseline {
        name: "flat_map_custom_native_true",
        steps: 104,
        allocations: 36,
        depth: 2,
        effects: &[
            ("input", 5),
            ("callback", 11),
            ("constructed", 23),
            ("done", 102),
        ],
        holes: &[],
    },
    Baseline {
        name: "flat_map_script_false",
        steps: 564,
        allocations: 133,
        depth: 3,
        effects: &[
            ("input", 9),
            ("callback", 15),
            ("constructed", 27),
            ("next", 47),
            ("visit", 66),
            ("next", 137),
            ("visit", 156),
            ("next", 227),
            ("visit", 246),
            ("next", 317),
            ("done", 562),
        ],
        holes: &[],
    },
    Baseline {
        name: "flat_map_custom_script_false",
        steps: 464,
        allocations: 98,
        depth: 3,
        effects: &[
            ("input", 9),
            ("callback", 15),
            ("constructed", 27),
            ("next", 47),
            ("visit", 66),
            ("iter", 79),
            ("next", 96),
            ("next", 133),
            ("next", 155),
            ("visit", 174),
            ("iter", 186),
            ("next", 203),
            ("next", 225),
            ("visit", 244),
            ("iter", 257),
            ("next", 274),
            ("next", 311),
            ("next", 333),
            ("done", 462),
        ],
        holes: &[],
    },
    Baseline {
        name: "flat_map_script_true",
        steps: 117,
        allocations: 37,
        depth: 3,
        effects: &[
            ("input", 6),
            ("callback", 12),
            ("constructed", 24),
            ("next", 44),
            ("done", 115),
        ],
        holes: &[],
    },
    Baseline {
        name: "flat_map_custom_script_true",
        steps: 117,
        allocations: 37,
        depth: 3,
        effects: &[
            ("input", 6),
            ("callback", 12),
            ("constructed", 24),
            ("next", 44),
            ("done", 115),
        ],
        holes: &[],
    },
    Baseline {
        name: "flat_map_lazy_false",
        steps: 562,
        allocations: 147,
        depth: 4,
        effects: &[
            ("input", 12),
            ("callback", 18),
            ("constructed", 30),
            ("upstream", 61),
            ("visit", 71),
            ("upstream", 150),
            ("visit", 160),
            ("upstream", 239),
            ("visit", 249),
            ("done", 560),
        ],
        holes: &[],
    },
    Baseline {
        name: "flat_map_custom_lazy_false",
        steps: 462,
        allocations: 112,
        depth: 4,
        effects: &[
            ("input", 12),
            ("callback", 18),
            ("constructed", 30),
            ("upstream", 61),
            ("visit", 71),
            ("iter", 84),
            ("next", 101),
            ("next", 138),
            ("upstream", 168),
            ("visit", 178),
            ("iter", 190),
            ("next", 207),
            ("upstream", 237),
            ("visit", 247),
            ("iter", 260),
            ("next", 277),
            ("next", 314),
            ("done", 460),
        ],
        holes: &[],
    },
    Baseline {
        name: "flat_map_lazy_true",
        steps: 118,
        allocations: 45,
        depth: 3,
        effects: &[
            ("input", 9),
            ("callback", 15),
            ("constructed", 27),
            ("done", 116),
        ],
        holes: &[],
    },
    Baseline {
        name: "flat_map_custom_lazy_true",
        steps: 118,
        allocations: 45,
        depth: 3,
        effects: &[
            ("input", 9),
            ("callback", 15),
            ("constructed", 27),
            ("done", 116),
        ],
        holes: &[],
    },
];
