// Recorded at 8e5df0d0 before native lazy constructors/steps.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "flatten_native_false_false",
        steps: 321,
        allocations: 96,
        depth: 2,
        effects: &[("input", 13), ("constructed", 25), ("done", 319)],
        holes: &[],
    },
    Baseline {
        name: "flatten_native_false_true",
        steps: 432,
        allocations: 105,
        depth: 3,
        effects: &[
            ("input", 16),
            ("constructed", 28),
            ("iter", 53),
            ("next", 70),
            ("next", 106),
            ("next", 142),
            ("iter", 168),
            ("next", 185),
            ("iter", 211),
            ("next", 228),
            ("next", 264),
            ("done", 430),
        ],
        holes: &[],
    },
    Baseline {
        name: "flatten_native_true_false",
        steps: 99,
        allocations: 33,
        depth: 2,
        effects: &[("input", 7), ("constructed", 19), ("done", 97)],
        holes: &[],
    },
    Baseline {
        name: "flatten_native_true_true",
        steps: 99,
        allocations: 33,
        depth: 2,
        effects: &[("input", 7), ("constructed", 19), ("done", 97)],
        holes: &[],
    },
    Baseline {
        name: "flatten_script_false_false",
        steps: 379,
        allocations: 97,
        depth: 3,
        effects: &[
            ("input", 14),
            ("constructed", 26),
            ("next", 45),
            ("next", 124),
            ("next", 161),
            ("next", 219),
            ("done", 377),
        ],
        holes: &[],
    },
    Baseline {
        name: "flatten_script_false_true",
        steps: 490,
        allocations: 106,
        depth: 3,
        effects: &[
            ("input", 17),
            ("constructed", 29),
            ("next", 48),
            ("iter", 67),
            ("next", 84),
            ("next", 120),
            ("next", 156),
            ("next", 178),
            ("iter", 197),
            ("next", 214),
            ("next", 236),
            ("iter", 255),
            ("next", 272),
            ("next", 308),
            ("next", 330),
            ("done", 488),
        ],
        holes: &[],
    },
    Baseline {
        name: "flatten_script_true_false",
        steps: 112,
        allocations: 34,
        depth: 3,
        effects: &[
            ("input", 8),
            ("constructed", 20),
            ("next", 39),
            ("done", 110),
        ],
        holes: &[],
    },
    Baseline {
        name: "flatten_script_true_true",
        steps: 112,
        allocations: 34,
        depth: 3,
        effects: &[
            ("input", 8),
            ("constructed", 20),
            ("next", 39),
            ("done", 110),
        ],
        holes: &[],
    },
    Baseline {
        name: "flatten_lazy_false_false",
        steps: 377,
        allocations: 111,
        depth: 4,
        effects: &[
            ("input", 17),
            ("constructed", 29),
            ("upstream", 59),
            ("upstream", 137),
            ("upstream", 173),
            ("done", 375),
        ],
        holes: &[],
    },
    Baseline {
        name: "flatten_lazy_false_true",
        steps: 488,
        allocations: 120,
        depth: 4,
        effects: &[
            ("input", 20),
            ("constructed", 32),
            ("upstream", 62),
            ("iter", 72),
            ("next", 89),
            ("next", 125),
            ("next", 161),
            ("upstream", 191),
            ("iter", 201),
            ("next", 218),
            ("upstream", 248),
            ("iter", 258),
            ("next", 275),
            ("next", 311),
            ("done", 486),
        ],
        holes: &[],
    },
    Baseline {
        name: "flatten_lazy_true_false",
        steps: 113,
        allocations: 42,
        depth: 3,
        effects: &[("input", 11), ("constructed", 23), ("done", 111)],
        holes: &[],
    },
    Baseline {
        name: "flatten_lazy_true_true",
        steps: 113,
        allocations: 42,
        depth: 3,
        effects: &[("input", 11), ("constructed", 23), ("done", 111)],
        holes: &[],
    },
];
