// Recorded at 8e5df0d0 before native lazy constructors/steps.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "inspect_native_false",
        steps: 239,
        allocations: 68,
        depth: 3,
        effects: &[
            ("input", 8),
            ("callback", 14),
            ("constructed", 22),
            ("visit", 40),
            ("visit", 60),
            ("visit", 80),
            ("done", 237),
        ],
        holes: &[],
    },
    Baseline {
        name: "inspect_native_true",
        steps: 89,
        allocations: 29,
        depth: 2,
        effects: &[
            ("input", 5),
            ("callback", 11),
            ("constructed", 19),
            ("done", 87),
        ],
        holes: &[],
    },
    Baseline {
        name: "inspect_script_false",
        steps: 297,
        allocations: 69,
        depth: 3,
        effects: &[
            ("input", 9),
            ("callback", 15),
            ("constructed", 23),
            ("next", 35),
            ("visit", 54),
            ("next", 70),
            ("visit", 89),
            ("next", 105),
            ("visit", 124),
            ("next", 140),
            ("done", 295),
        ],
        holes: &[],
    },
    Baseline {
        name: "inspect_script_true",
        steps: 102,
        allocations: 30,
        depth: 3,
        effects: &[
            ("input", 6),
            ("callback", 12),
            ("constructed", 20),
            ("next", 32),
            ("done", 100),
        ],
        holes: &[],
    },
    Baseline {
        name: "inspect_lazy_false",
        steps: 295,
        allocations: 83,
        depth: 4,
        effects: &[
            ("input", 12),
            ("callback", 18),
            ("constructed", 26),
            ("upstream", 49),
            ("visit", 59),
            ("upstream", 83),
            ("visit", 93),
            ("upstream", 117),
            ("visit", 127),
            ("done", 293),
        ],
        holes: &[],
    },
    Baseline {
        name: "inspect_lazy_true",
        steps: 103,
        allocations: 38,
        depth: 3,
        effects: &[
            ("input", 9),
            ("callback", 15),
            ("constructed", 23),
            ("done", 101),
        ],
        holes: &[],
    },
];
