// Recorded at 8e5df0d0 before native lazy constructors/steps.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "map_native_false",
        steps: 245,
        allocations: 68,
        depth: 3,
        effects: &[
            ("input", 8),
            ("callback", 14),
            ("constructed", 22),
            ("visit", 40),
            ("visit", 62),
            ("visit", 84),
            ("done", 243),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_native_true",
        steps: 89,
        allocations: 29,
        depth: 2,
        effects: &[
            ("input", 5),
            ("callback", 11),
            ("constructed", 19),
            ("done", 87),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_script_false",
        steps: 303,
        allocations: 69,
        depth: 3,
        effects: &[
            ("input", 9),
            ("callback", 15),
            ("constructed", 23),
            ("next", 35),
            ("visit", 54),
            ("next", 72),
            ("visit", 91),
            ("next", 109),
            ("visit", 128),
            ("next", 146),
            ("done", 301),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_script_true",
        steps: 102,
        allocations: 30,
        depth: 3,
        effects: &[
            ("input", 6),
            ("callback", 12),
            ("constructed", 20),
            ("next", 32),
            ("done", 100),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_lazy_false",
        steps: 301,
        allocations: 83,
        depth: 4,
        effects: &[
            ("input", 12),
            ("callback", 18),
            ("constructed", 26),
            ("upstream", 49),
            ("visit", 59),
            ("upstream", 85),
            ("visit", 95),
            ("upstream", 121),
            ("visit", 131),
            ("done", 299),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_lazy_true",
        steps: 103,
        allocations: 38,
        depth: 3,
        effects: &[
            ("input", 9),
            ("callback", 15),
            ("constructed", 23),
            ("done", 101),
        ],
        holes: &[],
    },
];
