// Recorded at 8e5df0d0 before native lazy constructors/steps.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "skip_native_false",
        steps: 173,
        allocations: 48,
        depth: 2,
        effects: &[
            ("input", 8),
            ("other", 14),
            ("constructed", 23),
            ("done", 171),
        ],
        holes: &[],
    },
    Baseline {
        name: "skip_native_true",
        steps: 93,
        allocations: 29,
        depth: 2,
        effects: &[
            ("input", 5),
            ("other", 11),
            ("constructed", 20),
            ("done", 91),
        ],
        holes: &[],
    },
    Baseline {
        name: "skip_script_false",
        steps: 231,
        allocations: 49,
        depth: 3,
        effects: &[
            ("input", 9),
            ("other", 15),
            ("constructed", 24),
            ("next", 36),
            ("next", 65),
            ("next", 94),
            ("next", 129),
            ("done", 229),
        ],
        holes: &[],
    },
    Baseline {
        name: "skip_script_true",
        steps: 106,
        allocations: 30,
        depth: 3,
        effects: &[
            ("input", 6),
            ("other", 12),
            ("constructed", 21),
            ("next", 33),
            ("done", 104),
        ],
        holes: &[],
    },
    Baseline {
        name: "skip_lazy_false",
        steps: 229,
        allocations: 63,
        depth: 4,
        effects: &[
            ("input", 12),
            ("other", 18),
            ("constructed", 27),
            ("upstream", 50),
            ("upstream", 78),
            ("upstream", 106),
            ("done", 227),
        ],
        holes: &[],
    },
    Baseline {
        name: "skip_lazy_true",
        steps: 107,
        allocations: 38,
        depth: 3,
        effects: &[
            ("input", 9),
            ("other", 15),
            ("constructed", 24),
            ("done", 105),
        ],
        holes: &[],
    },
    Baseline {
        name: "skip_limits_native_2",
        steps: 240,
        allocations: 68,
        depth: 2,
        effects: &[("input", 10), ("constructed", 20), ("done", 238)],
        holes: &[],
    },
    Baseline {
        name: "skip_limits_native_3",
        steps: 135,
        allocations: 38,
        depth: 2,
        effects: &[("input", 10), ("constructed", 20), ("done", 133)],
        holes: &[],
    },
    Baseline {
        name: "skip_limits_script_2",
        steps: 304,
        allocations: 69,
        depth: 3,
        effects: &[
            ("input", 11),
            ("constructed", 21),
            ("next", 33),
            ("next", 68),
            ("next", 103),
            ("next", 138),
            ("done", 302),
        ],
        holes: &[],
    },
    Baseline {
        name: "skip_limits_script_3",
        steps: 199,
        allocations: 39,
        depth: 3,
        effects: &[
            ("input", 11),
            ("constructed", 21),
            ("next", 33),
            ("next", 62),
            ("next", 91),
            ("next", 120),
            ("done", 197),
        ],
        holes: &[],
    },
    Baseline {
        name: "skip_limits_lazy_2",
        steps: 296,
        allocations: 83,
        depth: 4,
        effects: &[
            ("input", 14),
            ("constructed", 24),
            ("upstream", 47),
            ("upstream", 81),
            ("upstream", 115),
            ("done", 294),
        ],
        holes: &[],
    },
    Baseline {
        name: "skip_limits_lazy_3",
        steps: 191,
        allocations: 53,
        depth: 4,
        effects: &[
            ("input", 14),
            ("constructed", 24),
            ("upstream", 47),
            ("upstream", 75),
            ("upstream", 103),
            ("done", 189),
        ],
        holes: &[],
    },
];
