// Recorded at 8e5df0d0 before native lazy constructors/steps.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "skip_while_native_false",
        steps: 218,
        allocations: 61,
        depth: 3,
        effects: &[
            ("input", 8),
            ("callback", 14),
            ("constructed", 24),
            ("visit", 46),
            ("visit", 61),
            ("done", 216),
        ],
        holes: &[],
    },
    Baseline {
        name: "skip_while_native_true",
        steps: 92,
        allocations: 32,
        depth: 2,
        effects: &[
            ("input", 5),
            ("callback", 11),
            ("constructed", 21),
            ("done", 90),
        ],
        holes: &[],
    },
    Baseline {
        name: "skip_while_script_false",
        steps: 276,
        allocations: 62,
        depth: 3,
        effects: &[
            ("input", 9),
            ("callback", 15),
            ("constructed", 25),
            ("next", 38),
            ("visit", 60),
            ("next", 68),
            ("visit", 90),
            ("next", 114),
            ("next", 148),
            ("done", 274),
        ],
        holes: &[],
    },
    Baseline {
        name: "skip_while_script_true",
        steps: 105,
        allocations: 33,
        depth: 3,
        effects: &[
            ("input", 6),
            ("callback", 12),
            ("constructed", 22),
            ("next", 35),
            ("done", 103),
        ],
        holes: &[],
    },
    Baseline {
        name: "skip_while_lazy_false",
        steps: 274,
        allocations: 76,
        depth: 4,
        effects: &[
            ("input", 12),
            ("callback", 18),
            ("constructed", 28),
            ("upstream", 52),
            ("visit", 65),
            ("upstream", 81),
            ("visit", 94),
            ("upstream", 126),
            ("done", 272),
        ],
        holes: &[],
    },
    Baseline {
        name: "skip_while_lazy_true",
        steps: 106,
        allocations: 41,
        depth: 3,
        effects: &[
            ("input", 9),
            ("callback", 15),
            ("constructed", 25),
            ("done", 104),
        ],
        holes: &[],
    },
    Baseline {
        name: "skip_while_limits_native_5",
        steps: 131,
        allocations: 41,
        depth: 3,
        effects: &[
            ("input", 10),
            ("constructed", 21),
            ("visit", 43),
            ("visit", 56),
            ("visit", 69),
            ("done", 129),
        ],
        holes: &[],
    },
    Baseline {
        name: "skip_while_limits_script_5",
        steps: 195,
        allocations: 42,
        depth: 3,
        effects: &[
            ("input", 11),
            ("constructed", 22),
            ("next", 35),
            ("visit", 57),
            ("next", 63),
            ("visit", 85),
            ("next", 91),
            ("visit", 113),
            ("next", 119),
            ("done", 193),
        ],
        holes: &[],
    },
    Baseline {
        name: "skip_while_limits_lazy_5",
        steps: 187,
        allocations: 56,
        depth: 4,
        effects: &[
            ("input", 14),
            ("constructed", 25),
            ("upstream", 49),
            ("visit", 62),
            ("upstream", 76),
            ("visit", 89),
            ("upstream", 103),
            ("visit", 116),
            ("done", 185),
        ],
        holes: &[],
    },
];
