// Recorded at 8e5df0d0 before native lazy constructors/steps.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "take_while_native_false",
        steps: 166,
        allocations: 48,
        depth: 3,
        effects: &[
            ("input", 8),
            ("callback", 14),
            ("constructed", 24),
            ("visit", 46),
            ("visit", 73),
            ("done", 164),
        ],
        holes: &[],
    },
    Baseline {
        name: "take_while_native_true",
        steps: 98,
        allocations: 32,
        depth: 2,
        effects: &[
            ("input", 5),
            ("callback", 11),
            ("constructed", 21),
            ("done", 96),
        ],
        holes: &[],
    },
    Baseline {
        name: "take_while_script_false",
        steps: 194,
        allocations: 49,
        depth: 3,
        effects: &[
            ("input", 9),
            ("callback", 15),
            ("constructed", 25),
            ("next", 41),
            ("visit", 60),
            ("next", 83),
            ("visit", 102),
            ("done", 192),
        ],
        holes: &[],
    },
    Baseline {
        name: "take_while_script_true",
        steps: 111,
        allocations: 33,
        depth: 3,
        effects: &[
            ("input", 6),
            ("callback", 12),
            ("constructed", 22),
            ("next", 38),
            ("done", 109),
        ],
        holes: &[],
    },
    Baseline {
        name: "take_while_lazy_false",
        steps: 199,
        allocations: 60,
        depth: 4,
        effects: &[
            ("input", 12),
            ("callback", 18),
            ("constructed", 28),
            ("upstream", 55),
            ("visit", 65),
            ("upstream", 96),
            ("visit", 106),
            ("done", 197),
        ],
        holes: &[],
    },
    Baseline {
        name: "take_while_lazy_true",
        steps: 112,
        allocations: 41,
        depth: 3,
        effects: &[
            ("input", 9),
            ("callback", 15),
            ("constructed", 25),
            ("done", 110),
        ],
        holes: &[],
    },
    Baseline {
        name: "take_while_limits_native_4",
        steps: 105,
        allocations: 36,
        depth: 3,
        effects: &[
            ("input", 10),
            ("constructed", 21),
            ("visit", 43),
            ("done", 103),
        ],
        holes: &[],
    },
    Baseline {
        name: "take_while_limits_script_4",
        steps: 124,
        allocations: 37,
        depth: 3,
        effects: &[
            ("input", 11),
            ("constructed", 22),
            ("next", 38),
            ("visit", 57),
            ("done", 122),
        ],
        holes: &[],
    },
    Baseline {
        name: "take_while_limits_lazy_4",
        steps: 124,
        allocations: 46,
        depth: 4,
        effects: &[
            ("input", 14),
            ("constructed", 25),
            ("upstream", 52),
            ("visit", 62),
            ("done", 122),
        ],
        holes: &[],
    },
];
