// Recorded at 8e5df0d0 before native lazy constructors/steps.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "take_native_false",
        steps: 201,
        allocations: 55,
        depth: 2,
        effects: &[
            ("input", 8),
            ("other", 14),
            ("constructed", 23),
            ("done", 199),
        ],
        holes: &[],
    },
    Baseline {
        name: "take_native_true",
        steps: 99,
        allocations: 29,
        depth: 2,
        effects: &[
            ("input", 5),
            ("other", 11),
            ("constructed", 20),
            ("done", 97),
        ],
        holes: &[],
    },
    Baseline {
        name: "take_script_false",
        steps: 229,
        allocations: 56,
        depth: 3,
        effects: &[
            ("input", 9),
            ("other", 15),
            ("constructed", 24),
            ("next", 45),
            ("next", 84),
            ("done", 227),
        ],
        holes: &[],
    },
    Baseline {
        name: "take_script_true",
        steps: 112,
        allocations: 30,
        depth: 3,
        effects: &[
            ("input", 6),
            ("other", 12),
            ("constructed", 21),
            ("next", 42),
            ("done", 110),
        ],
        holes: &[],
    },
    Baseline {
        name: "take_lazy_false",
        steps: 234,
        allocations: 67,
        depth: 4,
        effects: &[
            ("input", 12),
            ("other", 18),
            ("constructed", 27),
            ("upstream", 59),
            ("upstream", 97),
            ("done", 232),
        ],
        holes: &[],
    },
    Baseline {
        name: "take_lazy_true",
        steps: 113,
        allocations: 38,
        depth: 3,
        effects: &[
            ("input", 9),
            ("other", 15),
            ("constructed", 24),
            ("done", 111),
        ],
        holes: &[],
    },
    Baseline {
        name: "take_limits_native_0",
        steps: 92,
        allocations: 31,
        depth: 2,
        effects: &[("input", 10), ("constructed", 20), ("done", 90)],
        holes: &[],
    },
    Baseline {
        name: "take_limits_native_1",
        steps: 258,
        allocations: 68,
        depth: 2,
        effects: &[("input", 10), ("constructed", 20), ("done", 256)],
        holes: &[],
    },
    Baseline {
        name: "take_limits_script_0",
        steps: 96,
        allocations: 32,
        depth: 2,
        effects: &[("input", 11), ("constructed", 21), ("done", 94)],
        holes: &[],
    },
    Baseline {
        name: "take_limits_script_1",
        steps: 322,
        allocations: 69,
        depth: 3,
        effects: &[
            ("input", 11),
            ("constructed", 21),
            ("next", 42),
            ("next", 81),
            ("next", 120),
            ("next", 159),
            ("done", 320),
        ],
        holes: &[],
    },
    Baseline {
        name: "take_limits_lazy_0",
        steps: 97,
        allocations: 39,
        depth: 2,
        effects: &[("input", 14), ("constructed", 24), ("done", 95)],
        holes: &[],
    },
    Baseline {
        name: "take_limits_lazy_1",
        steps: 314,
        allocations: 83,
        depth: 4,
        effects: &[
            ("input", 14),
            ("constructed", 24),
            ("upstream", 56),
            ("upstream", 94),
            ("upstream", 132),
            ("done", 312),
        ],
        holes: &[],
    },
];
