// Recorded at 8e5df0d0 before native lazy constructors/steps.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "windows_array_0_2",
        steps: 114,
        allocations: 35,
        depth: 3,
        effects: &[
            ("input", 8),
            ("other", 14),
            ("constructed", 29),
            ("done", 111),
        ],
        holes: &[],
    },
    Baseline {
        name: "windows_array_2_2",
        steps: 377,
        allocations: 116,
        depth: 4,
        effects: &[
            ("input", 11),
            ("other", 17),
            ("constructed", 32),
            ("done", 374),
        ],
        holes: &[],
    },
    Baseline {
        name: "windows_array_0_5",
        steps: 117,
        allocations: 38,
        depth: 3,
        effects: &[
            ("input", 11),
            ("other", 17),
            ("constructed", 32),
            ("done", 114),
        ],
        holes: &[],
    },
    Baseline {
        name: "windows_script_0_2",
        steps: 127,
        allocations: 37,
        depth: 3,
        effects: &[
            ("input", 9),
            ("other", 15),
            ("list iter", 24),
            ("len", 31),
            ("constructed", 42),
            ("done", 124),
        ],
        holes: &[],
    },
    Baseline {
        name: "windows_script_2_2",
        steps: 418,
        allocations: 118,
        depth: 4,
        effects: &[
            ("input", 12),
            ("other", 18),
            ("list iter", 27),
            ("len", 34),
            ("constructed", 45),
            ("get", 81),
            ("get", 98),
            ("get", 151),
            ("get", 168),
            ("done", 415),
        ],
        holes: &[],
    },
    Baseline {
        name: "windows_script_0_5",
        steps: 130,
        allocations: 40,
        depth: 3,
        effects: &[
            ("input", 12),
            ("other", 18),
            ("list iter", 27),
            ("len", 34),
            ("constructed", 45),
            ("done", 127),
        ],
        holes: &[],
    },
    Baseline {
        name: "windows_dynamic_0_2",
        steps: 128,
        allocations: 54,
        depth: 3,
        effects: &[
            ("input", 10),
            ("other", 16),
            ("list iter", 25),
            ("len", 32),
            ("constructed", 43),
            ("done", 125),
        ],
        holes: &[],
    },
    Baseline {
        name: "windows_dynamic_2_2",
        steps: 419,
        allocations: 135,
        depth: 4,
        effects: &[
            ("input", 13),
            ("other", 19),
            ("list iter", 28),
            ("len", 35),
            ("constructed", 46),
            ("get", 82),
            ("get", 99),
            ("get", 152),
            ("get", 169),
            ("done", 416),
        ],
        holes: &[],
    },
    Baseline {
        name: "windows_dynamic_0_5",
        steps: 131,
        allocations: 57,
        depth: 3,
        effects: &[
            ("input", 13),
            ("other", 19),
            ("list iter", 28),
            ("len", 35),
            ("constructed", 46),
            ("done", 128),
        ],
        holes: &[],
    },
    Baseline {
        name: "windows_view_0_2",
        steps: 121,
        allocations: 52,
        depth: 3,
        effects: &[
            ("input", 9),
            ("other", 15),
            ("constructed", 36),
            ("done", 118),
        ],
        holes: &[],
    },
    Baseline {
        name: "windows_view_2_2",
        steps: 400,
        allocations: 133,
        depth: 4,
        effects: &[
            ("input", 12),
            ("other", 18),
            ("constructed", 39),
            ("done", 397),
        ],
        holes: &[],
    },
    Baseline {
        name: "windows_view_0_5",
        steps: 124,
        allocations: 55,
        depth: 3,
        effects: &[
            ("input", 12),
            ("other", 18),
            ("constructed", 39),
            ("done", 121),
        ],
        holes: &[],
    },
];
