// Recorded at 8e5df0d0 before native lazy constructors/steps.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "zip_native_false",
        steps: 254,
        allocations: 68,
        depth: 3,
        effects: &[
            ("input", 8),
            ("other", 17),
            ("iter", 22),
            ("constructed", 33),
            ("next", 51),
            ("next", 86),
            ("next", 121),
            ("done", 252),
        ],
        holes: &[],
    },
    Baseline {
        name: "zip_native_true",
        steps: 100,
        allocations: 35,
        depth: 2,
        effects: &[
            ("input", 5),
            ("other", 14),
            ("iter", 19),
            ("constructed", 30),
            ("done", 98),
        ],
        holes: &[],
    },
    Baseline {
        name: "zip_script_false",
        steps: 297,
        allocations: 69,
        depth: 3,
        effects: &[
            ("input", 9),
            ("other", 18),
            ("iter", 23),
            ("constructed", 34),
            ("next", 46),
            ("next", 65),
            ("next", 96),
            ("next", 115),
            ("next", 146),
            ("next", 165),
            ("done", 295),
        ],
        holes: &[],
    },
    Baseline {
        name: "zip_script_true",
        steps: 113,
        allocations: 36,
        depth: 3,
        effects: &[
            ("input", 6),
            ("other", 15),
            ("iter", 20),
            ("constructed", 31),
            ("next", 43),
            ("done", 111),
        ],
        holes: &[],
    },
    Baseline {
        name: "zip_lazy_false",
        steps: 301,
        allocations: 82,
        depth: 4,
        effects: &[
            ("input", 12),
            ("other", 21),
            ("iter", 26),
            ("constructed", 37),
            ("upstream", 60),
            ("next", 70),
            ("upstream", 109),
            ("next", 119),
            ("upstream", 158),
            ("next", 168),
            ("done", 299),
        ],
        holes: &[],
    },
    Baseline {
        name: "zip_lazy_true",
        steps: 114,
        allocations: 44,
        depth: 3,
        effects: &[
            ("input", 9),
            ("other", 18),
            ("iter", 23),
            ("constructed", 34),
            ("done", 112),
        ],
        holes: &[],
    },
];
