use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "sort_by_key_scalar_0_direct",
        steps: 71,
        effects: &[
            ("receiver", 22),
            ("callback", 29),
            ("committed", 61),
            ("done", 69),
        ],
        holes: &[],
    },
    Baseline {
        name: "sort_by_key_scalar_0_generic",
        steps: 76,
        effects: &[
            ("receiver", 22),
            ("callback", 29),
            ("committed", 66),
            ("done", 74),
        ],
        holes: &[],
    },
    Baseline {
        name: "sort_by_key_scalar_1_direct",
        steps: 110,
        effects: &[
            ("receiver", 29),
            ("callback", 36),
            ("key", 56),
            ("committed", 93),
            ("done", 108),
        ],
        holes: &[(90, 89)],
    },
    Baseline {
        name: "sort_by_key_scalar_1_generic",
        steps: 116,
        effects: &[
            ("receiver", 29),
            ("callback", 36),
            ("key", 59),
            ("committed", 99),
            ("done", 114),
        ],
        holes: &[(94, 93)],
    },
    Baseline {
        name: "sort_by_key_scalar_3_direct",
        steps: 469,
        effects: &[
            ("receiver", 43),
            ("callback", 50),
            ("key", 70),
            ("key", 84),
            ("key", 98),
            ("committed", 438),
            ("done", 467),
        ],
        holes: &[(433, 432), (434, 432), (435, 432)],
    },
    Baseline {
        name: "sort_by_key_scalar_3_generic",
        steps: 467,
        effects: &[
            ("receiver", 43),
            ("callback", 50),
            ("key", 73),
            ("key", 88),
            ("key", 103),
            ("committed", 436),
            ("done", 465),
        ],
        holes: &[(429, 428), (430, 428), (431, 428)],
    },
    Baseline {
        name: "sort_by_key_scalar_5_direct",
        steps: 905,
        effects: &[
            ("receiver", 57),
            ("callback", 64),
            ("key", 84),
            ("key", 98),
            ("key", 112),
            ("key", 126),
            ("key", 140),
            ("committed", 860),
            ("done", 903),
        ],
        holes: &[(853, 852), (854, 852), (855, 852), (856, 852), (857, 852)],
    },
    Baseline {
        name: "sort_by_key_scalar_5_generic",
        steps: 906,
        effects: &[
            ("receiver", 57),
            ("callback", 64),
            ("key", 87),
            ("key", 102),
            ("key", 117),
            ("key", 132),
            ("key", 147),
            ("committed", 861),
            ("done", 904),
        ],
        holes: &[(852, 851), (853, 851), (854, 851), (855, 851), (856, 851)],
    },
    Baseline {
        name: "sort_by_key_nominal_0_direct",
        steps: 71,
        effects: &[
            ("receiver", 22),
            ("callback", 29),
            ("committed", 61),
            ("done", 69),
        ],
        holes: &[],
    },
    Baseline {
        name: "sort_by_key_nominal_0_generic",
        steps: 76,
        effects: &[
            ("receiver", 22),
            ("callback", 29),
            ("committed", 66),
            ("done", 74),
        ],
        holes: &[],
    },
    Baseline {
        name: "sort_by_key_nominal_1_direct",
        steps: 154,
        effects: &[
            ("receiver", 32),
            ("callback", 39),
            ("key", 59),
            ("committed", 106),
            ("done", 152),
        ],
        holes: &[(103, 102)],
    },
    Baseline {
        name: "sort_by_key_nominal_1_generic",
        steps: 160,
        effects: &[
            ("receiver", 32),
            ("callback", 39),
            ("key", 62),
            ("committed", 112),
            ("done", 158),
        ],
        holes: &[(107, 106)],
    },
    Baseline {
        name: "sort_by_key_nominal_3_direct",
        steps: 614,
        effects: &[
            ("receiver", 52),
            ("callback", 59),
            ("key", 79),
            ("key", 103),
            ("key", 127),
            ("cmp", 191),
            ("cmp", 352),
            ("cmp", 399),
            ("committed", 516),
            ("done", 612),
        ],
        holes: &[(511, 510), (512, 510), (513, 510)],
    },
    Baseline {
        name: "sort_by_key_nominal_3_generic",
        steps: 612,
        effects: &[
            ("receiver", 52),
            ("callback", 59),
            ("key", 82),
            ("key", 107),
            ("key", 132),
            ("cmp", 197),
            ("cmp", 353),
            ("cmp", 400),
            ("committed", 514),
            ("done", 610),
        ],
        holes: &[(507, 506), (508, 506), (509, 506)],
    },
    Baseline {
        name: "sort_by_key_nominal_5_direct",
        steps: 1190,
        effects: &[
            ("receiver", 72),
            ("callback", 79),
            ("key", 99),
            ("key", 123),
            ("key", 147),
            ("key", 171),
            ("key", 195),
            ("cmp", 259),
            ("cmp", 356),
            ("cmp", 513),
            ("cmp", 560),
            ("cmp", 607),
            ("cmp", 762),
            ("cmp", 809),
            ("cmp", 856),
            ("cmp", 903),
            ("committed", 1042),
            ("done", 1188),
        ],
        holes: &[
            (1035, 1034),
            (1036, 1034),
            (1037, 1034),
            (1038, 1034),
            (1039, 1034),
        ],
    },
    Baseline {
        name: "sort_by_key_nominal_5_generic",
        steps: 1178,
        effects: &[
            ("receiver", 72),
            ("callback", 79),
            ("key", 102),
            ("key", 127),
            ("key", 152),
            ("key", 177),
            ("key", 202),
            ("cmp", 267),
            ("cmp", 359),
            ("cmp", 521),
            ("cmp", 568),
            ("cmp", 615),
            ("cmp", 770),
            ("cmp", 817),
            ("cmp", 864),
            ("committed", 1030),
            ("done", 1176),
        ],
        holes: &[
            (1021, 1020),
            (1022, 1020),
            (1023, 1020),
            (1024, 1020),
            (1025, 1020),
        ],
    },
];
