use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "sort_by_scalar_0_direct",
        steps: 66,
        effects: &[
            ("receiver", 22),
            ("callback", 29),
            ("committed", 56),
            ("done", 64),
        ],
        holes: &[],
    },
    Baseline {
        name: "sort_by_scalar_0_generic",
        steps: 71,
        effects: &[
            ("receiver", 22),
            ("callback", 29),
            ("committed", 61),
            ("done", 69),
        ],
        holes: &[],
    },
    Baseline {
        name: "sort_by_scalar_1_direct",
        steps: 89,
        effects: &[
            ("receiver", 29),
            ("callback", 36),
            ("committed", 72),
            ("done", 87),
        ],
        holes: &[(69, 68)],
    },
    Baseline {
        name: "sort_by_scalar_1_generic",
        steps: 94,
        effects: &[
            ("receiver", 29),
            ("callback", 36),
            ("committed", 77),
            ("done", 92),
        ],
        holes: &[(72, 71)],
    },
    Baseline {
        name: "sort_by_scalar_3_direct",
        steps: 422,
        effects: &[
            ("receiver", 43),
            ("callback", 50),
            ("compare", 130),
            ("compare", 280),
            ("compare", 316),
            ("committed", 391),
            ("done", 420),
        ],
        holes: &[(386, 385), (387, 385), (388, 385)],
    },
    Baseline {
        name: "sort_by_scalar_3_generic",
        steps: 417,
        effects: &[
            ("receiver", 43),
            ("callback", 50),
            ("compare", 133),
            ("compare", 278),
            ("compare", 314),
            ("committed", 386),
            ("done", 415),
        ],
        holes: &[(379, 378), (380, 378), (381, 378)],
    },
    Baseline {
        name: "sort_by_scalar_5_direct",
        steps: 838,
        effects: &[
            ("receiver", 57),
            ("callback", 64),
            ("compare", 160),
            ("compare", 246),
            ("compare", 392),
            ("compare", 428),
            ("compare", 464),
            ("compare", 608),
            ("compare", 644),
            ("compare", 680),
            ("compare", 716),
            ("committed", 793),
            ("done", 836),
        ],
        holes: &[(786, 785), (787, 785), (788, 785), (789, 785), (790, 785)],
    },
    Baseline {
        name: "sort_by_scalar_5_generic",
        steps: 832,
        effects: &[
            ("receiver", 57),
            ("callback", 64),
            ("compare", 163),
            ("compare", 244),
            ("compare", 395),
            ("compare", 431),
            ("compare", 467),
            ("compare", 611),
            ("compare", 647),
            ("compare", 683),
            ("committed", 787),
            ("done", 830),
        ],
        holes: &[(778, 777), (779, 777), (780, 777), (781, 777), (782, 777)],
    },
    Baseline {
        name: "sort_by_nominal_0_direct",
        steps: 66,
        effects: &[
            ("receiver", 22),
            ("callback", 29),
            ("committed", 56),
            ("done", 64),
        ],
        holes: &[],
    },
    Baseline {
        name: "sort_by_nominal_0_generic",
        steps: 71,
        effects: &[
            ("receiver", 22),
            ("callback", 29),
            ("committed", 61),
            ("done", 69),
        ],
        holes: &[],
    },
    Baseline {
        name: "sort_by_nominal_1_direct",
        steps: 115,
        effects: &[
            ("receiver", 32),
            ("callback", 39),
            ("committed", 75),
            ("done", 113),
        ],
        holes: &[(72, 71)],
    },
    Baseline {
        name: "sort_by_nominal_1_generic",
        steps: 120,
        effects: &[
            ("receiver", 32),
            ("callback", 39),
            ("committed", 80),
            ("done", 118),
        ],
        holes: &[(75, 74)],
    },
    Baseline {
        name: "sort_by_nominal_3_direct",
        steps: 513,
        effects: &[
            ("receiver", 52),
            ("callback", 59),
            ("compare", 139),
            ("cmp", 144),
            ("compare", 302),
            ("cmp", 307),
            ("compare", 351),
            ("cmp", 356),
            ("committed", 439),
            ("done", 511),
        ],
        holes: &[(434, 433), (435, 433), (436, 433)],
    },
    Baseline {
        name: "sort_by_nominal_3_generic",
        steps: 508,
        effects: &[
            ("receiver", 52),
            ("callback", 59),
            ("compare", 142),
            ("cmp", 147),
            ("compare", 300),
            ("cmp", 305),
            ("compare", 349),
            ("cmp", 354),
            ("committed", 434),
            ("done", 506),
        ],
        holes: &[(427, 426), (428, 426), (429, 426)],
    },
    Baseline {
        name: "sort_by_nominal_5_direct",
        steps: 1033,
        effects: &[
            ("receiver", 72),
            ("callback", 79),
            ("compare", 175),
            ("cmp", 180),
            ("compare", 274),
            ("cmp", 279),
            ("compare", 433),
            ("cmp", 438),
            ("compare", 482),
            ("cmp", 487),
            ("compare", 531),
            ("cmp", 536),
            ("compare", 688),
            ("cmp", 693),
            ("compare", 737),
            ("cmp", 742),
            ("compare", 786),
            ("cmp", 791),
            ("compare", 835),
            ("cmp", 840),
            ("committed", 925),
            ("done", 1031),
        ],
        holes: &[(918, 917), (919, 917), (920, 917), (921, 917), (922, 917)],
    },
    Baseline {
        name: "sort_by_nominal_5_generic",
        steps: 1014,
        effects: &[
            ("receiver", 72),
            ("callback", 79),
            ("compare", 178),
            ("cmp", 183),
            ("compare", 272),
            ("cmp", 277),
            ("compare", 436),
            ("cmp", 441),
            ("compare", 485),
            ("cmp", 490),
            ("compare", 534),
            ("cmp", 539),
            ("compare", 691),
            ("cmp", 696),
            ("compare", 740),
            ("cmp", 745),
            ("compare", 789),
            ("cmp", 794),
            ("committed", 906),
            ("done", 1012),
        ],
        holes: &[(897, 896), (898, 896), (899, 896), (900, 896), (901, 896)],
    },
];
