#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, serde::Serialize, serde::Deserialize)]
pub struct CapabilitySet {
    pub fs_read: bool,
    pub fs_write: bool,
    pub net: bool,
    pub clock: bool,
    pub random: bool,
    pub host_calls: bool,
    pub path_mutation: bool,
    pub reflection_metadata: bool,
    pub reflection_read: bool,
    pub reflection_write: bool,
    pub dynamic_invocation: bool,
    pub downcast: bool,
    pub module_loading: bool,
    pub jit: bool,
    pub debug_attach: bool,
    pub debug_breakpoints: bool,
    pub debug_pause: bool,
    pub debug_stack_inspection: bool,
    pub debug_value_inspection: bool,
    pub debug_host_value_inspection: bool,
    pub debug_watch_evaluation: bool,
    pub debug_side_effecting_evaluation: bool,
}
