//! Explicit declarations, checked Rust bindings and synchronous native execution.
pub mod arguments;
pub mod binding;
pub mod builder;
pub mod callable;
pub mod catalog;
pub mod collections;
pub mod context;
pub mod conversion;
pub mod cursor;
pub mod declarations;
pub mod enums;
pub mod function_handle;
pub mod functions;
pub(crate) mod hash_storage;
pub(crate) mod hashed;
pub mod interfaces;
pub mod methods;
pub mod module;
pub mod objects;
pub mod payload;
pub mod registration;
pub(crate) mod registry;
mod result;
pub mod returns;
pub mod scalar;
mod selected;
pub mod selected_method;
pub mod sequence;
pub mod sequence_edit;
pub mod storage;
pub(crate) mod storage_type;
pub(crate) mod stored_selection;
pub mod typed;
pub mod types;
pub mod value_handle;
pub mod views;
