//! Explicit declarations, checked Rust bindings and synchronous native execution.
pub mod arguments;
pub mod binding;
pub mod builder;
pub mod callable;
pub mod catalog;
pub mod context;
pub mod cursor;
pub mod declarations;
pub mod foundation;
pub mod functions;
pub(crate) mod hash_storage;
pub(crate) mod hashed;
pub mod language;
pub mod module;
pub(crate) mod registry;
mod result;
pub mod returns;
pub mod scalar;
mod selected;
pub mod sequence;
pub mod sequence_edit;
pub mod storage;
pub(crate) mod storage_type;
pub mod types;
pub mod views;
