// Recorded at e54e8964 before checked required-method routing.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "list_len",
        steps: 24,
        allocations: 3,
        depth: 2,
        effects: &[("input", 6), ("read", 11), ("done", 22)],
        holes: &[],
    },
    Baseline {
        name: "map_len",
        steps: 64,
        allocations: 30,
        depth: 2,
        effects: &[("input", 46), ("read", 51), ("done", 62)],
        holes: &[],
    },
    Baseline {
        name: "set_len",
        steps: 52,
        allocations: 30,
        depth: 2,
        effects: &[("input", 34), ("read", 39), ("done", 50)],
        holes: &[],
    },
    Baseline {
        name: "list_empty",
        steps: 20,
        allocations: 1,
        depth: 2,
        effects: &[("input", 6), ("read", 11), ("done", 18)],
        holes: &[],
    },
    Baseline {
        name: "map_empty",
        steps: 20,
        allocations: 1,
        depth: 2,
        effects: &[("input", 6), ("read", 11), ("done", 18)],
        holes: &[],
    },
    Baseline {
        name: "set_empty",
        steps: 20,
        allocations: 1,
        depth: 2,
        effects: &[("input", 6), ("read", 11), ("done", 18)],
        holes: &[],
    },
    Baseline {
        name: "list_get",
        steps: 32,
        allocations: 7,
        depth: 3,
        effects: &[
            ("input", 6),
            ("change", 11),
            ("index", 16),
            ("changed", 26),
            ("done", 30),
        ],
        holes: &[],
    },
    Baseline {
        name: "list_pop",
        steps: 26,
        allocations: 7,
        depth: 2,
        effects: &[("input", 6), ("change", 11), ("changed", 20), ("done", 24)],
        holes: &[],
    },
    Baseline {
        name: "list_remove",
        steps: 32,
        allocations: 7,
        depth: 3,
        effects: &[
            ("input", 6),
            ("change", 11),
            ("index", 16),
            ("changed", 26),
            ("done", 30),
        ],
        holes: &[],
    },
    Baseline {
        name: "list_push",
        steps: 34,
        allocations: 4,
        depth: 3,
        effects: &[
            ("input", 6),
            ("change", 11),
            ("item", 16),
            ("changed", 28),
            ("done", 32),
        ],
        holes: &[],
    },
    Baseline {
        name: "list_insert",
        steps: 42,
        allocations: 8,
        depth: 3,
        effects: &[
            ("input", 6),
            ("change", 11),
            ("index", 16),
            ("item", 22),
            ("changed", 36),
            ("done", 40),
        ],
        holes: &[],
    },
    Baseline {
        name: "list_clear",
        steps: 26,
        allocations: 3,
        depth: 2,
        effects: &[("input", 6), ("change", 11), ("changed", 20), ("done", 24)],
        holes: &[],
    },
    Baseline {
        name: "list_set",
        steps: 42,
        allocations: 7,
        depth: 3,
        effects: &[
            ("input", 6),
            ("change", 11),
            ("index", 16),
            ("item", 22),
            ("changed", 36),
            ("done", 40),
        ],
        holes: &[],
    },
    Baseline {
        name: "list_swap",
        steps: 41,
        allocations: 7,
        depth: 3,
        effects: &[
            ("input", 6),
            ("change", 11),
            ("index", 16),
            ("index", 22),
            ("changed", 35),
            ("done", 39),
        ],
        holes: &[],
    },
    Baseline {
        name: "list_reverse",
        steps: 31,
        allocations: 7,
        depth: 2,
        effects: &[("input", 6), ("change", 11), ("changed", 25), ("done", 29)],
        holes: &[(14, 13)],
    },
    Baseline {
        name: "list_truncate",
        steps: 34,
        allocations: 3,
        depth: 3,
        effects: &[
            ("input", 6),
            ("change", 11),
            ("index", 16),
            ("changed", 28),
            ("done", 32),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_clear",
        steps: 66,
        allocations: 30,
        depth: 2,
        effects: &[("input", 46), ("change", 51), ("changed", 56), ("done", 64)],
        holes: &[],
    },
    Baseline {
        name: "set_clear",
        steps: 54,
        allocations: 30,
        depth: 2,
        effects: &[("input", 34), ("change", 39), ("changed", 44), ("done", 52)],
        holes: &[],
    },
    Baseline {
        name: "iter_array",
        steps: 29,
        allocations: 9,
        depth: 2,
        effects: &[("input", 6), ("iter", 11), ("next", 16), ("done", 27)],
        holes: &[],
    },
    Baseline {
        name: "iter_map",
        steps: 58,
        allocations: 32,
        depth: 2,
        effects: &[("input", 33), ("iter", 38), ("next", 43), ("done", 56)],
        holes: &[],
    },
    Baseline {
        name: "iter_set",
        steps: 57,
        allocations: 36,
        depth: 2,
        effects: &[("input", 34), ("iter", 39), ("next", 44), ("done", 55)],
        holes: &[],
    },
    Baseline {
        name: "iter_string",
        steps: 27,
        allocations: 6,
        depth: 2,
        effects: &[("input", 4), ("iter", 9), ("next", 14), ("done", 25)],
        holes: &[],
    },
    Baseline {
        name: "iter_range",
        steps: 29,
        allocations: 6,
        depth: 2,
        effects: &[("input", 6), ("iter", 11), ("next", 16), ("done", 27)],
        holes: &[],
    },
    Baseline {
        name: "iter_inclusive",
        steps: 29,
        allocations: 6,
        depth: 2,
        effects: &[("input", 6), ("iter", 11), ("next", 16), ("done", 27)],
        holes: &[],
    },
    Baseline {
        name: "iter_from",
        steps: 28,
        allocations: 6,
        depth: 2,
        effects: &[("input", 5), ("iter", 10), ("next", 15), ("done", 26)],
        holes: &[],
    },
    Baseline {
        name: "next_lazy",
        steps: 90,
        allocations: 28,
        depth: 4,
        effects: &[
            ("input", 11),
            ("next", 18),
            ("visit", 30),
            ("next", 44),
            ("visit", 56),
            ("next", 70),
            ("done", 88),
        ],
        holes: &[],
    },
    Baseline {
        name: "bounds_range",
        steps: 33,
        allocations: 8,
        depth: 2,
        effects: &[
            ("input", 6),
            ("start bound", 11),
            ("end bound", 20),
            ("done", 31),
        ],
        holes: &[],
    },
    Baseline {
        name: "bounds_inclusive",
        steps: 33,
        allocations: 8,
        depth: 2,
        effects: &[
            ("input", 6),
            ("start bound", 11),
            ("end bound", 20),
            ("done", 31),
        ],
        holes: &[],
    },
    Baseline {
        name: "bounds_from",
        steps: 31,
        allocations: 6,
        depth: 2,
        effects: &[
            ("input", 5),
            ("start bound", 10),
            ("end bound", 19),
            ("done", 29),
        ],
        holes: &[],
    },
    Baseline {
        name: "bounds_to",
        steps: 31,
        allocations: 6,
        depth: 2,
        effects: &[
            ("input", 5),
            ("start bound", 10),
            ("end bound", 18),
            ("done", 29),
        ],
        holes: &[],
    },
    Baseline {
        name: "bounds_to_inclusive",
        steps: 31,
        allocations: 6,
        depth: 2,
        effects: &[
            ("input", 5),
            ("start bound", 10),
            ("end bound", 18),
            ("done", 29),
        ],
        holes: &[],
    },
    Baseline {
        name: "bounds_full",
        steps: 29,
        allocations: 4,
        depth: 2,
        effects: &[
            ("input", 4),
            ("start bound", 9),
            ("end bound", 17),
            ("done", 27),
        ],
        holes: &[],
    },
    Baseline {
        name: "parse_i32",
        steps: 20,
        allocations: 4,
        depth: 2,
        effects: &[("input", 4), ("parsed", 10), ("done", 18)],
        holes: &[],
    },
    Baseline {
        name: "parse_bool",
        steps: 20,
        allocations: 4,
        depth: 2,
        effects: &[("input", 4), ("parsed", 10), ("done", 18)],
        holes: &[],
    },
    Baseline {
        name: "parse_bad",
        steps: 20,
        allocations: 6,
        depth: 2,
        effects: &[("input", 4), ("parsed", 10), ("done", 18)],
        holes: &[],
    },
];
