[package]
name = "kagari-compiler"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["source"]
source = ["dep:kagari-hir", "dep:kagari-syntax"]

[dependencies]
kagari-abi.workspace = true
kagari-contract.workspace = true
kagari-common.workspace = true
kagari-mir.workspace = true
kagari-bytecode.workspace = true
smallvec.workspace = true
thiserror.workspace = true
kagari-hir = { workspace = true, optional = true }
kagari-syntax = { workspace = true, optional = true }
bincode.workspace = true

[[test]]
name = "source_programs"
required-features = ["source"]

[[example]]
name = "applied_traits"
required-features = ["source"]

[[example]]
name = "layouts"
required-features = ["source"]

[[example]]
name = "regenerate_language_traits"
required-features = ["source"]
