// Observed at 2643293 before native string iterator construction.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "bytes_0_false",
        steps: 50,
        effects: &[("source", 6), ("created", 13), ("first", 25), ("done", 48)],
        holes: &[],
    },
    Baseline {
        name: "bytes_0_true",
        steps: 50,
        effects: &[("source", 6), ("created", 13), ("first", 25), ("done", 48)],
        holes: &[],
    },
    Baseline {
        name: "bytes_1_false",
        steps: 93,
        effects: &[
            ("source", 9),
            ("created", 16),
            ("first", 28),
            ("item", 46),
            ("item", 66),
            ("done", 91),
        ],
        holes: &[],
    },
    Baseline {
        name: "bytes_1_true",
        steps: 93,
        effects: &[
            ("source", 9),
            ("created", 16),
            ("first", 28),
            ("item", 46),
            ("item", 66),
            ("done", 91),
        ],
        holes: &[],
    },
    Baseline {
        name: "bytes_2_false",
        steps: 156,
        effects: &[
            ("source", 12),
            ("created", 19),
            ("first", 31),
            ("item", 49),
            ("item", 69),
            ("item", 89),
            ("item", 109),
            ("item", 129),
            ("done", 154),
        ],
        holes: &[],
    },
    Baseline {
        name: "bytes_2_true",
        steps: 156,
        effects: &[
            ("source", 12),
            ("created", 19),
            ("first", 31),
            ("item", 49),
            ("item", 69),
            ("item", 89),
            ("item", 109),
            ("item", 129),
            ("done", 154),
        ],
        holes: &[],
    },
    Baseline {
        name: "bytes_3_false",
        steps: 198,
        effects: &[
            ("source", 14),
            ("created", 21),
            ("first", 33),
            ("item", 51),
            ("item", 71),
            ("item", 91),
            ("item", 111),
            ("item", 131),
            ("item", 151),
            ("item", 171),
            ("done", 196),
        ],
        holes: &[],
    },
    Baseline {
        name: "bytes_3_true",
        steps: 198,
        effects: &[
            ("source", 14),
            ("created", 21),
            ("first", 33),
            ("item", 51),
            ("item", 71),
            ("item", 91),
            ("item", 111),
            ("item", 131),
            ("item", 151),
            ("item", 171),
            ("done", 196),
        ],
        holes: &[],
    },
    Baseline {
        name: "bytes_4_false",
        steps: 135,
        effects: &[
            ("source", 11),
            ("created", 18),
            ("first", 30),
            ("item", 48),
            ("item", 68),
            ("item", 88),
            ("item", 108),
            ("done", 133),
        ],
        holes: &[],
    },
    Baseline {
        name: "bytes_4_true",
        steps: 135,
        effects: &[
            ("source", 11),
            ("created", 18),
            ("first", 30),
            ("item", 48),
            ("item", 68),
            ("item", 88),
            ("item", 108),
            ("done", 133),
        ],
        holes: &[],
    },
    Baseline {
        name: "bytes_5_false",
        steps: 72,
        effects: &[
            ("source", 8),
            ("created", 15),
            ("first", 27),
            ("item", 45),
            ("done", 70),
        ],
        holes: &[],
    },
    Baseline {
        name: "bytes_5_true",
        steps: 72,
        effects: &[
            ("source", 8),
            ("created", 15),
            ("first", 27),
            ("item", 45),
            ("done", 70),
        ],
        holes: &[],
    },
];
