// Observed at 2643293 before native string iterator construction.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "char_indices_0_false",
        steps: 50,
        effects: &[("source", 6), ("created", 13), ("first", 25), ("done", 48)],
        holes: &[],
    },
    Baseline {
        name: "char_indices_0_true",
        steps: 50,
        effects: &[("source", 6), ("created", 13), ("first", 25), ("done", 48)],
        holes: &[],
    },
    Baseline {
        name: "char_indices_1_false",
        steps: 99,
        effects: &[
            ("source", 15),
            ("created", 22),
            ("first", 34),
            ("item", 52),
            ("item", 72),
            ("done", 97),
        ],
        holes: &[],
    },
    Baseline {
        name: "char_indices_1_true",
        steps: 99,
        effects: &[
            ("source", 15),
            ("created", 22),
            ("first", 34),
            ("item", 52),
            ("item", 72),
            ("done", 97),
        ],
        holes: &[],
    },
    Baseline {
        name: "char_indices_2_false",
        steps: 76,
        effects: &[
            ("source", 12),
            ("created", 19),
            ("first", 31),
            ("item", 49),
            ("done", 74),
        ],
        holes: &[],
    },
    Baseline {
        name: "char_indices_2_true",
        steps: 76,
        effects: &[
            ("source", 12),
            ("created", 19),
            ("first", 31),
            ("item", 49),
            ("done", 74),
        ],
        holes: &[],
    },
    Baseline {
        name: "char_indices_3_false",
        steps: 99,
        effects: &[
            ("source", 15),
            ("created", 22),
            ("first", 34),
            ("item", 52),
            ("item", 72),
            ("done", 97),
        ],
        holes: &[],
    },
    Baseline {
        name: "char_indices_3_true",
        steps: 99,
        effects: &[
            ("source", 15),
            ("created", 22),
            ("first", 34),
            ("item", 52),
            ("item", 72),
            ("done", 97),
        ],
        holes: &[],
    },
    Baseline {
        name: "char_indices_4_false",
        steps: 76,
        effects: &[
            ("source", 12),
            ("created", 19),
            ("first", 31),
            ("item", 49),
            ("done", 74),
        ],
        holes: &[],
    },
    Baseline {
        name: "char_indices_4_true",
        steps: 76,
        effects: &[
            ("source", 12),
            ("created", 19),
            ("first", 31),
            ("item", 49),
            ("done", 74),
        ],
        holes: &[],
    },
    Baseline {
        name: "char_indices_5_false",
        steps: 76,
        effects: &[
            ("source", 12),
            ("created", 19),
            ("first", 31),
            ("item", 49),
            ("done", 74),
        ],
        holes: &[],
    },
    Baseline {
        name: "char_indices_5_true",
        steps: 76,
        effects: &[
            ("source", 12),
            ("created", 19),
            ("first", 31),
            ("item", 49),
            ("done", 74),
        ],
        holes: &[],
    },
];
