// Observed at 2643293 before native string iterator construction.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "split_0_false",
        steps: 57,
        effects: &[
            ("source", 7),
            ("separator", 13),
            ("created", 20),
            ("first", 32),
            ("done", 55),
        ],
        holes: &[],
    },
    Baseline {
        name: "split_0_true",
        steps: 57,
        effects: &[
            ("source", 7),
            ("separator", 13),
            ("created", 20),
            ("first", 32),
            ("done", 55),
        ],
        holes: &[],
    },
    Baseline {
        name: "split_1_false",
        steps: 120,
        effects: &[
            ("source", 10),
            ("separator", 16),
            ("created", 23),
            ("first", 35),
            ("item", 53),
            ("item", 73),
            ("item", 93),
            ("done", 118),
        ],
        holes: &[],
    },
    Baseline {
        name: "split_1_true",
        steps: 120,
        effects: &[
            ("source", 10),
            ("separator", 16),
            ("created", 23),
            ("first", 35),
            ("item", 53),
            ("item", 73),
            ("item", 93),
            ("done", 118),
        ],
        holes: &[],
    },
    Baseline {
        name: "split_2_false",
        steps: 99,
        effects: &[
            ("source", 9),
            ("separator", 15),
            ("created", 22),
            ("first", 34),
            ("item", 52),
            ("item", 72),
            ("done", 97),
        ],
        holes: &[],
    },
    Baseline {
        name: "split_2_true",
        steps: 99,
        effects: &[
            ("source", 9),
            ("separator", 15),
            ("created", 22),
            ("first", 34),
            ("item", 52),
            ("item", 72),
            ("done", 97),
        ],
        holes: &[],
    },
    Baseline {
        name: "split_3_false",
        steps: 120,
        effects: &[
            ("source", 10),
            ("separator", 16),
            ("created", 23),
            ("first", 35),
            ("item", 53),
            ("item", 73),
            ("item", 93),
            ("done", 118),
        ],
        holes: &[],
    },
    Baseline {
        name: "split_3_true",
        steps: 120,
        effects: &[
            ("source", 10),
            ("separator", 16),
            ("created", 23),
            ("first", 35),
            ("item", 53),
            ("item", 73),
            ("item", 93),
            ("done", 118),
        ],
        holes: &[],
    },
    Baseline {
        name: "split_4_false",
        steps: 78,
        effects: &[
            ("source", 8),
            ("separator", 14),
            ("created", 21),
            ("first", 33),
            ("item", 51),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "split_4_true",
        steps: 78,
        effects: &[
            ("source", 8),
            ("separator", 14),
            ("created", 21),
            ("first", 33),
            ("item", 51),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "split_5_false",
        steps: 57,
        effects: &[
            ("source", 7),
            ("separator", 13),
            ("created", 20),
            ("first", 32),
            ("done", 55),
        ],
        holes: &[],
    },
    Baseline {
        name: "split_5_true",
        steps: 57,
        effects: &[
            ("source", 7),
            ("separator", 13),
            ("created", 20),
            ("first", 32),
            ("done", 55),
        ],
        holes: &[],
    },
];
