// Observed at 2643293 before native string iterator construction.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "splitn_0_false",
        steps: 62,
        effects: &[
            ("source", 6),
            ("count", 12),
            ("separator", 18),
            ("created", 25),
            ("first", 37),
            ("done", 60),
        ],
        holes: &[],
    },
    Baseline {
        name: "splitn_0_true",
        steps: 62,
        effects: &[
            ("source", 6),
            ("count", 12),
            ("separator", 18),
            ("created", 25),
            ("first", 37),
            ("done", 60),
        ],
        holes: &[],
    },
    Baseline {
        name: "splitn_1_false",
        steps: 63,
        effects: &[
            ("source", 7),
            ("count", 13),
            ("separator", 19),
            ("created", 26),
            ("first", 38),
            ("done", 61),
        ],
        holes: &[],
    },
    Baseline {
        name: "splitn_1_true",
        steps: 63,
        effects: &[
            ("source", 7),
            ("count", 13),
            ("separator", 19),
            ("created", 26),
            ("first", 38),
            ("done", 61),
        ],
        holes: &[],
    },
    Baseline {
        name: "splitn_2_false",
        steps: 84,
        effects: &[
            ("source", 8),
            ("count", 14),
            ("separator", 20),
            ("created", 27),
            ("first", 39),
            ("item", 57),
            ("done", 82),
        ],
        holes: &[],
    },
    Baseline {
        name: "splitn_2_true",
        steps: 84,
        effects: &[
            ("source", 8),
            ("count", 14),
            ("separator", 20),
            ("created", 27),
            ("first", 39),
            ("item", 57),
            ("done", 82),
        ],
        holes: &[],
    },
    Baseline {
        name: "splitn_3_false",
        steps: 84,
        effects: &[
            ("source", 8),
            ("count", 14),
            ("separator", 20),
            ("created", 27),
            ("first", 39),
            ("item", 57),
            ("done", 82),
        ],
        holes: &[],
    },
    Baseline {
        name: "splitn_3_true",
        steps: 84,
        effects: &[
            ("source", 8),
            ("count", 14),
            ("separator", 20),
            ("created", 27),
            ("first", 39),
            ("item", 57),
            ("done", 82),
        ],
        holes: &[],
    },
    Baseline {
        name: "splitn_4_false",
        steps: 105,
        effects: &[
            ("source", 9),
            ("count", 15),
            ("separator", 21),
            ("created", 28),
            ("first", 40),
            ("item", 58),
            ("item", 78),
            ("done", 103),
        ],
        holes: &[],
    },
    Baseline {
        name: "splitn_4_true",
        steps: 105,
        effects: &[
            ("source", 9),
            ("count", 15),
            ("separator", 21),
            ("created", 28),
            ("first", 40),
            ("item", 58),
            ("item", 78),
            ("done", 103),
        ],
        holes: &[],
    },
    Baseline {
        name: "splitn_5_false",
        steps: 63,
        effects: &[
            ("source", 7),
            ("count", 13),
            ("separator", 19),
            ("created", 26),
            ("first", 38),
            ("done", 61),
        ],
        holes: &[],
    },
    Baseline {
        name: "splitn_5_true",
        steps: 63,
        effects: &[
            ("source", 7),
            ("count", 13),
            ("separator", 19),
            ("created", 26),
            ("first", 38),
            ("done", 61),
        ],
        holes: &[],
    },
];
