// Observed at 59cc121 with canonical table projections, before native parse/assert entries.
pub(super) struct Baseline {
    pub name: &'static str,
    pub steps: u64,
    pub effects: &'static [(&'static str, u64)],
    pub holes: &'static [(u64, u64)],
    pub failure: Option<&'static str>,
    pub trace: &'static [&'static str],
}
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "parse_i8_0_false",
        steps: 18,
        effects: &[("source", 4), ("done", 16)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i8_0_true",
        steps: 21,
        effects: &[("source", 4), ("done", 19)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i8_1_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i8_1_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i8_2_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i8_2_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i8_3_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i8_3_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i16_0_false",
        steps: 18,
        effects: &[("source", 4), ("done", 16)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i16_0_true",
        steps: 21,
        effects: &[("source", 4), ("done", 19)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i16_1_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i16_1_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i16_2_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i16_2_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i16_3_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i16_3_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i32_0_false",
        steps: 18,
        effects: &[("source", 4), ("done", 16)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i32_0_true",
        steps: 21,
        effects: &[("source", 4), ("done", 19)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i32_1_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i32_1_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i32_2_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i32_2_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i32_3_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i32_3_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i64_0_false",
        steps: 18,
        effects: &[("source", 4), ("done", 16)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i64_0_true",
        steps: 21,
        effects: &[("source", 4), ("done", 19)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i64_1_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i64_1_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i64_2_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i64_2_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i64_3_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_i64_3_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_isize_0_false",
        steps: 18,
        effects: &[("source", 4), ("done", 16)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_isize_0_true",
        steps: 21,
        effects: &[("source", 4), ("done", 19)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_isize_1_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_isize_1_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_isize_2_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_isize_2_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_isize_3_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_isize_3_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u8_0_false",
        steps: 18,
        effects: &[("source", 4), ("done", 16)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u8_0_true",
        steps: 21,
        effects: &[("source", 4), ("done", 19)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u8_1_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u8_1_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u8_2_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u8_2_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u8_3_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u8_3_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u16_0_false",
        steps: 18,
        effects: &[("source", 4), ("done", 16)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u16_0_true",
        steps: 21,
        effects: &[("source", 4), ("done", 19)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u16_1_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u16_1_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u16_2_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u16_2_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u16_3_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u16_3_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u32_0_false",
        steps: 18,
        effects: &[("source", 4), ("done", 16)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u32_0_true",
        steps: 21,
        effects: &[("source", 4), ("done", 19)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u32_1_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u32_1_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u32_2_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u32_2_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u32_3_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u32_3_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u64_0_false",
        steps: 18,
        effects: &[("source", 4), ("done", 16)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u64_0_true",
        steps: 21,
        effects: &[("source", 4), ("done", 19)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u64_1_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u64_1_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u64_2_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u64_2_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u64_3_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_u64_3_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_usize_0_false",
        steps: 18,
        effects: &[("source", 4), ("done", 16)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_usize_0_true",
        steps: 21,
        effects: &[("source", 4), ("done", 19)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_usize_1_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_usize_1_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_usize_2_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_usize_2_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_usize_3_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_usize_3_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_f32_0_false",
        steps: 18,
        effects: &[("source", 4), ("done", 16)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_f32_0_true",
        steps: 21,
        effects: &[("source", 4), ("done", 19)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_f32_1_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_f32_1_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_f32_2_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_f32_2_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_f32_3_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_f32_3_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_f64_0_false",
        steps: 18,
        effects: &[("source", 4), ("done", 16)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_f64_0_true",
        steps: 21,
        effects: &[("source", 4), ("done", 19)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_f64_1_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_f64_1_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_f64_2_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_f64_2_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_f64_3_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_f64_3_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_bool_0_false",
        steps: 18,
        effects: &[("source", 4), ("done", 16)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_bool_0_true",
        steps: 21,
        effects: &[("source", 4), ("done", 19)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_bool_1_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_bool_1_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_bool_2_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_bool_2_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_bool_3_false",
        steps: 16,
        effects: &[("source", 4), ("done", 14)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_bool_3_true",
        steps: 19,
        effects: &[("source", 4), ("done", 17)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_custom_false_false",
        steps: 30,
        effects: &[("source", 4), ("parse", 9), ("done", 28)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_custom_false_true",
        steps: 33,
        effects: &[("source", 4), ("parse", 11), ("done", 31)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_custom_true_false",
        steps: 36,
        effects: &[("source", 4), ("parse", 9), ("wrap", 18), ("done", 34)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "parse_custom_true_true",
        steps: 39,
        effects: &[("source", 4), ("parse", 11), ("wrap", 20), ("done", 37)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "assert_scalar_false_false",
        steps: 26,
        effects: &[("left", 11), ("right", 17), ("message", 22)],
        holes: &[],
        failure: Some(
            "builtin:ScriptTrap:std::debug::assert: debug.assert failed: native assertion",
        ),
        trace: &["main"],
    },
    Baseline {
        name: "assert_scalar_false_true",
        steps: 30,
        effects: &[("left", 11), ("right", 17), ("message", 22)],
        holes: &[],
        failure: Some(
            "builtin:ScriptTrap:std::debug::assert: debug.assert failed: native assertion",
        ),
        trace: &["checked#4", "main"],
    },
    Baseline {
        name: "assert_scalar_true_false",
        steps: 30,
        effects: &[("left", 11), ("right", 17), ("message", 22), ("done", 28)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "assert_scalar_true_true",
        steps: 36,
        effects: &[("left", 11), ("right", 17), ("message", 22), ("done", 34)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "assert_identity_false_false",
        steps: 27,
        effects: &[("left", 12), ("right", 18), ("message", 23)],
        holes: &[],
        failure: Some(
            "builtin:ScriptTrap:std::debug::assert: debug.assert failed: native assertion",
        ),
        trace: &["main"],
    },
    Baseline {
        name: "assert_identity_false_true",
        steps: 31,
        effects: &[("left", 12), ("right", 18), ("message", 23)],
        holes: &[],
        failure: Some(
            "builtin:ScriptTrap:std::debug::assert: debug.assert failed: native assertion",
        ),
        trace: &["checked#4", "main"],
    },
    Baseline {
        name: "assert_identity_true_false",
        steps: 30,
        effects: &[("left", 11), ("right", 17), ("message", 22), ("done", 28)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "assert_identity_true_true",
        steps: 36,
        effects: &[("left", 11), ("right", 17), ("message", 22), ("done", 34)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "assert_nominal_false_false",
        steps: 43,
        effects: &[("left", 15), ("right", 21), ("message", 26), ("eq", 31)],
        holes: &[],
        failure: Some(
            "builtin:ScriptTrap:std::debug::assert: debug.assert failed: native assertion",
        ),
        trace: &["main"],
    },
    Baseline {
        name: "assert_nominal_false_true",
        steps: 47,
        effects: &[("left", 15), ("right", 21), ("message", 26), ("eq", 35)],
        holes: &[],
        failure: Some(
            "builtin:ScriptTrap:std::debug::assert: debug.assert failed: native assertion",
        ),
        trace: &["checked#4", "main"],
    },
    Baseline {
        name: "assert_nominal_true_false",
        steps: 47,
        effects: &[
            ("left", 15),
            ("right", 21),
            ("message", 26),
            ("eq", 31),
            ("done", 45),
        ],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "assert_nominal_true_true",
        steps: 53,
        effects: &[
            ("left", 15),
            ("right", 21),
            ("message", 26),
            ("eq", 35),
            ("done", 51),
        ],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "assert_option_false_false",
        steps: 61,
        effects: &[("left", 17), ("right", 23), ("message", 28), ("eq", 42)],
        holes: &[],
        failure: Some(
            "builtin:ScriptTrap:std::debug::assert: debug.assert failed: native assertion",
        ),
        trace: &["main"],
    },
    Baseline {
        name: "assert_option_false_true",
        steps: 65,
        effects: &[("left", 17), ("right", 23), ("message", 28), ("eq", 46)],
        holes: &[],
        failure: Some(
            "builtin:ScriptTrap:std::debug::assert: debug.assert failed: native assertion",
        ),
        trace: &["checked#4", "main"],
    },
    Baseline {
        name: "assert_option_true_false",
        steps: 65,
        effects: &[
            ("left", 17),
            ("right", 23),
            ("message", 28),
            ("eq", 42),
            ("done", 63),
        ],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "assert_option_true_true",
        steps: 71,
        effects: &[
            ("left", 17),
            ("right", 23),
            ("message", 28),
            ("eq", 46),
            ("done", 69),
        ],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "assert_tuple_false_false",
        steps: 61,
        effects: &[("left", 19), ("right", 25), ("message", 30), ("eq", 44)],
        holes: &[],
        failure: Some(
            "builtin:ScriptTrap:std::debug::assert: debug.assert failed: native assertion",
        ),
        trace: &["main"],
    },
    Baseline {
        name: "assert_tuple_false_true",
        steps: 65,
        effects: &[("left", 19), ("right", 25), ("message", 30), ("eq", 48)],
        holes: &[],
        failure: Some(
            "builtin:ScriptTrap:std::debug::assert: debug.assert failed: native assertion",
        ),
        trace: &["checked#4", "main"],
    },
    Baseline {
        name: "assert_tuple_true_false",
        steps: 67,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("message", 30),
            ("eq", 44),
            ("done", 65),
        ],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "assert_tuple_true_true",
        steps: 73,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("message", 30),
            ("eq", 48),
            ("done", 71),
        ],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "assert_enumeration_false_false",
        steps: 61,
        effects: &[("left", 17), ("right", 23), ("message", 28), ("eq", 42)],
        holes: &[],
        failure: Some(
            "builtin:ScriptTrap:std::debug::assert: debug.assert failed: native assertion",
        ),
        trace: &["main"],
    },
    Baseline {
        name: "assert_enumeration_false_true",
        steps: 65,
        effects: &[("left", 17), ("right", 23), ("message", 28), ("eq", 46)],
        holes: &[],
        failure: Some(
            "builtin:ScriptTrap:std::debug::assert: debug.assert failed: native assertion",
        ),
        trace: &["checked#4", "main"],
    },
    Baseline {
        name: "assert_enumeration_true_false",
        steps: 65,
        effects: &[
            ("left", 17),
            ("right", 23),
            ("message", 28),
            ("eq", 42),
            ("done", 63),
        ],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "assert_enumeration_true_true",
        steps: 71,
        effects: &[
            ("left", 17),
            ("right", 23),
            ("message", 28),
            ("eq", 46),
            ("done", 69),
        ],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "assert_dynamic_false_false",
        steps: 29,
        effects: &[("left", 14), ("right", 20), ("message", 25)],
        holes: &[],
        failure: Some(
            "builtin:ScriptTrap:std::debug::assert: debug.assert failed: native assertion",
        ),
        trace: &["main"],
    },
    Baseline {
        name: "assert_dynamic_false_true",
        steps: 33,
        effects: &[("left", 14), ("right", 20), ("message", 25)],
        holes: &[],
        failure: Some(
            "builtin:ScriptTrap:std::debug::assert: debug.assert failed: native assertion",
        ),
        trace: &["checked#9", "main"],
    },
    Baseline {
        name: "assert_dynamic_true_false",
        steps: 32,
        effects: &[("left", 13), ("right", 19), ("message", 24), ("done", 30)],
        holes: &[],
        failure: None,
        trace: &[],
    },
    Baseline {
        name: "assert_dynamic_true_true",
        steps: 38,
        effects: &[("left", 13), ("right", 19), ("message", 24), ("done", 36)],
        holes: &[],
        failure: None,
        trace: &[],
    },
];

pub(super) fn all() -> impl Iterator<Item = &'static Baseline> {
    BASELINE.iter()
}
