[package]
name = "kagari-embed"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kagari-codegen.workspace = true
kagari-compiler.workspace = true
kagari-mir.workspace = true
kagari-abi.workspace = true
thiserror.workspace = true
kagari-common.workspace = true
kagari-hir.workspace = true
kagari-bytecode.workspace = true
kagari-runtime.workspace = true
kagari-syntax.workspace = true
kagari-vm.workspace = true
smallvec.workspace = true

[dev-dependencies]
kagari-codegen-cranelift.workspace = true
