// Observed at 3ee6486 before native grouping.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "identity_repeat_native",
        steps: 408,
        effects: &[
            ("input", 41),
            ("function", 47),
            ("key", 61),
            ("key", 83),
            ("key", 105),
            ("key", 126),
            ("grouped", 149),
            ("done", 406),
        ],
        holes: &[],
    },
    Baseline {
        name: "identity_repeat_inspect",
        steps: 474,
        effects: &[
            ("input", 45),
            ("function", 51),
            ("next", 70),
            ("key", 79),
            ("next", 105),
            ("key", 114),
            ("next", 140),
            ("key", 149),
            ("next", 174),
            ("key", 183),
            ("grouped", 215),
            ("done", 472),
        ],
        holes: &[],
    },
    Baseline {
        name: "identity_repeat_custom",
        steps: 479,
        effects: &[
            ("input", 42),
            ("function", 48),
            ("next", 55),
            ("key", 74),
            ("next", 92),
            ("key", 111),
            ("next", 129),
            ("key", 148),
            ("next", 165),
            ("key", 184),
            ("next", 202),
            ("grouped", 220),
            ("done", 477),
        ],
        holes: &[],
    },
    Baseline {
        name: "identity_repeat_generic_native",
        steps: 412,
        effects: &[
            ("input", 41),
            ("function", 47),
            ("key", 64),
            ("key", 86),
            ("key", 108),
            ("key", 129),
            ("grouped", 153),
            ("done", 410),
        ],
        holes: &[],
    },
    Baseline {
        name: "identity_repeat_generic_custom",
        steps: 483,
        effects: &[
            ("input", 42),
            ("function", 48),
            ("next", 58),
            ("key", 77),
            ("next", 95),
            ("key", 114),
            ("next", 132),
            ("key", 151),
            ("next", 168),
            ("key", 187),
            ("next", 205),
            ("grouped", 224),
            ("done", 481),
        ],
        holes: &[],
    },
    Baseline {
        name: "identity_repeat_generic_inspect",
        steps: 478,
        effects: &[
            ("input", 45),
            ("function", 51),
            ("next", 73),
            ("key", 82),
            ("next", 108),
            ("key", 117),
            ("next", 143),
            ("key", 152),
            ("next", 177),
            ("key", 186),
            ("grouped", 219),
            ("done", 476),
        ],
        holes: &[],
    },
    Baseline {
        name: "identity_all_native",
        steps: 282,
        effects: &[
            ("input", 35),
            ("function", 41),
            ("key", 55),
            ("key", 77),
            ("key", 98),
            ("grouped", 120),
            ("done", 280),
        ],
        holes: &[],
    },
    Baseline {
        name: "identity_all_inspect",
        steps: 335,
        effects: &[
            ("input", 39),
            ("function", 45),
            ("next", 64),
            ("key", 73),
            ("next", 99),
            ("key", 108),
            ("next", 133),
            ("key", 142),
            ("grouped", 173),
            ("done", 333),
        ],
        holes: &[],
    },
    Baseline {
        name: "identity_all_custom",
        steps: 338,
        effects: &[
            ("input", 36),
            ("function", 42),
            ("next", 49),
            ("key", 68),
            ("next", 86),
            ("key", 105),
            ("next", 122),
            ("key", 141),
            ("next", 158),
            ("grouped", 176),
            ("done", 336),
        ],
        holes: &[],
    },
    Baseline {
        name: "identity_all_generic_native",
        steps: 286,
        effects: &[
            ("input", 35),
            ("function", 41),
            ("key", 58),
            ("key", 80),
            ("key", 101),
            ("grouped", 124),
            ("done", 284),
        ],
        holes: &[],
    },
    Baseline {
        name: "identity_all_generic_custom",
        steps: 342,
        effects: &[
            ("input", 36),
            ("function", 42),
            ("next", 52),
            ("key", 71),
            ("next", 89),
            ("key", 108),
            ("next", 125),
            ("key", 144),
            ("next", 161),
            ("grouped", 180),
            ("done", 340),
        ],
        holes: &[],
    },
    Baseline {
        name: "identity_all_generic_inspect",
        steps: 339,
        effects: &[
            ("input", 39),
            ("function", 45),
            ("next", 67),
            ("key", 76),
            ("next", 102),
            ("key", 111),
            ("next", 136),
            ("key", 145),
            ("grouped", 177),
            ("done", 337),
        ],
        holes: &[],
    },
];
