// Observed at 3ee6486 before native grouping.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "identity_empty_native",
        steps: 54,
        effects: &[
            ("input", 17),
            ("function", 23),
            ("grouped", 38),
            ("done", 52),
        ],
        holes: &[],
    },
    Baseline {
        name: "identity_empty_inspect",
        steps: 68,
        effects: &[
            ("input", 21),
            ("function", 27),
            ("grouped", 52),
            ("done", 66),
        ],
        holes: &[],
    },
    Baseline {
        name: "identity_empty_custom",
        steps: 65,
        effects: &[
            ("input", 18),
            ("function", 24),
            ("next", 31),
            ("grouped", 49),
            ("done", 63),
        ],
        holes: &[],
    },
    Baseline {
        name: "identity_empty_generic_native",
        steps: 58,
        effects: &[
            ("input", 17),
            ("function", 23),
            ("grouped", 42),
            ("done", 56),
        ],
        holes: &[],
    },
    Baseline {
        name: "identity_empty_generic_custom",
        steps: 69,
        effects: &[
            ("input", 18),
            ("function", 24),
            ("next", 34),
            ("grouped", 53),
            ("done", 67),
        ],
        holes: &[],
    },
    Baseline {
        name: "identity_empty_generic_inspect",
        steps: 72,
        effects: &[
            ("input", 21),
            ("function", 27),
            ("grouped", 56),
            ("done", 70),
        ],
        holes: &[],
    },
    Baseline {
        name: "identity_unique_native",
        steps: 342,
        effects: &[
            ("input", 35),
            ("function", 41),
            ("key", 55),
            ("key", 77),
            ("key", 99),
            ("grouped", 122),
            ("done", 340),
        ],
        holes: &[],
    },
    Baseline {
        name: "identity_unique_inspect",
        steps: 395,
        effects: &[
            ("input", 39),
            ("function", 45),
            ("next", 64),
            ("key", 73),
            ("next", 99),
            ("key", 108),
            ("next", 134),
            ("key", 143),
            ("grouped", 175),
            ("done", 393),
        ],
        holes: &[],
    },
    Baseline {
        name: "identity_unique_custom",
        steps: 398,
        effects: &[
            ("input", 36),
            ("function", 42),
            ("next", 49),
            ("key", 68),
            ("next", 86),
            ("key", 105),
            ("next", 123),
            ("key", 142),
            ("next", 160),
            ("grouped", 178),
            ("done", 396),
        ],
        holes: &[],
    },
    Baseline {
        name: "identity_unique_generic_native",
        steps: 346,
        effects: &[
            ("input", 35),
            ("function", 41),
            ("key", 58),
            ("key", 80),
            ("key", 102),
            ("grouped", 126),
            ("done", 344),
        ],
        holes: &[],
    },
    Baseline {
        name: "identity_unique_generic_custom",
        steps: 402,
        effects: &[
            ("input", 36),
            ("function", 42),
            ("next", 52),
            ("key", 71),
            ("next", 89),
            ("key", 108),
            ("next", 126),
            ("key", 145),
            ("next", 163),
            ("grouped", 182),
            ("done", 400),
        ],
        holes: &[],
    },
    Baseline {
        name: "identity_unique_generic_inspect",
        steps: 399,
        effects: &[
            ("input", 39),
            ("function", 45),
            ("next", 67),
            ("key", 76),
            ("next", 102),
            ("key", 111),
            ("next", 137),
            ("key", 146),
            ("grouped", 179),
            ("done", 397),
        ],
        holes: &[],
    },
];
