// Observed at 3ee6486 before native grouping.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "interface_repeat_native",
        steps: 411,
        effects: &[
            ("input", 44),
            ("function", 50),
            ("key", 64),
            ("key", 86),
            ("key", 108),
            ("key", 129),
            ("grouped", 152),
            ("done", 409),
        ],
        holes: &[],
    },
    Baseline {
        name: "interface_repeat_inspect",
        steps: 477,
        effects: &[
            ("input", 48),
            ("function", 54),
            ("next", 73),
            ("key", 82),
            ("next", 108),
            ("key", 117),
            ("next", 143),
            ("key", 152),
            ("next", 177),
            ("key", 186),
            ("grouped", 218),
            ("done", 475),
        ],
        holes: &[],
    },
    Baseline {
        name: "interface_repeat_custom",
        steps: 482,
        effects: &[
            ("input", 45),
            ("function", 51),
            ("next", 58),
            ("key", 77),
            ("next", 95),
            ("key", 114),
            ("next", 132),
            ("key", 151),
            ("next", 168),
            ("key", 187),
            ("next", 205),
            ("grouped", 223),
            ("done", 480),
        ],
        holes: &[],
    },
    Baseline {
        name: "interface_repeat_generic_native",
        steps: 415,
        effects: &[
            ("input", 44),
            ("function", 50),
            ("key", 67),
            ("key", 89),
            ("key", 111),
            ("key", 132),
            ("grouped", 156),
            ("done", 413),
        ],
        holes: &[],
    },
    Baseline {
        name: "interface_repeat_generic_custom",
        steps: 486,
        effects: &[
            ("input", 45),
            ("function", 51),
            ("next", 61),
            ("key", 80),
            ("next", 98),
            ("key", 117),
            ("next", 135),
            ("key", 154),
            ("next", 171),
            ("key", 190),
            ("next", 208),
            ("grouped", 227),
            ("done", 484),
        ],
        holes: &[],
    },
    Baseline {
        name: "interface_repeat_generic_inspect",
        steps: 481,
        effects: &[
            ("input", 48),
            ("function", 54),
            ("next", 76),
            ("key", 85),
            ("next", 111),
            ("key", 120),
            ("next", 146),
            ("key", 155),
            ("next", 180),
            ("key", 189),
            ("grouped", 222),
            ("done", 479),
        ],
        holes: &[],
    },
    Baseline {
        name: "interface_all_native",
        steps: 285,
        effects: &[
            ("input", 38),
            ("function", 44),
            ("key", 58),
            ("key", 80),
            ("key", 101),
            ("grouped", 123),
            ("done", 283),
        ],
        holes: &[],
    },
    Baseline {
        name: "interface_all_inspect",
        steps: 338,
        effects: &[
            ("input", 42),
            ("function", 48),
            ("next", 67),
            ("key", 76),
            ("next", 102),
            ("key", 111),
            ("next", 136),
            ("key", 145),
            ("grouped", 176),
            ("done", 336),
        ],
        holes: &[],
    },
    Baseline {
        name: "interface_all_custom",
        steps: 341,
        effects: &[
            ("input", 39),
            ("function", 45),
            ("next", 52),
            ("key", 71),
            ("next", 89),
            ("key", 108),
            ("next", 125),
            ("key", 144),
            ("next", 161),
            ("grouped", 179),
            ("done", 339),
        ],
        holes: &[],
    },
    Baseline {
        name: "interface_all_generic_native",
        steps: 289,
        effects: &[
            ("input", 38),
            ("function", 44),
            ("key", 61),
            ("key", 83),
            ("key", 104),
            ("grouped", 127),
            ("done", 287),
        ],
        holes: &[],
    },
    Baseline {
        name: "interface_all_generic_custom",
        steps: 345,
        effects: &[
            ("input", 39),
            ("function", 45),
            ("next", 55),
            ("key", 74),
            ("next", 92),
            ("key", 111),
            ("next", 128),
            ("key", 147),
            ("next", 164),
            ("grouped", 183),
            ("done", 343),
        ],
        holes: &[],
    },
    Baseline {
        name: "interface_all_generic_inspect",
        steps: 342,
        effects: &[
            ("input", 42),
            ("function", 48),
            ("next", 70),
            ("key", 79),
            ("next", 105),
            ("key", 114),
            ("next", 139),
            ("key", 148),
            ("grouped", 180),
            ("done", 340),
        ],
        holes: &[],
    },
];
