// Observed at 3ee6486 before native grouping.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "interface_empty_native",
        steps: 57,
        effects: &[
            ("input", 20),
            ("function", 26),
            ("grouped", 41),
            ("done", 55),
        ],
        holes: &[],
    },
    Baseline {
        name: "interface_empty_inspect",
        steps: 71,
        effects: &[
            ("input", 24),
            ("function", 30),
            ("grouped", 55),
            ("done", 69),
        ],
        holes: &[],
    },
    Baseline {
        name: "interface_empty_custom",
        steps: 68,
        effects: &[
            ("input", 21),
            ("function", 27),
            ("next", 34),
            ("grouped", 52),
            ("done", 66),
        ],
        holes: &[],
    },
    Baseline {
        name: "interface_empty_generic_native",
        steps: 61,
        effects: &[
            ("input", 20),
            ("function", 26),
            ("grouped", 45),
            ("done", 59),
        ],
        holes: &[],
    },
    Baseline {
        name: "interface_empty_generic_custom",
        steps: 72,
        effects: &[
            ("input", 21),
            ("function", 27),
            ("next", 37),
            ("grouped", 56),
            ("done", 70),
        ],
        holes: &[],
    },
    Baseline {
        name: "interface_empty_generic_inspect",
        steps: 75,
        effects: &[
            ("input", 24),
            ("function", 30),
            ("grouped", 59),
            ("done", 73),
        ],
        holes: &[],
    },
    Baseline {
        name: "interface_unique_native",
        steps: 345,
        effects: &[
            ("input", 38),
            ("function", 44),
            ("key", 58),
            ("key", 80),
            ("key", 102),
            ("grouped", 125),
            ("done", 343),
        ],
        holes: &[],
    },
    Baseline {
        name: "interface_unique_inspect",
        steps: 398,
        effects: &[
            ("input", 42),
            ("function", 48),
            ("next", 67),
            ("key", 76),
            ("next", 102),
            ("key", 111),
            ("next", 137),
            ("key", 146),
            ("grouped", 178),
            ("done", 396),
        ],
        holes: &[],
    },
    Baseline {
        name: "interface_unique_custom",
        steps: 401,
        effects: &[
            ("input", 39),
            ("function", 45),
            ("next", 52),
            ("key", 71),
            ("next", 89),
            ("key", 108),
            ("next", 126),
            ("key", 145),
            ("next", 163),
            ("grouped", 181),
            ("done", 399),
        ],
        holes: &[],
    },
    Baseline {
        name: "interface_unique_generic_native",
        steps: 349,
        effects: &[
            ("input", 38),
            ("function", 44),
            ("key", 61),
            ("key", 83),
            ("key", 105),
            ("grouped", 129),
            ("done", 347),
        ],
        holes: &[],
    },
    Baseline {
        name: "interface_unique_generic_custom",
        steps: 405,
        effects: &[
            ("input", 39),
            ("function", 45),
            ("next", 55),
            ("key", 74),
            ("next", 92),
            ("key", 111),
            ("next", 129),
            ("key", 148),
            ("next", 166),
            ("grouped", 185),
            ("done", 403),
        ],
        holes: &[],
    },
    Baseline {
        name: "interface_unique_generic_inspect",
        steps: 402,
        effects: &[
            ("input", 42),
            ("function", 48),
            ("next", 70),
            ("key", 79),
            ("next", 105),
            ("key", 114),
            ("next", 140),
            ("key", 149),
            ("grouped", 182),
            ("done", 400),
        ],
        holes: &[],
    },
];
