// Observed at 3ee6486 before native grouping.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "nominal_empty_native",
        steps: 57,
        effects: &[
            ("input", 20),
            ("function", 26),
            ("grouped", 41),
            ("done", 55),
        ],
        holes: &[],
    },
    Baseline {
        name: "nominal_empty_inspect",
        steps: 71,
        effects: &[
            ("input", 24),
            ("function", 30),
            ("grouped", 55),
            ("done", 69),
        ],
        holes: &[],
    },
    Baseline {
        name: "nominal_empty_custom",
        steps: 68,
        effects: &[
            ("input", 21),
            ("function", 27),
            ("next", 34),
            ("grouped", 52),
            ("done", 66),
        ],
        holes: &[],
    },
    Baseline {
        name: "nominal_empty_generic_native",
        steps: 61,
        effects: &[
            ("input", 20),
            ("function", 26),
            ("grouped", 45),
            ("done", 59),
        ],
        holes: &[],
    },
    Baseline {
        name: "nominal_empty_generic_custom",
        steps: 72,
        effects: &[
            ("input", 21),
            ("function", 27),
            ("next", 37),
            ("grouped", 56),
            ("done", 70),
        ],
        holes: &[],
    },
    Baseline {
        name: "nominal_empty_generic_inspect",
        steps: 75,
        effects: &[
            ("input", 24),
            ("function", 30),
            ("grouped", 59),
            ("done", 73),
        ],
        holes: &[],
    },
    Baseline {
        name: "nominal_unique_native",
        steps: 651,
        effects: &[
            ("input", 38),
            ("function", 44),
            ("key", 58),
            ("hash", 70),
            ("hash", 93),
            ("key", 116),
            ("hash", 128),
            ("eq", 150),
            ("hash", 177),
            ("eq", 199),
            ("key", 226),
            ("hash", 238),
            ("eq", 260),
            ("eq", 286),
            ("hash", 313),
            ("eq", 335),
            ("eq", 361),
            ("grouped", 389),
            ("done", 649),
        ],
        holes: &[],
    },
    Baseline {
        name: "nominal_unique_inspect",
        steps: 704,
        effects: &[
            ("input", 42),
            ("function", 48),
            ("next", 67),
            ("key", 76),
            ("hash", 88),
            ("hash", 111),
            ("next", 138),
            ("key", 147),
            ("hash", 159),
            ("eq", 181),
            ("hash", 208),
            ("eq", 230),
            ("next", 261),
            ("key", 270),
            ("hash", 282),
            ("eq", 304),
            ("eq", 330),
            ("hash", 357),
            ("eq", 379),
            ("eq", 405),
            ("grouped", 442),
            ("done", 702),
        ],
        holes: &[],
    },
    Baseline {
        name: "nominal_unique_custom",
        steps: 707,
        effects: &[
            ("input", 39),
            ("function", 45),
            ("next", 52),
            ("key", 71),
            ("hash", 83),
            ("hash", 106),
            ("next", 125),
            ("key", 144),
            ("hash", 156),
            ("eq", 178),
            ("hash", 205),
            ("eq", 227),
            ("next", 250),
            ("key", 269),
            ("hash", 281),
            ("eq", 303),
            ("eq", 329),
            ("hash", 356),
            ("eq", 378),
            ("eq", 404),
            ("next", 427),
            ("grouped", 445),
            ("done", 705),
        ],
        holes: &[],
    },
    Baseline {
        name: "nominal_unique_generic_native",
        steps: 655,
        effects: &[
            ("input", 38),
            ("function", 44),
            ("key", 61),
            ("hash", 73),
            ("hash", 96),
            ("key", 119),
            ("hash", 131),
            ("eq", 153),
            ("hash", 180),
            ("eq", 202),
            ("key", 229),
            ("hash", 241),
            ("eq", 263),
            ("eq", 289),
            ("hash", 316),
            ("eq", 338),
            ("eq", 364),
            ("grouped", 393),
            ("done", 653),
        ],
        holes: &[],
    },
    Baseline {
        name: "nominal_unique_generic_custom",
        steps: 711,
        effects: &[
            ("input", 39),
            ("function", 45),
            ("next", 55),
            ("key", 74),
            ("hash", 86),
            ("hash", 109),
            ("next", 128),
            ("key", 147),
            ("hash", 159),
            ("eq", 181),
            ("hash", 208),
            ("eq", 230),
            ("next", 253),
            ("key", 272),
            ("hash", 284),
            ("eq", 306),
            ("eq", 332),
            ("hash", 359),
            ("eq", 381),
            ("eq", 407),
            ("next", 430),
            ("grouped", 449),
            ("done", 709),
        ],
        holes: &[],
    },
    Baseline {
        name: "nominal_unique_generic_inspect",
        steps: 708,
        effects: &[
            ("input", 42),
            ("function", 48),
            ("next", 70),
            ("key", 79),
            ("hash", 91),
            ("hash", 114),
            ("next", 141),
            ("key", 150),
            ("hash", 162),
            ("eq", 184),
            ("hash", 211),
            ("eq", 233),
            ("next", 264),
            ("key", 273),
            ("hash", 285),
            ("eq", 307),
            ("eq", 333),
            ("hash", 360),
            ("eq", 382),
            ("eq", 408),
            ("grouped", 446),
            ("done", 706),
        ],
        holes: &[],
    },
];
