// Observed at 3ee6486 before native grouping.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "option_empty_native",
        steps: 57,
        effects: &[
            ("input", 20),
            ("function", 26),
            ("grouped", 41),
            ("done", 55),
        ],
        holes: &[],
    },
    Baseline {
        name: "option_empty_inspect",
        steps: 71,
        effects: &[
            ("input", 24),
            ("function", 30),
            ("grouped", 55),
            ("done", 69),
        ],
        holes: &[],
    },
    Baseline {
        name: "option_empty_custom",
        steps: 68,
        effects: &[
            ("input", 21),
            ("function", 27),
            ("next", 34),
            ("grouped", 52),
            ("done", 66),
        ],
        holes: &[],
    },
    Baseline {
        name: "option_empty_generic_native",
        steps: 61,
        effects: &[
            ("input", 20),
            ("function", 26),
            ("grouped", 45),
            ("done", 59),
        ],
        holes: &[],
    },
    Baseline {
        name: "option_empty_generic_custom",
        steps: 72,
        effects: &[
            ("input", 21),
            ("function", 27),
            ("next", 37),
            ("grouped", 56),
            ("done", 70),
        ],
        holes: &[],
    },
    Baseline {
        name: "option_empty_generic_inspect",
        steps: 75,
        effects: &[
            ("input", 24),
            ("function", 30),
            ("grouped", 59),
            ("done", 73),
        ],
        holes: &[],
    },
    Baseline {
        name: "option_unique_native",
        steps: 882,
        effects: &[
            ("input", 41),
            ("function", 47),
            ("key", 61),
            ("hash", 79),
            ("hash", 113),
            ("key", 141),
            ("hash", 159),
            ("eq", 195),
            ("hash", 235),
            ("eq", 271),
            ("key", 305),
            ("hash", 323),
            ("eq", 359),
            ("eq", 401),
            ("hash", 441),
            ("eq", 477),
            ("eq", 519),
            ("grouped", 554),
            ("done", 880),
        ],
        holes: &[],
    },
    Baseline {
        name: "option_unique_inspect",
        steps: 935,
        effects: &[
            ("input", 45),
            ("function", 51),
            ("next", 70),
            ("key", 79),
            ("hash", 97),
            ("hash", 131),
            ("next", 163),
            ("key", 172),
            ("hash", 190),
            ("eq", 226),
            ("hash", 266),
            ("eq", 302),
            ("next", 340),
            ("key", 349),
            ("hash", 367),
            ("eq", 403),
            ("eq", 445),
            ("hash", 485),
            ("eq", 521),
            ("eq", 563),
            ("grouped", 607),
            ("done", 933),
        ],
        holes: &[],
    },
    Baseline {
        name: "option_unique_custom",
        steps: 938,
        effects: &[
            ("input", 42),
            ("function", 48),
            ("next", 55),
            ("key", 74),
            ("hash", 92),
            ("hash", 126),
            ("next", 150),
            ("key", 169),
            ("hash", 187),
            ("eq", 223),
            ("hash", 263),
            ("eq", 299),
            ("next", 329),
            ("key", 348),
            ("hash", 366),
            ("eq", 402),
            ("eq", 444),
            ("hash", 484),
            ("eq", 520),
            ("eq", 562),
            ("next", 592),
            ("grouped", 610),
            ("done", 936),
        ],
        holes: &[],
    },
    Baseline {
        name: "option_unique_generic_native",
        steps: 886,
        effects: &[
            ("input", 41),
            ("function", 47),
            ("key", 64),
            ("hash", 82),
            ("hash", 116),
            ("key", 144),
            ("hash", 162),
            ("eq", 198),
            ("hash", 238),
            ("eq", 274),
            ("key", 308),
            ("hash", 326),
            ("eq", 362),
            ("eq", 404),
            ("hash", 444),
            ("eq", 480),
            ("eq", 522),
            ("grouped", 558),
            ("done", 884),
        ],
        holes: &[],
    },
    Baseline {
        name: "option_unique_generic_custom",
        steps: 942,
        effects: &[
            ("input", 42),
            ("function", 48),
            ("next", 58),
            ("key", 77),
            ("hash", 95),
            ("hash", 129),
            ("next", 153),
            ("key", 172),
            ("hash", 190),
            ("eq", 226),
            ("hash", 266),
            ("eq", 302),
            ("next", 332),
            ("key", 351),
            ("hash", 369),
            ("eq", 405),
            ("eq", 447),
            ("hash", 487),
            ("eq", 523),
            ("eq", 565),
            ("next", 595),
            ("grouped", 614),
            ("done", 940),
        ],
        holes: &[],
    },
    Baseline {
        name: "option_unique_generic_inspect",
        steps: 939,
        effects: &[
            ("input", 45),
            ("function", 51),
            ("next", 73),
            ("key", 82),
            ("hash", 100),
            ("hash", 134),
            ("next", 166),
            ("key", 175),
            ("hash", 193),
            ("eq", 229),
            ("hash", 269),
            ("eq", 305),
            ("next", 343),
            ("key", 352),
            ("hash", 370),
            ("eq", 406),
            ("eq", 448),
            ("hash", 488),
            ("eq", 524),
            ("eq", 566),
            ("grouped", 611),
            ("done", 937),
        ],
        holes: &[],
    },
];
