// Observed at 3ee6486 before native grouping.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "scalar_repeat_native",
        steps: 403,
        effects: &[
            ("input", 36),
            ("function", 42),
            ("key", 56),
            ("key", 78),
            ("key", 100),
            ("key", 121),
            ("grouped", 144),
            ("done", 401),
        ],
        holes: &[],
    },
    Baseline {
        name: "scalar_repeat_inspect",
        steps: 469,
        effects: &[
            ("input", 40),
            ("function", 46),
            ("next", 65),
            ("key", 74),
            ("next", 100),
            ("key", 109),
            ("next", 135),
            ("key", 144),
            ("next", 169),
            ("key", 178),
            ("grouped", 210),
            ("done", 467),
        ],
        holes: &[],
    },
    Baseline {
        name: "scalar_repeat_custom",
        steps: 474,
        effects: &[
            ("input", 37),
            ("function", 43),
            ("next", 50),
            ("key", 69),
            ("next", 87),
            ("key", 106),
            ("next", 124),
            ("key", 143),
            ("next", 160),
            ("key", 179),
            ("next", 197),
            ("grouped", 215),
            ("done", 472),
        ],
        holes: &[],
    },
    Baseline {
        name: "scalar_repeat_generic_native",
        steps: 407,
        effects: &[
            ("input", 36),
            ("function", 42),
            ("key", 59),
            ("key", 81),
            ("key", 103),
            ("key", 124),
            ("grouped", 148),
            ("done", 405),
        ],
        holes: &[],
    },
    Baseline {
        name: "scalar_repeat_generic_custom",
        steps: 478,
        effects: &[
            ("input", 37),
            ("function", 43),
            ("next", 53),
            ("key", 72),
            ("next", 90),
            ("key", 109),
            ("next", 127),
            ("key", 146),
            ("next", 163),
            ("key", 182),
            ("next", 200),
            ("grouped", 219),
            ("done", 476),
        ],
        holes: &[],
    },
    Baseline {
        name: "scalar_repeat_generic_inspect",
        steps: 473,
        effects: &[
            ("input", 40),
            ("function", 46),
            ("next", 68),
            ("key", 77),
            ("next", 103),
            ("key", 112),
            ("next", 138),
            ("key", 147),
            ("next", 172),
            ("key", 181),
            ("grouped", 214),
            ("done", 471),
        ],
        holes: &[],
    },
    Baseline {
        name: "scalar_all_native",
        steps: 279,
        effects: &[
            ("input", 32),
            ("function", 38),
            ("key", 52),
            ("key", 74),
            ("key", 95),
            ("grouped", 117),
            ("done", 277),
        ],
        holes: &[],
    },
    Baseline {
        name: "scalar_all_inspect",
        steps: 332,
        effects: &[
            ("input", 36),
            ("function", 42),
            ("next", 61),
            ("key", 70),
            ("next", 96),
            ("key", 105),
            ("next", 130),
            ("key", 139),
            ("grouped", 170),
            ("done", 330),
        ],
        holes: &[],
    },
    Baseline {
        name: "scalar_all_custom",
        steps: 335,
        effects: &[
            ("input", 33),
            ("function", 39),
            ("next", 46),
            ("key", 65),
            ("next", 83),
            ("key", 102),
            ("next", 119),
            ("key", 138),
            ("next", 155),
            ("grouped", 173),
            ("done", 333),
        ],
        holes: &[],
    },
    Baseline {
        name: "scalar_all_generic_native",
        steps: 283,
        effects: &[
            ("input", 32),
            ("function", 38),
            ("key", 55),
            ("key", 77),
            ("key", 98),
            ("grouped", 121),
            ("done", 281),
        ],
        holes: &[],
    },
    Baseline {
        name: "scalar_all_generic_custom",
        steps: 339,
        effects: &[
            ("input", 33),
            ("function", 39),
            ("next", 49),
            ("key", 68),
            ("next", 86),
            ("key", 105),
            ("next", 122),
            ("key", 141),
            ("next", 158),
            ("grouped", 177),
            ("done", 337),
        ],
        holes: &[],
    },
    Baseline {
        name: "scalar_all_generic_inspect",
        steps: 336,
        effects: &[
            ("input", 36),
            ("function", 42),
            ("next", 64),
            ("key", 73),
            ("next", 99),
            ("key", 108),
            ("next", 133),
            ("key", 142),
            ("grouped", 174),
            ("done", 334),
        ],
        holes: &[],
    },
];
