// Observed at 3ee6486 before native grouping.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "scalar_empty_native",
        steps: 57,
        effects: &[
            ("input", 20),
            ("function", 26),
            ("grouped", 41),
            ("done", 55),
        ],
        holes: &[],
    },
    Baseline {
        name: "scalar_empty_inspect",
        steps: 71,
        effects: &[
            ("input", 24),
            ("function", 30),
            ("grouped", 55),
            ("done", 69),
        ],
        holes: &[],
    },
    Baseline {
        name: "scalar_empty_custom",
        steps: 68,
        effects: &[
            ("input", 21),
            ("function", 27),
            ("next", 34),
            ("grouped", 52),
            ("done", 66),
        ],
        holes: &[],
    },
    Baseline {
        name: "scalar_empty_generic_native",
        steps: 61,
        effects: &[
            ("input", 20),
            ("function", 26),
            ("grouped", 45),
            ("done", 59),
        ],
        holes: &[],
    },
    Baseline {
        name: "scalar_empty_generic_custom",
        steps: 72,
        effects: &[
            ("input", 21),
            ("function", 27),
            ("next", 37),
            ("grouped", 56),
            ("done", 70),
        ],
        holes: &[],
    },
    Baseline {
        name: "scalar_empty_generic_inspect",
        steps: 75,
        effects: &[
            ("input", 24),
            ("function", 30),
            ("grouped", 59),
            ("done", 73),
        ],
        holes: &[],
    },
    Baseline {
        name: "scalar_unique_native",
        steps: 339,
        effects: &[
            ("input", 32),
            ("function", 38),
            ("key", 52),
            ("key", 74),
            ("key", 96),
            ("grouped", 119),
            ("done", 337),
        ],
        holes: &[],
    },
    Baseline {
        name: "scalar_unique_inspect",
        steps: 392,
        effects: &[
            ("input", 36),
            ("function", 42),
            ("next", 61),
            ("key", 70),
            ("next", 96),
            ("key", 105),
            ("next", 131),
            ("key", 140),
            ("grouped", 172),
            ("done", 390),
        ],
        holes: &[],
    },
    Baseline {
        name: "scalar_unique_custom",
        steps: 395,
        effects: &[
            ("input", 33),
            ("function", 39),
            ("next", 46),
            ("key", 65),
            ("next", 83),
            ("key", 102),
            ("next", 120),
            ("key", 139),
            ("next", 157),
            ("grouped", 175),
            ("done", 393),
        ],
        holes: &[],
    },
    Baseline {
        name: "scalar_unique_generic_native",
        steps: 343,
        effects: &[
            ("input", 32),
            ("function", 38),
            ("key", 55),
            ("key", 77),
            ("key", 99),
            ("grouped", 123),
            ("done", 341),
        ],
        holes: &[],
    },
    Baseline {
        name: "scalar_unique_generic_custom",
        steps: 399,
        effects: &[
            ("input", 33),
            ("function", 39),
            ("next", 49),
            ("key", 68),
            ("next", 86),
            ("key", 105),
            ("next", 123),
            ("key", 142),
            ("next", 160),
            ("grouped", 179),
            ("done", 397),
        ],
        holes: &[],
    },
    Baseline {
        name: "scalar_unique_generic_inspect",
        steps: 396,
        effects: &[
            ("input", 36),
            ("function", 42),
            ("next", 64),
            ("key", 73),
            ("next", 99),
            ("key", 108),
            ("next", 134),
            ("key", 143),
            ("grouped", 176),
            ("done", 394),
        ],
        holes: &[],
    },
];
