// Observed at 3ee6486 before native grouping.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "tuple_empty_native",
        steps: 57,
        effects: &[
            ("input", 20),
            ("function", 26),
            ("grouped", 41),
            ("done", 55),
        ],
        holes: &[],
    },
    Baseline {
        name: "tuple_empty_inspect",
        steps: 71,
        effects: &[
            ("input", 24),
            ("function", 30),
            ("grouped", 55),
            ("done", 69),
        ],
        holes: &[],
    },
    Baseline {
        name: "tuple_empty_custom",
        steps: 68,
        effects: &[
            ("input", 21),
            ("function", 27),
            ("next", 34),
            ("grouped", 52),
            ("done", 66),
        ],
        holes: &[],
    },
    Baseline {
        name: "tuple_empty_generic_native",
        steps: 61,
        effects: &[
            ("input", 20),
            ("function", 26),
            ("grouped", 45),
            ("done", 59),
        ],
        holes: &[],
    },
    Baseline {
        name: "tuple_empty_generic_custom",
        steps: 72,
        effects: &[
            ("input", 21),
            ("function", 27),
            ("next", 37),
            ("grouped", 56),
            ("done", 70),
        ],
        holes: &[],
    },
    Baseline {
        name: "tuple_empty_generic_inspect",
        steps: 75,
        effects: &[
            ("input", 24),
            ("function", 30),
            ("grouped", 59),
            ("done", 73),
        ],
        holes: &[],
    },
    Baseline {
        name: "tuple_unique_native",
        steps: 813,
        effects: &[
            ("input", 44),
            ("function", 50),
            ("key", 64),
            ("hash", 82),
            ("hash", 115),
            ("key", 142),
            ("hash", 160),
            ("eq", 195),
            ("hash", 233),
            ("eq", 268),
            ("key", 300),
            ("hash", 318),
            ("eq", 353),
            ("eq", 393),
            ("hash", 431),
            ("eq", 466),
            ("eq", 506),
            ("grouped", 539),
            ("done", 811),
        ],
        holes: &[],
    },
    Baseline {
        name: "tuple_unique_inspect",
        steps: 866,
        effects: &[
            ("input", 48),
            ("function", 54),
            ("next", 73),
            ("key", 82),
            ("hash", 100),
            ("hash", 133),
            ("next", 164),
            ("key", 173),
            ("hash", 191),
            ("eq", 226),
            ("hash", 264),
            ("eq", 299),
            ("next", 335),
            ("key", 344),
            ("hash", 362),
            ("eq", 397),
            ("eq", 437),
            ("hash", 475),
            ("eq", 510),
            ("eq", 550),
            ("grouped", 592),
            ("done", 864),
        ],
        holes: &[],
    },
    Baseline {
        name: "tuple_unique_custom",
        steps: 869,
        effects: &[
            ("input", 45),
            ("function", 51),
            ("next", 58),
            ("key", 77),
            ("hash", 95),
            ("hash", 128),
            ("next", 151),
            ("key", 170),
            ("hash", 188),
            ("eq", 223),
            ("hash", 261),
            ("eq", 296),
            ("next", 324),
            ("key", 343),
            ("hash", 361),
            ("eq", 396),
            ("eq", 436),
            ("hash", 474),
            ("eq", 509),
            ("eq", 549),
            ("next", 577),
            ("grouped", 595),
            ("done", 867),
        ],
        holes: &[],
    },
    Baseline {
        name: "tuple_unique_generic_native",
        steps: 817,
        effects: &[
            ("input", 44),
            ("function", 50),
            ("key", 67),
            ("hash", 85),
            ("hash", 118),
            ("key", 145),
            ("hash", 163),
            ("eq", 198),
            ("hash", 236),
            ("eq", 271),
            ("key", 303),
            ("hash", 321),
            ("eq", 356),
            ("eq", 396),
            ("hash", 434),
            ("eq", 469),
            ("eq", 509),
            ("grouped", 543),
            ("done", 815),
        ],
        holes: &[],
    },
    Baseline {
        name: "tuple_unique_generic_custom",
        steps: 873,
        effects: &[
            ("input", 45),
            ("function", 51),
            ("next", 61),
            ("key", 80),
            ("hash", 98),
            ("hash", 131),
            ("next", 154),
            ("key", 173),
            ("hash", 191),
            ("eq", 226),
            ("hash", 264),
            ("eq", 299),
            ("next", 327),
            ("key", 346),
            ("hash", 364),
            ("eq", 399),
            ("eq", 439),
            ("hash", 477),
            ("eq", 512),
            ("eq", 552),
            ("next", 580),
            ("grouped", 599),
            ("done", 871),
        ],
        holes: &[],
    },
    Baseline {
        name: "tuple_unique_generic_inspect",
        steps: 870,
        effects: &[
            ("input", 48),
            ("function", 54),
            ("next", 76),
            ("key", 85),
            ("hash", 103),
            ("hash", 136),
            ("next", 167),
            ("key", 176),
            ("hash", 194),
            ("eq", 229),
            ("hash", 267),
            ("eq", 302),
            ("next", 338),
            ("key", 347),
            ("hash", 365),
            ("eq", 400),
            ("eq", 440),
            ("hash", 478),
            ("eq", 513),
            ("eq", 553),
            ("grouped", 596),
            ("done", 868),
        ],
        holes: &[],
    },
];
