use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "difference_nominal_native_empty",
        steps: 108,
        effects: &[
            ("left", 32),
            ("right", 38),
            ("r-iter", 54),
            ("result", 79),
            ("done", 106),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_nominal_native_all",
        steps: 322,
        effects: &[
            ("hash", 27),
            ("hash", 51),
            ("eq", 73),
            ("left", 118),
            ("right", 124),
            ("r-iter", 140),
            ("r-contains", 169),
            ("eq", 189),
            ("r-contains", 222),
            ("eq", 242),
            ("eq", 264),
            ("result", 293),
            ("done", 320),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_nominal_native_overlap",
        steps: 355,
        effects: &[
            ("hash", 27),
            ("hash", 51),
            ("eq", 73),
            ("left", 115),
            ("right", 121),
            ("r-iter", 137),
            ("r-contains", 166),
            ("eq", 186),
            ("eq", 208),
            ("hash", 233),
            ("r-contains", 263),
            ("eq", 283),
            ("result", 312),
            ("done", 353),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_nominal_native_disjoint",
        steps: 439,
        effects: &[
            ("hash", 27),
            ("hash", 51),
            ("eq", 73),
            ("left", 115),
            ("right", 121),
            ("r-iter", 137),
            ("r-contains", 166),
            ("eq", 186),
            ("eq", 208),
            ("hash", 233),
            ("r-contains", 263),
            ("eq", 283),
            ("eq", 305),
            ("hash", 330),
            ("eq", 352),
            ("result", 382),
            ("done", 437),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_nominal_native_same",
        steps: 293,
        effects: &[
            ("hash", 27),
            ("hash", 51),
            ("eq", 73),
            ("left", 107),
            ("right", 113),
            ("hash", 139),
            ("eq", 161),
            ("hash", 189),
            ("eq", 211),
            ("eq", 237),
            ("result", 264),
            ("done", 291),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_nominal_proxy_empty",
        steps: 122,
        effects: &[
            ("left", 18),
            ("right", 24),
            ("l-iter", 36),
            ("r-iter", 59),
            ("result", 93),
            ("done", 120),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_nominal_proxy_all",
        steps: 302,
        effects: &[
            ("left", 30),
            ("right", 36),
            ("l-iter", 48),
            ("r-iter", 71),
            ("l-next", 104),
            ("r-contains", 120),
            ("eq", 140),
            ("l-next", 177),
            ("r-contains", 193),
            ("eq", 213),
            ("eq", 235),
            ("result", 273),
            ("done", 300),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_nominal_proxy_overlap",
        steps: 335,
        effects: &[
            ("left", 27),
            ("right", 33),
            ("l-iter", 45),
            ("r-iter", 68),
            ("l-next", 101),
            ("r-contains", 117),
            ("eq", 137),
            ("eq", 159),
            ("hash", 184),
            ("l-next", 218),
            ("r-contains", 234),
            ("eq", 254),
            ("result", 292),
            ("done", 333),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_nominal_proxy_disjoint",
        steps: 419,
        effects: &[
            ("left", 27),
            ("right", 33),
            ("l-iter", 45),
            ("r-iter", 68),
            ("l-next", 101),
            ("r-contains", 117),
            ("eq", 137),
            ("eq", 159),
            ("hash", 184),
            ("l-next", 218),
            ("r-contains", 234),
            ("eq", 254),
            ("eq", 276),
            ("hash", 301),
            ("eq", 323),
            ("result", 362),
            ("done", 417),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_nominal_proxy_same",
        steps: 291,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 37),
            ("l-iter", 60),
            ("l-next", 93),
            ("l-contains", 109),
            ("eq", 129),
            ("l-next", 166),
            ("l-contains", 182),
            ("eq", 202),
            ("eq", 224),
            ("result", 262),
            ("done", 289),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_nominal_generic_empty",
        steps: 126,
        effects: &[
            ("left", 18),
            ("right", 24),
            ("l-iter", 39),
            ("r-iter", 62),
            ("result", 97),
            ("done", 124),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_nominal_generic_all",
        steps: 306,
        effects: &[
            ("left", 30),
            ("right", 36),
            ("l-iter", 51),
            ("r-iter", 74),
            ("l-next", 107),
            ("r-contains", 123),
            ("eq", 143),
            ("l-next", 180),
            ("r-contains", 196),
            ("eq", 216),
            ("eq", 238),
            ("result", 277),
            ("done", 304),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_nominal_generic_overlap",
        steps: 339,
        effects: &[
            ("left", 27),
            ("right", 33),
            ("l-iter", 48),
            ("r-iter", 71),
            ("l-next", 104),
            ("r-contains", 120),
            ("eq", 140),
            ("eq", 162),
            ("hash", 187),
            ("l-next", 221),
            ("r-contains", 237),
            ("eq", 257),
            ("result", 296),
            ("done", 337),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_nominal_generic_disjoint",
        steps: 423,
        effects: &[
            ("left", 27),
            ("right", 33),
            ("l-iter", 48),
            ("r-iter", 71),
            ("l-next", 104),
            ("r-contains", 120),
            ("eq", 140),
            ("eq", 162),
            ("hash", 187),
            ("l-next", 221),
            ("r-contains", 237),
            ("eq", 257),
            ("eq", 279),
            ("hash", 304),
            ("eq", 326),
            ("result", 366),
            ("done", 421),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_nominal_generic_same",
        steps: 295,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 40),
            ("l-iter", 63),
            ("l-next", 96),
            ("l-contains", 112),
            ("eq", 132),
            ("l-next", 169),
            ("l-contains", 185),
            ("eq", 205),
            ("eq", 227),
            ("result", 266),
            ("done", 293),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_nominal_dynamic_empty",
        steps: 125,
        effects: &[
            ("left", 21),
            ("right", 27),
            ("l-iter", 39),
            ("r-iter", 62),
            ("result", 96),
            ("done", 123),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_nominal_dynamic_all",
        steps: 305,
        effects: &[
            ("left", 33),
            ("right", 39),
            ("l-iter", 51),
            ("r-iter", 74),
            ("l-next", 107),
            ("r-contains", 123),
            ("eq", 143),
            ("l-next", 180),
            ("r-contains", 196),
            ("eq", 216),
            ("eq", 238),
            ("result", 276),
            ("done", 303),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_nominal_dynamic_overlap",
        steps: 338,
        effects: &[
            ("left", 30),
            ("right", 36),
            ("l-iter", 48),
            ("r-iter", 71),
            ("l-next", 104),
            ("r-contains", 120),
            ("eq", 140),
            ("eq", 162),
            ("hash", 187),
            ("l-next", 221),
            ("r-contains", 237),
            ("eq", 257),
            ("result", 295),
            ("done", 336),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_nominal_dynamic_disjoint",
        steps: 422,
        effects: &[
            ("left", 30),
            ("right", 36),
            ("l-iter", 48),
            ("r-iter", 71),
            ("l-next", 104),
            ("r-contains", 120),
            ("eq", 140),
            ("eq", 162),
            ("hash", 187),
            ("l-next", 221),
            ("r-contains", 237),
            ("eq", 257),
            ("eq", 279),
            ("hash", 304),
            ("eq", 326),
            ("result", 365),
            ("done", 420),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_nominal_dynamic_same",
        steps: 294,
        effects: &[
            ("left", 22),
            ("right", 28),
            ("l-iter", 40),
            ("l-iter", 63),
            ("l-next", 96),
            ("l-contains", 112),
            ("eq", 132),
            ("l-next", 169),
            ("l-contains", 185),
            ("eq", 205),
            ("eq", 227),
            ("result", 265),
            ("done", 292),
        ],
        holes: &[],
    },
];
