use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "difference_scalar_native_empty",
        steps: 106,
        effects: &[
            ("left", 30),
            ("right", 36),
            ("r-iter", 52),
            ("result", 77),
            ("done", 104),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_scalar_native_all",
        steps: 211,
        effects: &[
            ("left", 46),
            ("right", 52),
            ("r-iter", 68),
            ("r-contains", 97),
            ("r-contains", 137),
            ("result", 182),
            ("done", 209),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_scalar_native_overlap",
        steps: 227,
        effects: &[
            ("left", 45),
            ("right", 51),
            ("r-iter", 67),
            ("r-contains", 96),
            ("r-contains", 149),
            ("result", 185),
            ("done", 225),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_scalar_native_disjoint",
        steps: 253,
        effects: &[
            ("left", 45),
            ("right", 51),
            ("r-iter", 67),
            ("r-contains", 96),
            ("r-contains", 149),
            ("result", 198),
            ("done", 251),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_scalar_native_same",
        steps: 121,
        effects: &[("left", 41), ("right", 47), ("result", 92), ("done", 119)],
        holes: &[],
    },
    Baseline {
        name: "difference_scalar_proxy_empty",
        steps: 120,
        effects: &[
            ("left", 16),
            ("right", 22),
            ("l-iter", 34),
            ("r-iter", 57),
            ("result", 91),
            ("done", 118),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_scalar_proxy_all",
        steps: 253,
        effects: &[
            ("left", 20),
            ("right", 26),
            ("l-iter", 38),
            ("r-iter", 61),
            ("l-next", 94),
            ("r-contains", 110),
            ("l-next", 154),
            ("r-contains", 170),
            ("result", 224),
            ("done", 251),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_scalar_proxy_overlap",
        steps: 269,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 37),
            ("r-iter", 60),
            ("l-next", 93),
            ("r-contains", 109),
            ("l-next", 166),
            ("r-contains", 182),
            ("result", 227),
            ("done", 267),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_scalar_proxy_disjoint",
        steps: 295,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 37),
            ("r-iter", 60),
            ("l-next", 93),
            ("r-contains", 109),
            ("l-next", 166),
            ("r-contains", 182),
            ("result", 240),
            ("done", 293),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_scalar_proxy_same",
        steps: 248,
        effects: &[
            ("left", 15),
            ("right", 21),
            ("l-iter", 33),
            ("l-iter", 56),
            ("l-next", 89),
            ("l-contains", 105),
            ("l-next", 149),
            ("l-contains", 165),
            ("result", 219),
            ("done", 246),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_scalar_generic_empty",
        steps: 124,
        effects: &[
            ("left", 16),
            ("right", 22),
            ("l-iter", 37),
            ("r-iter", 60),
            ("result", 95),
            ("done", 122),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_scalar_generic_all",
        steps: 257,
        effects: &[
            ("left", 20),
            ("right", 26),
            ("l-iter", 41),
            ("r-iter", 64),
            ("l-next", 97),
            ("r-contains", 113),
            ("l-next", 157),
            ("r-contains", 173),
            ("result", 228),
            ("done", 255),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_scalar_generic_overlap",
        steps: 273,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 40),
            ("r-iter", 63),
            ("l-next", 96),
            ("r-contains", 112),
            ("l-next", 169),
            ("r-contains", 185),
            ("result", 231),
            ("done", 271),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_scalar_generic_disjoint",
        steps: 299,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 40),
            ("r-iter", 63),
            ("l-next", 96),
            ("r-contains", 112),
            ("l-next", 169),
            ("r-contains", 185),
            ("result", 244),
            ("done", 297),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_scalar_generic_same",
        steps: 252,
        effects: &[
            ("left", 15),
            ("right", 21),
            ("l-iter", 36),
            ("l-iter", 59),
            ("l-next", 92),
            ("l-contains", 108),
            ("l-next", 152),
            ("l-contains", 168),
            ("result", 223),
            ("done", 250),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_scalar_dynamic_empty",
        steps: 123,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 37),
            ("r-iter", 60),
            ("result", 94),
            ("done", 121),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_scalar_dynamic_all",
        steps: 256,
        effects: &[
            ("left", 23),
            ("right", 29),
            ("l-iter", 41),
            ("r-iter", 64),
            ("l-next", 97),
            ("r-contains", 113),
            ("l-next", 157),
            ("r-contains", 173),
            ("result", 227),
            ("done", 254),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_scalar_dynamic_overlap",
        steps: 272,
        effects: &[
            ("left", 22),
            ("right", 28),
            ("l-iter", 40),
            ("r-iter", 63),
            ("l-next", 96),
            ("r-contains", 112),
            ("l-next", 169),
            ("r-contains", 185),
            ("result", 230),
            ("done", 270),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_scalar_dynamic_disjoint",
        steps: 298,
        effects: &[
            ("left", 22),
            ("right", 28),
            ("l-iter", 40),
            ("r-iter", 63),
            ("l-next", 96),
            ("r-contains", 112),
            ("l-next", 169),
            ("r-contains", 185),
            ("result", 243),
            ("done", 296),
        ],
        holes: &[],
    },
    Baseline {
        name: "difference_scalar_dynamic_same",
        steps: 251,
        effects: &[
            ("left", 18),
            ("right", 24),
            ("l-iter", 36),
            ("l-iter", 59),
            ("l-next", 92),
            ("l-contains", 108),
            ("l-next", 152),
            ("l-contains", 168),
            ("result", 222),
            ("done", 249),
        ],
        holes: &[],
    },
];
