use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "intersection_nominal_native_empty",
        steps: 108,
        effects: &[
            ("left", 32),
            ("right", 38),
            ("r-iter", 54),
            ("result", 79),
            ("done", 106),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_nominal_native_all",
        steps: 416,
        effects: &[
            ("hash", 27),
            ("hash", 51),
            ("eq", 73),
            ("left", 118),
            ("right", 124),
            ("r-iter", 140),
            ("r-contains", 169),
            ("eq", 189),
            ("hash", 212),
            ("r-contains", 242),
            ("eq", 262),
            ("eq", 284),
            ("hash", 307),
            ("eq", 329),
            ("result", 359),
            ("done", 414),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_nominal_native_overlap",
        steps: 355,
        effects: &[
            ("hash", 27),
            ("hash", 51),
            ("eq", 73),
            ("left", 115),
            ("right", 121),
            ("r-iter", 137),
            ("r-contains", 166),
            ("eq", 186),
            ("eq", 208),
            ("r-contains", 243),
            ("eq", 263),
            ("hash", 286),
            ("result", 312),
            ("done", 353),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_nominal_native_disjoint",
        steps: 345,
        effects: &[
            ("hash", 27),
            ("hash", 51),
            ("eq", 73),
            ("left", 115),
            ("right", 121),
            ("r-iter", 137),
            ("r-contains", 166),
            ("eq", 186),
            ("eq", 208),
            ("r-contains", 243),
            ("eq", 263),
            ("eq", 285),
            ("result", 316),
            ("done", 343),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_nominal_native_same",
        steps: 387,
        effects: &[
            ("hash", 27),
            ("hash", 51),
            ("eq", 73),
            ("left", 107),
            ("right", 113),
            ("hash", 139),
            ("eq", 161),
            ("hash", 182),
            ("hash", 209),
            ("eq", 231),
            ("eq", 257),
            ("hash", 278),
            ("eq", 300),
            ("result", 330),
            ("done", 385),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_nominal_proxy_empty",
        steps: 122,
        effects: &[
            ("left", 18),
            ("right", 24),
            ("l-iter", 36),
            ("r-iter", 59),
            ("result", 93),
            ("done", 120),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_nominal_proxy_all",
        steps: 396,
        effects: &[
            ("left", 30),
            ("right", 36),
            ("l-iter", 48),
            ("r-iter", 71),
            ("l-next", 104),
            ("r-contains", 120),
            ("eq", 140),
            ("hash", 163),
            ("l-next", 197),
            ("r-contains", 213),
            ("eq", 233),
            ("eq", 255),
            ("hash", 278),
            ("eq", 300),
            ("result", 339),
            ("done", 394),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_nominal_proxy_overlap",
        steps: 335,
        effects: &[
            ("left", 27),
            ("right", 33),
            ("l-iter", 45),
            ("r-iter", 68),
            ("l-next", 101),
            ("r-contains", 117),
            ("eq", 137),
            ("eq", 159),
            ("l-next", 198),
            ("r-contains", 214),
            ("eq", 234),
            ("hash", 257),
            ("result", 292),
            ("done", 333),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_nominal_proxy_disjoint",
        steps: 325,
        effects: &[
            ("left", 27),
            ("right", 33),
            ("l-iter", 45),
            ("r-iter", 68),
            ("l-next", 101),
            ("r-contains", 117),
            ("eq", 137),
            ("eq", 159),
            ("l-next", 198),
            ("r-contains", 214),
            ("eq", 234),
            ("eq", 256),
            ("result", 296),
            ("done", 323),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_nominal_proxy_same",
        steps: 385,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 37),
            ("l-iter", 60),
            ("l-next", 93),
            ("l-contains", 109),
            ("eq", 129),
            ("hash", 152),
            ("l-next", 186),
            ("l-contains", 202),
            ("eq", 222),
            ("eq", 244),
            ("hash", 267),
            ("eq", 289),
            ("result", 328),
            ("done", 383),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_nominal_generic_empty",
        steps: 126,
        effects: &[
            ("left", 18),
            ("right", 24),
            ("l-iter", 39),
            ("r-iter", 62),
            ("result", 97),
            ("done", 124),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_nominal_generic_all",
        steps: 400,
        effects: &[
            ("left", 30),
            ("right", 36),
            ("l-iter", 51),
            ("r-iter", 74),
            ("l-next", 107),
            ("r-contains", 123),
            ("eq", 143),
            ("hash", 166),
            ("l-next", 200),
            ("r-contains", 216),
            ("eq", 236),
            ("eq", 258),
            ("hash", 281),
            ("eq", 303),
            ("result", 343),
            ("done", 398),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_nominal_generic_overlap",
        steps: 339,
        effects: &[
            ("left", 27),
            ("right", 33),
            ("l-iter", 48),
            ("r-iter", 71),
            ("l-next", 104),
            ("r-contains", 120),
            ("eq", 140),
            ("eq", 162),
            ("l-next", 201),
            ("r-contains", 217),
            ("eq", 237),
            ("hash", 260),
            ("result", 296),
            ("done", 337),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_nominal_generic_disjoint",
        steps: 329,
        effects: &[
            ("left", 27),
            ("right", 33),
            ("l-iter", 48),
            ("r-iter", 71),
            ("l-next", 104),
            ("r-contains", 120),
            ("eq", 140),
            ("eq", 162),
            ("l-next", 201),
            ("r-contains", 217),
            ("eq", 237),
            ("eq", 259),
            ("result", 300),
            ("done", 327),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_nominal_generic_same",
        steps: 389,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 40),
            ("l-iter", 63),
            ("l-next", 96),
            ("l-contains", 112),
            ("eq", 132),
            ("hash", 155),
            ("l-next", 189),
            ("l-contains", 205),
            ("eq", 225),
            ("eq", 247),
            ("hash", 270),
            ("eq", 292),
            ("result", 332),
            ("done", 387),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_nominal_dynamic_empty",
        steps: 125,
        effects: &[
            ("left", 21),
            ("right", 27),
            ("l-iter", 39),
            ("r-iter", 62),
            ("result", 96),
            ("done", 123),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_nominal_dynamic_all",
        steps: 399,
        effects: &[
            ("left", 33),
            ("right", 39),
            ("l-iter", 51),
            ("r-iter", 74),
            ("l-next", 107),
            ("r-contains", 123),
            ("eq", 143),
            ("hash", 166),
            ("l-next", 200),
            ("r-contains", 216),
            ("eq", 236),
            ("eq", 258),
            ("hash", 281),
            ("eq", 303),
            ("result", 342),
            ("done", 397),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_nominal_dynamic_overlap",
        steps: 338,
        effects: &[
            ("left", 30),
            ("right", 36),
            ("l-iter", 48),
            ("r-iter", 71),
            ("l-next", 104),
            ("r-contains", 120),
            ("eq", 140),
            ("eq", 162),
            ("l-next", 201),
            ("r-contains", 217),
            ("eq", 237),
            ("hash", 260),
            ("result", 295),
            ("done", 336),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_nominal_dynamic_disjoint",
        steps: 328,
        effects: &[
            ("left", 30),
            ("right", 36),
            ("l-iter", 48),
            ("r-iter", 71),
            ("l-next", 104),
            ("r-contains", 120),
            ("eq", 140),
            ("eq", 162),
            ("l-next", 201),
            ("r-contains", 217),
            ("eq", 237),
            ("eq", 259),
            ("result", 299),
            ("done", 326),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_nominal_dynamic_same",
        steps: 388,
        effects: &[
            ("left", 22),
            ("right", 28),
            ("l-iter", 40),
            ("l-iter", 63),
            ("l-next", 96),
            ("l-contains", 112),
            ("eq", 132),
            ("hash", 155),
            ("l-next", 189),
            ("l-contains", 205),
            ("eq", 225),
            ("eq", 247),
            ("hash", 270),
            ("eq", 292),
            ("result", 331),
            ("done", 386),
        ],
        holes: &[],
    },
];
