use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "intersection_scalar_native_empty",
        steps: 106,
        effects: &[
            ("left", 30),
            ("right", 36),
            ("r-iter", 52),
            ("result", 77),
            ("done", 104),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_scalar_native_all",
        steps: 241,
        effects: &[
            ("left", 46),
            ("right", 52),
            ("r-iter", 68),
            ("r-contains", 97),
            ("r-contains", 139),
            ("result", 186),
            ("done", 239),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_scalar_native_overlap",
        steps: 227,
        effects: &[
            ("left", 45),
            ("right", 51),
            ("r-iter", 67),
            ("r-contains", 96),
            ("r-contains", 147),
            ("result", 185),
            ("done", 225),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_scalar_native_disjoint",
        steps: 223,
        effects: &[
            ("left", 45),
            ("right", 51),
            ("r-iter", 67),
            ("r-contains", 96),
            ("r-contains", 147),
            ("result", 194),
            ("done", 221),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_scalar_native_same",
        steps: 151,
        effects: &[("left", 41), ("right", 47), ("result", 96), ("done", 149)],
        holes: &[],
    },
    Baseline {
        name: "intersection_scalar_proxy_empty",
        steps: 120,
        effects: &[
            ("left", 16),
            ("right", 22),
            ("l-iter", 34),
            ("r-iter", 57),
            ("result", 91),
            ("done", 118),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_scalar_proxy_all",
        steps: 283,
        effects: &[
            ("left", 20),
            ("right", 26),
            ("l-iter", 38),
            ("r-iter", 61),
            ("l-next", 94),
            ("r-contains", 110),
            ("l-next", 156),
            ("r-contains", 172),
            ("result", 228),
            ("done", 281),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_scalar_proxy_overlap",
        steps: 269,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 37),
            ("r-iter", 60),
            ("l-next", 93),
            ("r-contains", 109),
            ("l-next", 164),
            ("r-contains", 180),
            ("result", 227),
            ("done", 267),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_scalar_proxy_disjoint",
        steps: 265,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 37),
            ("r-iter", 60),
            ("l-next", 93),
            ("r-contains", 109),
            ("l-next", 164),
            ("r-contains", 180),
            ("result", 236),
            ("done", 263),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_scalar_proxy_same",
        steps: 278,
        effects: &[
            ("left", 15),
            ("right", 21),
            ("l-iter", 33),
            ("l-iter", 56),
            ("l-next", 89),
            ("l-contains", 105),
            ("l-next", 151),
            ("l-contains", 167),
            ("result", 223),
            ("done", 276),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_scalar_generic_empty",
        steps: 124,
        effects: &[
            ("left", 16),
            ("right", 22),
            ("l-iter", 37),
            ("r-iter", 60),
            ("result", 95),
            ("done", 122),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_scalar_generic_all",
        steps: 287,
        effects: &[
            ("left", 20),
            ("right", 26),
            ("l-iter", 41),
            ("r-iter", 64),
            ("l-next", 97),
            ("r-contains", 113),
            ("l-next", 159),
            ("r-contains", 175),
            ("result", 232),
            ("done", 285),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_scalar_generic_overlap",
        steps: 273,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 40),
            ("r-iter", 63),
            ("l-next", 96),
            ("r-contains", 112),
            ("l-next", 167),
            ("r-contains", 183),
            ("result", 231),
            ("done", 271),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_scalar_generic_disjoint",
        steps: 269,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 40),
            ("r-iter", 63),
            ("l-next", 96),
            ("r-contains", 112),
            ("l-next", 167),
            ("r-contains", 183),
            ("result", 240),
            ("done", 267),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_scalar_generic_same",
        steps: 282,
        effects: &[
            ("left", 15),
            ("right", 21),
            ("l-iter", 36),
            ("l-iter", 59),
            ("l-next", 92),
            ("l-contains", 108),
            ("l-next", 154),
            ("l-contains", 170),
            ("result", 227),
            ("done", 280),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_scalar_dynamic_empty",
        steps: 123,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 37),
            ("r-iter", 60),
            ("result", 94),
            ("done", 121),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_scalar_dynamic_all",
        steps: 286,
        effects: &[
            ("left", 23),
            ("right", 29),
            ("l-iter", 41),
            ("r-iter", 64),
            ("l-next", 97),
            ("r-contains", 113),
            ("l-next", 159),
            ("r-contains", 175),
            ("result", 231),
            ("done", 284),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_scalar_dynamic_overlap",
        steps: 272,
        effects: &[
            ("left", 22),
            ("right", 28),
            ("l-iter", 40),
            ("r-iter", 63),
            ("l-next", 96),
            ("r-contains", 112),
            ("l-next", 167),
            ("r-contains", 183),
            ("result", 230),
            ("done", 270),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_scalar_dynamic_disjoint",
        steps: 268,
        effects: &[
            ("left", 22),
            ("right", 28),
            ("l-iter", 40),
            ("r-iter", 63),
            ("l-next", 96),
            ("r-contains", 112),
            ("l-next", 167),
            ("r-contains", 183),
            ("result", 239),
            ("done", 266),
        ],
        holes: &[],
    },
    Baseline {
        name: "intersection_scalar_dynamic_same",
        steps: 281,
        effects: &[
            ("left", 18),
            ("right", 24),
            ("l-iter", 36),
            ("l-iter", 59),
            ("l-next", 92),
            ("l-contains", 108),
            ("l-next", 154),
            ("l-contains", 170),
            ("result", 226),
            ("done", 279),
        ],
        holes: &[],
    },
];
