use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "is_disjoint_nominal_native_empty",
        steps: 88,
        effects: &[
            ("left", 32),
            ("right", 38),
            ("r-iter", 54),
            ("result", 79),
            ("done", 86),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_nominal_native_all",
        steps: 227,
        effects: &[
            ("hash", 27),
            ("hash", 51),
            ("eq", 73),
            ("left", 118),
            ("right", 124),
            ("r-iter", 140),
            ("r-contains", 169),
            ("eq", 189),
            ("result", 218),
            ("done", 225),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_nominal_native_overlap",
        steps: 301,
        effects: &[
            ("hash", 27),
            ("hash", 51),
            ("eq", 73),
            ("left", 115),
            ("right", 121),
            ("r-iter", 137),
            ("r-contains", 166),
            ("eq", 186),
            ("eq", 208),
            ("r-contains", 243),
            ("eq", 263),
            ("result", 292),
            ("done", 299),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_nominal_native_disjoint",
        steps: 325,
        effects: &[
            ("hash", 27),
            ("hash", 51),
            ("eq", 73),
            ("left", 115),
            ("right", 121),
            ("r-iter", 137),
            ("r-contains", 166),
            ("eq", 186),
            ("eq", 208),
            ("r-contains", 243),
            ("eq", 263),
            ("eq", 285),
            ("result", 316),
            ("done", 323),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_nominal_native_same",
        steps: 197,
        effects: &[
            ("hash", 27),
            ("hash", 51),
            ("eq", 73),
            ("left", 107),
            ("right", 113),
            ("hash", 139),
            ("eq", 161),
            ("result", 188),
            ("done", 195),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_nominal_proxy_empty",
        steps: 102,
        effects: &[
            ("left", 18),
            ("right", 24),
            ("l-iter", 36),
            ("r-iter", 59),
            ("result", 93),
            ("done", 100),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_nominal_proxy_all",
        steps: 178,
        effects: &[
            ("left", 30),
            ("right", 36),
            ("l-iter", 48),
            ("r-iter", 71),
            ("l-next", 104),
            ("r-contains", 120),
            ("eq", 140),
            ("result", 169),
            ("done", 176),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_nominal_proxy_overlap",
        steps: 272,
        effects: &[
            ("left", 27),
            ("right", 33),
            ("l-iter", 45),
            ("r-iter", 68),
            ("l-next", 101),
            ("r-contains", 117),
            ("eq", 137),
            ("eq", 159),
            ("l-next", 198),
            ("r-contains", 214),
            ("eq", 234),
            ("result", 263),
            ("done", 270),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_nominal_proxy_disjoint",
        steps: 305,
        effects: &[
            ("left", 27),
            ("right", 33),
            ("l-iter", 45),
            ("r-iter", 68),
            ("l-next", 101),
            ("r-contains", 117),
            ("eq", 137),
            ("eq", 159),
            ("l-next", 198),
            ("r-contains", 214),
            ("eq", 234),
            ("eq", 256),
            ("result", 296),
            ("done", 303),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_nominal_proxy_same",
        steps: 167,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 37),
            ("l-iter", 60),
            ("l-next", 93),
            ("l-contains", 109),
            ("eq", 129),
            ("result", 158),
            ("done", 165),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_nominal_generic_empty",
        steps: 106,
        effects: &[
            ("left", 18),
            ("right", 24),
            ("l-iter", 39),
            ("r-iter", 62),
            ("result", 97),
            ("done", 104),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_nominal_generic_all",
        steps: 182,
        effects: &[
            ("left", 30),
            ("right", 36),
            ("l-iter", 51),
            ("r-iter", 74),
            ("l-next", 107),
            ("r-contains", 123),
            ("eq", 143),
            ("result", 173),
            ("done", 180),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_nominal_generic_overlap",
        steps: 276,
        effects: &[
            ("left", 27),
            ("right", 33),
            ("l-iter", 48),
            ("r-iter", 71),
            ("l-next", 104),
            ("r-contains", 120),
            ("eq", 140),
            ("eq", 162),
            ("l-next", 201),
            ("r-contains", 217),
            ("eq", 237),
            ("result", 267),
            ("done", 274),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_nominal_generic_disjoint",
        steps: 309,
        effects: &[
            ("left", 27),
            ("right", 33),
            ("l-iter", 48),
            ("r-iter", 71),
            ("l-next", 104),
            ("r-contains", 120),
            ("eq", 140),
            ("eq", 162),
            ("l-next", 201),
            ("r-contains", 217),
            ("eq", 237),
            ("eq", 259),
            ("result", 300),
            ("done", 307),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_nominal_generic_same",
        steps: 171,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 40),
            ("l-iter", 63),
            ("l-next", 96),
            ("l-contains", 112),
            ("eq", 132),
            ("result", 162),
            ("done", 169),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_nominal_dynamic_empty",
        steps: 105,
        effects: &[
            ("left", 21),
            ("right", 27),
            ("l-iter", 39),
            ("r-iter", 62),
            ("result", 96),
            ("done", 103),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_nominal_dynamic_all",
        steps: 181,
        effects: &[
            ("left", 33),
            ("right", 39),
            ("l-iter", 51),
            ("r-iter", 74),
            ("l-next", 107),
            ("r-contains", 123),
            ("eq", 143),
            ("result", 172),
            ("done", 179),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_nominal_dynamic_overlap",
        steps: 275,
        effects: &[
            ("left", 30),
            ("right", 36),
            ("l-iter", 48),
            ("r-iter", 71),
            ("l-next", 104),
            ("r-contains", 120),
            ("eq", 140),
            ("eq", 162),
            ("l-next", 201),
            ("r-contains", 217),
            ("eq", 237),
            ("result", 266),
            ("done", 273),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_nominal_dynamic_disjoint",
        steps: 308,
        effects: &[
            ("left", 30),
            ("right", 36),
            ("l-iter", 48),
            ("r-iter", 71),
            ("l-next", 104),
            ("r-contains", 120),
            ("eq", 140),
            ("eq", 162),
            ("l-next", 201),
            ("r-contains", 217),
            ("eq", 237),
            ("eq", 259),
            ("result", 299),
            ("done", 306),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_nominal_dynamic_same",
        steps: 170,
        effects: &[
            ("left", 22),
            ("right", 28),
            ("l-iter", 40),
            ("l-iter", 63),
            ("l-next", 96),
            ("l-contains", 112),
            ("eq", 132),
            ("result", 161),
            ("done", 168),
        ],
        holes: &[],
    },
];
