use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "is_disjoint_scalar_native_empty",
        steps: 86,
        effects: &[
            ("left", 30),
            ("right", 36),
            ("r-iter", 52),
            ("result", 77),
            ("done", 84),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_scalar_native_all",
        steps: 142,
        effects: &[
            ("left", 46),
            ("right", 52),
            ("r-iter", 68),
            ("r-contains", 97),
            ("result", 133),
            ("done", 140),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_scalar_native_overlap",
        steps: 192,
        effects: &[
            ("left", 45),
            ("right", 51),
            ("r-iter", 67),
            ("r-contains", 96),
            ("r-contains", 147),
            ("result", 183),
            ("done", 190),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_scalar_native_disjoint",
        steps: 203,
        effects: &[
            ("left", 45),
            ("right", 51),
            ("r-iter", 67),
            ("r-contains", 96),
            ("r-contains", 147),
            ("result", 194),
            ("done", 201),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_scalar_native_same",
        steps: 91,
        effects: &[("left", 41), ("right", 47), ("result", 82), ("done", 89)],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_scalar_proxy_empty",
        steps: 100,
        effects: &[
            ("left", 16),
            ("right", 22),
            ("l-iter", 34),
            ("r-iter", 57),
            ("result", 91),
            ("done", 98),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_scalar_proxy_all",
        steps: 155,
        effects: &[
            ("left", 20),
            ("right", 26),
            ("l-iter", 38),
            ("r-iter", 61),
            ("l-next", 94),
            ("r-contains", 110),
            ("result", 146),
            ("done", 153),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_scalar_proxy_overlap",
        steps: 225,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 37),
            ("r-iter", 60),
            ("l-next", 93),
            ("r-contains", 109),
            ("l-next", 164),
            ("r-contains", 180),
            ("result", 216),
            ("done", 223),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_scalar_proxy_disjoint",
        steps: 245,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 37),
            ("r-iter", 60),
            ("l-next", 93),
            ("r-contains", 109),
            ("l-next", 164),
            ("r-contains", 180),
            ("result", 236),
            ("done", 243),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_scalar_proxy_same",
        steps: 150,
        effects: &[
            ("left", 15),
            ("right", 21),
            ("l-iter", 33),
            ("l-iter", 56),
            ("l-next", 89),
            ("l-contains", 105),
            ("result", 141),
            ("done", 148),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_scalar_generic_empty",
        steps: 104,
        effects: &[
            ("left", 16),
            ("right", 22),
            ("l-iter", 37),
            ("r-iter", 60),
            ("result", 95),
            ("done", 102),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_scalar_generic_all",
        steps: 159,
        effects: &[
            ("left", 20),
            ("right", 26),
            ("l-iter", 41),
            ("r-iter", 64),
            ("l-next", 97),
            ("r-contains", 113),
            ("result", 150),
            ("done", 157),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_scalar_generic_overlap",
        steps: 229,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 40),
            ("r-iter", 63),
            ("l-next", 96),
            ("r-contains", 112),
            ("l-next", 167),
            ("r-contains", 183),
            ("result", 220),
            ("done", 227),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_scalar_generic_disjoint",
        steps: 249,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 40),
            ("r-iter", 63),
            ("l-next", 96),
            ("r-contains", 112),
            ("l-next", 167),
            ("r-contains", 183),
            ("result", 240),
            ("done", 247),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_scalar_generic_same",
        steps: 154,
        effects: &[
            ("left", 15),
            ("right", 21),
            ("l-iter", 36),
            ("l-iter", 59),
            ("l-next", 92),
            ("l-contains", 108),
            ("result", 145),
            ("done", 152),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_scalar_dynamic_empty",
        steps: 103,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 37),
            ("r-iter", 60),
            ("result", 94),
            ("done", 101),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_scalar_dynamic_all",
        steps: 158,
        effects: &[
            ("left", 23),
            ("right", 29),
            ("l-iter", 41),
            ("r-iter", 64),
            ("l-next", 97),
            ("r-contains", 113),
            ("result", 149),
            ("done", 156),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_scalar_dynamic_overlap",
        steps: 228,
        effects: &[
            ("left", 22),
            ("right", 28),
            ("l-iter", 40),
            ("r-iter", 63),
            ("l-next", 96),
            ("r-contains", 112),
            ("l-next", 167),
            ("r-contains", 183),
            ("result", 219),
            ("done", 226),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_scalar_dynamic_disjoint",
        steps: 248,
        effects: &[
            ("left", 22),
            ("right", 28),
            ("l-iter", 40),
            ("r-iter", 63),
            ("l-next", 96),
            ("r-contains", 112),
            ("l-next", 167),
            ("r-contains", 183),
            ("result", 239),
            ("done", 246),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_disjoint_scalar_dynamic_same",
        steps: 153,
        effects: &[
            ("left", 18),
            ("right", 24),
            ("l-iter", 36),
            ("l-iter", 59),
            ("l-next", 92),
            ("l-contains", 108),
            ("result", 144),
            ("done", 151),
        ],
        holes: &[],
    },
];
