use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "is_superset_nominal_native_empty",
        steps: 132,
        effects: &[
            ("left", 32),
            ("right", 38),
            ("r-iter", 54),
            ("r-next", 87),
            ("hash", 97),
            ("result", 123),
            ("done", 130),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_nominal_native_all",
        steps: 428,
        effects: &[
            ("hash", 27),
            ("hash", 51),
            ("eq", 73),
            ("left", 118),
            ("right", 124),
            ("r-iter", 140),
            ("r-next", 173),
            ("hash", 183),
            ("eq", 205),
            ("r-next", 239),
            ("hash", 249),
            ("eq", 271),
            ("eq", 297),
            ("r-next", 331),
            ("hash", 341),
            ("eq", 363),
            ("eq", 389),
            ("result", 419),
            ("done", 426),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_nominal_native_overlap",
        steps: 359,
        effects: &[
            ("hash", 27),
            ("hash", 51),
            ("eq", 73),
            ("left", 115),
            ("right", 121),
            ("r-iter", 137),
            ("r-next", 170),
            ("hash", 180),
            ("eq", 202),
            ("eq", 228),
            ("r-next", 262),
            ("hash", 272),
            ("eq", 294),
            ("eq", 320),
            ("result", 350),
            ("done", 357),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_nominal_native_disjoint",
        steps: 267,
        effects: &[
            ("hash", 27),
            ("hash", 51),
            ("eq", 73),
            ("left", 115),
            ("right", 121),
            ("r-iter", 137),
            ("r-next", 170),
            ("hash", 180),
            ("eq", 202),
            ("eq", 228),
            ("result", 258),
            ("done", 265),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_nominal_native_same",
        steps: 265,
        effects: &[
            ("hash", 27),
            ("hash", 51),
            ("eq", 73),
            ("left", 107),
            ("right", 113),
            ("hash", 136),
            ("eq", 158),
            ("hash", 182),
            ("eq", 204),
            ("eq", 230),
            ("result", 256),
            ("done", 263),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_nominal_proxy_empty",
        steps: 146,
        effects: &[
            ("left", 18),
            ("right", 24),
            ("l-iter", 36),
            ("r-iter", 59),
            ("r-next", 92),
            ("l-contains", 108),
            ("result", 137),
            ("done", 144),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_nominal_proxy_all",
        steps: 370,
        effects: &[
            ("left", 30),
            ("right", 36),
            ("l-iter", 48),
            ("r-iter", 71),
            ("r-next", 104),
            ("l-contains", 120),
            ("eq", 140),
            ("r-next", 177),
            ("l-contains", 193),
            ("eq", 213),
            ("eq", 235),
            ("r-next", 272),
            ("l-contains", 288),
            ("eq", 308),
            ("eq", 330),
            ("result", 361),
            ("done", 368),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_nominal_proxy_overlap",
        steps: 294,
        effects: &[
            ("left", 27),
            ("right", 33),
            ("l-iter", 45),
            ("r-iter", 68),
            ("r-next", 101),
            ("l-contains", 117),
            ("eq", 137),
            ("eq", 159),
            ("r-next", 196),
            ("l-contains", 212),
            ("eq", 232),
            ("eq", 254),
            ("result", 285),
            ("done", 292),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_nominal_proxy_disjoint",
        steps: 199,
        effects: &[
            ("left", 27),
            ("right", 33),
            ("l-iter", 45),
            ("r-iter", 68),
            ("r-next", 101),
            ("l-contains", 117),
            ("eq", 137),
            ("eq", 159),
            ("result", 190),
            ("done", 197),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_nominal_proxy_same",
        steps: 271,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 37),
            ("l-iter", 60),
            ("l-next", 93),
            ("l-contains", 109),
            ("eq", 129),
            ("l-next", 166),
            ("l-contains", 182),
            ("eq", 202),
            ("eq", 224),
            ("result", 262),
            ("done", 269),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_nominal_generic_empty",
        steps: 150,
        effects: &[
            ("left", 18),
            ("right", 24),
            ("l-iter", 39),
            ("r-iter", 62),
            ("r-next", 95),
            ("l-contains", 111),
            ("result", 141),
            ("done", 148),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_nominal_generic_all",
        steps: 374,
        effects: &[
            ("left", 30),
            ("right", 36),
            ("l-iter", 51),
            ("r-iter", 74),
            ("r-next", 107),
            ("l-contains", 123),
            ("eq", 143),
            ("r-next", 180),
            ("l-contains", 196),
            ("eq", 216),
            ("eq", 238),
            ("r-next", 275),
            ("l-contains", 291),
            ("eq", 311),
            ("eq", 333),
            ("result", 365),
            ("done", 372),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_nominal_generic_overlap",
        steps: 298,
        effects: &[
            ("left", 27),
            ("right", 33),
            ("l-iter", 48),
            ("r-iter", 71),
            ("r-next", 104),
            ("l-contains", 120),
            ("eq", 140),
            ("eq", 162),
            ("r-next", 199),
            ("l-contains", 215),
            ("eq", 235),
            ("eq", 257),
            ("result", 289),
            ("done", 296),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_nominal_generic_disjoint",
        steps: 203,
        effects: &[
            ("left", 27),
            ("right", 33),
            ("l-iter", 48),
            ("r-iter", 71),
            ("r-next", 104),
            ("l-contains", 120),
            ("eq", 140),
            ("eq", 162),
            ("result", 194),
            ("done", 201),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_nominal_generic_same",
        steps: 275,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 40),
            ("l-iter", 63),
            ("l-next", 96),
            ("l-contains", 112),
            ("eq", 132),
            ("l-next", 169),
            ("l-contains", 185),
            ("eq", 205),
            ("eq", 227),
            ("result", 266),
            ("done", 273),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_nominal_dynamic_empty",
        steps: 149,
        effects: &[
            ("left", 21),
            ("right", 27),
            ("l-iter", 39),
            ("r-iter", 62),
            ("r-next", 95),
            ("l-contains", 111),
            ("result", 140),
            ("done", 147),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_nominal_dynamic_all",
        steps: 373,
        effects: &[
            ("left", 33),
            ("right", 39),
            ("l-iter", 51),
            ("r-iter", 74),
            ("r-next", 107),
            ("l-contains", 123),
            ("eq", 143),
            ("r-next", 180),
            ("l-contains", 196),
            ("eq", 216),
            ("eq", 238),
            ("r-next", 275),
            ("l-contains", 291),
            ("eq", 311),
            ("eq", 333),
            ("result", 364),
            ("done", 371),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_nominal_dynamic_overlap",
        steps: 297,
        effects: &[
            ("left", 30),
            ("right", 36),
            ("l-iter", 48),
            ("r-iter", 71),
            ("r-next", 104),
            ("l-contains", 120),
            ("eq", 140),
            ("eq", 162),
            ("r-next", 199),
            ("l-contains", 215),
            ("eq", 235),
            ("eq", 257),
            ("result", 288),
            ("done", 295),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_nominal_dynamic_disjoint",
        steps: 202,
        effects: &[
            ("left", 30),
            ("right", 36),
            ("l-iter", 48),
            ("r-iter", 71),
            ("r-next", 104),
            ("l-contains", 120),
            ("eq", 140),
            ("eq", 162),
            ("result", 193),
            ("done", 200),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_nominal_dynamic_same",
        steps: 274,
        effects: &[
            ("left", 22),
            ("right", 28),
            ("l-iter", 40),
            ("l-iter", 63),
            ("l-next", 96),
            ("l-contains", 112),
            ("eq", 132),
            ("l-next", 169),
            ("l-contains", 185),
            ("eq", 205),
            ("eq", 227),
            ("result", 265),
            ("done", 272),
        ],
        holes: &[],
    },
];
