use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "is_superset_scalar_native_empty",
        steps: 112,
        effects: &[
            ("left", 30),
            ("right", 36),
            ("r-iter", 52),
            ("r-next", 85),
            ("result", 103),
            ("done", 110),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_scalar_native_all",
        steps: 180,
        effects: &[
            ("left", 46),
            ("right", 52),
            ("r-iter", 68),
            ("r-next", 101),
            ("r-next", 127),
            ("r-next", 153),
            ("result", 171),
            ("done", 178),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_scalar_native_overlap",
        steps: 153,
        effects: &[
            ("left", 45),
            ("right", 51),
            ("r-iter", 67),
            ("r-next", 100),
            ("r-next", 126),
            ("result", 144),
            ("done", 151),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_scalar_native_disjoint",
        steps: 127,
        effects: &[
            ("left", 45),
            ("right", 51),
            ("r-iter", 67),
            ("r-next", 100),
            ("result", 118),
            ("done", 125),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_scalar_native_same",
        steps: 93,
        effects: &[("left", 41), ("right", 47), ("result", 84), ("done", 91)],
        holes: &[],
    },
    Baseline {
        name: "is_superset_scalar_proxy_empty",
        steps: 144,
        effects: &[
            ("left", 16),
            ("right", 22),
            ("l-iter", 34),
            ("r-iter", 57),
            ("r-next", 90),
            ("l-contains", 106),
            ("result", 135),
            ("done", 142),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_scalar_proxy_all",
        steps: 295,
        effects: &[
            ("left", 20),
            ("right", 26),
            ("l-iter", 38),
            ("r-iter", 61),
            ("r-next", 94),
            ("l-contains", 110),
            ("r-next", 154),
            ("l-contains", 170),
            ("r-next", 223),
            ("l-contains", 239),
            ("result", 286),
            ("done", 293),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_scalar_proxy_overlap",
        steps: 234,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 37),
            ("r-iter", 60),
            ("r-next", 93),
            ("l-contains", 109),
            ("r-next", 162),
            ("l-contains", 178),
            ("result", 225),
            ("done", 232),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_scalar_proxy_disjoint",
        steps: 165,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 37),
            ("r-iter", 60),
            ("r-next", 93),
            ("l-contains", 109),
            ("result", 156),
            ("done", 163),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_scalar_proxy_same",
        steps: 228,
        effects: &[
            ("left", 15),
            ("right", 21),
            ("l-iter", 33),
            ("l-iter", 56),
            ("l-next", 89),
            ("l-contains", 105),
            ("l-next", 149),
            ("l-contains", 165),
            ("result", 219),
            ("done", 226),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_scalar_generic_empty",
        steps: 148,
        effects: &[
            ("left", 16),
            ("right", 22),
            ("l-iter", 37),
            ("r-iter", 60),
            ("r-next", 93),
            ("l-contains", 109),
            ("result", 139),
            ("done", 146),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_scalar_generic_all",
        steps: 299,
        effects: &[
            ("left", 20),
            ("right", 26),
            ("l-iter", 41),
            ("r-iter", 64),
            ("r-next", 97),
            ("l-contains", 113),
            ("r-next", 157),
            ("l-contains", 173),
            ("r-next", 226),
            ("l-contains", 242),
            ("result", 290),
            ("done", 297),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_scalar_generic_overlap",
        steps: 238,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 40),
            ("r-iter", 63),
            ("r-next", 96),
            ("l-contains", 112),
            ("r-next", 165),
            ("l-contains", 181),
            ("result", 229),
            ("done", 236),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_scalar_generic_disjoint",
        steps: 169,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 40),
            ("r-iter", 63),
            ("r-next", 96),
            ("l-contains", 112),
            ("result", 160),
            ("done", 167),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_scalar_generic_same",
        steps: 232,
        effects: &[
            ("left", 15),
            ("right", 21),
            ("l-iter", 36),
            ("l-iter", 59),
            ("l-next", 92),
            ("l-contains", 108),
            ("l-next", 152),
            ("l-contains", 168),
            ("result", 223),
            ("done", 230),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_scalar_dynamic_empty",
        steps: 147,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 37),
            ("r-iter", 60),
            ("r-next", 93),
            ("l-contains", 109),
            ("result", 138),
            ("done", 145),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_scalar_dynamic_all",
        steps: 298,
        effects: &[
            ("left", 23),
            ("right", 29),
            ("l-iter", 41),
            ("r-iter", 64),
            ("r-next", 97),
            ("l-contains", 113),
            ("r-next", 157),
            ("l-contains", 173),
            ("r-next", 226),
            ("l-contains", 242),
            ("result", 289),
            ("done", 296),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_scalar_dynamic_overlap",
        steps: 237,
        effects: &[
            ("left", 22),
            ("right", 28),
            ("l-iter", 40),
            ("r-iter", 63),
            ("r-next", 96),
            ("l-contains", 112),
            ("r-next", 165),
            ("l-contains", 181),
            ("result", 228),
            ("done", 235),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_scalar_dynamic_disjoint",
        steps: 168,
        effects: &[
            ("left", 22),
            ("right", 28),
            ("l-iter", 40),
            ("r-iter", 63),
            ("r-next", 96),
            ("l-contains", 112),
            ("result", 159),
            ("done", 166),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_superset_scalar_dynamic_same",
        steps: 231,
        effects: &[
            ("left", 18),
            ("right", 24),
            ("l-iter", 36),
            ("l-iter", 59),
            ("l-next", 92),
            ("l-contains", 108),
            ("l-next", 152),
            ("l-contains", 168),
            ("result", 222),
            ("done", 229),
        ],
        holes: &[],
    },
];
