use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "is_subset_nominal_native_empty",
        steps: 88,
        effects: &[
            ("left", 32),
            ("right", 38),
            ("r-iter", 54),
            ("result", 79),
            ("done", 86),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_nominal_native_all",
        steps: 302,
        effects: &[
            ("hash", 27),
            ("hash", 51),
            ("eq", 73),
            ("left", 118),
            ("right", 124),
            ("r-iter", 140),
            ("r-contains", 169),
            ("eq", 189),
            ("r-contains", 222),
            ("eq", 242),
            ("eq", 264),
            ("result", 293),
            ("done", 300),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_nominal_native_overlap",
        steps: 248,
        effects: &[
            ("hash", 27),
            ("hash", 51),
            ("eq", 73),
            ("left", 115),
            ("right", 121),
            ("r-iter", 137),
            ("r-contains", 166),
            ("eq", 186),
            ("eq", 208),
            ("result", 239),
            ("done", 246),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_nominal_native_disjoint",
        steps: 248,
        effects: &[
            ("hash", 27),
            ("hash", 51),
            ("eq", 73),
            ("left", 115),
            ("right", 121),
            ("r-iter", 137),
            ("r-contains", 166),
            ("eq", 186),
            ("eq", 208),
            ("result", 239),
            ("done", 246),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_nominal_native_same",
        steps: 273,
        effects: &[
            ("hash", 27),
            ("hash", 51),
            ("eq", 73),
            ("left", 107),
            ("right", 113),
            ("hash", 139),
            ("eq", 161),
            ("hash", 189),
            ("eq", 211),
            ("eq", 237),
            ("result", 264),
            ("done", 271),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_nominal_proxy_empty",
        steps: 102,
        effects: &[
            ("left", 18),
            ("right", 24),
            ("l-iter", 36),
            ("r-iter", 59),
            ("result", 93),
            ("done", 100),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_nominal_proxy_all",
        steps: 282,
        effects: &[
            ("left", 30),
            ("right", 36),
            ("l-iter", 48),
            ("r-iter", 71),
            ("l-next", 104),
            ("r-contains", 120),
            ("eq", 140),
            ("l-next", 177),
            ("r-contains", 193),
            ("eq", 213),
            ("eq", 235),
            ("result", 273),
            ("done", 280),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_nominal_proxy_overlap",
        steps: 199,
        effects: &[
            ("left", 27),
            ("right", 33),
            ("l-iter", 45),
            ("r-iter", 68),
            ("l-next", 101),
            ("r-contains", 117),
            ("eq", 137),
            ("eq", 159),
            ("result", 190),
            ("done", 197),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_nominal_proxy_disjoint",
        steps: 199,
        effects: &[
            ("left", 27),
            ("right", 33),
            ("l-iter", 45),
            ("r-iter", 68),
            ("l-next", 101),
            ("r-contains", 117),
            ("eq", 137),
            ("eq", 159),
            ("result", 190),
            ("done", 197),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_nominal_proxy_same",
        steps: 271,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 37),
            ("l-iter", 60),
            ("l-next", 93),
            ("l-contains", 109),
            ("eq", 129),
            ("l-next", 166),
            ("l-contains", 182),
            ("eq", 202),
            ("eq", 224),
            ("result", 262),
            ("done", 269),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_nominal_generic_empty",
        steps: 106,
        effects: &[
            ("left", 18),
            ("right", 24),
            ("l-iter", 39),
            ("r-iter", 62),
            ("result", 97),
            ("done", 104),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_nominal_generic_all",
        steps: 286,
        effects: &[
            ("left", 30),
            ("right", 36),
            ("l-iter", 51),
            ("r-iter", 74),
            ("l-next", 107),
            ("r-contains", 123),
            ("eq", 143),
            ("l-next", 180),
            ("r-contains", 196),
            ("eq", 216),
            ("eq", 238),
            ("result", 277),
            ("done", 284),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_nominal_generic_overlap",
        steps: 203,
        effects: &[
            ("left", 27),
            ("right", 33),
            ("l-iter", 48),
            ("r-iter", 71),
            ("l-next", 104),
            ("r-contains", 120),
            ("eq", 140),
            ("eq", 162),
            ("result", 194),
            ("done", 201),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_nominal_generic_disjoint",
        steps: 203,
        effects: &[
            ("left", 27),
            ("right", 33),
            ("l-iter", 48),
            ("r-iter", 71),
            ("l-next", 104),
            ("r-contains", 120),
            ("eq", 140),
            ("eq", 162),
            ("result", 194),
            ("done", 201),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_nominal_generic_same",
        steps: 275,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 40),
            ("l-iter", 63),
            ("l-next", 96),
            ("l-contains", 112),
            ("eq", 132),
            ("l-next", 169),
            ("l-contains", 185),
            ("eq", 205),
            ("eq", 227),
            ("result", 266),
            ("done", 273),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_nominal_dynamic_empty",
        steps: 105,
        effects: &[
            ("left", 21),
            ("right", 27),
            ("l-iter", 39),
            ("r-iter", 62),
            ("result", 96),
            ("done", 103),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_nominal_dynamic_all",
        steps: 285,
        effects: &[
            ("left", 33),
            ("right", 39),
            ("l-iter", 51),
            ("r-iter", 74),
            ("l-next", 107),
            ("r-contains", 123),
            ("eq", 143),
            ("l-next", 180),
            ("r-contains", 196),
            ("eq", 216),
            ("eq", 238),
            ("result", 276),
            ("done", 283),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_nominal_dynamic_overlap",
        steps: 202,
        effects: &[
            ("left", 30),
            ("right", 36),
            ("l-iter", 48),
            ("r-iter", 71),
            ("l-next", 104),
            ("r-contains", 120),
            ("eq", 140),
            ("eq", 162),
            ("result", 193),
            ("done", 200),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_nominal_dynamic_disjoint",
        steps: 202,
        effects: &[
            ("left", 30),
            ("right", 36),
            ("l-iter", 48),
            ("r-iter", 71),
            ("l-next", 104),
            ("r-contains", 120),
            ("eq", 140),
            ("eq", 162),
            ("result", 193),
            ("done", 200),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_nominal_dynamic_same",
        steps: 274,
        effects: &[
            ("left", 22),
            ("right", 28),
            ("l-iter", 40),
            ("l-iter", 63),
            ("l-next", 96),
            ("l-contains", 112),
            ("eq", 132),
            ("l-next", 169),
            ("l-contains", 185),
            ("eq", 205),
            ("eq", 227),
            ("result", 265),
            ("done", 272),
        ],
        holes: &[],
    },
];
