use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "is_subset_scalar_native_empty",
        steps: 86,
        effects: &[
            ("left", 30),
            ("right", 36),
            ("r-iter", 52),
            ("result", 77),
            ("done", 84),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_scalar_native_all",
        steps: 191,
        effects: &[
            ("left", 46),
            ("right", 52),
            ("r-iter", 68),
            ("r-contains", 97),
            ("r-contains", 137),
            ("result", 182),
            ("done", 189),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_scalar_native_overlap",
        steps: 152,
        effects: &[
            ("left", 45),
            ("right", 51),
            ("r-iter", 67),
            ("r-contains", 96),
            ("result", 143),
            ("done", 150),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_scalar_native_disjoint",
        steps: 152,
        effects: &[
            ("left", 45),
            ("right", 51),
            ("r-iter", 67),
            ("r-contains", 96),
            ("result", 143),
            ("done", 150),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_scalar_native_same",
        steps: 101,
        effects: &[("left", 41), ("right", 47), ("result", 92), ("done", 99)],
        holes: &[],
    },
    Baseline {
        name: "is_subset_scalar_proxy_empty",
        steps: 100,
        effects: &[
            ("left", 16),
            ("right", 22),
            ("l-iter", 34),
            ("r-iter", 57),
            ("result", 91),
            ("done", 98),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_scalar_proxy_all",
        steps: 233,
        effects: &[
            ("left", 20),
            ("right", 26),
            ("l-iter", 38),
            ("r-iter", 61),
            ("l-next", 94),
            ("r-contains", 110),
            ("l-next", 154),
            ("r-contains", 170),
            ("result", 224),
            ("done", 231),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_scalar_proxy_overlap",
        steps: 165,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 37),
            ("r-iter", 60),
            ("l-next", 93),
            ("r-contains", 109),
            ("result", 156),
            ("done", 163),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_scalar_proxy_disjoint",
        steps: 165,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 37),
            ("r-iter", 60),
            ("l-next", 93),
            ("r-contains", 109),
            ("result", 156),
            ("done", 163),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_scalar_proxy_same",
        steps: 228,
        effects: &[
            ("left", 15),
            ("right", 21),
            ("l-iter", 33),
            ("l-iter", 56),
            ("l-next", 89),
            ("l-contains", 105),
            ("l-next", 149),
            ("l-contains", 165),
            ("result", 219),
            ("done", 226),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_scalar_generic_empty",
        steps: 104,
        effects: &[
            ("left", 16),
            ("right", 22),
            ("l-iter", 37),
            ("r-iter", 60),
            ("result", 95),
            ("done", 102),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_scalar_generic_all",
        steps: 237,
        effects: &[
            ("left", 20),
            ("right", 26),
            ("l-iter", 41),
            ("r-iter", 64),
            ("l-next", 97),
            ("r-contains", 113),
            ("l-next", 157),
            ("r-contains", 173),
            ("result", 228),
            ("done", 235),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_scalar_generic_overlap",
        steps: 169,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 40),
            ("r-iter", 63),
            ("l-next", 96),
            ("r-contains", 112),
            ("result", 160),
            ("done", 167),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_scalar_generic_disjoint",
        steps: 169,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 40),
            ("r-iter", 63),
            ("l-next", 96),
            ("r-contains", 112),
            ("result", 160),
            ("done", 167),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_scalar_generic_same",
        steps: 232,
        effects: &[
            ("left", 15),
            ("right", 21),
            ("l-iter", 36),
            ("l-iter", 59),
            ("l-next", 92),
            ("l-contains", 108),
            ("l-next", 152),
            ("l-contains", 168),
            ("result", 223),
            ("done", 230),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_scalar_dynamic_empty",
        steps: 103,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 37),
            ("r-iter", 60),
            ("result", 94),
            ("done", 101),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_scalar_dynamic_all",
        steps: 236,
        effects: &[
            ("left", 23),
            ("right", 29),
            ("l-iter", 41),
            ("r-iter", 64),
            ("l-next", 97),
            ("r-contains", 113),
            ("l-next", 157),
            ("r-contains", 173),
            ("result", 227),
            ("done", 234),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_scalar_dynamic_overlap",
        steps: 168,
        effects: &[
            ("left", 22),
            ("right", 28),
            ("l-iter", 40),
            ("r-iter", 63),
            ("l-next", 96),
            ("r-contains", 112),
            ("result", 159),
            ("done", 166),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_scalar_dynamic_disjoint",
        steps: 168,
        effects: &[
            ("left", 22),
            ("right", 28),
            ("l-iter", 40),
            ("r-iter", 63),
            ("l-next", 96),
            ("r-contains", 112),
            ("result", 159),
            ("done", 166),
        ],
        holes: &[],
    },
    Baseline {
        name: "is_subset_scalar_dynamic_same",
        steps: 231,
        effects: &[
            ("left", 18),
            ("right", 24),
            ("l-iter", 36),
            ("l-iter", 59),
            ("l-next", 92),
            ("l-contains", 108),
            ("l-next", 152),
            ("l-contains", 168),
            ("result", 222),
            ("done", 229),
        ],
        holes: &[],
    },
];
