use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "symmetric_difference_scalar_native_empty",
        steps: 160,
        effects: &[
            ("left", 30),
            ("right", 36),
            ("r-iter", 52),
            ("r-next", 89),
            ("result", 118),
            ("done", 158),
        ],
        holes: &[],
    },
    Baseline {
        name: "symmetric_difference_scalar_native_all",
        steps: 317,
        effects: &[
            ("left", 46),
            ("right", 52),
            ("r-iter", 68),
            ("r-contains", 97),
            ("r-contains", 137),
            ("r-next", 194),
            ("r-next", 220),
            ("r-next", 246),
            ("result", 275),
            ("done", 315),
        ],
        holes: &[],
    },
    Baseline {
        name: "symmetric_difference_scalar_native_overlap",
        steps: 307,
        effects: &[
            ("left", 45),
            ("right", 51),
            ("r-iter", 67),
            ("r-contains", 96),
            ("r-contains", 149),
            ("r-next", 197),
            ("r-next", 223),
            ("result", 252),
            ("done", 305),
        ],
        holes: &[],
    },
    Baseline {
        name: "symmetric_difference_scalar_native_disjoint",
        steps: 348,
        effects: &[
            ("left", 45),
            ("right", 51),
            ("r-iter", 67),
            ("r-contains", 96),
            ("r-contains", 149),
            ("r-next", 210),
            ("r-next", 238),
            ("result", 267),
            ("done", 346),
        ],
        holes: &[],
    },
    Baseline {
        name: "symmetric_difference_scalar_native_same",
        steps: 137,
        effects: &[("left", 41), ("right", 47), ("result", 108), ("done", 135)],
        holes: &[],
    },
    Baseline {
        name: "symmetric_difference_scalar_proxy_empty",
        steps: 201,
        effects: &[
            ("left", 16),
            ("right", 22),
            ("l-iter", 34),
            ("r-iter", 57),
            ("r-next", 103),
            ("l-contains", 119),
            ("result", 159),
            ("done", 199),
        ],
        holes: &[],
    },
    Baseline {
        name: "symmetric_difference_scalar_proxy_all",
        steps: 481,
        effects: &[
            ("left", 20),
            ("right", 26),
            ("l-iter", 38),
            ("r-iter", 61),
            ("l-next", 94),
            ("r-contains", 110),
            ("l-next", 154),
            ("r-contains", 170),
            ("r-next", 236),
            ("l-contains", 252),
            ("r-next", 296),
            ("l-contains", 312),
            ("r-next", 365),
            ("l-contains", 381),
            ("result", 439),
            ("done", 479),
        ],
        holes: &[],
    },
    Baseline {
        name: "symmetric_difference_scalar_proxy_overlap",
        steps: 437,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 37),
            ("r-iter", 60),
            ("l-next", 93),
            ("r-contains", 109),
            ("l-next", 166),
            ("r-contains", 182),
            ("r-next", 239),
            ("l-contains", 255),
            ("r-next", 308),
            ("l-contains", 324),
            ("result", 382),
            ("done", 435),
        ],
        holes: &[],
    },
    Baseline {
        name: "symmetric_difference_scalar_proxy_disjoint",
        steps: 480,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 37),
            ("r-iter", 60),
            ("l-next", 93),
            ("r-contains", 109),
            ("l-next", 166),
            ("r-contains", 182),
            ("r-next", 252),
            ("l-contains", 268),
            ("r-next", 325),
            ("l-contains", 341),
            ("result", 399),
            ("done", 478),
        ],
        holes: &[],
    },
    Baseline {
        name: "symmetric_difference_scalar_proxy_same",
        steps: 390,
        effects: &[
            ("left", 15),
            ("right", 21),
            ("l-iter", 33),
            ("l-iter", 56),
            ("l-next", 89),
            ("l-contains", 105),
            ("l-next", 149),
            ("l-contains", 165),
            ("l-next", 231),
            ("l-contains", 247),
            ("l-next", 291),
            ("l-contains", 307),
            ("result", 361),
            ("done", 388),
        ],
        holes: &[],
    },
    Baseline {
        name: "symmetric_difference_scalar_generic_empty",
        steps: 205,
        effects: &[
            ("left", 16),
            ("right", 22),
            ("l-iter", 37),
            ("r-iter", 60),
            ("r-next", 106),
            ("l-contains", 122),
            ("result", 163),
            ("done", 203),
        ],
        holes: &[],
    },
    Baseline {
        name: "symmetric_difference_scalar_generic_all",
        steps: 485,
        effects: &[
            ("left", 20),
            ("right", 26),
            ("l-iter", 41),
            ("r-iter", 64),
            ("l-next", 97),
            ("r-contains", 113),
            ("l-next", 157),
            ("r-contains", 173),
            ("r-next", 239),
            ("l-contains", 255),
            ("r-next", 299),
            ("l-contains", 315),
            ("r-next", 368),
            ("l-contains", 384),
            ("result", 443),
            ("done", 483),
        ],
        holes: &[],
    },
    Baseline {
        name: "symmetric_difference_scalar_generic_overlap",
        steps: 441,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 40),
            ("r-iter", 63),
            ("l-next", 96),
            ("r-contains", 112),
            ("l-next", 169),
            ("r-contains", 185),
            ("r-next", 242),
            ("l-contains", 258),
            ("r-next", 311),
            ("l-contains", 327),
            ("result", 386),
            ("done", 439),
        ],
        holes: &[],
    },
    Baseline {
        name: "symmetric_difference_scalar_generic_disjoint",
        steps: 484,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 40),
            ("r-iter", 63),
            ("l-next", 96),
            ("r-contains", 112),
            ("l-next", 169),
            ("r-contains", 185),
            ("r-next", 255),
            ("l-contains", 271),
            ("r-next", 328),
            ("l-contains", 344),
            ("result", 403),
            ("done", 482),
        ],
        holes: &[],
    },
    Baseline {
        name: "symmetric_difference_scalar_generic_same",
        steps: 394,
        effects: &[
            ("left", 15),
            ("right", 21),
            ("l-iter", 36),
            ("l-iter", 59),
            ("l-next", 92),
            ("l-contains", 108),
            ("l-next", 152),
            ("l-contains", 168),
            ("l-next", 234),
            ("l-contains", 250),
            ("l-next", 294),
            ("l-contains", 310),
            ("result", 365),
            ("done", 392),
        ],
        holes: &[],
    },
    Baseline {
        name: "symmetric_difference_scalar_dynamic_empty",
        steps: 204,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 37),
            ("r-iter", 60),
            ("r-next", 106),
            ("l-contains", 122),
            ("result", 162),
            ("done", 202),
        ],
        holes: &[],
    },
    Baseline {
        name: "symmetric_difference_scalar_dynamic_all",
        steps: 484,
        effects: &[
            ("left", 23),
            ("right", 29),
            ("l-iter", 41),
            ("r-iter", 64),
            ("l-next", 97),
            ("r-contains", 113),
            ("l-next", 157),
            ("r-contains", 173),
            ("r-next", 239),
            ("l-contains", 255),
            ("r-next", 299),
            ("l-contains", 315),
            ("r-next", 368),
            ("l-contains", 384),
            ("result", 442),
            ("done", 482),
        ],
        holes: &[],
    },
    Baseline {
        name: "symmetric_difference_scalar_dynamic_overlap",
        steps: 440,
        effects: &[
            ("left", 22),
            ("right", 28),
            ("l-iter", 40),
            ("r-iter", 63),
            ("l-next", 96),
            ("r-contains", 112),
            ("l-next", 169),
            ("r-contains", 185),
            ("r-next", 242),
            ("l-contains", 258),
            ("r-next", 311),
            ("l-contains", 327),
            ("result", 385),
            ("done", 438),
        ],
        holes: &[],
    },
    Baseline {
        name: "symmetric_difference_scalar_dynamic_disjoint",
        steps: 483,
        effects: &[
            ("left", 22),
            ("right", 28),
            ("l-iter", 40),
            ("r-iter", 63),
            ("l-next", 96),
            ("r-contains", 112),
            ("l-next", 169),
            ("r-contains", 185),
            ("r-next", 255),
            ("l-contains", 271),
            ("r-next", 328),
            ("l-contains", 344),
            ("result", 402),
            ("done", 481),
        ],
        holes: &[],
    },
    Baseline {
        name: "symmetric_difference_scalar_dynamic_same",
        steps: 393,
        effects: &[
            ("left", 18),
            ("right", 24),
            ("l-iter", 36),
            ("l-iter", 59),
            ("l-next", 92),
            ("l-contains", 108),
            ("l-next", 152),
            ("l-contains", 168),
            ("l-next", 234),
            ("l-contains", 250),
            ("l-next", 294),
            ("l-contains", 310),
            ("result", 364),
            ("done", 391),
        ],
        holes: &[],
    },
];
