use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "union_scalar_native_empty",
        steps: 159,
        effects: &[
            ("left", 30),
            ("right", 36),
            ("r-iter", 52),
            ("r-next", 89),
            ("result", 117),
            ("done", 157),
        ],
        holes: &[],
    },
    Baseline {
        name: "union_scalar_native_all",
        steps: 269,
        effects: &[
            ("left", 46),
            ("right", 52),
            ("r-iter", 68),
            ("r-next", 119),
            ("r-next", 146),
            ("r-next", 173),
            ("result", 201),
            ("done", 267),
        ],
        holes: &[],
    },
    Baseline {
        name: "union_scalar_native_overlap",
        steps: 241,
        effects: &[
            ("left", 45),
            ("right", 51),
            ("r-iter", 67),
            ("r-next", 118),
            ("r-next", 145),
            ("result", 173),
            ("done", 239),
        ],
        holes: &[],
    },
    Baseline {
        name: "union_scalar_native_disjoint",
        steps: 254,
        effects: &[
            ("left", 45),
            ("right", 51),
            ("r-iter", 67),
            ("r-next", 118),
            ("r-next", 145),
            ("result", 173),
            ("done", 252),
        ],
        holes: &[],
    },
    Baseline {
        name: "union_scalar_native_same",
        steps: 159,
        effects: &[("left", 41), ("right", 47), ("result", 104), ("done", 157)],
        holes: &[],
    },
    Baseline {
        name: "union_scalar_proxy_empty",
        steps: 173,
        effects: &[
            ("left", 16),
            ("right", 22),
            ("l-iter", 34),
            ("r-iter", 57),
            ("r-next", 103),
            ("result", 131),
            ("done", 171),
        ],
        holes: &[],
    },
    Baseline {
        name: "union_scalar_proxy_all",
        steps: 311,
        effects: &[
            ("left", 20),
            ("right", 26),
            ("l-iter", 38),
            ("r-iter", 61),
            ("l-next", 94),
            ("l-next", 121),
            ("r-next", 161),
            ("r-next", 188),
            ("r-next", 215),
            ("result", 243),
            ("done", 309),
        ],
        holes: &[],
    },
    Baseline {
        name: "union_scalar_proxy_overlap",
        steps: 283,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 37),
            ("r-iter", 60),
            ("l-next", 93),
            ("l-next", 120),
            ("r-next", 160),
            ("r-next", 187),
            ("result", 215),
            ("done", 281),
        ],
        holes: &[],
    },
    Baseline {
        name: "union_scalar_proxy_disjoint",
        steps: 296,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 37),
            ("r-iter", 60),
            ("l-next", 93),
            ("l-next", 120),
            ("r-next", 160),
            ("r-next", 187),
            ("result", 215),
            ("done", 294),
        ],
        holes: &[],
    },
    Baseline {
        name: "union_scalar_proxy_same",
        steps: 266,
        effects: &[
            ("left", 15),
            ("right", 21),
            ("l-iter", 33),
            ("l-iter", 56),
            ("l-next", 89),
            ("l-next", 116),
            ("l-next", 156),
            ("l-next", 183),
            ("result", 211),
            ("done", 264),
        ],
        holes: &[],
    },
    Baseline {
        name: "union_scalar_generic_empty",
        steps: 177,
        effects: &[
            ("left", 16),
            ("right", 22),
            ("l-iter", 37),
            ("r-iter", 60),
            ("r-next", 106),
            ("result", 135),
            ("done", 175),
        ],
        holes: &[],
    },
    Baseline {
        name: "union_scalar_generic_all",
        steps: 315,
        effects: &[
            ("left", 20),
            ("right", 26),
            ("l-iter", 41),
            ("r-iter", 64),
            ("l-next", 97),
            ("l-next", 124),
            ("r-next", 164),
            ("r-next", 191),
            ("r-next", 218),
            ("result", 247),
            ("done", 313),
        ],
        holes: &[],
    },
    Baseline {
        name: "union_scalar_generic_overlap",
        steps: 287,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 40),
            ("r-iter", 63),
            ("l-next", 96),
            ("l-next", 123),
            ("r-next", 163),
            ("r-next", 190),
            ("result", 219),
            ("done", 285),
        ],
        holes: &[],
    },
    Baseline {
        name: "union_scalar_generic_disjoint",
        steps: 300,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 40),
            ("r-iter", 63),
            ("l-next", 96),
            ("l-next", 123),
            ("r-next", 163),
            ("r-next", 190),
            ("result", 219),
            ("done", 298),
        ],
        holes: &[],
    },
    Baseline {
        name: "union_scalar_generic_same",
        steps: 270,
        effects: &[
            ("left", 15),
            ("right", 21),
            ("l-iter", 36),
            ("l-iter", 59),
            ("l-next", 92),
            ("l-next", 119),
            ("l-next", 159),
            ("l-next", 186),
            ("result", 215),
            ("done", 268),
        ],
        holes: &[],
    },
    Baseline {
        name: "union_scalar_dynamic_empty",
        steps: 176,
        effects: &[
            ("left", 19),
            ("right", 25),
            ("l-iter", 37),
            ("r-iter", 60),
            ("r-next", 106),
            ("result", 134),
            ("done", 174),
        ],
        holes: &[],
    },
    Baseline {
        name: "union_scalar_dynamic_all",
        steps: 314,
        effects: &[
            ("left", 23),
            ("right", 29),
            ("l-iter", 41),
            ("r-iter", 64),
            ("l-next", 97),
            ("l-next", 124),
            ("r-next", 164),
            ("r-next", 191),
            ("r-next", 218),
            ("result", 246),
            ("done", 312),
        ],
        holes: &[],
    },
    Baseline {
        name: "union_scalar_dynamic_overlap",
        steps: 286,
        effects: &[
            ("left", 22),
            ("right", 28),
            ("l-iter", 40),
            ("r-iter", 63),
            ("l-next", 96),
            ("l-next", 123),
            ("r-next", 163),
            ("r-next", 190),
            ("result", 218),
            ("done", 284),
        ],
        holes: &[],
    },
    Baseline {
        name: "union_scalar_dynamic_disjoint",
        steps: 299,
        effects: &[
            ("left", 22),
            ("right", 28),
            ("l-iter", 40),
            ("r-iter", 63),
            ("l-next", 96),
            ("l-next", 123),
            ("r-next", 163),
            ("r-next", 190),
            ("result", 218),
            ("done", 297),
        ],
        holes: &[],
    },
    Baseline {
        name: "union_scalar_dynamic_same",
        steps: 269,
        effects: &[
            ("left", 18),
            ("right", 24),
            ("l-iter", 36),
            ("l-iter", 59),
            ("l-next", 92),
            ("l-next", 119),
            ("l-next", 159),
            ("l-next", 186),
            ("result", 214),
            ("done", 267),
        ],
        holes: &[],
    },
];
