use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "map_from_iter_nominal_true_array",
        steps: 48,
        effects: &[("input", 19), ("constructed", 36), ("done", 46)],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_nominal_true_iter",
        steps: 48,
        effects: &[("input", 20), ("constructed", 36), ("done", 46)],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_nominal_true_proxy",
        steps: 69,
        effects: &[
            ("input", 20),
            ("iter", 25),
            ("constructed", 57),
            ("done", 67),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_nominal_true_custom_iter",
        steps: 66,
        effects: &[
            ("input", 20),
            ("iter", 25),
            ("next", 35),
            ("constructed", 54),
            ("done", 64),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_nominal_true_dynamic",
        steps: 70,
        effects: &[
            ("input", 21),
            ("iter", 26),
            ("constructed", 58),
            ("done", 68),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_nominal_true_generic",
        steps: 51,
        effects: &[("input", 19), ("constructed", 39), ("done", 49)],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_nominal_false_array",
        steps: 453,
        effects: &[
            ("input", 39),
            ("hash", 59),
            ("hash", 87),
            ("eq", 109),
            ("hash", 141),
            ("eq", 163),
            ("hash", 191),
            ("eq", 213),
            ("eq", 239),
            ("constructed", 268),
            ("hash", 282),
            ("eq", 304),
            ("eq", 354),
            ("eq", 392),
            ("eq", 432),
            ("done", 451),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_nominal_false_iter",
        steps: 453,
        effects: &[
            ("input", 40),
            ("hash", 59),
            ("hash", 87),
            ("eq", 109),
            ("hash", 141),
            ("eq", 163),
            ("hash", 191),
            ("eq", 213),
            ("eq", 239),
            ("constructed", 268),
            ("hash", 282),
            ("eq", 304),
            ("eq", 354),
            ("eq", 392),
            ("eq", 432),
            ("done", 451),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_nominal_false_proxy",
        steps: 526,
        effects: &[
            ("input", 40),
            ("iter", 45),
            ("next", 70),
            ("hash", 84),
            ("next", 111),
            ("hash", 125),
            ("eq", 147),
            ("next", 178),
            ("hash", 192),
            ("eq", 214),
            ("next", 241),
            ("hash", 255),
            ("eq", 277),
            ("eq", 303),
            ("constructed", 341),
            ("hash", 355),
            ("eq", 377),
            ("eq", 427),
            ("eq", 465),
            ("eq", 505),
            ("done", 524),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_nominal_false_custom_iter",
        steps: 531,
        effects: &[
            ("input", 40),
            ("iter", 45),
            ("next", 55),
            ("hash", 79),
            ("next", 98),
            ("hash", 122),
            ("eq", 144),
            ("next", 167),
            ("hash", 191),
            ("eq", 213),
            ("next", 232),
            ("hash", 256),
            ("eq", 278),
            ("eq", 304),
            ("next", 327),
            ("constructed", 346),
            ("hash", 360),
            ("eq", 382),
            ("eq", 432),
            ("eq", 470),
            ("eq", 510),
            ("done", 529),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_nominal_false_dynamic",
        steps: 527,
        effects: &[
            ("input", 41),
            ("iter", 46),
            ("next", 71),
            ("hash", 85),
            ("next", 112),
            ("hash", 126),
            ("eq", 148),
            ("next", 179),
            ("hash", 193),
            ("eq", 215),
            ("next", 242),
            ("hash", 256),
            ("eq", 278),
            ("eq", 304),
            ("constructed", 342),
            ("hash", 356),
            ("eq", 378),
            ("eq", 428),
            ("eq", 466),
            ("eq", 506),
            ("done", 525),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_nominal_false_generic",
        steps: 456,
        effects: &[
            ("input", 39),
            ("hash", 61),
            ("hash", 89),
            ("eq", 111),
            ("hash", 143),
            ("eq", 165),
            ("hash", 193),
            ("eq", 215),
            ("eq", 241),
            ("constructed", 271),
            ("hash", 285),
            ("eq", 307),
            ("eq", 357),
            ("eq", 395),
            ("eq", 435),
            ("done", 454),
        ],
        holes: &[],
    },
];
