use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "map_from_iter_scalar_true_array",
        steps: 42,
        effects: &[("input", 13), ("constructed", 30), ("done", 40)],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_scalar_true_iter",
        steps: 42,
        effects: &[("input", 14), ("constructed", 30), ("done", 40)],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_scalar_true_proxy",
        steps: 63,
        effects: &[
            ("input", 14),
            ("iter", 19),
            ("constructed", 51),
            ("done", 61),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_scalar_true_custom_iter",
        steps: 60,
        effects: &[
            ("input", 14),
            ("iter", 19),
            ("next", 29),
            ("constructed", 48),
            ("done", 58),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_scalar_true_dynamic",
        steps: 64,
        effects: &[
            ("input", 15),
            ("iter", 20),
            ("constructed", 52),
            ("done", 62),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_scalar_true_generic",
        steps: 45,
        effects: &[("input", 13), ("constructed", 33), ("done", 43)],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_scalar_false_array",
        steps: 196,
        effects: &[("input", 33), ("constructed", 90), ("done", 194)],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_scalar_false_iter",
        steps: 196,
        effects: &[("input", 34), ("constructed", 90), ("done", 194)],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_scalar_false_proxy",
        steps: 269,
        effects: &[
            ("input", 34),
            ("iter", 39),
            ("next", 64),
            ("next", 87),
            ("next", 110),
            ("next", 133),
            ("constructed", 163),
            ("done", 267),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_scalar_false_custom_iter",
        steps: 274,
        effects: &[
            ("input", 34),
            ("iter", 39),
            ("next", 49),
            ("next", 74),
            ("next", 99),
            ("next", 124),
            ("next", 149),
            ("constructed", 168),
            ("done", 272),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_scalar_false_dynamic",
        steps: 270,
        effects: &[
            ("input", 35),
            ("iter", 40),
            ("next", 65),
            ("next", 88),
            ("next", 111),
            ("next", 134),
            ("constructed", 164),
            ("done", 268),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_scalar_false_generic",
        steps: 199,
        effects: &[("input", 33), ("constructed", 93), ("done", 197)],
        holes: &[],
    },
];
