use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "map_from_tuple_true_native",
        steps: 58,
        effects: &[("input", 26), ("constructed", 46), ("done", 56)],
        holes: &[],
    },
    Baseline {
        name: "map_from_tuple_true_proxy",
        steps: 76,
        effects: &[
            ("input", 27),
            ("iter", 32),
            ("constructed", 64),
            ("done", 74),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_tuple_true_generic",
        steps: 61,
        effects: &[("input", 26), ("constructed", 49), ("done", 59)],
        holes: &[],
    },
    Baseline {
        name: "map_from_tuple_true_dynamic",
        steps: 76,
        effects: &[
            ("input", 27),
            ("iter", 32),
            ("constructed", 64),
            ("done", 74),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_tuple_false_native",
        steps: 635,
        effects: &[
            ("input", 46),
            ("hash", 75),
            ("hash", 113),
            ("eq", 148),
            ("hash", 191),
            ("eq", 226),
            ("hash", 267),
            ("eq", 302),
            ("eq", 342),
            ("constructed", 376),
            ("hash", 396),
            ("eq", 431),
            ("eq", 497),
            ("eq", 551),
            ("eq", 607),
            ("done", 633),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_tuple_false_proxy",
        steps: 705,
        effects: &[
            ("input", 47),
            ("iter", 52),
            ("next", 77),
            ("hash", 97),
            ("next", 128),
            ("hash", 148),
            ("eq", 183),
            ("next", 219),
            ("hash", 239),
            ("eq", 274),
            ("next", 308),
            ("hash", 328),
            ("eq", 363),
            ("eq", 403),
            ("constructed", 446),
            ("hash", 466),
            ("eq", 501),
            ("eq", 567),
            ("eq", 621),
            ("eq", 677),
            ("done", 703),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_tuple_false_generic",
        steps: 638,
        effects: &[
            ("input", 46),
            ("hash", 77),
            ("hash", 115),
            ("eq", 150),
            ("hash", 193),
            ("eq", 228),
            ("hash", 269),
            ("eq", 304),
            ("eq", 344),
            ("constructed", 379),
            ("hash", 399),
            ("eq", 434),
            ("eq", 500),
            ("eq", 554),
            ("eq", 610),
            ("done", 636),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_tuple_false_dynamic",
        steps: 705,
        effects: &[
            ("input", 47),
            ("iter", 52),
            ("next", 77),
            ("hash", 97),
            ("next", 128),
            ("hash", 148),
            ("eq", 183),
            ("next", 219),
            ("hash", 239),
            ("eq", 274),
            ("next", 308),
            ("hash", 328),
            ("eq", 363),
            ("eq", 403),
            ("constructed", 446),
            ("hash", 466),
            ("eq", 501),
            ("eq", 567),
            ("eq", 621),
            ("eq", 677),
            ("done", 703),
        ],
        holes: &[],
    },
];
