use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "map_from_iter_identity_true_array",
        steps: 45,
        effects: &[("input", 16), ("constructed", 33), ("done", 43)],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_identity_true_iter",
        steps: 45,
        effects: &[("input", 17), ("constructed", 33), ("done", 43)],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_identity_true_proxy",
        steps: 66,
        effects: &[
            ("input", 17),
            ("iter", 22),
            ("constructed", 54),
            ("done", 64),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_identity_true_custom_iter",
        steps: 63,
        effects: &[
            ("input", 17),
            ("iter", 22),
            ("next", 32),
            ("constructed", 51),
            ("done", 61),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_identity_true_dynamic",
        steps: 67,
        effects: &[
            ("input", 18),
            ("iter", 23),
            ("constructed", 55),
            ("done", 65),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_identity_true_generic",
        steps: 48,
        effects: &[("input", 16), ("constructed", 36), ("done", 46)],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_identity_false_array",
        steps: 199,
        effects: &[("input", 36), ("constructed", 93), ("done", 197)],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_identity_false_iter",
        steps: 199,
        effects: &[("input", 37), ("constructed", 93), ("done", 197)],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_identity_false_proxy",
        steps: 272,
        effects: &[
            ("input", 37),
            ("iter", 42),
            ("next", 67),
            ("next", 90),
            ("next", 113),
            ("next", 136),
            ("constructed", 166),
            ("done", 270),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_identity_false_custom_iter",
        steps: 277,
        effects: &[
            ("input", 37),
            ("iter", 42),
            ("next", 52),
            ("next", 77),
            ("next", 102),
            ("next", 127),
            ("next", 152),
            ("constructed", 171),
            ("done", 275),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_identity_false_dynamic",
        steps: 273,
        effects: &[
            ("input", 38),
            ("iter", 43),
            ("next", 68),
            ("next", 91),
            ("next", 114),
            ("next", 137),
            ("constructed", 167),
            ("done", 271),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_identity_false_generic",
        steps: 202,
        effects: &[("input", 36), ("constructed", 96), ("done", 200)],
        holes: &[],
    },
];
