use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "map_from_iter_option_true_array",
        steps: 51,
        effects: &[("input", 22), ("constructed", 39), ("done", 49)],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_option_true_iter",
        steps: 51,
        effects: &[("input", 23), ("constructed", 39), ("done", 49)],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_option_true_proxy",
        steps: 72,
        effects: &[
            ("input", 23),
            ("iter", 28),
            ("constructed", 60),
            ("done", 70),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_option_true_custom_iter",
        steps: 69,
        effects: &[
            ("input", 23),
            ("iter", 28),
            ("next", 38),
            ("constructed", 57),
            ("done", 67),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_option_true_dynamic",
        steps: 73,
        effects: &[
            ("input", 24),
            ("iter", 29),
            ("constructed", 61),
            ("done", 71),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_option_true_generic",
        steps: 54,
        effects: &[("input", 22), ("constructed", 42), ("done", 52)],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_option_false_array",
        steps: 639,
        effects: &[
            ("input", 42),
            ("hash", 68),
            ("hash", 107),
            ("eq", 143),
            ("hash", 188),
            ("eq", 224),
            ("hash", 265),
            ("eq", 301),
            ("eq", 343),
            ("constructed", 379),
            ("hash", 399),
            ("eq", 435),
            ("eq", 501),
            ("eq", 555),
            ("eq", 611),
            ("done", 637),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_option_false_iter",
        steps: 639,
        effects: &[
            ("input", 43),
            ("hash", 68),
            ("hash", 107),
            ("eq", 143),
            ("hash", 188),
            ("eq", 224),
            ("hash", 265),
            ("eq", 301),
            ("eq", 343),
            ("constructed", 379),
            ("hash", 399),
            ("eq", 435),
            ("eq", 501),
            ("eq", 555),
            ("eq", 611),
            ("done", 637),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_option_false_proxy",
        steps: 712,
        effects: &[
            ("input", 43),
            ("iter", 48),
            ("next", 73),
            ("hash", 93),
            ("next", 125),
            ("hash", 145),
            ("eq", 181),
            ("next", 219),
            ("hash", 239),
            ("eq", 275),
            ("next", 309),
            ("hash", 329),
            ("eq", 365),
            ("eq", 407),
            ("constructed", 452),
            ("hash", 472),
            ("eq", 508),
            ("eq", 574),
            ("eq", 628),
            ("eq", 684),
            ("done", 710),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_option_false_custom_iter",
        steps: 717,
        effects: &[
            ("input", 43),
            ("iter", 48),
            ("next", 58),
            ("hash", 88),
            ("next", 112),
            ("hash", 142),
            ("eq", 178),
            ("next", 208),
            ("hash", 238),
            ("eq", 274),
            ("next", 300),
            ("hash", 330),
            ("eq", 366),
            ("eq", 408),
            ("next", 438),
            ("constructed", 457),
            ("hash", 477),
            ("eq", 513),
            ("eq", 579),
            ("eq", 633),
            ("eq", 689),
            ("done", 715),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_option_false_dynamic",
        steps: 713,
        effects: &[
            ("input", 44),
            ("iter", 49),
            ("next", 74),
            ("hash", 94),
            ("next", 126),
            ("hash", 146),
            ("eq", 182),
            ("next", 220),
            ("hash", 240),
            ("eq", 276),
            ("next", 310),
            ("hash", 330),
            ("eq", 366),
            ("eq", 408),
            ("constructed", 453),
            ("hash", 473),
            ("eq", 509),
            ("eq", 575),
            ("eq", 629),
            ("eq", 685),
            ("done", 711),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_option_false_generic",
        steps: 642,
        effects: &[
            ("input", 42),
            ("hash", 70),
            ("hash", 109),
            ("eq", 145),
            ("hash", 190),
            ("eq", 226),
            ("hash", 267),
            ("eq", 303),
            ("eq", 345),
            ("constructed", 382),
            ("hash", 402),
            ("eq", 438),
            ("eq", 504),
            ("eq", 558),
            ("eq", 614),
            ("done", 640),
        ],
        holes: &[],
    },
];
