use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "map_from_iter_tuple_true_array",
        steps: 54,
        effects: &[("input", 25), ("constructed", 42), ("done", 52)],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_tuple_true_iter",
        steps: 54,
        effects: &[("input", 26), ("constructed", 42), ("done", 52)],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_tuple_true_proxy",
        steps: 75,
        effects: &[
            ("input", 26),
            ("iter", 31),
            ("constructed", 63),
            ("done", 73),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_tuple_true_custom_iter",
        steps: 72,
        effects: &[
            ("input", 26),
            ("iter", 31),
            ("next", 41),
            ("constructed", 60),
            ("done", 70),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_tuple_true_dynamic",
        steps: 76,
        effects: &[
            ("input", 27),
            ("iter", 32),
            ("constructed", 64),
            ("done", 74),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_tuple_true_generic",
        steps: 57,
        effects: &[("input", 25), ("constructed", 45), ("done", 55)],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_tuple_false_array",
        steps: 631,
        effects: &[
            ("input", 45),
            ("hash", 71),
            ("hash", 109),
            ("eq", 144),
            ("hash", 187),
            ("eq", 222),
            ("hash", 263),
            ("eq", 298),
            ("eq", 338),
            ("constructed", 372),
            ("hash", 392),
            ("eq", 427),
            ("eq", 493),
            ("eq", 547),
            ("eq", 603),
            ("done", 629),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_tuple_false_iter",
        steps: 631,
        effects: &[
            ("input", 46),
            ("hash", 71),
            ("hash", 109),
            ("eq", 144),
            ("hash", 187),
            ("eq", 222),
            ("hash", 263),
            ("eq", 298),
            ("eq", 338),
            ("constructed", 372),
            ("hash", 392),
            ("eq", 427),
            ("eq", 493),
            ("eq", 547),
            ("eq", 603),
            ("done", 629),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_tuple_false_proxy",
        steps: 704,
        effects: &[
            ("input", 46),
            ("iter", 51),
            ("next", 76),
            ("hash", 96),
            ("next", 127),
            ("hash", 147),
            ("eq", 182),
            ("next", 218),
            ("hash", 238),
            ("eq", 273),
            ("next", 307),
            ("hash", 327),
            ("eq", 362),
            ("eq", 402),
            ("constructed", 445),
            ("hash", 465),
            ("eq", 500),
            ("eq", 566),
            ("eq", 620),
            ("eq", 676),
            ("done", 702),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_tuple_false_custom_iter",
        steps: 709,
        effects: &[
            ("input", 46),
            ("iter", 51),
            ("next", 61),
            ("hash", 91),
            ("next", 114),
            ("hash", 144),
            ("eq", 179),
            ("next", 207),
            ("hash", 237),
            ("eq", 272),
            ("next", 298),
            ("hash", 328),
            ("eq", 363),
            ("eq", 403),
            ("next", 431),
            ("constructed", 450),
            ("hash", 470),
            ("eq", 505),
            ("eq", 571),
            ("eq", 625),
            ("eq", 681),
            ("done", 707),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_tuple_false_dynamic",
        steps: 705,
        effects: &[
            ("input", 47),
            ("iter", 52),
            ("next", 77),
            ("hash", 97),
            ("next", 128),
            ("hash", 148),
            ("eq", 183),
            ("next", 219),
            ("hash", 239),
            ("eq", 274),
            ("next", 308),
            ("hash", 328),
            ("eq", 363),
            ("eq", 403),
            ("constructed", 446),
            ("hash", 466),
            ("eq", 501),
            ("eq", 567),
            ("eq", 621),
            ("eq", 677),
            ("done", 703),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_iter_tuple_false_generic",
        steps: 634,
        effects: &[
            ("input", 45),
            ("hash", 73),
            ("hash", 111),
            ("eq", 146),
            ("hash", 189),
            ("eq", 224),
            ("hash", 265),
            ("eq", 300),
            ("eq", 340),
            ("constructed", 375),
            ("hash", 395),
            ("eq", 430),
            ("eq", 496),
            ("eq", 550),
            ("eq", 606),
            ("done", 632),
        ],
        holes: &[],
    },
];
