use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "map_from_option_true_native",
        steps: 55,
        effects: &[("input", 23), ("constructed", 43), ("done", 53)],
        holes: &[],
    },
    Baseline {
        name: "map_from_option_true_proxy",
        steps: 73,
        effects: &[
            ("input", 24),
            ("iter", 29),
            ("constructed", 61),
            ("done", 71),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_option_true_generic",
        steps: 58,
        effects: &[("input", 23), ("constructed", 46), ("done", 56)],
        holes: &[],
    },
    Baseline {
        name: "map_from_option_true_dynamic",
        steps: 73,
        effects: &[
            ("input", 24),
            ("iter", 29),
            ("constructed", 61),
            ("done", 71),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_option_false_native",
        steps: 643,
        effects: &[
            ("input", 43),
            ("hash", 72),
            ("hash", 111),
            ("eq", 147),
            ("hash", 192),
            ("eq", 228),
            ("hash", 269),
            ("eq", 305),
            ("eq", 347),
            ("constructed", 383),
            ("hash", 403),
            ("eq", 439),
            ("eq", 505),
            ("eq", 559),
            ("eq", 615),
            ("done", 641),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_option_false_proxy",
        steps: 713,
        effects: &[
            ("input", 44),
            ("iter", 49),
            ("next", 74),
            ("hash", 94),
            ("next", 126),
            ("hash", 146),
            ("eq", 182),
            ("next", 220),
            ("hash", 240),
            ("eq", 276),
            ("next", 310),
            ("hash", 330),
            ("eq", 366),
            ("eq", 408),
            ("constructed", 453),
            ("hash", 473),
            ("eq", 509),
            ("eq", 575),
            ("eq", 629),
            ("eq", 685),
            ("done", 711),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_option_false_generic",
        steps: 646,
        effects: &[
            ("input", 43),
            ("hash", 74),
            ("hash", 113),
            ("eq", 149),
            ("hash", 194),
            ("eq", 230),
            ("hash", 271),
            ("eq", 307),
            ("eq", 349),
            ("constructed", 386),
            ("hash", 406),
            ("eq", 442),
            ("eq", 508),
            ("eq", 562),
            ("eq", 618),
            ("done", 644),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_option_false_dynamic",
        steps: 713,
        effects: &[
            ("input", 44),
            ("iter", 49),
            ("next", 74),
            ("hash", 94),
            ("next", 126),
            ("hash", 146),
            ("eq", 182),
            ("next", 220),
            ("hash", 240),
            ("eq", 276),
            ("next", 310),
            ("hash", 330),
            ("eq", 366),
            ("eq", 408),
            ("constructed", 453),
            ("hash", 473),
            ("eq", 509),
            ("eq", 575),
            ("eq", 629),
            ("eq", 685),
            ("done", 711),
        ],
        holes: &[],
    },
];
