use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "map_from_nominal_true_native",
        steps: 52,
        effects: &[("input", 20), ("constructed", 40), ("done", 50)],
        holes: &[],
    },
    Baseline {
        name: "map_from_nominal_true_proxy",
        steps: 70,
        effects: &[
            ("input", 21),
            ("iter", 26),
            ("constructed", 58),
            ("done", 68),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_nominal_true_generic",
        steps: 55,
        effects: &[("input", 20), ("constructed", 43), ("done", 53)],
        holes: &[],
    },
    Baseline {
        name: "map_from_nominal_true_dynamic",
        steps: 70,
        effects: &[
            ("input", 21),
            ("iter", 26),
            ("constructed", 58),
            ("done", 68),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_nominal_false_native",
        steps: 457,
        effects: &[
            ("input", 40),
            ("hash", 63),
            ("hash", 91),
            ("eq", 113),
            ("hash", 145),
            ("eq", 167),
            ("hash", 195),
            ("eq", 217),
            ("eq", 243),
            ("constructed", 272),
            ("hash", 286),
            ("eq", 308),
            ("eq", 358),
            ("eq", 396),
            ("eq", 436),
            ("done", 455),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_nominal_false_proxy",
        steps: 527,
        effects: &[
            ("input", 41),
            ("iter", 46),
            ("next", 71),
            ("hash", 85),
            ("next", 112),
            ("hash", 126),
            ("eq", 148),
            ("next", 179),
            ("hash", 193),
            ("eq", 215),
            ("next", 242),
            ("hash", 256),
            ("eq", 278),
            ("eq", 304),
            ("constructed", 342),
            ("hash", 356),
            ("eq", 378),
            ("eq", 428),
            ("eq", 466),
            ("eq", 506),
            ("done", 525),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_nominal_false_generic",
        steps: 460,
        effects: &[
            ("input", 40),
            ("hash", 65),
            ("hash", 93),
            ("eq", 115),
            ("hash", 147),
            ("eq", 169),
            ("hash", 197),
            ("eq", 219),
            ("eq", 245),
            ("constructed", 275),
            ("hash", 289),
            ("eq", 311),
            ("eq", 361),
            ("eq", 399),
            ("eq", 439),
            ("done", 458),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_from_nominal_false_dynamic",
        steps: 527,
        effects: &[
            ("input", 41),
            ("iter", 46),
            ("next", 71),
            ("hash", 85),
            ("next", 112),
            ("hash", 126),
            ("eq", 148),
            ("next", 179),
            ("hash", 193),
            ("eq", 215),
            ("next", 242),
            ("hash", 256),
            ("eq", 278),
            ("eq", 304),
            ("constructed", 342),
            ("hash", 356),
            ("eq", 378),
            ("eq", 428),
            ("eq", 466),
            ("eq", 506),
            ("done", 525),
        ],
        holes: &[],
    },
];
