use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "set_from_option_true_native",
        steps: 55,
        effects: &[("input", 23), ("constructed", 43), ("done", 53)],
        holes: &[],
    },
    Baseline {
        name: "set_from_option_true_proxy",
        steps: 73,
        effects: &[
            ("input", 24),
            ("iter", 29),
            ("constructed", 61),
            ("done", 71),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_option_true_generic",
        steps: 58,
        effects: &[("input", 23), ("constructed", 46), ("done", 56)],
        holes: &[],
    },
    Baseline {
        name: "set_from_option_true_dynamic",
        steps: 73,
        effects: &[
            ("input", 24),
            ("iter", 29),
            ("constructed", 61),
            ("done", 71),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_option_false_native",
        steps: 523,
        effects: &[
            ("input", 35),
            ("hash", 60),
            ("hash", 95),
            ("eq", 131),
            ("hash", 172),
            ("eq", 208),
            ("hash", 245),
            ("eq", 281),
            ("eq", 323),
            ("constructed", 359),
            ("eq", 397),
            ("eq", 445),
            ("eq", 495),
            ("done", 521),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_option_false_proxy",
        steps: 593,
        effects: &[
            ("input", 36),
            ("iter", 41),
            ("next", 66),
            ("hash", 82),
            ("next", 114),
            ("hash", 130),
            ("eq", 166),
            ("next", 204),
            ("hash", 220),
            ("eq", 256),
            ("next", 290),
            ("hash", 306),
            ("eq", 342),
            ("eq", 384),
            ("constructed", 429),
            ("eq", 467),
            ("eq", 515),
            ("eq", 565),
            ("done", 591),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_option_false_generic",
        steps: 526,
        effects: &[
            ("input", 35),
            ("hash", 62),
            ("hash", 97),
            ("eq", 133),
            ("hash", 174),
            ("eq", 210),
            ("hash", 247),
            ("eq", 283),
            ("eq", 325),
            ("constructed", 362),
            ("eq", 400),
            ("eq", 448),
            ("eq", 498),
            ("done", 524),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_option_false_dynamic",
        steps: 593,
        effects: &[
            ("input", 36),
            ("iter", 41),
            ("next", 66),
            ("hash", 82),
            ("next", 114),
            ("hash", 130),
            ("eq", 166),
            ("next", 204),
            ("hash", 220),
            ("eq", 256),
            ("next", 290),
            ("hash", 306),
            ("eq", 342),
            ("eq", 384),
            ("constructed", 429),
            ("eq", 467),
            ("eq", 515),
            ("eq", 565),
            ("done", 591),
        ],
        holes: &[],
    },
];
