use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "set_from_iter_tuple_true_array",
        steps: 54,
        effects: &[("input", 25), ("constructed", 42), ("done", 52)],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_tuple_true_iter",
        steps: 54,
        effects: &[("input", 26), ("constructed", 42), ("done", 52)],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_tuple_true_proxy",
        steps: 75,
        effects: &[
            ("input", 26),
            ("iter", 31),
            ("constructed", 63),
            ("done", 73),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_tuple_true_custom_iter",
        steps: 72,
        effects: &[
            ("input", 26),
            ("iter", 31),
            ("next", 41),
            ("constructed", 60),
            ("done", 70),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_tuple_true_dynamic",
        steps: 76,
        effects: &[
            ("input", 27),
            ("iter", 32),
            ("constructed", 64),
            ("done", 74),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_tuple_true_generic",
        steps: 57,
        effects: &[("input", 25), ("constructed", 45), ("done", 55)],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_tuple_false_array",
        steps: 512,
        effects: &[
            ("input", 37),
            ("hash", 59),
            ("hash", 93),
            ("eq", 128),
            ("hash", 167),
            ("eq", 202),
            ("hash", 239),
            ("eq", 274),
            ("eq", 314),
            ("constructed", 348),
            ("eq", 386),
            ("eq", 434),
            ("eq", 484),
            ("done", 510),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_tuple_false_iter",
        steps: 512,
        effects: &[
            ("input", 38),
            ("hash", 59),
            ("hash", 93),
            ("eq", 128),
            ("hash", 167),
            ("eq", 202),
            ("hash", 239),
            ("eq", 274),
            ("eq", 314),
            ("constructed", 348),
            ("eq", 386),
            ("eq", 434),
            ("eq", 484),
            ("done", 510),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_tuple_false_proxy",
        steps: 585,
        effects: &[
            ("input", 38),
            ("iter", 43),
            ("next", 68),
            ("hash", 84),
            ("next", 115),
            ("hash", 131),
            ("eq", 166),
            ("next", 202),
            ("hash", 218),
            ("eq", 253),
            ("next", 287),
            ("hash", 303),
            ("eq", 338),
            ("eq", 378),
            ("constructed", 421),
            ("eq", 459),
            ("eq", 507),
            ("eq", 557),
            ("done", 583),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_tuple_false_custom_iter",
        steps: 590,
        effects: &[
            ("input", 38),
            ("iter", 43),
            ("next", 53),
            ("hash", 79),
            ("next", 102),
            ("hash", 128),
            ("eq", 163),
            ("next", 191),
            ("hash", 217),
            ("eq", 252),
            ("next", 278),
            ("hash", 304),
            ("eq", 339),
            ("eq", 379),
            ("next", 407),
            ("constructed", 426),
            ("eq", 464),
            ("eq", 512),
            ("eq", 562),
            ("done", 588),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_tuple_false_dynamic",
        steps: 586,
        effects: &[
            ("input", 39),
            ("iter", 44),
            ("next", 69),
            ("hash", 85),
            ("next", 116),
            ("hash", 132),
            ("eq", 167),
            ("next", 203),
            ("hash", 219),
            ("eq", 254),
            ("next", 288),
            ("hash", 304),
            ("eq", 339),
            ("eq", 379),
            ("constructed", 422),
            ("eq", 460),
            ("eq", 508),
            ("eq", 558),
            ("done", 584),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_tuple_false_generic",
        steps: 515,
        effects: &[
            ("input", 37),
            ("hash", 61),
            ("hash", 95),
            ("eq", 130),
            ("hash", 169),
            ("eq", 204),
            ("hash", 241),
            ("eq", 276),
            ("eq", 316),
            ("constructed", 351),
            ("eq", 389),
            ("eq", 437),
            ("eq", 487),
            ("done", 513),
        ],
        holes: &[],
    },
];
