use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "set_from_tuple_true_native",
        steps: 58,
        effects: &[("input", 26), ("constructed", 46), ("done", 56)],
        holes: &[],
    },
    Baseline {
        name: "set_from_tuple_true_proxy",
        steps: 76,
        effects: &[
            ("input", 27),
            ("iter", 32),
            ("constructed", 64),
            ("done", 74),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_tuple_true_generic",
        steps: 61,
        effects: &[("input", 26), ("constructed", 49), ("done", 59)],
        holes: &[],
    },
    Baseline {
        name: "set_from_tuple_true_dynamic",
        steps: 76,
        effects: &[
            ("input", 27),
            ("iter", 32),
            ("constructed", 64),
            ("done", 74),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_tuple_false_native",
        steps: 516,
        effects: &[
            ("input", 38),
            ("hash", 63),
            ("hash", 97),
            ("eq", 132),
            ("hash", 171),
            ("eq", 206),
            ("hash", 243),
            ("eq", 278),
            ("eq", 318),
            ("constructed", 352),
            ("eq", 390),
            ("eq", 438),
            ("eq", 488),
            ("done", 514),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_tuple_false_proxy",
        steps: 586,
        effects: &[
            ("input", 39),
            ("iter", 44),
            ("next", 69),
            ("hash", 85),
            ("next", 116),
            ("hash", 132),
            ("eq", 167),
            ("next", 203),
            ("hash", 219),
            ("eq", 254),
            ("next", 288),
            ("hash", 304),
            ("eq", 339),
            ("eq", 379),
            ("constructed", 422),
            ("eq", 460),
            ("eq", 508),
            ("eq", 558),
            ("done", 584),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_tuple_false_generic",
        steps: 519,
        effects: &[
            ("input", 38),
            ("hash", 65),
            ("hash", 99),
            ("eq", 134),
            ("hash", 173),
            ("eq", 208),
            ("hash", 245),
            ("eq", 280),
            ("eq", 320),
            ("constructed", 355),
            ("eq", 393),
            ("eq", 441),
            ("eq", 491),
            ("done", 517),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_tuple_false_dynamic",
        steps: 586,
        effects: &[
            ("input", 39),
            ("iter", 44),
            ("next", 69),
            ("hash", 85),
            ("next", 116),
            ("hash", 132),
            ("eq", 167),
            ("next", 203),
            ("hash", 219),
            ("eq", 254),
            ("next", 288),
            ("hash", 304),
            ("eq", 339),
            ("eq", 379),
            ("constructed", 422),
            ("eq", 460),
            ("eq", 508),
            ("eq", 558),
            ("done", 584),
        ],
        holes: &[],
    },
];
