use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "set_from_iter_option_true_array",
        steps: 51,
        effects: &[("input", 22), ("constructed", 39), ("done", 49)],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_option_true_iter",
        steps: 51,
        effects: &[("input", 23), ("constructed", 39), ("done", 49)],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_option_true_proxy",
        steps: 72,
        effects: &[
            ("input", 23),
            ("iter", 28),
            ("constructed", 60),
            ("done", 70),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_option_true_custom_iter",
        steps: 69,
        effects: &[
            ("input", 23),
            ("iter", 28),
            ("next", 38),
            ("constructed", 57),
            ("done", 67),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_option_true_dynamic",
        steps: 73,
        effects: &[
            ("input", 24),
            ("iter", 29),
            ("constructed", 61),
            ("done", 71),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_option_true_generic",
        steps: 54,
        effects: &[("input", 22), ("constructed", 42), ("done", 52)],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_option_false_array",
        steps: 519,
        effects: &[
            ("input", 34),
            ("hash", 56),
            ("hash", 91),
            ("eq", 127),
            ("hash", 168),
            ("eq", 204),
            ("hash", 241),
            ("eq", 277),
            ("eq", 319),
            ("constructed", 355),
            ("eq", 393),
            ("eq", 441),
            ("eq", 491),
            ("done", 517),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_option_false_iter",
        steps: 519,
        effects: &[
            ("input", 35),
            ("hash", 56),
            ("hash", 91),
            ("eq", 127),
            ("hash", 168),
            ("eq", 204),
            ("hash", 241),
            ("eq", 277),
            ("eq", 319),
            ("constructed", 355),
            ("eq", 393),
            ("eq", 441),
            ("eq", 491),
            ("done", 517),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_option_false_proxy",
        steps: 592,
        effects: &[
            ("input", 35),
            ("iter", 40),
            ("next", 65),
            ("hash", 81),
            ("next", 113),
            ("hash", 129),
            ("eq", 165),
            ("next", 203),
            ("hash", 219),
            ("eq", 255),
            ("next", 289),
            ("hash", 305),
            ("eq", 341),
            ("eq", 383),
            ("constructed", 428),
            ("eq", 466),
            ("eq", 514),
            ("eq", 564),
            ("done", 590),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_option_false_custom_iter",
        steps: 597,
        effects: &[
            ("input", 35),
            ("iter", 40),
            ("next", 50),
            ("hash", 76),
            ("next", 100),
            ("hash", 126),
            ("eq", 162),
            ("next", 192),
            ("hash", 218),
            ("eq", 254),
            ("next", 280),
            ("hash", 306),
            ("eq", 342),
            ("eq", 384),
            ("next", 414),
            ("constructed", 433),
            ("eq", 471),
            ("eq", 519),
            ("eq", 569),
            ("done", 595),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_option_false_dynamic",
        steps: 593,
        effects: &[
            ("input", 36),
            ("iter", 41),
            ("next", 66),
            ("hash", 82),
            ("next", 114),
            ("hash", 130),
            ("eq", 166),
            ("next", 204),
            ("hash", 220),
            ("eq", 256),
            ("next", 290),
            ("hash", 306),
            ("eq", 342),
            ("eq", 384),
            ("constructed", 429),
            ("eq", 467),
            ("eq", 515),
            ("eq", 565),
            ("done", 591),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_option_false_generic",
        steps: 522,
        effects: &[
            ("input", 34),
            ("hash", 58),
            ("hash", 93),
            ("eq", 129),
            ("hash", 170),
            ("eq", 206),
            ("hash", 243),
            ("eq", 279),
            ("eq", 321),
            ("constructed", 358),
            ("eq", 396),
            ("eq", 444),
            ("eq", 494),
            ("done", 520),
        ],
        holes: &[],
    },
];
