use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "set_from_iter_identity_true_array",
        steps: 45,
        effects: &[("input", 16), ("constructed", 33), ("done", 43)],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_identity_true_iter",
        steps: 45,
        effects: &[("input", 17), ("constructed", 33), ("done", 43)],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_identity_true_proxy",
        steps: 66,
        effects: &[
            ("input", 17),
            ("iter", 22),
            ("constructed", 54),
            ("done", 64),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_identity_true_custom_iter",
        steps: 63,
        effects: &[
            ("input", 17),
            ("iter", 22),
            ("next", 32),
            ("constructed", 51),
            ("done", 61),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_identity_true_dynamic",
        steps: 67,
        effects: &[
            ("input", 18),
            ("iter", 23),
            ("constructed", 55),
            ("done", 65),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_identity_true_generic",
        steps: 48,
        effects: &[("input", 16), ("constructed", 36), ("done", 46)],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_identity_false_array",
        steps: 146,
        effects: &[("input", 28), ("constructed", 69), ("done", 144)],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_identity_false_iter",
        steps: 146,
        effects: &[("input", 29), ("constructed", 69), ("done", 144)],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_identity_false_proxy",
        steps: 219,
        effects: &[
            ("input", 29),
            ("iter", 34),
            ("next", 59),
            ("next", 78),
            ("next", 97),
            ("next", 116),
            ("constructed", 142),
            ("done", 217),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_identity_false_custom_iter",
        steps: 224,
        effects: &[
            ("input", 29),
            ("iter", 34),
            ("next", 44),
            ("next", 65),
            ("next", 86),
            ("next", 107),
            ("next", 128),
            ("constructed", 147),
            ("done", 222),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_identity_false_dynamic",
        steps: 220,
        effects: &[
            ("input", 30),
            ("iter", 35),
            ("next", 60),
            ("next", 79),
            ("next", 98),
            ("next", 117),
            ("constructed", 143),
            ("done", 218),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_identity_false_generic",
        steps: 149,
        effects: &[("input", 28), ("constructed", 72), ("done", 147)],
        holes: &[],
    },
];
