use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "set_from_iter_nominal_true_array",
        steps: 48,
        effects: &[("input", 19), ("constructed", 36), ("done", 46)],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_nominal_true_iter",
        steps: 48,
        effects: &[("input", 20), ("constructed", 36), ("done", 46)],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_nominal_true_proxy",
        steps: 69,
        effects: &[
            ("input", 20),
            ("iter", 25),
            ("constructed", 57),
            ("done", 67),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_nominal_true_custom_iter",
        steps: 66,
        effects: &[
            ("input", 20),
            ("iter", 25),
            ("next", 35),
            ("constructed", 54),
            ("done", 64),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_nominal_true_dynamic",
        steps: 70,
        effects: &[
            ("input", 21),
            ("iter", 26),
            ("constructed", 58),
            ("done", 68),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_nominal_true_generic",
        steps: 51,
        effects: &[("input", 19), ("constructed", 39), ("done", 49)],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_nominal_false_array",
        steps: 360,
        effects: &[
            ("input", 31),
            ("hash", 47),
            ("hash", 71),
            ("eq", 93),
            ("hash", 121),
            ("eq", 143),
            ("hash", 167),
            ("eq", 189),
            ("eq", 215),
            ("constructed", 244),
            ("eq", 273),
            ("eq", 305),
            ("eq", 339),
            ("done", 358),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_nominal_false_iter",
        steps: 360,
        effects: &[
            ("input", 32),
            ("hash", 47),
            ("hash", 71),
            ("eq", 93),
            ("hash", 121),
            ("eq", 143),
            ("hash", 167),
            ("eq", 189),
            ("eq", 215),
            ("constructed", 244),
            ("eq", 273),
            ("eq", 305),
            ("eq", 339),
            ("done", 358),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_nominal_false_proxy",
        steps: 433,
        effects: &[
            ("input", 32),
            ("iter", 37),
            ("next", 62),
            ("hash", 72),
            ("next", 99),
            ("hash", 109),
            ("eq", 131),
            ("next", 162),
            ("hash", 172),
            ("eq", 194),
            ("next", 221),
            ("hash", 231),
            ("eq", 253),
            ("eq", 279),
            ("constructed", 317),
            ("eq", 346),
            ("eq", 378),
            ("eq", 412),
            ("done", 431),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_nominal_false_custom_iter",
        steps: 438,
        effects: &[
            ("input", 32),
            ("iter", 37),
            ("next", 47),
            ("hash", 67),
            ("next", 86),
            ("hash", 106),
            ("eq", 128),
            ("next", 151),
            ("hash", 171),
            ("eq", 193),
            ("next", 212),
            ("hash", 232),
            ("eq", 254),
            ("eq", 280),
            ("next", 303),
            ("constructed", 322),
            ("eq", 351),
            ("eq", 383),
            ("eq", 417),
            ("done", 436),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_nominal_false_dynamic",
        steps: 434,
        effects: &[
            ("input", 33),
            ("iter", 38),
            ("next", 63),
            ("hash", 73),
            ("next", 100),
            ("hash", 110),
            ("eq", 132),
            ("next", 163),
            ("hash", 173),
            ("eq", 195),
            ("next", 222),
            ("hash", 232),
            ("eq", 254),
            ("eq", 280),
            ("constructed", 318),
            ("eq", 347),
            ("eq", 379),
            ("eq", 413),
            ("done", 432),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_nominal_false_generic",
        steps: 363,
        effects: &[
            ("input", 31),
            ("hash", 49),
            ("hash", 73),
            ("eq", 95),
            ("hash", 123),
            ("eq", 145),
            ("hash", 169),
            ("eq", 191),
            ("eq", 217),
            ("constructed", 247),
            ("eq", 276),
            ("eq", 308),
            ("eq", 342),
            ("done", 361),
        ],
        holes: &[],
    },
];
