use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "set_from_iter_scalar_true_array",
        steps: 42,
        effects: &[("input", 13), ("constructed", 30), ("done", 40)],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_scalar_true_iter",
        steps: 42,
        effects: &[("input", 14), ("constructed", 30), ("done", 40)],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_scalar_true_proxy",
        steps: 63,
        effects: &[
            ("input", 14),
            ("iter", 19),
            ("constructed", 51),
            ("done", 61),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_scalar_true_custom_iter",
        steps: 60,
        effects: &[
            ("input", 14),
            ("iter", 19),
            ("next", 29),
            ("constructed", 48),
            ("done", 58),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_scalar_true_dynamic",
        steps: 64,
        effects: &[
            ("input", 15),
            ("iter", 20),
            ("constructed", 52),
            ("done", 62),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_scalar_true_generic",
        steps: 45,
        effects: &[("input", 13), ("constructed", 33), ("done", 43)],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_scalar_false_array",
        steps: 143,
        effects: &[("input", 25), ("constructed", 66), ("done", 141)],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_scalar_false_iter",
        steps: 143,
        effects: &[("input", 26), ("constructed", 66), ("done", 141)],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_scalar_false_proxy",
        steps: 216,
        effects: &[
            ("input", 26),
            ("iter", 31),
            ("next", 56),
            ("next", 75),
            ("next", 94),
            ("next", 113),
            ("constructed", 139),
            ("done", 214),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_scalar_false_custom_iter",
        steps: 221,
        effects: &[
            ("input", 26),
            ("iter", 31),
            ("next", 41),
            ("next", 62),
            ("next", 83),
            ("next", 104),
            ("next", 125),
            ("constructed", 144),
            ("done", 219),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_scalar_false_dynamic",
        steps: 217,
        effects: &[
            ("input", 27),
            ("iter", 32),
            ("next", 57),
            ("next", 76),
            ("next", 95),
            ("next", 114),
            ("constructed", 140),
            ("done", 215),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_iter_scalar_false_generic",
        steps: 146,
        effects: &[("input", 25), ("constructed", 69), ("done", 144)],
        holes: &[],
    },
];
