use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "set_from_nominal_true_native",
        steps: 52,
        effects: &[("input", 20), ("constructed", 40), ("done", 50)],
        holes: &[],
    },
    Baseline {
        name: "set_from_nominal_true_proxy",
        steps: 70,
        effects: &[
            ("input", 21),
            ("iter", 26),
            ("constructed", 58),
            ("done", 68),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_nominal_true_generic",
        steps: 55,
        effects: &[("input", 20), ("constructed", 43), ("done", 53)],
        holes: &[],
    },
    Baseline {
        name: "set_from_nominal_true_dynamic",
        steps: 70,
        effects: &[
            ("input", 21),
            ("iter", 26),
            ("constructed", 58),
            ("done", 68),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_nominal_false_native",
        steps: 364,
        effects: &[
            ("input", 32),
            ("hash", 51),
            ("hash", 75),
            ("eq", 97),
            ("hash", 125),
            ("eq", 147),
            ("hash", 171),
            ("eq", 193),
            ("eq", 219),
            ("constructed", 248),
            ("eq", 277),
            ("eq", 309),
            ("eq", 343),
            ("done", 362),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_nominal_false_proxy",
        steps: 434,
        effects: &[
            ("input", 33),
            ("iter", 38),
            ("next", 63),
            ("hash", 73),
            ("next", 100),
            ("hash", 110),
            ("eq", 132),
            ("next", 163),
            ("hash", 173),
            ("eq", 195),
            ("next", 222),
            ("hash", 232),
            ("eq", 254),
            ("eq", 280),
            ("constructed", 318),
            ("eq", 347),
            ("eq", 379),
            ("eq", 413),
            ("done", 432),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_nominal_false_generic",
        steps: 367,
        effects: &[
            ("input", 32),
            ("hash", 53),
            ("hash", 77),
            ("eq", 99),
            ("hash", 127),
            ("eq", 149),
            ("hash", 173),
            ("eq", 195),
            ("eq", 221),
            ("constructed", 251),
            ("eq", 280),
            ("eq", 312),
            ("eq", 346),
            ("done", 365),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_from_nominal_false_dynamic",
        steps: 434,
        effects: &[
            ("input", 33),
            ("iter", 38),
            ("next", 63),
            ("hash", 73),
            ("next", 100),
            ("hash", 110),
            ("eq", 132),
            ("next", 163),
            ("hash", 173),
            ("eq", 195),
            ("next", 222),
            ("hash", 232),
            ("eq", 254),
            ("eq", 280),
            ("constructed", 318),
            ("eq", 347),
            ("eq", 379),
            ("eq", 413),
            ("done", 432),
        ],
        holes: &[],
    },
];
