use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "array_scalar_0_all_closure",
        steps: 48,
        effects: &[
            ("receiver", 8),
            ("callback", 15),
            ("committed", 38),
            ("done", 46),
        ],
        holes: &[],
    },
    Baseline {
        name: "array_scalar_0_all_generic",
        steps: 53,
        effects: &[
            ("receiver", 8),
            ("callback", 15),
            ("committed", 43),
            ("done", 51),
        ],
        holes: &[],
    },
    Baseline {
        name: "array_scalar_0_all_named",
        steps: 48,
        effects: &[
            ("receiver", 8),
            ("callback", 15),
            ("committed", 38),
            ("done", 46),
        ],
        holes: &[],
    },
    Baseline {
        name: "array_scalar_0_none_closure",
        steps: 48,
        effects: &[
            ("receiver", 8),
            ("callback", 15),
            ("committed", 38),
            ("done", 46),
        ],
        holes: &[],
    },
    Baseline {
        name: "array_scalar_0_none_generic",
        steps: 53,
        effects: &[
            ("receiver", 8),
            ("callback", 15),
            ("committed", 43),
            ("done", 51),
        ],
        holes: &[],
    },
    Baseline {
        name: "array_scalar_0_none_named",
        steps: 48,
        effects: &[
            ("receiver", 8),
            ("callback", 15),
            ("committed", 38),
            ("done", 46),
        ],
        holes: &[],
    },
    Baseline {
        name: "array_scalar_0_even_closure",
        steps: 48,
        effects: &[
            ("receiver", 8),
            ("callback", 15),
            ("committed", 38),
            ("done", 46),
        ],
        holes: &[],
    },
    Baseline {
        name: "array_scalar_0_even_generic",
        steps: 53,
        effects: &[
            ("receiver", 8),
            ("callback", 15),
            ("committed", 43),
            ("done", 51),
        ],
        holes: &[],
    },
    Baseline {
        name: "array_scalar_0_even_named",
        steps: 48,
        effects: &[
            ("receiver", 8),
            ("callback", 15),
            ("committed", 38),
            ("done", 46),
        ],
        holes: &[],
    },
    Baseline {
        name: "array_scalar_1_all_closure",
        steps: 69,
        effects: &[
            ("receiver", 9),
            ("callback", 16),
            ("predicate", 36),
            ("committed", 52),
            ("done", 67),
        ],
        holes: &[(49, 48)],
    },
    Baseline {
        name: "array_scalar_1_all_generic",
        steps: 74,
        effects: &[
            ("receiver", 9),
            ("callback", 16),
            ("predicate", 39),
            ("committed", 57),
            ("done", 72),
        ],
        holes: &[(52, 51)],
    },
    Baseline {
        name: "array_scalar_1_all_named",
        steps: 72,
        effects: &[
            ("receiver", 9),
            ("callback", 16),
            ("predicate", 38),
            ("committed", 55),
            ("done", 70),
        ],
        holes: &[(52, 51)],
    },
    Baseline {
        name: "array_scalar_1_none_closure",
        steps: 62,
        effects: &[
            ("receiver", 9),
            ("callback", 16),
            ("predicate", 36),
            ("committed", 52),
            ("done", 60),
        ],
        holes: &[(49, 48)],
    },
    Baseline {
        name: "array_scalar_1_none_generic",
        steps: 67,
        effects: &[
            ("receiver", 9),
            ("callback", 16),
            ("predicate", 39),
            ("committed", 57),
            ("done", 65),
        ],
        holes: &[(52, 51)],
    },
    Baseline {
        name: "array_scalar_1_none_named",
        steps: 65,
        effects: &[
            ("receiver", 9),
            ("callback", 16),
            ("predicate", 38),
            ("committed", 55),
            ("done", 63),
        ],
        holes: &[(52, 51)],
    },
    Baseline {
        name: "array_scalar_1_even_closure",
        steps: 73,
        effects: &[
            ("receiver", 9),
            ("callback", 16),
            ("predicate", 36),
            ("committed", 56),
            ("done", 71),
        ],
        holes: &[(53, 52)],
    },
    Baseline {
        name: "array_scalar_1_even_generic",
        steps: 78,
        effects: &[
            ("receiver", 9),
            ("callback", 16),
            ("predicate", 39),
            ("committed", 61),
            ("done", 76),
        ],
        holes: &[(56, 55)],
    },
    Baseline {
        name: "array_scalar_1_even_named",
        steps: 76,
        effects: &[
            ("receiver", 9),
            ("callback", 16),
            ("predicate", 38),
            ("committed", 59),
            ("done", 74),
        ],
        holes: &[(56, 55)],
    },
    Baseline {
        name: "array_scalar_3_all_closure",
        steps: 111,
        effects: &[
            ("receiver", 11),
            ("callback", 18),
            ("predicate", 38),
            ("predicate", 50),
            ("predicate", 62),
            ("committed", 80),
            ("done", 109),
        ],
        holes: &[(75, 74), (76, 74), (77, 74)],
    },
    Baseline {
        name: "array_scalar_3_all_generic",
        steps: 116,
        effects: &[
            ("receiver", 11),
            ("callback", 18),
            ("predicate", 41),
            ("predicate", 53),
            ("predicate", 65),
            ("committed", 85),
            ("done", 114),
        ],
        holes: &[(78, 77), (79, 77), (80, 77)],
    },
    Baseline {
        name: "array_scalar_3_all_named",
        steps: 120,
        effects: &[
            ("receiver", 11),
            ("callback", 18),
            ("predicate", 40),
            ("predicate", 55),
            ("predicate", 70),
            ("committed", 89),
            ("done", 118),
        ],
        holes: &[(84, 83), (85, 83), (86, 83)],
    },
    Baseline {
        name: "array_scalar_3_none_closure",
        steps: 90,
        effects: &[
            ("receiver", 11),
            ("callback", 18),
            ("predicate", 38),
            ("predicate", 50),
            ("predicate", 62),
            ("committed", 80),
            ("done", 88),
        ],
        holes: &[(75, 74), (76, 74), (77, 74)],
    },
    Baseline {
        name: "array_scalar_3_none_generic",
        steps: 95,
        effects: &[
            ("receiver", 11),
            ("callback", 18),
            ("predicate", 41),
            ("predicate", 53),
            ("predicate", 65),
            ("committed", 85),
            ("done", 93),
        ],
        holes: &[(78, 77), (79, 77), (80, 77)],
    },
    Baseline {
        name: "array_scalar_3_none_named",
        steps: 99,
        effects: &[
            ("receiver", 11),
            ("callback", 18),
            ("predicate", 40),
            ("predicate", 55),
            ("predicate", 70),
            ("committed", 89),
            ("done", 97),
        ],
        holes: &[(84, 83), (85, 83), (86, 83)],
    },
    Baseline {
        name: "array_scalar_3_even_closure",
        steps: 116,
        effects: &[
            ("receiver", 11),
            ("callback", 18),
            ("predicate", 38),
            ("predicate", 54),
            ("predicate", 70),
            ("committed", 92),
            ("done", 114),
        ],
        holes: &[(87, 86), (88, 86), (89, 86)],
    },
    Baseline {
        name: "array_scalar_3_even_generic",
        steps: 121,
        effects: &[
            ("receiver", 11),
            ("callback", 18),
            ("predicate", 41),
            ("predicate", 57),
            ("predicate", 73),
            ("committed", 97),
            ("done", 119),
        ],
        holes: &[(90, 89), (91, 89), (92, 89)],
    },
    Baseline {
        name: "array_scalar_3_even_named",
        steps: 125,
        effects: &[
            ("receiver", 11),
            ("callback", 18),
            ("predicate", 40),
            ("predicate", 59),
            ("predicate", 78),
            ("committed", 101),
            ("done", 123),
        ],
        holes: &[(96, 95), (97, 95), (98, 95)],
    },
];
