use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "array_heap_0_all_closure",
        steps: 48,
        effects: &[
            ("receiver", 8),
            ("callback", 15),
            ("committed", 38),
            ("done", 46),
        ],
        holes: &[],
    },
    Baseline {
        name: "array_heap_0_all_generic",
        steps: 53,
        effects: &[
            ("receiver", 8),
            ("callback", 15),
            ("committed", 43),
            ("done", 51),
        ],
        holes: &[],
    },
    Baseline {
        name: "array_heap_0_all_named",
        steps: 48,
        effects: &[
            ("receiver", 8),
            ("callback", 15),
            ("committed", 38),
            ("done", 46),
        ],
        holes: &[],
    },
    Baseline {
        name: "array_heap_0_none_closure",
        steps: 48,
        effects: &[
            ("receiver", 8),
            ("callback", 15),
            ("committed", 38),
            ("done", 46),
        ],
        holes: &[],
    },
    Baseline {
        name: "array_heap_0_none_generic",
        steps: 53,
        effects: &[
            ("receiver", 8),
            ("callback", 15),
            ("committed", 43),
            ("done", 51),
        ],
        holes: &[],
    },
    Baseline {
        name: "array_heap_0_none_named",
        steps: 48,
        effects: &[
            ("receiver", 8),
            ("callback", 15),
            ("committed", 38),
            ("done", 46),
        ],
        holes: &[],
    },
    Baseline {
        name: "array_heap_0_even_closure",
        steps: 48,
        effects: &[
            ("receiver", 8),
            ("callback", 15),
            ("committed", 38),
            ("done", 46),
        ],
        holes: &[],
    },
    Baseline {
        name: "array_heap_0_even_generic",
        steps: 53,
        effects: &[
            ("receiver", 8),
            ("callback", 15),
            ("committed", 43),
            ("done", 51),
        ],
        holes: &[],
    },
    Baseline {
        name: "array_heap_0_even_named",
        steps: 48,
        effects: &[
            ("receiver", 8),
            ("callback", 15),
            ("committed", 38),
            ("done", 46),
        ],
        holes: &[],
    },
    Baseline {
        name: "array_heap_1_all_closure",
        steps: 76,
        effects: &[
            ("receiver", 10),
            ("callback", 17),
            ("predicate", 37),
            ("committed", 58),
            ("done", 74),
        ],
        holes: &[(55, 54)],
    },
    Baseline {
        name: "array_heap_1_all_generic",
        steps: 81,
        effects: &[
            ("receiver", 10),
            ("callback", 17),
            ("predicate", 40),
            ("committed", 63),
            ("done", 79),
        ],
        holes: &[(58, 57)],
    },
    Baseline {
        name: "array_heap_1_all_named",
        steps: 79,
        effects: &[
            ("receiver", 10),
            ("callback", 17),
            ("predicate", 39),
            ("committed", 61),
            ("done", 77),
        ],
        holes: &[(58, 57)],
    },
    Baseline {
        name: "array_heap_1_none_closure",
        steps: 68,
        effects: &[
            ("receiver", 10),
            ("callback", 17),
            ("predicate", 37),
            ("committed", 58),
            ("done", 66),
        ],
        holes: &[(55, 54)],
    },
    Baseline {
        name: "array_heap_1_none_generic",
        steps: 73,
        effects: &[
            ("receiver", 10),
            ("callback", 17),
            ("predicate", 40),
            ("committed", 63),
            ("done", 71),
        ],
        holes: &[(58, 57)],
    },
    Baseline {
        name: "array_heap_1_none_named",
        steps: 71,
        effects: &[
            ("receiver", 10),
            ("callback", 17),
            ("predicate", 39),
            ("committed", 61),
            ("done", 69),
        ],
        holes: &[(58, 57)],
    },
    Baseline {
        name: "array_heap_1_even_closure",
        steps: 83,
        effects: &[
            ("receiver", 10),
            ("callback", 17),
            ("predicate", 37),
            ("committed", 65),
            ("done", 81),
        ],
        holes: &[(62, 61)],
    },
    Baseline {
        name: "array_heap_1_even_generic",
        steps: 88,
        effects: &[
            ("receiver", 10),
            ("callback", 17),
            ("predicate", 40),
            ("committed", 70),
            ("done", 86),
        ],
        holes: &[(65, 64)],
    },
    Baseline {
        name: "array_heap_1_even_named",
        steps: 86,
        effects: &[
            ("receiver", 10),
            ("callback", 17),
            ("predicate", 39),
            ("committed", 68),
            ("done", 84),
        ],
        holes: &[(65, 64)],
    },
    Baseline {
        name: "array_heap_3_all_closure",
        steps: 132,
        effects: &[
            ("receiver", 14),
            ("callback", 21),
            ("predicate", 41),
            ("predicate", 58),
            ("predicate", 75),
            ("committed", 98),
            ("done", 130),
        ],
        holes: &[(93, 92), (94, 92), (95, 92)],
    },
    Baseline {
        name: "array_heap_3_all_generic",
        steps: 137,
        effects: &[
            ("receiver", 14),
            ("callback", 21),
            ("predicate", 44),
            ("predicate", 61),
            ("predicate", 78),
            ("committed", 103),
            ("done", 135),
        ],
        holes: &[(96, 95), (97, 95), (98, 95)],
    },
    Baseline {
        name: "array_heap_3_all_named",
        steps: 141,
        effects: &[
            ("receiver", 14),
            ("callback", 21),
            ("predicate", 43),
            ("predicate", 63),
            ("predicate", 83),
            ("committed", 107),
            ("done", 139),
        ],
        holes: &[(102, 101), (103, 101), (104, 101)],
    },
    Baseline {
        name: "array_heap_3_none_closure",
        steps: 108,
        effects: &[
            ("receiver", 14),
            ("callback", 21),
            ("predicate", 41),
            ("predicate", 58),
            ("predicate", 75),
            ("committed", 98),
            ("done", 106),
        ],
        holes: &[(93, 92), (94, 92), (95, 92)],
    },
    Baseline {
        name: "array_heap_3_none_generic",
        steps: 113,
        effects: &[
            ("receiver", 14),
            ("callback", 21),
            ("predicate", 44),
            ("predicate", 61),
            ("predicate", 78),
            ("committed", 103),
            ("done", 111),
        ],
        holes: &[(96, 95), (97, 95), (98, 95)],
    },
    Baseline {
        name: "array_heap_3_none_named",
        steps: 117,
        effects: &[
            ("receiver", 14),
            ("callback", 21),
            ("predicate", 43),
            ("predicate", 63),
            ("predicate", 83),
            ("committed", 107),
            ("done", 115),
        ],
        holes: &[(102, 101), (103, 101), (104, 101)],
    },
    Baseline {
        name: "array_heap_3_even_closure",
        steps: 145,
        effects: &[
            ("receiver", 14),
            ("callback", 21),
            ("predicate", 41),
            ("predicate", 65),
            ("predicate", 89),
            ("committed", 119),
            ("done", 143),
        ],
        holes: &[(114, 113), (115, 113), (116, 113)],
    },
    Baseline {
        name: "array_heap_3_even_generic",
        steps: 150,
        effects: &[
            ("receiver", 14),
            ("callback", 21),
            ("predicate", 44),
            ("predicate", 68),
            ("predicate", 92),
            ("committed", 124),
            ("done", 148),
        ],
        holes: &[(117, 116), (118, 116), (119, 116)],
    },
    Baseline {
        name: "array_heap_3_even_named",
        steps: 154,
        effects: &[
            ("receiver", 14),
            ("callback", 21),
            ("predicate", 43),
            ("predicate", 70),
            ("predicate", 97),
            ("committed", 128),
            ("done", 152),
        ],
        holes: &[(123, 122), (124, 122), (125, 122)],
    },
];
