use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "map_custom_0_all_closure",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_custom_0_all_generic",
        steps: 83,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 59),
            ("done", 81),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_custom_0_all_named",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_custom_0_none_closure",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_custom_0_none_generic",
        steps: 83,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 59),
            ("done", 81),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_custom_0_none_named",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_custom_0_even_closure",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_custom_0_even_generic",
        steps: 83,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 59),
            ("done", 81),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_custom_0_even_named",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_custom_1_all_closure",
        steps: 190,
        effects: &[
            ("hash", 31),
            ("receiver", 53),
            ("callback", 60),
            ("predicate", 84),
            ("committed", 110),
            ("done", 188),
        ],
        holes: &[(107, 106)],
    },
    Baseline {
        name: "map_custom_1_all_generic",
        steps: 195,
        effects: &[
            ("hash", 31),
            ("receiver", 53),
            ("callback", 60),
            ("predicate", 87),
            ("committed", 115),
            ("done", 193),
        ],
        holes: &[(110, 109)],
    },
    Baseline {
        name: "map_custom_1_all_named",
        steps: 194,
        effects: &[
            ("hash", 31),
            ("receiver", 53),
            ("callback", 60),
            ("predicate", 87),
            ("committed", 114),
            ("done", 192),
        ],
        holes: &[(111, 110)],
    },
    Baseline {
        name: "map_custom_1_none_closure",
        steps: 154,
        effects: &[
            ("hash", 31),
            ("receiver", 53),
            ("callback", 60),
            ("predicate", 84),
            ("committed", 110),
            ("done", 152),
        ],
        holes: &[(107, 106)],
    },
    Baseline {
        name: "map_custom_1_none_generic",
        steps: 159,
        effects: &[
            ("hash", 31),
            ("receiver", 53),
            ("callback", 60),
            ("predicate", 87),
            ("committed", 115),
            ("done", 157),
        ],
        holes: &[(110, 109)],
    },
    Baseline {
        name: "map_custom_1_none_named",
        steps: 158,
        effects: &[
            ("hash", 31),
            ("receiver", 53),
            ("callback", 60),
            ("predicate", 87),
            ("committed", 114),
            ("done", 156),
        ],
        holes: &[(111, 110)],
    },
    Baseline {
        name: "map_custom_1_even_closure",
        steps: 195,
        effects: &[
            ("hash", 31),
            ("receiver", 53),
            ("callback", 60),
            ("predicate", 84),
            ("committed", 115),
            ("done", 193),
        ],
        holes: &[(112, 111)],
    },
    Baseline {
        name: "map_custom_1_even_generic",
        steps: 200,
        effects: &[
            ("hash", 31),
            ("receiver", 53),
            ("callback", 60),
            ("predicate", 87),
            ("committed", 120),
            ("done", 198),
        ],
        holes: &[(115, 114)],
    },
    Baseline {
        name: "map_custom_1_even_named",
        steps: 199,
        effects: &[
            ("hash", 31),
            ("receiver", 53),
            ("callback", 60),
            ("predicate", 87),
            ("committed", 119),
            ("done", 197),
        ],
        holes: &[(116, 115)],
    },
    Baseline {
        name: "map_custom_3_all_closure",
        steps: 477,
        effects: &[
            ("hash", 43),
            ("hash", 66),
            ("eq", 83),
            ("hash", 110),
            ("eq", 127),
            ("eq", 148),
            ("receiver", 174),
            ("callback", 181),
            ("predicate", 205),
            ("predicate", 231),
            ("predicate", 257),
            ("committed", 285),
            ("done", 475),
        ],
        holes: &[(280, 279), (281, 279), (282, 279)],
    },
    Baseline {
        name: "map_custom_3_all_generic",
        steps: 482,
        effects: &[
            ("hash", 43),
            ("hash", 66),
            ("eq", 83),
            ("hash", 110),
            ("eq", 127),
            ("eq", 148),
            ("receiver", 174),
            ("callback", 181),
            ("predicate", 208),
            ("predicate", 234),
            ("predicate", 260),
            ("committed", 290),
            ("done", 480),
        ],
        holes: &[(283, 282), (284, 282), (285, 282)],
    },
    Baseline {
        name: "map_custom_3_all_named",
        steps: 489,
        effects: &[
            ("hash", 43),
            ("hash", 66),
            ("eq", 83),
            ("hash", 110),
            ("eq", 127),
            ("eq", 148),
            ("receiver", 174),
            ("callback", 181),
            ("predicate", 208),
            ("predicate", 238),
            ("predicate", 268),
            ("committed", 297),
            ("done", 487),
        ],
        holes: &[(292, 291), (293, 291), (294, 291)],
    },
    Baseline {
        name: "map_custom_3_none_closure",
        steps: 369,
        effects: &[
            ("hash", 43),
            ("hash", 66),
            ("eq", 83),
            ("hash", 110),
            ("eq", 127),
            ("eq", 148),
            ("receiver", 174),
            ("callback", 181),
            ("predicate", 205),
            ("predicate", 231),
            ("predicate", 257),
            ("committed", 285),
            ("done", 367),
        ],
        holes: &[(280, 279), (281, 279), (282, 279)],
    },
    Baseline {
        name: "map_custom_3_none_generic",
        steps: 374,
        effects: &[
            ("hash", 43),
            ("hash", 66),
            ("eq", 83),
            ("hash", 110),
            ("eq", 127),
            ("eq", 148),
            ("receiver", 174),
            ("callback", 181),
            ("predicate", 208),
            ("predicate", 234),
            ("predicate", 260),
            ("committed", 290),
            ("done", 372),
        ],
        holes: &[(283, 282), (284, 282), (285, 282)],
    },
    Baseline {
        name: "map_custom_3_none_named",
        steps: 381,
        effects: &[
            ("hash", 43),
            ("hash", 66),
            ("eq", 83),
            ("hash", 110),
            ("eq", 127),
            ("eq", 148),
            ("receiver", 174),
            ("callback", 181),
            ("predicate", 208),
            ("predicate", 238),
            ("predicate", 268),
            ("committed", 297),
            ("done", 379),
        ],
        holes: &[(292, 291), (293, 291), (294, 291)],
    },
    Baseline {
        name: "map_custom_3_even_closure",
        steps: 456,
        effects: &[
            ("hash", 43),
            ("hash", 66),
            ("eq", 83),
            ("hash", 110),
            ("eq", 127),
            ("eq", 148),
            ("receiver", 174),
            ("callback", 181),
            ("predicate", 205),
            ("predicate", 236),
            ("predicate", 267),
            ("committed", 300),
            ("done", 454),
        ],
        holes: &[(295, 294), (296, 294), (297, 294)],
    },
    Baseline {
        name: "map_custom_3_even_generic",
        steps: 461,
        effects: &[
            ("hash", 43),
            ("hash", 66),
            ("eq", 83),
            ("hash", 110),
            ("eq", 127),
            ("eq", 148),
            ("receiver", 174),
            ("callback", 181),
            ("predicate", 208),
            ("predicate", 239),
            ("predicate", 270),
            ("committed", 305),
            ("done", 459),
        ],
        holes: &[(298, 297), (299, 297), (300, 297)],
    },
    Baseline {
        name: "map_custom_3_even_named",
        steps: 468,
        effects: &[
            ("hash", 43),
            ("hash", 66),
            ("eq", 83),
            ("hash", 110),
            ("eq", 127),
            ("eq", 148),
            ("receiver", 174),
            ("callback", 181),
            ("predicate", 208),
            ("predicate", 243),
            ("predicate", 278),
            ("committed", 312),
            ("done", 466),
        ],
        holes: &[(307, 306), (308, 306), (309, 306)],
    },
];
