use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "map_heap_0_all_closure",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_heap_0_all_generic",
        steps: 83,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 59),
            ("done", 81),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_heap_0_all_named",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_heap_0_none_closure",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_heap_0_none_generic",
        steps: 83,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 59),
            ("done", 81),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_heap_0_none_named",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_heap_0_even_closure",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_heap_0_even_generic",
        steps: 83,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 59),
            ("done", 81),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_heap_0_even_named",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_heap_1_all_closure",
        steps: 149,
        effects: &[
            ("receiver", 38),
            ("callback", 45),
            ("predicate", 69),
            ("committed", 90),
            ("done", 147),
        ],
        holes: &[(87, 86)],
    },
    Baseline {
        name: "map_heap_1_all_generic",
        steps: 154,
        effects: &[
            ("receiver", 38),
            ("callback", 45),
            ("predicate", 72),
            ("committed", 95),
            ("done", 152),
        ],
        holes: &[(90, 89)],
    },
    Baseline {
        name: "map_heap_1_all_named",
        steps: 153,
        effects: &[
            ("receiver", 38),
            ("callback", 45),
            ("predicate", 72),
            ("committed", 94),
            ("done", 151),
        ],
        holes: &[(91, 90)],
    },
    Baseline {
        name: "map_heap_1_none_closure",
        steps: 124,
        effects: &[
            ("receiver", 38),
            ("callback", 45),
            ("predicate", 69),
            ("committed", 90),
            ("done", 122),
        ],
        holes: &[(87, 86)],
    },
    Baseline {
        name: "map_heap_1_none_generic",
        steps: 129,
        effects: &[
            ("receiver", 38),
            ("callback", 45),
            ("predicate", 72),
            ("committed", 95),
            ("done", 127),
        ],
        holes: &[(90, 89)],
    },
    Baseline {
        name: "map_heap_1_none_named",
        steps: 128,
        effects: &[
            ("receiver", 38),
            ("callback", 45),
            ("predicate", 72),
            ("committed", 94),
            ("done", 126),
        ],
        holes: &[(91, 90)],
    },
    Baseline {
        name: "map_heap_1_even_closure",
        steps: 153,
        effects: &[
            ("receiver", 38),
            ("callback", 45),
            ("predicate", 69),
            ("committed", 94),
            ("done", 151),
        ],
        holes: &[(91, 90)],
    },
    Baseline {
        name: "map_heap_1_even_generic",
        steps: 158,
        effects: &[
            ("receiver", 38),
            ("callback", 45),
            ("predicate", 72),
            ("committed", 99),
            ("done", 156),
        ],
        holes: &[(94, 93)],
    },
    Baseline {
        name: "map_heap_1_even_named",
        steps: 157,
        effects: &[
            ("receiver", 38),
            ("callback", 45),
            ("predicate", 72),
            ("committed", 98),
            ("done", 155),
        ],
        holes: &[(95, 94)],
    },
    Baseline {
        name: "map_heap_3_all_closure",
        steps: 291,
        effects: &[
            ("receiver", 66),
            ("callback", 73),
            ("predicate", 97),
            ("predicate", 118),
            ("predicate", 139),
            ("committed", 162),
            ("done", 289),
        ],
        holes: &[(157, 156), (158, 156), (159, 156)],
    },
    Baseline {
        name: "map_heap_3_all_generic",
        steps: 296,
        effects: &[
            ("receiver", 66),
            ("callback", 73),
            ("predicate", 100),
            ("predicate", 121),
            ("predicate", 142),
            ("committed", 167),
            ("done", 294),
        ],
        holes: &[(160, 159), (161, 159), (162, 159)],
    },
    Baseline {
        name: "map_heap_3_all_named",
        steps: 303,
        effects: &[
            ("receiver", 66),
            ("callback", 73),
            ("predicate", 100),
            ("predicate", 125),
            ("predicate", 150),
            ("committed", 174),
            ("done", 301),
        ],
        holes: &[(169, 168), (170, 168), (171, 168)],
    },
    Baseline {
        name: "map_heap_3_none_closure",
        steps: 216,
        effects: &[
            ("receiver", 66),
            ("callback", 73),
            ("predicate", 97),
            ("predicate", 118),
            ("predicate", 139),
            ("committed", 162),
            ("done", 214),
        ],
        holes: &[(157, 156), (158, 156), (159, 156)],
    },
    Baseline {
        name: "map_heap_3_none_generic",
        steps: 221,
        effects: &[
            ("receiver", 66),
            ("callback", 73),
            ("predicate", 100),
            ("predicate", 121),
            ("predicate", 142),
            ("committed", 167),
            ("done", 219),
        ],
        holes: &[(160, 159), (161, 159), (162, 159)],
    },
    Baseline {
        name: "map_heap_3_none_named",
        steps: 228,
        effects: &[
            ("receiver", 66),
            ("callback", 73),
            ("predicate", 100),
            ("predicate", 125),
            ("predicate", 150),
            ("committed", 174),
            ("done", 226),
        ],
        holes: &[(169, 168), (170, 168), (171, 168)],
    },
    Baseline {
        name: "map_heap_3_even_closure",
        steps: 278,
        effects: &[
            ("receiver", 66),
            ("callback", 73),
            ("predicate", 97),
            ("predicate", 122),
            ("predicate", 147),
            ("committed", 174),
            ("done", 276),
        ],
        holes: &[(169, 168), (170, 168), (171, 168)],
    },
    Baseline {
        name: "map_heap_3_even_generic",
        steps: 283,
        effects: &[
            ("receiver", 66),
            ("callback", 73),
            ("predicate", 100),
            ("predicate", 125),
            ("predicate", 150),
            ("committed", 179),
            ("done", 281),
        ],
        holes: &[(172, 171), (173, 171), (174, 171)],
    },
    Baseline {
        name: "map_heap_3_even_named",
        steps: 290,
        effects: &[
            ("receiver", 66),
            ("callback", 73),
            ("predicate", 100),
            ("predicate", 129),
            ("predicate", 158),
            ("committed", 186),
            ("done", 288),
        ],
        holes: &[(181, 180), (182, 180), (183, 180)],
    },
];
