use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "map_scalar_0_all_closure",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_scalar_0_all_generic",
        steps: 83,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 59),
            ("done", 81),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_scalar_0_all_named",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_scalar_0_none_closure",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_scalar_0_none_generic",
        steps: 83,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 59),
            ("done", 81),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_scalar_0_none_named",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_scalar_0_even_closure",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_scalar_0_even_generic",
        steps: 83,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 59),
            ("done", 81),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_scalar_0_even_named",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_scalar_1_all_closure",
        steps: 132,
        effects: &[
            ("receiver", 37),
            ("callback", 44),
            ("predicate", 68),
            ("committed", 84),
            ("done", 130),
        ],
        holes: &[(81, 80)],
    },
    Baseline {
        name: "map_scalar_1_all_generic",
        steps: 137,
        effects: &[
            ("receiver", 37),
            ("callback", 44),
            ("predicate", 71),
            ("committed", 89),
            ("done", 135),
        ],
        holes: &[(84, 83)],
    },
    Baseline {
        name: "map_scalar_1_all_named",
        steps: 136,
        effects: &[
            ("receiver", 37),
            ("callback", 44),
            ("predicate", 71),
            ("committed", 88),
            ("done", 134),
        ],
        holes: &[(85, 84)],
    },
    Baseline {
        name: "map_scalar_1_none_closure",
        steps: 108,
        effects: &[
            ("receiver", 37),
            ("callback", 44),
            ("predicate", 68),
            ("committed", 84),
            ("done", 106),
        ],
        holes: &[(81, 80)],
    },
    Baseline {
        name: "map_scalar_1_none_generic",
        steps: 113,
        effects: &[
            ("receiver", 37),
            ("callback", 44),
            ("predicate", 71),
            ("committed", 89),
            ("done", 111),
        ],
        holes: &[(84, 83)],
    },
    Baseline {
        name: "map_scalar_1_none_named",
        steps: 112,
        effects: &[
            ("receiver", 37),
            ("callback", 44),
            ("predicate", 71),
            ("committed", 88),
            ("done", 110),
        ],
        holes: &[(85, 84)],
    },
    Baseline {
        name: "map_scalar_1_even_closure",
        steps: 136,
        effects: &[
            ("receiver", 37),
            ("callback", 44),
            ("predicate", 68),
            ("committed", 88),
            ("done", 134),
        ],
        holes: &[(85, 84)],
    },
    Baseline {
        name: "map_scalar_1_even_generic",
        steps: 141,
        effects: &[
            ("receiver", 37),
            ("callback", 44),
            ("predicate", 71),
            ("committed", 93),
            ("done", 139),
        ],
        holes: &[(88, 87)],
    },
    Baseline {
        name: "map_scalar_1_even_named",
        steps: 140,
        effects: &[
            ("receiver", 37),
            ("callback", 44),
            ("predicate", 71),
            ("committed", 92),
            ("done", 138),
        ],
        holes: &[(89, 88)],
    },
    Baseline {
        name: "map_scalar_3_all_closure",
        steps: 240,
        effects: &[
            ("receiver", 63),
            ("callback", 70),
            ("predicate", 94),
            ("predicate", 110),
            ("predicate", 126),
            ("committed", 144),
            ("done", 238),
        ],
        holes: &[(139, 138), (140, 138), (141, 138)],
    },
    Baseline {
        name: "map_scalar_3_all_generic",
        steps: 245,
        effects: &[
            ("receiver", 63),
            ("callback", 70),
            ("predicate", 97),
            ("predicate", 113),
            ("predicate", 129),
            ("committed", 149),
            ("done", 243),
        ],
        holes: &[(142, 141), (143, 141), (144, 141)],
    },
    Baseline {
        name: "map_scalar_3_all_named",
        steps: 252,
        effects: &[
            ("receiver", 63),
            ("callback", 70),
            ("predicate", 97),
            ("predicate", 117),
            ("predicate", 137),
            ("committed", 156),
            ("done", 250),
        ],
        holes: &[(151, 150), (152, 150), (153, 150)],
    },
    Baseline {
        name: "map_scalar_3_none_closure",
        steps: 168,
        effects: &[
            ("receiver", 63),
            ("callback", 70),
            ("predicate", 94),
            ("predicate", 110),
            ("predicate", 126),
            ("committed", 144),
            ("done", 166),
        ],
        holes: &[(139, 138), (140, 138), (141, 138)],
    },
    Baseline {
        name: "map_scalar_3_none_generic",
        steps: 173,
        effects: &[
            ("receiver", 63),
            ("callback", 70),
            ("predicate", 97),
            ("predicate", 113),
            ("predicate", 129),
            ("committed", 149),
            ("done", 171),
        ],
        holes: &[(142, 141), (143, 141), (144, 141)],
    },
    Baseline {
        name: "map_scalar_3_none_named",
        steps: 180,
        effects: &[
            ("receiver", 63),
            ("callback", 70),
            ("predicate", 97),
            ("predicate", 117),
            ("predicate", 137),
            ("committed", 156),
            ("done", 178),
        ],
        holes: &[(151, 150), (152, 150), (153, 150)],
    },
    Baseline {
        name: "map_scalar_3_even_closure",
        steps: 228,
        effects: &[
            ("receiver", 63),
            ("callback", 70),
            ("predicate", 94),
            ("predicate", 114),
            ("predicate", 134),
            ("committed", 156),
            ("done", 226),
        ],
        holes: &[(151, 150), (152, 150), (153, 150)],
    },
    Baseline {
        name: "map_scalar_3_even_generic",
        steps: 233,
        effects: &[
            ("receiver", 63),
            ("callback", 70),
            ("predicate", 97),
            ("predicate", 117),
            ("predicate", 137),
            ("committed", 161),
            ("done", 231),
        ],
        holes: &[(154, 153), (155, 153), (156, 153)],
    },
    Baseline {
        name: "map_scalar_3_even_named",
        steps: 240,
        effects: &[
            ("receiver", 63),
            ("callback", 70),
            ("predicate", 97),
            ("predicate", 121),
            ("predicate", 145),
            ("committed", 168),
            ("done", 238),
        ],
        holes: &[(163, 162), (164, 162), (165, 162)],
    },
];
