use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "set_scalar_0_all_closure",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_scalar_0_all_generic",
        steps: 83,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 59),
            ("done", 81),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_scalar_0_all_named",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_scalar_0_none_closure",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_scalar_0_none_generic",
        steps: 83,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 59),
            ("done", 81),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_scalar_0_none_named",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_scalar_0_even_closure",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_scalar_0_even_generic",
        steps: 83,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 59),
            ("done", 81),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_scalar_0_even_named",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_scalar_1_all_closure",
        steps: 111,
        effects: &[
            ("receiver", 31),
            ("callback", 38),
            ("predicate", 58),
            ("committed", 74),
            ("done", 109),
        ],
        holes: &[(71, 70)],
    },
    Baseline {
        name: "set_scalar_1_all_generic",
        steps: 116,
        effects: &[
            ("receiver", 31),
            ("callback", 38),
            ("predicate", 61),
            ("committed", 79),
            ("done", 114),
        ],
        holes: &[(74, 73)],
    },
    Baseline {
        name: "set_scalar_1_all_named",
        steps: 114,
        effects: &[
            ("receiver", 31),
            ("callback", 38),
            ("predicate", 60),
            ("committed", 77),
            ("done", 112),
        ],
        holes: &[(74, 73)],
    },
    Baseline {
        name: "set_scalar_1_none_closure",
        steps: 98,
        effects: &[
            ("receiver", 31),
            ("callback", 38),
            ("predicate", 58),
            ("committed", 74),
            ("done", 96),
        ],
        holes: &[(71, 70)],
    },
    Baseline {
        name: "set_scalar_1_none_generic",
        steps: 103,
        effects: &[
            ("receiver", 31),
            ("callback", 38),
            ("predicate", 61),
            ("committed", 79),
            ("done", 101),
        ],
        holes: &[(74, 73)],
    },
    Baseline {
        name: "set_scalar_1_none_named",
        steps: 101,
        effects: &[
            ("receiver", 31),
            ("callback", 38),
            ("predicate", 60),
            ("committed", 77),
            ("done", 99),
        ],
        holes: &[(74, 73)],
    },
    Baseline {
        name: "set_scalar_1_even_closure",
        steps: 115,
        effects: &[
            ("receiver", 31),
            ("callback", 38),
            ("predicate", 58),
            ("committed", 78),
            ("done", 113),
        ],
        holes: &[(75, 74)],
    },
    Baseline {
        name: "set_scalar_1_even_generic",
        steps: 120,
        effects: &[
            ("receiver", 31),
            ("callback", 38),
            ("predicate", 61),
            ("committed", 83),
            ("done", 118),
        ],
        holes: &[(78, 77)],
    },
    Baseline {
        name: "set_scalar_1_even_named",
        steps: 118,
        effects: &[
            ("receiver", 31),
            ("callback", 38),
            ("predicate", 60),
            ("committed", 81),
            ("done", 116),
        ],
        holes: &[(78, 77)],
    },
    Baseline {
        name: "set_scalar_3_all_closure",
        steps: 177,
        effects: &[
            ("receiver", 45),
            ("callback", 52),
            ("predicate", 72),
            ("predicate", 84),
            ("predicate", 96),
            ("committed", 114),
            ("done", 175),
        ],
        holes: &[(109, 108), (110, 108), (111, 108)],
    },
    Baseline {
        name: "set_scalar_3_all_generic",
        steps: 182,
        effects: &[
            ("receiver", 45),
            ("callback", 52),
            ("predicate", 75),
            ("predicate", 87),
            ("predicate", 99),
            ("committed", 119),
            ("done", 180),
        ],
        holes: &[(112, 111), (113, 111), (114, 111)],
    },
    Baseline {
        name: "set_scalar_3_all_named",
        steps: 186,
        effects: &[
            ("receiver", 45),
            ("callback", 52),
            ("predicate", 74),
            ("predicate", 89),
            ("predicate", 104),
            ("committed", 123),
            ("done", 184),
        ],
        holes: &[(118, 117), (119, 117), (120, 117)],
    },
    Baseline {
        name: "set_scalar_3_none_closure",
        steps: 138,
        effects: &[
            ("receiver", 45),
            ("callback", 52),
            ("predicate", 72),
            ("predicate", 84),
            ("predicate", 96),
            ("committed", 114),
            ("done", 136),
        ],
        holes: &[(109, 108), (110, 108), (111, 108)],
    },
    Baseline {
        name: "set_scalar_3_none_generic",
        steps: 143,
        effects: &[
            ("receiver", 45),
            ("callback", 52),
            ("predicate", 75),
            ("predicate", 87),
            ("predicate", 99),
            ("committed", 119),
            ("done", 141),
        ],
        holes: &[(112, 111), (113, 111), (114, 111)],
    },
    Baseline {
        name: "set_scalar_3_none_named",
        steps: 147,
        effects: &[
            ("receiver", 45),
            ("callback", 52),
            ("predicate", 74),
            ("predicate", 89),
            ("predicate", 104),
            ("committed", 123),
            ("done", 145),
        ],
        holes: &[(118, 117), (119, 117), (120, 117)],
    },
    Baseline {
        name: "set_scalar_3_even_closure",
        steps: 176,
        effects: &[
            ("receiver", 45),
            ("callback", 52),
            ("predicate", 72),
            ("predicate", 88),
            ("predicate", 104),
            ("committed", 126),
            ("done", 174),
        ],
        holes: &[(121, 120), (122, 120), (123, 120)],
    },
    Baseline {
        name: "set_scalar_3_even_generic",
        steps: 181,
        effects: &[
            ("receiver", 45),
            ("callback", 52),
            ("predicate", 75),
            ("predicate", 91),
            ("predicate", 107),
            ("committed", 131),
            ("done", 179),
        ],
        holes: &[(124, 123), (125, 123), (126, 123)],
    },
    Baseline {
        name: "set_scalar_3_even_named",
        steps: 185,
        effects: &[
            ("receiver", 45),
            ("callback", 52),
            ("predicate", 74),
            ("predicate", 93),
            ("predicate", 112),
            ("committed", 135),
            ("done", 183),
        ],
        holes: &[(130, 129), (131, 129), (132, 129)],
    },
];
