use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "set_custom_0_all_closure",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_custom_0_all_generic",
        steps: 83,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 59),
            ("done", 81),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_custom_0_all_named",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_custom_0_none_closure",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_custom_0_none_generic",
        steps: 83,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 59),
            ("done", 81),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_custom_0_none_named",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_custom_0_even_closure",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_custom_0_even_generic",
        steps: 83,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 59),
            ("done", 81),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_custom_0_even_named",
        steps: 78,
        effects: &[
            ("receiver", 24),
            ("callback", 31),
            ("committed", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_custom_1_all_closure",
        steps: 148,
        effects: &[
            ("hash", 24),
            ("receiver", 46),
            ("callback", 53),
            ("predicate", 73),
            ("committed", 94),
            ("done", 146),
        ],
        holes: &[(91, 90)],
    },
    Baseline {
        name: "set_custom_1_all_generic",
        steps: 153,
        effects: &[
            ("hash", 24),
            ("receiver", 46),
            ("callback", 53),
            ("predicate", 76),
            ("committed", 99),
            ("done", 151),
        ],
        holes: &[(94, 93)],
    },
    Baseline {
        name: "set_custom_1_all_named",
        steps: 151,
        effects: &[
            ("hash", 24),
            ("receiver", 46),
            ("callback", 53),
            ("predicate", 75),
            ("committed", 97),
            ("done", 149),
        ],
        holes: &[(94, 93)],
    },
    Baseline {
        name: "set_custom_1_none_closure",
        steps: 126,
        effects: &[
            ("hash", 24),
            ("receiver", 46),
            ("callback", 53),
            ("predicate", 73),
            ("committed", 94),
            ("done", 124),
        ],
        holes: &[(91, 90)],
    },
    Baseline {
        name: "set_custom_1_none_generic",
        steps: 131,
        effects: &[
            ("hash", 24),
            ("receiver", 46),
            ("callback", 53),
            ("predicate", 76),
            ("committed", 99),
            ("done", 129),
        ],
        holes: &[(94, 93)],
    },
    Baseline {
        name: "set_custom_1_none_named",
        steps: 129,
        effects: &[
            ("hash", 24),
            ("receiver", 46),
            ("callback", 53),
            ("predicate", 75),
            ("committed", 97),
            ("done", 127),
        ],
        holes: &[(94, 93)],
    },
    Baseline {
        name: "set_custom_1_even_closure",
        steps: 153,
        effects: &[
            ("hash", 24),
            ("receiver", 46),
            ("callback", 53),
            ("predicate", 73),
            ("committed", 99),
            ("done", 151),
        ],
        holes: &[(96, 95)],
    },
    Baseline {
        name: "set_custom_1_even_generic",
        steps: 158,
        effects: &[
            ("hash", 24),
            ("receiver", 46),
            ("callback", 53),
            ("predicate", 76),
            ("committed", 104),
            ("done", 156),
        ],
        holes: &[(99, 98)],
    },
    Baseline {
        name: "set_custom_1_even_named",
        steps: 156,
        effects: &[
            ("hash", 24),
            ("receiver", 46),
            ("callback", 53),
            ("predicate", 75),
            ("committed", 102),
            ("done", 154),
        ],
        holes: &[(99, 98)],
    },
    Baseline {
        name: "set_custom_3_all_closure",
        steps: 351,
        effects: &[
            ("hash", 30),
            ("hash", 49),
            ("eq", 66),
            ("hash", 89),
            ("eq", 106),
            ("eq", 127),
            ("receiver", 153),
            ("callback", 160),
            ("predicate", 180),
            ("predicate", 197),
            ("predicate", 214),
            ("committed", 237),
            ("done", 349),
        ],
        holes: &[(232, 231), (233, 231), (234, 231)],
    },
    Baseline {
        name: "set_custom_3_all_generic",
        steps: 356,
        effects: &[
            ("hash", 30),
            ("hash", 49),
            ("eq", 66),
            ("hash", 89),
            ("eq", 106),
            ("eq", 127),
            ("receiver", 153),
            ("callback", 160),
            ("predicate", 183),
            ("predicate", 200),
            ("predicate", 217),
            ("committed", 242),
            ("done", 354),
        ],
        holes: &[(235, 234), (236, 234), (237, 234)],
    },
    Baseline {
        name: "set_custom_3_all_named",
        steps: 360,
        effects: &[
            ("hash", 30),
            ("hash", 49),
            ("eq", 66),
            ("hash", 89),
            ("eq", 106),
            ("eq", 127),
            ("receiver", 153),
            ("callback", 160),
            ("predicate", 182),
            ("predicate", 202),
            ("predicate", 222),
            ("committed", 246),
            ("done", 358),
        ],
        holes: &[(241, 240), (242, 240), (243, 240)],
    },
    Baseline {
        name: "set_custom_3_none_closure",
        steps: 285,
        effects: &[
            ("hash", 30),
            ("hash", 49),
            ("eq", 66),
            ("hash", 89),
            ("eq", 106),
            ("eq", 127),
            ("receiver", 153),
            ("callback", 160),
            ("predicate", 180),
            ("predicate", 197),
            ("predicate", 214),
            ("committed", 237),
            ("done", 283),
        ],
        holes: &[(232, 231), (233, 231), (234, 231)],
    },
    Baseline {
        name: "set_custom_3_none_generic",
        steps: 290,
        effects: &[
            ("hash", 30),
            ("hash", 49),
            ("eq", 66),
            ("hash", 89),
            ("eq", 106),
            ("eq", 127),
            ("receiver", 153),
            ("callback", 160),
            ("predicate", 183),
            ("predicate", 200),
            ("predicate", 217),
            ("committed", 242),
            ("done", 288),
        ],
        holes: &[(235, 234), (236, 234), (237, 234)],
    },
    Baseline {
        name: "set_custom_3_none_named",
        steps: 294,
        effects: &[
            ("hash", 30),
            ("hash", 49),
            ("eq", 66),
            ("hash", 89),
            ("eq", 106),
            ("eq", 127),
            ("receiver", 153),
            ("callback", 160),
            ("predicate", 182),
            ("predicate", 202),
            ("predicate", 222),
            ("committed", 246),
            ("done", 292),
        ],
        holes: &[(241, 240), (242, 240), (243, 240)],
    },
    Baseline {
        name: "set_custom_3_even_closure",
        steps: 344,
        effects: &[
            ("hash", 30),
            ("hash", 49),
            ("eq", 66),
            ("hash", 89),
            ("eq", 106),
            ("eq", 127),
            ("receiver", 153),
            ("callback", 160),
            ("predicate", 180),
            ("predicate", 202),
            ("predicate", 224),
            ("committed", 252),
            ("done", 342),
        ],
        holes: &[(247, 246), (248, 246), (249, 246)],
    },
    Baseline {
        name: "set_custom_3_even_generic",
        steps: 349,
        effects: &[
            ("hash", 30),
            ("hash", 49),
            ("eq", 66),
            ("hash", 89),
            ("eq", 106),
            ("eq", 127),
            ("receiver", 153),
            ("callback", 160),
            ("predicate", 183),
            ("predicate", 205),
            ("predicate", 227),
            ("committed", 257),
            ("done", 347),
        ],
        holes: &[(250, 249), (251, 249), (252, 249)],
    },
    Baseline {
        name: "set_custom_3_even_named",
        steps: 353,
        effects: &[
            ("hash", 30),
            ("hash", 49),
            ("eq", 66),
            ("hash", 89),
            ("eq", 106),
            ("eq", 127),
            ("receiver", 153),
            ("callback", 160),
            ("predicate", 182),
            ("predicate", 207),
            ("predicate", 232),
            ("committed", 261),
            ("done", 351),
        ],
        holes: &[(256, 255), (257, 255), (258, 255)],
    },
];
