use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "enum_array_contains_0",
        steps: 35,
        effects: &[("done", 31)],
    },
    Baseline {
        name: "enum_array_contains_1",
        steps: 100,
        effects: &[("eq", 69), ("done", 96)],
    },
    Baseline {
        name: "enum_array_contains_2",
        steps: 104,
        effects: &[("done", 100)],
    },
    Baseline {
        name: "enum_array_starts_with_0",
        steps: 60,
        effects: &[("done", 56)],
    },
    Baseline {
        name: "enum_array_starts_with_1",
        steps: 137,
        effects: &[("eq", 102), ("done", 133)],
    },
    Baseline {
        name: "enum_array_starts_with_2",
        steps: 116,
        effects: &[("done", 112)],
    },
    Baseline {
        name: "enum_array_starts_with_3",
        steps: 53,
        effects: &[("done", 49)],
    },
    Baseline {
        name: "enum_array_starts_with_4",
        steps: 58,
        effects: &[("done", 54)],
    },
    Baseline {
        name: "enum_array_ends_with_0",
        steps: 60,
        effects: &[("done", 56)],
    },
    Baseline {
        name: "enum_array_ends_with_1",
        steps: 162,
        effects: &[("eq", 80), ("eq", 127), ("done", 158)],
    },
    Baseline {
        name: "enum_array_ends_with_2",
        steps: 141,
        effects: &[("eq", 79), ("done", 137)],
    },
    Baseline {
        name: "enum_array_ends_with_3",
        steps: 53,
        effects: &[("done", 49)],
    },
    Baseline {
        name: "enum_array_ends_with_4",
        steps: 58,
        effects: &[("done", 54)],
    },
    Baseline {
        name: "enum_custom_contains_0",
        steps: 48,
        effects: &[("iter", 14), ("len", 24), ("done", 44)],
    },
    Baseline {
        name: "enum_custom_contains_1",
        steps: 127,
        effects: &[
            ("iter", 23),
            ("len", 33),
            ("get", 46),
            ("get", 72),
            ("eq", 96),
            ("done", 123),
        ],
    },
    Baseline {
        name: "enum_custom_contains_2",
        steps: 138,
        effects: &[
            ("iter", 22),
            ("len", 32),
            ("get", 45),
            ("get", 71),
            ("get", 99),
            ("done", 134),
        ],
    },
    Baseline {
        name: "enum_custom_starts_with_0",
        steps: 80,
        effects: &[
            ("iter", 26),
            ("len", 36),
            ("iter", 44),
            ("len", 54),
            ("done", 76),
        ],
    },
    Baseline {
        name: "enum_custom_starts_with_1",
        steps: 177,
        effects: &[
            ("iter", 31),
            ("len", 41),
            ("iter", 49),
            ("len", 59),
            ("get", 72),
            ("get", 81),
            ("get", 109),
            ("get", 118),
            ("eq", 142),
            ("done", 173),
        ],
    },
    Baseline {
        name: "enum_custom_starts_with_2",
        steps: 156,
        effects: &[
            ("iter", 30),
            ("len", 40),
            ("iter", 48),
            ("len", 58),
            ("get", 71),
            ("get", 80),
            ("get", 108),
            ("get", 117),
            ("done", 152),
        ],
    },
    Baseline {
        name: "enum_custom_starts_with_3",
        steps: 73,
        effects: &[
            ("iter", 18),
            ("len", 28),
            ("iter", 36),
            ("len", 46),
            ("done", 69),
        ],
    },
    Baseline {
        name: "enum_custom_starts_with_4",
        steps: 78,
        effects: &[
            ("iter", 23),
            ("len", 33),
            ("iter", 41),
            ("len", 51),
            ("done", 74),
        ],
    },
    Baseline {
        name: "enum_custom_ends_with_0",
        steps: 80,
        effects: &[
            ("iter", 26),
            ("len", 36),
            ("iter", 44),
            ("len", 54),
            ("done", 76),
        ],
    },
    Baseline {
        name: "enum_custom_ends_with_1",
        steps: 202,
        effects: &[
            ("iter", 34),
            ("len", 44),
            ("iter", 52),
            ("len", 62),
            ("get", 77),
            ("get", 86),
            ("eq", 110),
            ("get", 134),
            ("get", 143),
            ("eq", 167),
            ("done", 198),
        ],
    },
    Baseline {
        name: "enum_custom_ends_with_2",
        steps: 181,
        effects: &[
            ("iter", 33),
            ("len", 43),
            ("iter", 51),
            ("len", 61),
            ("get", 76),
            ("get", 85),
            ("eq", 109),
            ("get", 133),
            ("get", 142),
            ("done", 177),
        ],
    },
    Baseline {
        name: "enum_custom_ends_with_3",
        steps: 73,
        effects: &[
            ("iter", 18),
            ("len", 28),
            ("iter", 36),
            ("len", 46),
            ("done", 69),
        ],
    },
    Baseline {
        name: "enum_custom_ends_with_4",
        steps: 78,
        effects: &[
            ("iter", 23),
            ("len", 33),
            ("iter", 41),
            ("len", 51),
            ("done", 74),
        ],
    },
    Baseline {
        name: "enum_dynamic_contains_0",
        steps: 49,
        effects: &[("iter", 15), ("len", 25), ("done", 45)],
    },
    Baseline {
        name: "enum_dynamic_contains_1",
        steps: 128,
        effects: &[
            ("iter", 24),
            ("len", 34),
            ("get", 47),
            ("get", 73),
            ("eq", 97),
            ("done", 124),
        ],
    },
    Baseline {
        name: "enum_dynamic_contains_2",
        steps: 139,
        effects: &[
            ("iter", 23),
            ("len", 33),
            ("get", 46),
            ("get", 72),
            ("get", 100),
            ("done", 135),
        ],
    },
    Baseline {
        name: "enum_dynamic_starts_with_0",
        steps: 81,
        effects: &[
            ("iter", 27),
            ("len", 37),
            ("iter", 45),
            ("len", 55),
            ("done", 77),
        ],
    },
    Baseline {
        name: "enum_dynamic_starts_with_1",
        steps: 178,
        effects: &[
            ("iter", 32),
            ("len", 42),
            ("iter", 50),
            ("len", 60),
            ("get", 73),
            ("get", 82),
            ("get", 110),
            ("get", 119),
            ("eq", 143),
            ("done", 174),
        ],
    },
    Baseline {
        name: "enum_dynamic_starts_with_2",
        steps: 157,
        effects: &[
            ("iter", 31),
            ("len", 41),
            ("iter", 49),
            ("len", 59),
            ("get", 72),
            ("get", 81),
            ("get", 109),
            ("get", 118),
            ("done", 153),
        ],
    },
    Baseline {
        name: "enum_dynamic_starts_with_3",
        steps: 74,
        effects: &[
            ("iter", 19),
            ("len", 29),
            ("iter", 37),
            ("len", 47),
            ("done", 70),
        ],
    },
    Baseline {
        name: "enum_dynamic_starts_with_4",
        steps: 79,
        effects: &[
            ("iter", 24),
            ("len", 34),
            ("iter", 42),
            ("len", 52),
            ("done", 75),
        ],
    },
    Baseline {
        name: "enum_dynamic_ends_with_0",
        steps: 81,
        effects: &[
            ("iter", 27),
            ("len", 37),
            ("iter", 45),
            ("len", 55),
            ("done", 77),
        ],
    },
    Baseline {
        name: "enum_dynamic_ends_with_1",
        steps: 203,
        effects: &[
            ("iter", 35),
            ("len", 45),
            ("iter", 53),
            ("len", 63),
            ("get", 78),
            ("get", 87),
            ("eq", 111),
            ("get", 135),
            ("get", 144),
            ("eq", 168),
            ("done", 199),
        ],
    },
    Baseline {
        name: "enum_dynamic_ends_with_2",
        steps: 182,
        effects: &[
            ("iter", 34),
            ("len", 44),
            ("iter", 52),
            ("len", 62),
            ("get", 77),
            ("get", 86),
            ("eq", 110),
            ("get", 134),
            ("get", 143),
            ("done", 178),
        ],
    },
    Baseline {
        name: "enum_dynamic_ends_with_3",
        steps: 74,
        effects: &[
            ("iter", 19),
            ("len", 29),
            ("iter", 37),
            ("len", 47),
            ("done", 70),
        ],
    },
    Baseline {
        name: "enum_dynamic_ends_with_4",
        steps: 79,
        effects: &[
            ("iter", 24),
            ("len", 34),
            ("iter", 42),
            ("len", 52),
            ("done", 75),
        ],
    },
    Baseline {
        name: "enum_view_contains_0",
        steps: 42,
        effects: &[("done", 38)],
    },
    Baseline {
        name: "enum_view_contains_1",
        steps: 115,
        effects: &[("eq", 84), ("done", 111)],
    },
    Baseline {
        name: "enum_view_contains_2",
        steps: 123,
        effects: &[("done", 119)],
    },
    Baseline {
        name: "enum_view_starts_with_0",
        steps: 67,
        effects: &[("done", 63)],
    },
    Baseline {
        name: "enum_view_starts_with_1",
        steps: 152,
        effects: &[("eq", 117), ("done", 148)],
    },
    Baseline {
        name: "enum_view_starts_with_2",
        steps: 131,
        effects: &[("done", 127)],
    },
    Baseline {
        name: "enum_view_starts_with_3",
        steps: 60,
        effects: &[("done", 56)],
    },
    Baseline {
        name: "enum_view_starts_with_4",
        steps: 65,
        effects: &[("done", 61)],
    },
    Baseline {
        name: "enum_view_ends_with_0",
        steps: 67,
        effects: &[("done", 63)],
    },
    Baseline {
        name: "enum_view_ends_with_1",
        steps: 177,
        effects: &[("eq", 91), ("eq", 142), ("done", 173)],
    },
    Baseline {
        name: "enum_view_ends_with_2",
        steps: 156,
        effects: &[("eq", 90), ("done", 152)],
    },
    Baseline {
        name: "enum_view_ends_with_3",
        steps: 60,
        effects: &[("done", 56)],
    },
    Baseline {
        name: "enum_view_ends_with_4",
        steps: 65,
        effects: &[("done", 61)],
    },
];
