use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "leaf_array_contains_0",
        steps: 33,
        effects: &[("done", 29)],
    },
    Baseline {
        name: "leaf_array_contains_1",
        steps: 71,
        effects: &[("eq", 30), ("eq", 47), ("done", 67)],
    },
    Baseline {
        name: "leaf_array_contains_2",
        steps: 90,
        effects: &[("eq", 30), ("eq", 47), ("eq", 64), ("done", 86)],
    },
    Baseline {
        name: "leaf_array_starts_with_0",
        steps: 57,
        effects: &[("done", 53)],
    },
    Baseline {
        name: "leaf_array_starts_with_1",
        steps: 107,
        effects: &[("eq", 56), ("eq", 79), ("done", 103)],
    },
    Baseline {
        name: "leaf_array_starts_with_2",
        steps: 105,
        effects: &[("eq", 56), ("eq", 79), ("done", 101)],
    },
    Baseline {
        name: "leaf_array_starts_with_3",
        steps: 54,
        effects: &[("done", 50)],
    },
    Baseline {
        name: "leaf_array_starts_with_4",
        steps: 58,
        effects: &[("done", 54)],
    },
    Baseline {
        name: "leaf_array_ends_with_0",
        steps: 57,
        effects: &[("done", 53)],
    },
    Baseline {
        name: "leaf_array_ends_with_1",
        steps: 111,
        effects: &[("eq", 58), ("eq", 83), ("done", 107)],
    },
    Baseline {
        name: "leaf_array_ends_with_2",
        steps: 109,
        effects: &[("eq", 58), ("eq", 83), ("done", 105)],
    },
    Baseline {
        name: "leaf_array_ends_with_3",
        steps: 54,
        effects: &[("done", 50)],
    },
    Baseline {
        name: "leaf_array_ends_with_4",
        steps: 58,
        effects: &[("done", 54)],
    },
    Baseline {
        name: "leaf_custom_contains_0",
        steps: 46,
        effects: &[("iter", 12), ("len", 22), ("done", 42)],
    },
    Baseline {
        name: "leaf_custom_contains_1",
        steps: 98,
        effects: &[
            ("iter", 18),
            ("len", 28),
            ("get", 41),
            ("eq", 50),
            ("get", 65),
            ("eq", 74),
            ("done", 94),
        ],
    },
    Baseline {
        name: "leaf_custom_contains_2",
        steps: 124,
        effects: &[
            ("iter", 18),
            ("len", 28),
            ("get", 41),
            ("eq", 50),
            ("get", 65),
            ("eq", 74),
            ("get", 89),
            ("eq", 98),
            ("done", 120),
        ],
    },
    Baseline {
        name: "leaf_custom_starts_with_0",
        steps: 77,
        effects: &[
            ("iter", 23),
            ("len", 33),
            ("iter", 41),
            ("len", 51),
            ("done", 73),
        ],
    },
    Baseline {
        name: "leaf_custom_starts_with_1",
        steps: 147,
        effects: &[
            ("iter", 27),
            ("len", 37),
            ("iter", 45),
            ("len", 55),
            ("get", 68),
            ("get", 77),
            ("eq", 86),
            ("get", 101),
            ("get", 110),
            ("eq", 119),
            ("done", 143),
        ],
    },
    Baseline {
        name: "leaf_custom_starts_with_2",
        steps: 145,
        effects: &[
            ("iter", 27),
            ("len", 37),
            ("iter", 45),
            ("len", 55),
            ("get", 68),
            ("get", 77),
            ("eq", 86),
            ("get", 101),
            ("get", 110),
            ("eq", 119),
            ("done", 141),
        ],
    },
    Baseline {
        name: "leaf_custom_starts_with_3",
        steps: 74,
        effects: &[
            ("iter", 19),
            ("len", 29),
            ("iter", 37),
            ("len", 47),
            ("done", 70),
        ],
    },
    Baseline {
        name: "leaf_custom_starts_with_4",
        steps: 78,
        effects: &[
            ("iter", 23),
            ("len", 33),
            ("iter", 41),
            ("len", 51),
            ("done", 74),
        ],
    },
    Baseline {
        name: "leaf_custom_ends_with_0",
        steps: 77,
        effects: &[
            ("iter", 23),
            ("len", 33),
            ("iter", 41),
            ("len", 51),
            ("done", 73),
        ],
    },
    Baseline {
        name: "leaf_custom_ends_with_1",
        steps: 151,
        effects: &[
            ("iter", 27),
            ("len", 37),
            ("iter", 45),
            ("len", 55),
            ("get", 70),
            ("get", 79),
            ("eq", 88),
            ("get", 105),
            ("get", 114),
            ("eq", 123),
            ("done", 147),
        ],
    },
    Baseline {
        name: "leaf_custom_ends_with_2",
        steps: 149,
        effects: &[
            ("iter", 27),
            ("len", 37),
            ("iter", 45),
            ("len", 55),
            ("get", 70),
            ("get", 79),
            ("eq", 88),
            ("get", 105),
            ("get", 114),
            ("eq", 123),
            ("done", 145),
        ],
    },
    Baseline {
        name: "leaf_custom_ends_with_3",
        steps: 74,
        effects: &[
            ("iter", 19),
            ("len", 29),
            ("iter", 37),
            ("len", 47),
            ("done", 70),
        ],
    },
    Baseline {
        name: "leaf_custom_ends_with_4",
        steps: 78,
        effects: &[
            ("iter", 23),
            ("len", 33),
            ("iter", 41),
            ("len", 51),
            ("done", 74),
        ],
    },
    Baseline {
        name: "leaf_dynamic_contains_0",
        steps: 47,
        effects: &[("iter", 13), ("len", 23), ("done", 43)],
    },
    Baseline {
        name: "leaf_dynamic_contains_1",
        steps: 99,
        effects: &[
            ("iter", 19),
            ("len", 29),
            ("get", 42),
            ("eq", 51),
            ("get", 66),
            ("eq", 75),
            ("done", 95),
        ],
    },
    Baseline {
        name: "leaf_dynamic_contains_2",
        steps: 125,
        effects: &[
            ("iter", 19),
            ("len", 29),
            ("get", 42),
            ("eq", 51),
            ("get", 66),
            ("eq", 75),
            ("get", 90),
            ("eq", 99),
            ("done", 121),
        ],
    },
    Baseline {
        name: "leaf_dynamic_starts_with_0",
        steps: 78,
        effects: &[
            ("iter", 24),
            ("len", 34),
            ("iter", 42),
            ("len", 52),
            ("done", 74),
        ],
    },
    Baseline {
        name: "leaf_dynamic_starts_with_1",
        steps: 148,
        effects: &[
            ("iter", 28),
            ("len", 38),
            ("iter", 46),
            ("len", 56),
            ("get", 69),
            ("get", 78),
            ("eq", 87),
            ("get", 102),
            ("get", 111),
            ("eq", 120),
            ("done", 144),
        ],
    },
    Baseline {
        name: "leaf_dynamic_starts_with_2",
        steps: 146,
        effects: &[
            ("iter", 28),
            ("len", 38),
            ("iter", 46),
            ("len", 56),
            ("get", 69),
            ("get", 78),
            ("eq", 87),
            ("get", 102),
            ("get", 111),
            ("eq", 120),
            ("done", 142),
        ],
    },
    Baseline {
        name: "leaf_dynamic_starts_with_3",
        steps: 75,
        effects: &[
            ("iter", 20),
            ("len", 30),
            ("iter", 38),
            ("len", 48),
            ("done", 71),
        ],
    },
    Baseline {
        name: "leaf_dynamic_starts_with_4",
        steps: 79,
        effects: &[
            ("iter", 24),
            ("len", 34),
            ("iter", 42),
            ("len", 52),
            ("done", 75),
        ],
    },
    Baseline {
        name: "leaf_dynamic_ends_with_0",
        steps: 78,
        effects: &[
            ("iter", 24),
            ("len", 34),
            ("iter", 42),
            ("len", 52),
            ("done", 74),
        ],
    },
    Baseline {
        name: "leaf_dynamic_ends_with_1",
        steps: 152,
        effects: &[
            ("iter", 28),
            ("len", 38),
            ("iter", 46),
            ("len", 56),
            ("get", 71),
            ("get", 80),
            ("eq", 89),
            ("get", 106),
            ("get", 115),
            ("eq", 124),
            ("done", 148),
        ],
    },
    Baseline {
        name: "leaf_dynamic_ends_with_2",
        steps: 150,
        effects: &[
            ("iter", 28),
            ("len", 38),
            ("iter", 46),
            ("len", 56),
            ("get", 71),
            ("get", 80),
            ("eq", 89),
            ("get", 106),
            ("get", 115),
            ("eq", 124),
            ("done", 146),
        ],
    },
    Baseline {
        name: "leaf_dynamic_ends_with_3",
        steps: 75,
        effects: &[
            ("iter", 20),
            ("len", 30),
            ("iter", 38),
            ("len", 48),
            ("done", 71),
        ],
    },
    Baseline {
        name: "leaf_dynamic_ends_with_4",
        steps: 79,
        effects: &[
            ("iter", 24),
            ("len", 34),
            ("iter", 42),
            ("len", 52),
            ("done", 75),
        ],
    },
    Baseline {
        name: "leaf_view_contains_0",
        steps: 40,
        effects: &[("done", 36)],
    },
    Baseline {
        name: "leaf_view_contains_1",
        steps: 86,
        effects: &[("eq", 41), ("eq", 62), ("done", 82)],
    },
    Baseline {
        name: "leaf_view_contains_2",
        steps: 109,
        effects: &[("eq", 41), ("eq", 62), ("eq", 83), ("done", 105)],
    },
    Baseline {
        name: "leaf_view_starts_with_0",
        steps: 64,
        effects: &[("done", 60)],
    },
    Baseline {
        name: "leaf_view_starts_with_1",
        steps: 122,
        effects: &[("eq", 67), ("eq", 94), ("done", 118)],
    },
    Baseline {
        name: "leaf_view_starts_with_2",
        steps: 120,
        effects: &[("eq", 67), ("eq", 94), ("done", 116)],
    },
    Baseline {
        name: "leaf_view_starts_with_3",
        steps: 61,
        effects: &[("done", 57)],
    },
    Baseline {
        name: "leaf_view_starts_with_4",
        steps: 65,
        effects: &[("done", 61)],
    },
    Baseline {
        name: "leaf_view_ends_with_0",
        steps: 64,
        effects: &[("done", 60)],
    },
    Baseline {
        name: "leaf_view_ends_with_1",
        steps: 126,
        effects: &[("eq", 69), ("eq", 98), ("done", 122)],
    },
    Baseline {
        name: "leaf_view_ends_with_2",
        steps: 124,
        effects: &[("eq", 69), ("eq", 98), ("done", 120)],
    },
    Baseline {
        name: "leaf_view_ends_with_3",
        steps: 61,
        effects: &[("done", 57)],
    },
    Baseline {
        name: "leaf_view_ends_with_4",
        steps: 65,
        effects: &[("done", 61)],
    },
];
