use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "nested_array_contains_0",
        steps: 39,
        effects: &[("done", 35)],
    },
    Baseline {
        name: "nested_array_contains_1",
        steps: 170,
        effects: &[("eq", 102), ("eq", 134), ("done", 166)],
    },
    Baseline {
        name: "nested_array_contains_2",
        steps: 186,
        effects: &[("eq", 101), ("eq", 148), ("done", 182)],
    },
    Baseline {
        name: "nested_array_starts_with_0",
        steps: 70,
        effects: &[("done", 66)],
    },
    Baseline {
        name: "nested_array_starts_with_1",
        steps: 223,
        effects: &[("eq", 151), ("eq", 183), ("done", 219)],
    },
    Baseline {
        name: "nested_array_starts_with_2",
        steps: 188,
        effects: &[("eq", 150), ("done", 184)],
    },
    Baseline {
        name: "nested_array_starts_with_3",
        steps: 55,
        effects: &[("done", 51)],
    },
    Baseline {
        name: "nested_array_starts_with_4",
        steps: 66,
        effects: &[("done", 62)],
    },
    Baseline {
        name: "nested_array_ends_with_0",
        steps: 70,
        effects: &[("done", 66)],
    },
    Baseline {
        name: "nested_array_ends_with_1",
        steps: 260,
        effects: &[
            ("eq", 101),
            ("eq", 133),
            ("eq", 188),
            ("eq", 220),
            ("done", 256),
        ],
    },
    Baseline {
        name: "nested_array_ends_with_2",
        steps: 225,
        effects: &[("eq", 100), ("eq", 132), ("eq", 187), ("done", 221)],
    },
    Baseline {
        name: "nested_array_ends_with_3",
        steps: 55,
        effects: &[("done", 51)],
    },
    Baseline {
        name: "nested_array_ends_with_4",
        steps: 66,
        effects: &[("done", 62)],
    },
    Baseline {
        name: "nested_custom_contains_0",
        steps: 52,
        effects: &[("iter", 18), ("len", 28), ("done", 48)],
    },
    Baseline {
        name: "nested_custom_contains_1",
        steps: 197,
        effects: &[
            ("iter", 37),
            ("len", 47),
            ("get", 60),
            ("get", 102),
            ("eq", 129),
            ("eq", 161),
            ("done", 193),
        ],
    },
    Baseline {
        name: "nested_custom_contains_2",
        steps: 220,
        effects: &[
            ("iter", 36),
            ("len", 46),
            ("get", 59),
            ("get", 101),
            ("eq", 128),
            ("get", 155),
            ("eq", 182),
            ("done", 216),
        ],
    },
    Baseline {
        name: "nested_custom_starts_with_0",
        steps: 90,
        effects: &[
            ("iter", 36),
            ("len", 46),
            ("iter", 54),
            ("len", 64),
            ("done", 86),
        ],
    },
    Baseline {
        name: "nested_custom_starts_with_1",
        steps: 263,
        effects: &[
            ("iter", 47),
            ("len", 57),
            ("iter", 65),
            ("len", 75),
            ("get", 88),
            ("get", 97),
            ("get", 155),
            ("get", 164),
            ("eq", 191),
            ("eq", 223),
            ("done", 259),
        ],
    },
    Baseline {
        name: "nested_custom_starts_with_2",
        steps: 228,
        effects: &[
            ("iter", 46),
            ("len", 56),
            ("iter", 64),
            ("len", 74),
            ("get", 87),
            ("get", 96),
            ("get", 154),
            ("get", 163),
            ("eq", 190),
            ("done", 224),
        ],
    },
    Baseline {
        name: "nested_custom_starts_with_3",
        steps: 75,
        effects: &[
            ("iter", 20),
            ("len", 30),
            ("iter", 38),
            ("len", 48),
            ("done", 71),
        ],
    },
    Baseline {
        name: "nested_custom_starts_with_4",
        steps: 86,
        effects: &[
            ("iter", 31),
            ("len", 41),
            ("iter", 49),
            ("len", 59),
            ("done", 82),
        ],
    },
    Baseline {
        name: "nested_custom_ends_with_0",
        steps: 90,
        effects: &[
            ("iter", 36),
            ("len", 46),
            ("iter", 54),
            ("len", 64),
            ("done", 86),
        ],
    },
    Baseline {
        name: "nested_custom_ends_with_1",
        steps: 300,
        effects: &[
            ("iter", 52),
            ("len", 62),
            ("iter", 70),
            ("len", 80),
            ("get", 95),
            ("get", 104),
            ("eq", 131),
            ("eq", 163),
            ("get", 192),
            ("get", 201),
            ("eq", 228),
            ("eq", 260),
            ("done", 296),
        ],
    },
    Baseline {
        name: "nested_custom_ends_with_2",
        steps: 265,
        effects: &[
            ("iter", 51),
            ("len", 61),
            ("iter", 69),
            ("len", 79),
            ("get", 94),
            ("get", 103),
            ("eq", 130),
            ("eq", 162),
            ("get", 191),
            ("get", 200),
            ("eq", 227),
            ("done", 261),
        ],
    },
    Baseline {
        name: "nested_custom_ends_with_3",
        steps: 75,
        effects: &[
            ("iter", 20),
            ("len", 30),
            ("iter", 38),
            ("len", 48),
            ("done", 71),
        ],
    },
    Baseline {
        name: "nested_custom_ends_with_4",
        steps: 86,
        effects: &[
            ("iter", 31),
            ("len", 41),
            ("iter", 49),
            ("len", 59),
            ("done", 82),
        ],
    },
    Baseline {
        name: "nested_dynamic_contains_0",
        steps: 53,
        effects: &[("iter", 19), ("len", 29), ("done", 49)],
    },
    Baseline {
        name: "nested_dynamic_contains_1",
        steps: 198,
        effects: &[
            ("iter", 38),
            ("len", 48),
            ("get", 61),
            ("get", 103),
            ("eq", 130),
            ("eq", 162),
            ("done", 194),
        ],
    },
    Baseline {
        name: "nested_dynamic_contains_2",
        steps: 221,
        effects: &[
            ("iter", 37),
            ("len", 47),
            ("get", 60),
            ("get", 102),
            ("eq", 129),
            ("get", 156),
            ("eq", 183),
            ("done", 217),
        ],
    },
    Baseline {
        name: "nested_dynamic_starts_with_0",
        steps: 91,
        effects: &[
            ("iter", 37),
            ("len", 47),
            ("iter", 55),
            ("len", 65),
            ("done", 87),
        ],
    },
    Baseline {
        name: "nested_dynamic_starts_with_1",
        steps: 264,
        effects: &[
            ("iter", 48),
            ("len", 58),
            ("iter", 66),
            ("len", 76),
            ("get", 89),
            ("get", 98),
            ("get", 156),
            ("get", 165),
            ("eq", 192),
            ("eq", 224),
            ("done", 260),
        ],
    },
    Baseline {
        name: "nested_dynamic_starts_with_2",
        steps: 229,
        effects: &[
            ("iter", 47),
            ("len", 57),
            ("iter", 65),
            ("len", 75),
            ("get", 88),
            ("get", 97),
            ("get", 155),
            ("get", 164),
            ("eq", 191),
            ("done", 225),
        ],
    },
    Baseline {
        name: "nested_dynamic_starts_with_3",
        steps: 76,
        effects: &[
            ("iter", 21),
            ("len", 31),
            ("iter", 39),
            ("len", 49),
            ("done", 72),
        ],
    },
    Baseline {
        name: "nested_dynamic_starts_with_4",
        steps: 87,
        effects: &[
            ("iter", 32),
            ("len", 42),
            ("iter", 50),
            ("len", 60),
            ("done", 83),
        ],
    },
    Baseline {
        name: "nested_dynamic_ends_with_0",
        steps: 91,
        effects: &[
            ("iter", 37),
            ("len", 47),
            ("iter", 55),
            ("len", 65),
            ("done", 87),
        ],
    },
    Baseline {
        name: "nested_dynamic_ends_with_1",
        steps: 301,
        effects: &[
            ("iter", 53),
            ("len", 63),
            ("iter", 71),
            ("len", 81),
            ("get", 96),
            ("get", 105),
            ("eq", 132),
            ("eq", 164),
            ("get", 193),
            ("get", 202),
            ("eq", 229),
            ("eq", 261),
            ("done", 297),
        ],
    },
    Baseline {
        name: "nested_dynamic_ends_with_2",
        steps: 266,
        effects: &[
            ("iter", 52),
            ("len", 62),
            ("iter", 70),
            ("len", 80),
            ("get", 95),
            ("get", 104),
            ("eq", 131),
            ("eq", 163),
            ("get", 192),
            ("get", 201),
            ("eq", 228),
            ("done", 262),
        ],
    },
    Baseline {
        name: "nested_dynamic_ends_with_3",
        steps: 76,
        effects: &[
            ("iter", 21),
            ("len", 31),
            ("iter", 39),
            ("len", 49),
            ("done", 72),
        ],
    },
    Baseline {
        name: "nested_dynamic_ends_with_4",
        steps: 87,
        effects: &[
            ("iter", 32),
            ("len", 42),
            ("iter", 50),
            ("len", 60),
            ("done", 83),
        ],
    },
    Baseline {
        name: "nested_view_contains_0",
        steps: 46,
        effects: &[("done", 42)],
    },
    Baseline {
        name: "nested_view_contains_1",
        steps: 185,
        effects: &[("eq", 117), ("eq", 149), ("done", 181)],
    },
    Baseline {
        name: "nested_view_contains_2",
        steps: 205,
        effects: &[("eq", 116), ("eq", 167), ("done", 201)],
    },
    Baseline {
        name: "nested_view_starts_with_0",
        steps: 77,
        effects: &[("done", 73)],
    },
    Baseline {
        name: "nested_view_starts_with_1",
        steps: 238,
        effects: &[("eq", 166), ("eq", 198), ("done", 234)],
    },
    Baseline {
        name: "nested_view_starts_with_2",
        steps: 203,
        effects: &[("eq", 165), ("done", 199)],
    },
    Baseline {
        name: "nested_view_starts_with_3",
        steps: 62,
        effects: &[("done", 58)],
    },
    Baseline {
        name: "nested_view_starts_with_4",
        steps: 73,
        effects: &[("done", 69)],
    },
    Baseline {
        name: "nested_view_ends_with_0",
        steps: 77,
        effects: &[("done", 73)],
    },
    Baseline {
        name: "nested_view_ends_with_1",
        steps: 275,
        effects: &[
            ("eq", 112),
            ("eq", 144),
            ("eq", 203),
            ("eq", 235),
            ("done", 271),
        ],
    },
    Baseline {
        name: "nested_view_ends_with_2",
        steps: 240,
        effects: &[("eq", 111), ("eq", 143), ("eq", 202), ("done", 236)],
    },
    Baseline {
        name: "nested_view_ends_with_3",
        steps: 62,
        effects: &[("done", 58)],
    },
    Baseline {
        name: "nested_view_ends_with_4",
        steps: 73,
        effects: &[("done", 69)],
    },
];
