use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "option_array_contains_0",
        steps: 34,
        effects: &[("done", 30)],
    },
    Baseline {
        name: "option_array_contains_1",
        steps: 93,
        effects: &[("eq", 62), ("done", 89)],
    },
    Baseline {
        name: "option_array_contains_2",
        steps: 128,
        effects: &[("eq", 62), ("eq", 95), ("done", 124)],
    },
    Baseline {
        name: "option_array_starts_with_0",
        steps: 58,
        effects: &[("done", 54)],
    },
    Baseline {
        name: "option_array_starts_with_1",
        steps: 130,
        effects: &[("eq", 95), ("done", 126)],
    },
    Baseline {
        name: "option_array_starts_with_2",
        steps: 128,
        effects: &[("eq", 95), ("done", 124)],
    },
    Baseline {
        name: "option_array_starts_with_3",
        steps: 53,
        effects: &[("done", 49)],
    },
    Baseline {
        name: "option_array_starts_with_4",
        steps: 57,
        effects: &[("done", 53)],
    },
    Baseline {
        name: "option_array_ends_with_0",
        steps: 58,
        effects: &[("done", 54)],
    },
    Baseline {
        name: "option_array_ends_with_1",
        steps: 146,
        effects: &[("eq", 70), ("eq", 111), ("done", 142)],
    },
    Baseline {
        name: "option_array_ends_with_2",
        steps: 144,
        effects: &[("eq", 70), ("eq", 111), ("done", 140)],
    },
    Baseline {
        name: "option_array_ends_with_3",
        steps: 53,
        effects: &[("done", 49)],
    },
    Baseline {
        name: "option_array_ends_with_4",
        steps: 57,
        effects: &[("done", 53)],
    },
    Baseline {
        name: "option_custom_contains_0",
        steps: 47,
        effects: &[("iter", 13), ("len", 23), ("done", 43)],
    },
    Baseline {
        name: "option_custom_contains_1",
        steps: 120,
        effects: &[
            ("iter", 20),
            ("len", 30),
            ("get", 43),
            ("get", 71),
            ("eq", 89),
            ("done", 116),
        ],
    },
    Baseline {
        name: "option_custom_contains_2",
        steps: 162,
        effects: &[
            ("iter", 20),
            ("len", 30),
            ("get", 43),
            ("get", 71),
            ("eq", 89),
            ("get", 111),
            ("eq", 129),
            ("done", 158),
        ],
    },
    Baseline {
        name: "option_custom_starts_with_0",
        steps: 78,
        effects: &[
            ("iter", 24),
            ("len", 34),
            ("iter", 42),
            ("len", 52),
            ("done", 74),
        ],
    },
    Baseline {
        name: "option_custom_starts_with_1",
        steps: 170,
        effects: &[
            ("iter", 28),
            ("len", 38),
            ("iter", 46),
            ("len", 56),
            ("get", 69),
            ("get", 78),
            ("get", 108),
            ("get", 117),
            ("eq", 135),
            ("done", 166),
        ],
    },
    Baseline {
        name: "option_custom_starts_with_2",
        steps: 168,
        effects: &[
            ("iter", 28),
            ("len", 38),
            ("iter", 46),
            ("len", 56),
            ("get", 69),
            ("get", 78),
            ("get", 108),
            ("get", 117),
            ("eq", 135),
            ("done", 164),
        ],
    },
    Baseline {
        name: "option_custom_starts_with_3",
        steps: 73,
        effects: &[
            ("iter", 18),
            ("len", 28),
            ("iter", 36),
            ("len", 46),
            ("done", 69),
        ],
    },
    Baseline {
        name: "option_custom_starts_with_4",
        steps: 77,
        effects: &[
            ("iter", 22),
            ("len", 32),
            ("iter", 40),
            ("len", 50),
            ("done", 73),
        ],
    },
    Baseline {
        name: "option_custom_ends_with_0",
        steps: 78,
        effects: &[
            ("iter", 24),
            ("len", 34),
            ("iter", 42),
            ("len", 52),
            ("done", 74),
        ],
    },
    Baseline {
        name: "option_custom_ends_with_1",
        steps: 186,
        effects: &[
            ("iter", 30),
            ("len", 40),
            ("iter", 48),
            ("len", 58),
            ("get", 73),
            ("get", 82),
            ("eq", 100),
            ("get", 124),
            ("get", 133),
            ("eq", 151),
            ("done", 182),
        ],
    },
    Baseline {
        name: "option_custom_ends_with_2",
        steps: 184,
        effects: &[
            ("iter", 30),
            ("len", 40),
            ("iter", 48),
            ("len", 58),
            ("get", 73),
            ("get", 82),
            ("eq", 100),
            ("get", 124),
            ("get", 133),
            ("eq", 151),
            ("done", 180),
        ],
    },
    Baseline {
        name: "option_custom_ends_with_3",
        steps: 73,
        effects: &[
            ("iter", 18),
            ("len", 28),
            ("iter", 36),
            ("len", 46),
            ("done", 69),
        ],
    },
    Baseline {
        name: "option_custom_ends_with_4",
        steps: 77,
        effects: &[
            ("iter", 22),
            ("len", 32),
            ("iter", 40),
            ("len", 50),
            ("done", 73),
        ],
    },
    Baseline {
        name: "option_dynamic_contains_0",
        steps: 48,
        effects: &[("iter", 14), ("len", 24), ("done", 44)],
    },
    Baseline {
        name: "option_dynamic_contains_1",
        steps: 121,
        effects: &[
            ("iter", 21),
            ("len", 31),
            ("get", 44),
            ("get", 72),
            ("eq", 90),
            ("done", 117),
        ],
    },
    Baseline {
        name: "option_dynamic_contains_2",
        steps: 163,
        effects: &[
            ("iter", 21),
            ("len", 31),
            ("get", 44),
            ("get", 72),
            ("eq", 90),
            ("get", 112),
            ("eq", 130),
            ("done", 159),
        ],
    },
    Baseline {
        name: "option_dynamic_starts_with_0",
        steps: 79,
        effects: &[
            ("iter", 25),
            ("len", 35),
            ("iter", 43),
            ("len", 53),
            ("done", 75),
        ],
    },
    Baseline {
        name: "option_dynamic_starts_with_1",
        steps: 171,
        effects: &[
            ("iter", 29),
            ("len", 39),
            ("iter", 47),
            ("len", 57),
            ("get", 70),
            ("get", 79),
            ("get", 109),
            ("get", 118),
            ("eq", 136),
            ("done", 167),
        ],
    },
    Baseline {
        name: "option_dynamic_starts_with_2",
        steps: 169,
        effects: &[
            ("iter", 29),
            ("len", 39),
            ("iter", 47),
            ("len", 57),
            ("get", 70),
            ("get", 79),
            ("get", 109),
            ("get", 118),
            ("eq", 136),
            ("done", 165),
        ],
    },
    Baseline {
        name: "option_dynamic_starts_with_3",
        steps: 74,
        effects: &[
            ("iter", 19),
            ("len", 29),
            ("iter", 37),
            ("len", 47),
            ("done", 70),
        ],
    },
    Baseline {
        name: "option_dynamic_starts_with_4",
        steps: 78,
        effects: &[
            ("iter", 23),
            ("len", 33),
            ("iter", 41),
            ("len", 51),
            ("done", 74),
        ],
    },
    Baseline {
        name: "option_dynamic_ends_with_0",
        steps: 79,
        effects: &[
            ("iter", 25),
            ("len", 35),
            ("iter", 43),
            ("len", 53),
            ("done", 75),
        ],
    },
    Baseline {
        name: "option_dynamic_ends_with_1",
        steps: 187,
        effects: &[
            ("iter", 31),
            ("len", 41),
            ("iter", 49),
            ("len", 59),
            ("get", 74),
            ("get", 83),
            ("eq", 101),
            ("get", 125),
            ("get", 134),
            ("eq", 152),
            ("done", 183),
        ],
    },
    Baseline {
        name: "option_dynamic_ends_with_2",
        steps: 185,
        effects: &[
            ("iter", 31),
            ("len", 41),
            ("iter", 49),
            ("len", 59),
            ("get", 74),
            ("get", 83),
            ("eq", 101),
            ("get", 125),
            ("get", 134),
            ("eq", 152),
            ("done", 181),
        ],
    },
    Baseline {
        name: "option_dynamic_ends_with_3",
        steps: 74,
        effects: &[
            ("iter", 19),
            ("len", 29),
            ("iter", 37),
            ("len", 47),
            ("done", 70),
        ],
    },
    Baseline {
        name: "option_dynamic_ends_with_4",
        steps: 78,
        effects: &[
            ("iter", 23),
            ("len", 33),
            ("iter", 41),
            ("len", 51),
            ("done", 74),
        ],
    },
    Baseline {
        name: "option_view_contains_0",
        steps: 41,
        effects: &[("done", 37)],
    },
    Baseline {
        name: "option_view_contains_1",
        steps: 108,
        effects: &[("eq", 77), ("done", 104)],
    },
    Baseline {
        name: "option_view_contains_2",
        steps: 147,
        effects: &[("eq", 77), ("eq", 114), ("done", 143)],
    },
    Baseline {
        name: "option_view_starts_with_0",
        steps: 65,
        effects: &[("done", 61)],
    },
    Baseline {
        name: "option_view_starts_with_1",
        steps: 145,
        effects: &[("eq", 110), ("done", 141)],
    },
    Baseline {
        name: "option_view_starts_with_2",
        steps: 143,
        effects: &[("eq", 110), ("done", 139)],
    },
    Baseline {
        name: "option_view_starts_with_3",
        steps: 60,
        effects: &[("done", 56)],
    },
    Baseline {
        name: "option_view_starts_with_4",
        steps: 64,
        effects: &[("done", 60)],
    },
    Baseline {
        name: "option_view_ends_with_0",
        steps: 65,
        effects: &[("done", 61)],
    },
    Baseline {
        name: "option_view_ends_with_1",
        steps: 161,
        effects: &[("eq", 81), ("eq", 126), ("done", 157)],
    },
    Baseline {
        name: "option_view_ends_with_2",
        steps: 159,
        effects: &[("eq", 81), ("eq", 126), ("done", 155)],
    },
    Baseline {
        name: "option_view_ends_with_3",
        steps: 60,
        effects: &[("done", 56)],
    },
    Baseline {
        name: "option_view_ends_with_4",
        steps: 64,
        effects: &[("done", 60)],
    },
];
