use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "scalar_array_contains_0",
        steps: 32,
        effects: &[("done", 28)],
    },
    Baseline {
        name: "scalar_array_contains_1",
        steps: 51,
        effects: &[("done", 47)],
    },
    Baseline {
        name: "scalar_array_contains_2",
        steps: 62,
        effects: &[("done", 58)],
    },
    Baseline {
        name: "scalar_array_starts_with_0",
        steps: 54,
        effects: &[("done", 50)],
    },
    Baseline {
        name: "scalar_array_starts_with_1",
        steps: 86,
        effects: &[("done", 82)],
    },
    Baseline {
        name: "scalar_array_starts_with_2",
        steps: 84,
        effects: &[("done", 80)],
    },
    Baseline {
        name: "scalar_array_starts_with_3",
        steps: 53,
        effects: &[("done", 49)],
    },
    Baseline {
        name: "scalar_array_starts_with_4",
        steps: 55,
        effects: &[("done", 51)],
    },
    Baseline {
        name: "scalar_array_ends_with_0",
        steps: 54,
        effects: &[("done", 50)],
    },
    Baseline {
        name: "scalar_array_ends_with_1",
        steps: 90,
        effects: &[("done", 86)],
    },
    Baseline {
        name: "scalar_array_ends_with_2",
        steps: 88,
        effects: &[("done", 84)],
    },
    Baseline {
        name: "scalar_array_ends_with_3",
        steps: 53,
        effects: &[("done", 49)],
    },
    Baseline {
        name: "scalar_array_ends_with_4",
        steps: 55,
        effects: &[("done", 51)],
    },
    Baseline {
        name: "scalar_custom_contains_0",
        steps: 45,
        effects: &[("iter", 11), ("len", 21), ("done", 41)],
    },
    Baseline {
        name: "scalar_custom_contains_1",
        steps: 78,
        effects: &[
            ("iter", 14),
            ("len", 24),
            ("get", 37),
            ("get", 53),
            ("done", 74),
        ],
    },
    Baseline {
        name: "scalar_custom_contains_2",
        steps: 96,
        effects: &[
            ("iter", 14),
            ("len", 24),
            ("get", 37),
            ("get", 53),
            ("get", 69),
            ("done", 92),
        ],
    },
    Baseline {
        name: "scalar_custom_starts_with_0",
        steps: 74,
        effects: &[
            ("iter", 20),
            ("len", 30),
            ("iter", 38),
            ("len", 48),
            ("done", 70),
        ],
    },
    Baseline {
        name: "scalar_custom_starts_with_1",
        steps: 126,
        effects: &[
            ("iter", 22),
            ("len", 32),
            ("iter", 40),
            ("len", 50),
            ("get", 63),
            ("get", 72),
            ("get", 88),
            ("get", 97),
            ("done", 122),
        ],
    },
    Baseline {
        name: "scalar_custom_starts_with_2",
        steps: 124,
        effects: &[
            ("iter", 22),
            ("len", 32),
            ("iter", 40),
            ("len", 50),
            ("get", 63),
            ("get", 72),
            ("get", 88),
            ("get", 97),
            ("done", 120),
        ],
    },
    Baseline {
        name: "scalar_custom_starts_with_3",
        steps: 73,
        effects: &[
            ("iter", 18),
            ("len", 28),
            ("iter", 36),
            ("len", 46),
            ("done", 69),
        ],
    },
    Baseline {
        name: "scalar_custom_starts_with_4",
        steps: 75,
        effects: &[
            ("iter", 20),
            ("len", 30),
            ("iter", 38),
            ("len", 48),
            ("done", 71),
        ],
    },
    Baseline {
        name: "scalar_custom_ends_with_0",
        steps: 74,
        effects: &[
            ("iter", 20),
            ("len", 30),
            ("iter", 38),
            ("len", 48),
            ("done", 70),
        ],
    },
    Baseline {
        name: "scalar_custom_ends_with_1",
        steps: 130,
        effects: &[
            ("iter", 22),
            ("len", 32),
            ("iter", 40),
            ("len", 50),
            ("get", 65),
            ("get", 74),
            ("get", 92),
            ("get", 101),
            ("done", 126),
        ],
    },
    Baseline {
        name: "scalar_custom_ends_with_2",
        steps: 128,
        effects: &[
            ("iter", 22),
            ("len", 32),
            ("iter", 40),
            ("len", 50),
            ("get", 65),
            ("get", 74),
            ("get", 92),
            ("get", 101),
            ("done", 124),
        ],
    },
    Baseline {
        name: "scalar_custom_ends_with_3",
        steps: 73,
        effects: &[
            ("iter", 18),
            ("len", 28),
            ("iter", 36),
            ("len", 46),
            ("done", 69),
        ],
    },
    Baseline {
        name: "scalar_custom_ends_with_4",
        steps: 75,
        effects: &[
            ("iter", 20),
            ("len", 30),
            ("iter", 38),
            ("len", 48),
            ("done", 71),
        ],
    },
    Baseline {
        name: "scalar_dynamic_contains_0",
        steps: 46,
        effects: &[("iter", 12), ("len", 22), ("done", 42)],
    },
    Baseline {
        name: "scalar_dynamic_contains_1",
        steps: 79,
        effects: &[
            ("iter", 15),
            ("len", 25),
            ("get", 38),
            ("get", 54),
            ("done", 75),
        ],
    },
    Baseline {
        name: "scalar_dynamic_contains_2",
        steps: 97,
        effects: &[
            ("iter", 15),
            ("len", 25),
            ("get", 38),
            ("get", 54),
            ("get", 70),
            ("done", 93),
        ],
    },
    Baseline {
        name: "scalar_dynamic_starts_with_0",
        steps: 75,
        effects: &[
            ("iter", 21),
            ("len", 31),
            ("iter", 39),
            ("len", 49),
            ("done", 71),
        ],
    },
    Baseline {
        name: "scalar_dynamic_starts_with_1",
        steps: 127,
        effects: &[
            ("iter", 23),
            ("len", 33),
            ("iter", 41),
            ("len", 51),
            ("get", 64),
            ("get", 73),
            ("get", 89),
            ("get", 98),
            ("done", 123),
        ],
    },
    Baseline {
        name: "scalar_dynamic_starts_with_2",
        steps: 125,
        effects: &[
            ("iter", 23),
            ("len", 33),
            ("iter", 41),
            ("len", 51),
            ("get", 64),
            ("get", 73),
            ("get", 89),
            ("get", 98),
            ("done", 121),
        ],
    },
    Baseline {
        name: "scalar_dynamic_starts_with_3",
        steps: 74,
        effects: &[
            ("iter", 19),
            ("len", 29),
            ("iter", 37),
            ("len", 47),
            ("done", 70),
        ],
    },
    Baseline {
        name: "scalar_dynamic_starts_with_4",
        steps: 76,
        effects: &[
            ("iter", 21),
            ("len", 31),
            ("iter", 39),
            ("len", 49),
            ("done", 72),
        ],
    },
    Baseline {
        name: "scalar_dynamic_ends_with_0",
        steps: 75,
        effects: &[
            ("iter", 21),
            ("len", 31),
            ("iter", 39),
            ("len", 49),
            ("done", 71),
        ],
    },
    Baseline {
        name: "scalar_dynamic_ends_with_1",
        steps: 131,
        effects: &[
            ("iter", 23),
            ("len", 33),
            ("iter", 41),
            ("len", 51),
            ("get", 66),
            ("get", 75),
            ("get", 93),
            ("get", 102),
            ("done", 127),
        ],
    },
    Baseline {
        name: "scalar_dynamic_ends_with_2",
        steps: 129,
        effects: &[
            ("iter", 23),
            ("len", 33),
            ("iter", 41),
            ("len", 51),
            ("get", 66),
            ("get", 75),
            ("get", 93),
            ("get", 102),
            ("done", 125),
        ],
    },
    Baseline {
        name: "scalar_dynamic_ends_with_3",
        steps: 74,
        effects: &[
            ("iter", 19),
            ("len", 29),
            ("iter", 37),
            ("len", 47),
            ("done", 70),
        ],
    },
    Baseline {
        name: "scalar_dynamic_ends_with_4",
        steps: 76,
        effects: &[
            ("iter", 21),
            ("len", 31),
            ("iter", 39),
            ("len", 49),
            ("done", 72),
        ],
    },
    Baseline {
        name: "scalar_view_contains_0",
        steps: 39,
        effects: &[("done", 35)],
    },
    Baseline {
        name: "scalar_view_contains_1",
        steps: 66,
        effects: &[("done", 62)],
    },
    Baseline {
        name: "scalar_view_contains_2",
        steps: 81,
        effects: &[("done", 77)],
    },
    Baseline {
        name: "scalar_view_starts_with_0",
        steps: 61,
        effects: &[("done", 57)],
    },
    Baseline {
        name: "scalar_view_starts_with_1",
        steps: 101,
        effects: &[("done", 97)],
    },
    Baseline {
        name: "scalar_view_starts_with_2",
        steps: 99,
        effects: &[("done", 95)],
    },
    Baseline {
        name: "scalar_view_starts_with_3",
        steps: 60,
        effects: &[("done", 56)],
    },
    Baseline {
        name: "scalar_view_starts_with_4",
        steps: 62,
        effects: &[("done", 58)],
    },
    Baseline {
        name: "scalar_view_ends_with_0",
        steps: 61,
        effects: &[("done", 57)],
    },
    Baseline {
        name: "scalar_view_ends_with_1",
        steps: 105,
        effects: &[("done", 101)],
    },
    Baseline {
        name: "scalar_view_ends_with_2",
        steps: 103,
        effects: &[("done", 99)],
    },
    Baseline {
        name: "scalar_view_ends_with_3",
        steps: 60,
        effects: &[("done", 56)],
    },
    Baseline {
        name: "scalar_view_ends_with_4",
        steps: 62,
        effects: &[("done", 58)],
    },
];
