use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "tuple_array_contains_0",
        steps: 35,
        effects: &[("done", 31)],
    },
    Baseline {
        name: "tuple_array_contains_1",
        steps: 109,
        effects: &[("eq", 47), ("eq", 78), ("done", 105)],
    },
    Baseline {
        name: "tuple_array_contains_2",
        steps: 140,
        effects: &[("eq", 47), ("eq", 78), ("eq", 109), ("done", 136)],
    },
    Baseline {
        name: "tuple_array_starts_with_0",
        steps: 63,
        effects: &[("done", 59)],
    },
    Baseline {
        name: "tuple_array_starts_with_1",
        steps: 149,
        effects: &[("eq", 75), ("eq", 114), ("done", 145)],
    },
    Baseline {
        name: "tuple_array_starts_with_2",
        steps: 145,
        effects: &[("eq", 75), ("eq", 114), ("done", 141)],
    },
    Baseline {
        name: "tuple_array_starts_with_3",
        steps: 56,
        effects: &[("done", 52)],
    },
    Baseline {
        name: "tuple_array_starts_with_4",
        steps: 64,
        effects: &[("done", 60)],
    },
    Baseline {
        name: "tuple_array_ends_with_0",
        steps: 63,
        effects: &[("done", 59)],
    },
    Baseline {
        name: "tuple_array_ends_with_1",
        steps: 153,
        effects: &[("eq", 77), ("eq", 118), ("done", 149)],
    },
    Baseline {
        name: "tuple_array_ends_with_2",
        steps: 149,
        effects: &[("eq", 77), ("eq", 118), ("done", 145)],
    },
    Baseline {
        name: "tuple_array_ends_with_3",
        steps: 56,
        effects: &[("done", 52)],
    },
    Baseline {
        name: "tuple_array_ends_with_4",
        steps: 64,
        effects: &[("done", 60)],
    },
    Baseline {
        name: "tuple_custom_contains_0",
        steps: 48,
        effects: &[("iter", 14), ("len", 24), ("done", 44)],
    },
    Baseline {
        name: "tuple_custom_contains_1",
        steps: 136,
        effects: &[
            ("iter", 26),
            ("len", 36),
            ("get", 49),
            ("eq", 67),
            ("get", 87),
            ("eq", 105),
            ("done", 132),
        ],
    },
    Baseline {
        name: "tuple_custom_contains_2",
        steps: 174,
        effects: &[
            ("iter", 26),
            ("len", 36),
            ("get", 49),
            ("eq", 67),
            ("get", 87),
            ("eq", 105),
            ("get", 125),
            ("eq", 143),
            ("done", 170),
        ],
    },
    Baseline {
        name: "tuple_custom_starts_with_0",
        steps: 83,
        effects: &[
            ("iter", 29),
            ("len", 39),
            ("iter", 47),
            ("len", 57),
            ("done", 79),
        ],
    },
    Baseline {
        name: "tuple_custom_starts_with_1",
        steps: 189,
        effects: &[
            ("iter", 37),
            ("len", 47),
            ("iter", 55),
            ("len", 65),
            ("get", 78),
            ("get", 87),
            ("eq", 105),
            ("get", 127),
            ("get", 136),
            ("eq", 154),
            ("done", 185),
        ],
    },
    Baseline {
        name: "tuple_custom_starts_with_2",
        steps: 185,
        effects: &[
            ("iter", 37),
            ("len", 47),
            ("iter", 55),
            ("len", 65),
            ("get", 78),
            ("get", 87),
            ("eq", 105),
            ("get", 127),
            ("get", 136),
            ("eq", 154),
            ("done", 181),
        ],
    },
    Baseline {
        name: "tuple_custom_starts_with_3",
        steps: 76,
        effects: &[
            ("iter", 21),
            ("len", 31),
            ("iter", 39),
            ("len", 49),
            ("done", 72),
        ],
    },
    Baseline {
        name: "tuple_custom_starts_with_4",
        steps: 84,
        effects: &[
            ("iter", 29),
            ("len", 39),
            ("iter", 47),
            ("len", 57),
            ("done", 80),
        ],
    },
    Baseline {
        name: "tuple_custom_ends_with_0",
        steps: 83,
        effects: &[
            ("iter", 29),
            ("len", 39),
            ("iter", 47),
            ("len", 57),
            ("done", 79),
        ],
    },
    Baseline {
        name: "tuple_custom_ends_with_1",
        steps: 193,
        effects: &[
            ("iter", 37),
            ("len", 47),
            ("iter", 55),
            ("len", 65),
            ("get", 80),
            ("get", 89),
            ("eq", 107),
            ("get", 131),
            ("get", 140),
            ("eq", 158),
            ("done", 189),
        ],
    },
    Baseline {
        name: "tuple_custom_ends_with_2",
        steps: 189,
        effects: &[
            ("iter", 37),
            ("len", 47),
            ("iter", 55),
            ("len", 65),
            ("get", 80),
            ("get", 89),
            ("eq", 107),
            ("get", 131),
            ("get", 140),
            ("eq", 158),
            ("done", 185),
        ],
    },
    Baseline {
        name: "tuple_custom_ends_with_3",
        steps: 76,
        effects: &[
            ("iter", 21),
            ("len", 31),
            ("iter", 39),
            ("len", 49),
            ("done", 72),
        ],
    },
    Baseline {
        name: "tuple_custom_ends_with_4",
        steps: 84,
        effects: &[
            ("iter", 29),
            ("len", 39),
            ("iter", 47),
            ("len", 57),
            ("done", 80),
        ],
    },
    Baseline {
        name: "tuple_dynamic_contains_0",
        steps: 49,
        effects: &[("iter", 15), ("len", 25), ("done", 45)],
    },
    Baseline {
        name: "tuple_dynamic_contains_1",
        steps: 137,
        effects: &[
            ("iter", 27),
            ("len", 37),
            ("get", 50),
            ("eq", 68),
            ("get", 88),
            ("eq", 106),
            ("done", 133),
        ],
    },
    Baseline {
        name: "tuple_dynamic_contains_2",
        steps: 175,
        effects: &[
            ("iter", 27),
            ("len", 37),
            ("get", 50),
            ("eq", 68),
            ("get", 88),
            ("eq", 106),
            ("get", 126),
            ("eq", 144),
            ("done", 171),
        ],
    },
    Baseline {
        name: "tuple_dynamic_starts_with_0",
        steps: 84,
        effects: &[
            ("iter", 30),
            ("len", 40),
            ("iter", 48),
            ("len", 58),
            ("done", 80),
        ],
    },
    Baseline {
        name: "tuple_dynamic_starts_with_1",
        steps: 190,
        effects: &[
            ("iter", 38),
            ("len", 48),
            ("iter", 56),
            ("len", 66),
            ("get", 79),
            ("get", 88),
            ("eq", 106),
            ("get", 128),
            ("get", 137),
            ("eq", 155),
            ("done", 186),
        ],
    },
    Baseline {
        name: "tuple_dynamic_starts_with_2",
        steps: 186,
        effects: &[
            ("iter", 38),
            ("len", 48),
            ("iter", 56),
            ("len", 66),
            ("get", 79),
            ("get", 88),
            ("eq", 106),
            ("get", 128),
            ("get", 137),
            ("eq", 155),
            ("done", 182),
        ],
    },
    Baseline {
        name: "tuple_dynamic_starts_with_3",
        steps: 77,
        effects: &[
            ("iter", 22),
            ("len", 32),
            ("iter", 40),
            ("len", 50),
            ("done", 73),
        ],
    },
    Baseline {
        name: "tuple_dynamic_starts_with_4",
        steps: 85,
        effects: &[
            ("iter", 30),
            ("len", 40),
            ("iter", 48),
            ("len", 58),
            ("done", 81),
        ],
    },
    Baseline {
        name: "tuple_dynamic_ends_with_0",
        steps: 84,
        effects: &[
            ("iter", 30),
            ("len", 40),
            ("iter", 48),
            ("len", 58),
            ("done", 80),
        ],
    },
    Baseline {
        name: "tuple_dynamic_ends_with_1",
        steps: 194,
        effects: &[
            ("iter", 38),
            ("len", 48),
            ("iter", 56),
            ("len", 66),
            ("get", 81),
            ("get", 90),
            ("eq", 108),
            ("get", 132),
            ("get", 141),
            ("eq", 159),
            ("done", 190),
        ],
    },
    Baseline {
        name: "tuple_dynamic_ends_with_2",
        steps: 190,
        effects: &[
            ("iter", 38),
            ("len", 48),
            ("iter", 56),
            ("len", 66),
            ("get", 81),
            ("get", 90),
            ("eq", 108),
            ("get", 132),
            ("get", 141),
            ("eq", 159),
            ("done", 186),
        ],
    },
    Baseline {
        name: "tuple_dynamic_ends_with_3",
        steps: 77,
        effects: &[
            ("iter", 22),
            ("len", 32),
            ("iter", 40),
            ("len", 50),
            ("done", 73),
        ],
    },
    Baseline {
        name: "tuple_dynamic_ends_with_4",
        steps: 85,
        effects: &[
            ("iter", 30),
            ("len", 40),
            ("iter", 48),
            ("len", 58),
            ("done", 81),
        ],
    },
    Baseline {
        name: "tuple_view_contains_0",
        steps: 42,
        effects: &[("done", 38)],
    },
    Baseline {
        name: "tuple_view_contains_1",
        steps: 124,
        effects: &[("eq", 58), ("eq", 93), ("done", 120)],
    },
    Baseline {
        name: "tuple_view_contains_2",
        steps: 159,
        effects: &[("eq", 58), ("eq", 93), ("eq", 128), ("done", 155)],
    },
    Baseline {
        name: "tuple_view_starts_with_0",
        steps: 70,
        effects: &[("done", 66)],
    },
    Baseline {
        name: "tuple_view_starts_with_1",
        steps: 164,
        effects: &[("eq", 86), ("eq", 129), ("done", 160)],
    },
    Baseline {
        name: "tuple_view_starts_with_2",
        steps: 160,
        effects: &[("eq", 86), ("eq", 129), ("done", 156)],
    },
    Baseline {
        name: "tuple_view_starts_with_3",
        steps: 63,
        effects: &[("done", 59)],
    },
    Baseline {
        name: "tuple_view_starts_with_4",
        steps: 71,
        effects: &[("done", 67)],
    },
    Baseline {
        name: "tuple_view_ends_with_0",
        steps: 70,
        effects: &[("done", 66)],
    },
    Baseline {
        name: "tuple_view_ends_with_1",
        steps: 168,
        effects: &[("eq", 88), ("eq", 133), ("done", 164)],
    },
    Baseline {
        name: "tuple_view_ends_with_2",
        steps: 164,
        effects: &[("eq", 88), ("eq", 133), ("done", 160)],
    },
    Baseline {
        name: "tuple_view_ends_with_3",
        steps: 63,
        effects: &[("done", 59)],
    },
    Baseline {
        name: "tuple_view_ends_with_4",
        steps: 71,
        effects: &[("done", 67)],
    },
];
