[package]
name = "kagari-hir"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kagari-types.workspace = true
kagari-source.workspace = true
kagari-common.workspace = true
kagari-syntax.workspace = true
serde.workspace = true
smallvec.workspace = true
thiserror.workspace = true

[dev-dependencies]
kagari-stdlib.workspace = true
kagari-contract.workspace = true
