[package]
name = "kagari-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
kagari-common.workspace = true
kagari-embed.workspace = true
kagari-codegen-cranelift = { workspace = true, optional = true }
kagari-syntax.workspace = true
kagari-runtime.workspace = true
kagari-vm.workspace = true

[features]
default = []
jit = ["dep:kagari-codegen-cranelift", "kagari-codegen-cranelift/jit"]
