use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "copy_native_true_0",
        steps: 79,
        effects: &[
            ("receiver", 18),
            ("range", 24),
            ("destination", 30),
            ("committed", 37),
            ("done", 77),
        ],
        holes: &[],
    },
    Baseline {
        name: "copy_generic_true_0",
        steps: 85,
        effects: &[
            ("receiver", 18),
            ("range", 24),
            ("destination", 30),
            ("committed", 43),
            ("done", 83),
        ],
        holes: &[],
    },
    Baseline {
        name: "copy_custom_true_0",
        steps: 91,
        effects: &[
            ("receiver", 20),
            ("range", 26),
            ("destination", 32),
            ("start", 37),
            ("end", 43),
            ("committed", 49),
            ("done", 89),
        ],
        holes: &[],
    },
    Baseline {
        name: "copy_generic_custom_true_0",
        steps: 97,
        effects: &[
            ("receiver", 20),
            ("range", 26),
            ("destination", 32),
            ("start", 41),
            ("end", 47),
            ("committed", 55),
            ("done", 95),
        ],
        holes: &[],
    },
    Baseline {
        name: "copy_native_true_1",
        steps: 81,
        effects: &[
            ("receiver", 18),
            ("range", 24),
            ("destination", 30),
            ("committed", 39),
            ("done", 79),
        ],
        holes: &[(36, 35)],
    },
    Baseline {
        name: "copy_generic_true_1",
        steps: 87,
        effects: &[
            ("receiver", 18),
            ("range", 24),
            ("destination", 30),
            ("committed", 45),
            ("done", 85),
        ],
        holes: &[(40, 39)],
    },
    Baseline {
        name: "copy_custom_true_1",
        steps: 93,
        effects: &[
            ("receiver", 20),
            ("range", 26),
            ("destination", 32),
            ("start", 37),
            ("end", 43),
            ("committed", 51),
            ("done", 91),
        ],
        holes: &[(48, 47)],
    },
    Baseline {
        name: "copy_generic_custom_true_1",
        steps: 99,
        effects: &[
            ("receiver", 20),
            ("range", 26),
            ("destination", 32),
            ("start", 41),
            ("end", 47),
            ("committed", 57),
            ("done", 97),
        ],
        holes: &[(52, 51)],
    },
    Baseline {
        name: "copy_native_true_2",
        steps: 81,
        effects: &[
            ("receiver", 18),
            ("range", 24),
            ("destination", 30),
            ("committed", 39),
            ("done", 79),
        ],
        holes: &[(36, 35)],
    },
    Baseline {
        name: "copy_generic_true_2",
        steps: 87,
        effects: &[
            ("receiver", 18),
            ("range", 24),
            ("destination", 30),
            ("committed", 45),
            ("done", 85),
        ],
        holes: &[(40, 39)],
    },
    Baseline {
        name: "copy_custom_true_2",
        steps: 94,
        effects: &[
            ("receiver", 21),
            ("range", 27),
            ("destination", 33),
            ("start", 38),
            ("end", 44),
            ("committed", 52),
            ("done", 92),
        ],
        holes: &[(49, 48)],
    },
    Baseline {
        name: "copy_generic_custom_true_2",
        steps: 100,
        effects: &[
            ("receiver", 21),
            ("range", 27),
            ("destination", 33),
            ("start", 42),
            ("end", 48),
            ("committed", 58),
            ("done", 98),
        ],
        holes: &[(53, 52)],
    },
    Baseline {
        name: "copy_native_true_3",
        steps: 80,
        effects: &[
            ("receiver", 17),
            ("range", 23),
            ("destination", 29),
            ("committed", 38),
            ("done", 78),
        ],
        holes: &[(35, 34)],
    },
    Baseline {
        name: "copy_generic_true_3",
        steps: 86,
        effects: &[
            ("receiver", 17),
            ("range", 23),
            ("destination", 29),
            ("committed", 44),
            ("done", 84),
        ],
        holes: &[(39, 38)],
    },
    Baseline {
        name: "copy_custom_true_3",
        steps: 93,
        effects: &[
            ("receiver", 20),
            ("range", 26),
            ("destination", 32),
            ("start", 37),
            ("end", 43),
            ("committed", 51),
            ("done", 91),
        ],
        holes: &[(48, 47)],
    },
    Baseline {
        name: "copy_generic_custom_true_3",
        steps: 99,
        effects: &[
            ("receiver", 20),
            ("range", 26),
            ("destination", 32),
            ("start", 41),
            ("end", 47),
            ("committed", 57),
            ("done", 97),
        ],
        holes: &[(52, 51)],
    },
    Baseline {
        name: "copy_native_true_4",
        steps: 80,
        effects: &[
            ("receiver", 17),
            ("range", 23),
            ("destination", 29),
            ("committed", 38),
            ("done", 78),
        ],
        holes: &[(35, 34)],
    },
    Baseline {
        name: "copy_generic_true_4",
        steps: 86,
        effects: &[
            ("receiver", 17),
            ("range", 23),
            ("destination", 29),
            ("committed", 44),
            ("done", 84),
        ],
        holes: &[(39, 38)],
    },
    Baseline {
        name: "copy_custom_true_4",
        steps: 93,
        effects: &[
            ("receiver", 20),
            ("range", 26),
            ("destination", 32),
            ("start", 37),
            ("end", 43),
            ("committed", 51),
            ("done", 91),
        ],
        holes: &[(48, 47)],
    },
    Baseline {
        name: "copy_generic_custom_true_4",
        steps: 99,
        effects: &[
            ("receiver", 20),
            ("range", 26),
            ("destination", 32),
            ("start", 41),
            ("end", 47),
            ("committed", 57),
            ("done", 97),
        ],
        holes: &[(52, 51)],
    },
    Baseline {
        name: "copy_native_true_5",
        steps: 81,
        effects: &[
            ("receiver", 17),
            ("range", 23),
            ("destination", 29),
            ("committed", 39),
            ("done", 79),
        ],
        holes: &[(35, 34), (36, 34)],
    },
    Baseline {
        name: "copy_generic_true_5",
        steps: 87,
        effects: &[
            ("receiver", 17),
            ("range", 23),
            ("destination", 29),
            ("committed", 45),
            ("done", 85),
        ],
        holes: &[(39, 38), (40, 38)],
    },
    Baseline {
        name: "copy_custom_true_5",
        steps: 94,
        effects: &[
            ("receiver", 20),
            ("range", 26),
            ("destination", 32),
            ("start", 37),
            ("end", 43),
            ("committed", 52),
            ("done", 92),
        ],
        holes: &[(48, 47), (49, 47)],
    },
    Baseline {
        name: "copy_generic_custom_true_5",
        steps: 100,
        effects: &[
            ("receiver", 20),
            ("range", 26),
            ("destination", 32),
            ("start", 41),
            ("end", 47),
            ("committed", 58),
            ("done", 98),
        ],
        holes: &[(52, 51), (53, 51)],
    },
    Baseline {
        name: "copy_native_true_6",
        steps: 81,
        effects: &[
            ("receiver", 16),
            ("range", 22),
            ("destination", 28),
            ("committed", 39),
            ("done", 79),
        ],
        holes: &[(34, 33), (35, 33), (36, 33)],
    },
    Baseline {
        name: "copy_generic_true_6",
        steps: 87,
        effects: &[
            ("receiver", 16),
            ("range", 22),
            ("destination", 28),
            ("committed", 45),
            ("done", 85),
        ],
        holes: &[(38, 37), (39, 37), (40, 37)],
    },
    Baseline {
        name: "copy_custom_true_6",
        steps: 94,
        effects: &[
            ("receiver", 19),
            ("range", 25),
            ("destination", 31),
            ("start", 36),
            ("end", 42),
            ("committed", 52),
            ("done", 92),
        ],
        holes: &[(47, 46), (48, 46), (49, 46)],
    },
    Baseline {
        name: "copy_generic_custom_true_6",
        steps: 100,
        effects: &[
            ("receiver", 19),
            ("range", 25),
            ("destination", 31),
            ("start", 40),
            ("end", 46),
            ("committed", 58),
            ("done", 98),
        ],
        holes: &[(51, 50), (52, 50), (53, 50)],
    },
    Baseline {
        name: "copy_native_true_7",
        steps: 79,
        effects: &[
            ("receiver", 18),
            ("range", 24),
            ("destination", 30),
            ("committed", 37),
            ("done", 77),
        ],
        holes: &[],
    },
    Baseline {
        name: "copy_generic_true_7",
        steps: 85,
        effects: &[
            ("receiver", 18),
            ("range", 24),
            ("destination", 30),
            ("committed", 43),
            ("done", 83),
        ],
        holes: &[],
    },
    Baseline {
        name: "copy_custom_true_7",
        steps: 91,
        effects: &[
            ("receiver", 20),
            ("range", 26),
            ("destination", 32),
            ("start", 37),
            ("end", 43),
            ("committed", 49),
            ("done", 89),
        ],
        holes: &[],
    },
    Baseline {
        name: "copy_generic_custom_true_7",
        steps: 97,
        effects: &[
            ("receiver", 20),
            ("range", 26),
            ("destination", 32),
            ("start", 41),
            ("end", 47),
            ("committed", 55),
            ("done", 95),
        ],
        holes: &[],
    },
    Baseline {
        name: "copy_native_true_8",
        steps: 79,
        effects: &[
            ("receiver", 18),
            ("range", 24),
            ("destination", 30),
            ("committed", 37),
            ("done", 77),
        ],
        holes: &[],
    },
    Baseline {
        name: "copy_generic_true_8",
        steps: 85,
        effects: &[
            ("receiver", 18),
            ("range", 24),
            ("destination", 30),
            ("committed", 43),
            ("done", 83),
        ],
        holes: &[],
    },
    Baseline {
        name: "copy_custom_true_8",
        steps: 92,
        effects: &[
            ("receiver", 21),
            ("range", 27),
            ("destination", 33),
            ("start", 38),
            ("end", 44),
            ("committed", 50),
            ("done", 90),
        ],
        holes: &[],
    },
    Baseline {
        name: "copy_generic_custom_true_8",
        steps: 98,
        effects: &[
            ("receiver", 21),
            ("range", 27),
            ("destination", 33),
            ("start", 42),
            ("end", 48),
            ("committed", 56),
            ("done", 96),
        ],
        holes: &[],
    },
];
