use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "copy_native_false_0",
        steps: 71,
        effects: &[
            ("receiver", 14),
            ("range", 20),
            ("destination", 26),
            ("committed", 33),
            ("done", 69),
        ],
        holes: &[],
    },
    Baseline {
        name: "copy_generic_false_0",
        steps: 77,
        effects: &[
            ("receiver", 14),
            ("range", 20),
            ("destination", 26),
            ("committed", 39),
            ("done", 75),
        ],
        holes: &[],
    },
    Baseline {
        name: "copy_custom_false_0",
        steps: 83,
        effects: &[
            ("receiver", 16),
            ("range", 22),
            ("destination", 28),
            ("start", 33),
            ("end", 39),
            ("committed", 45),
            ("done", 81),
        ],
        holes: &[],
    },
    Baseline {
        name: "copy_generic_custom_false_0",
        steps: 89,
        effects: &[
            ("receiver", 16),
            ("range", 22),
            ("destination", 28),
            ("start", 37),
            ("end", 43),
            ("committed", 51),
            ("done", 87),
        ],
        holes: &[],
    },
    Baseline {
        name: "copy_native_false_1",
        steps: 73,
        effects: &[
            ("receiver", 14),
            ("range", 20),
            ("destination", 26),
            ("committed", 35),
            ("done", 71),
        ],
        holes: &[(32, 31)],
    },
    Baseline {
        name: "copy_generic_false_1",
        steps: 79,
        effects: &[
            ("receiver", 14),
            ("range", 20),
            ("destination", 26),
            ("committed", 41),
            ("done", 77),
        ],
        holes: &[(36, 35)],
    },
    Baseline {
        name: "copy_custom_false_1",
        steps: 85,
        effects: &[
            ("receiver", 16),
            ("range", 22),
            ("destination", 28),
            ("start", 33),
            ("end", 39),
            ("committed", 47),
            ("done", 83),
        ],
        holes: &[(44, 43)],
    },
    Baseline {
        name: "copy_generic_custom_false_1",
        steps: 91,
        effects: &[
            ("receiver", 16),
            ("range", 22),
            ("destination", 28),
            ("start", 37),
            ("end", 43),
            ("committed", 53),
            ("done", 89),
        ],
        holes: &[(48, 47)],
    },
    Baseline {
        name: "copy_native_false_2",
        steps: 73,
        effects: &[
            ("receiver", 14),
            ("range", 20),
            ("destination", 26),
            ("committed", 35),
            ("done", 71),
        ],
        holes: &[(32, 31)],
    },
    Baseline {
        name: "copy_generic_false_2",
        steps: 79,
        effects: &[
            ("receiver", 14),
            ("range", 20),
            ("destination", 26),
            ("committed", 41),
            ("done", 77),
        ],
        holes: &[(36, 35)],
    },
    Baseline {
        name: "copy_custom_false_2",
        steps: 86,
        effects: &[
            ("receiver", 17),
            ("range", 23),
            ("destination", 29),
            ("start", 34),
            ("end", 40),
            ("committed", 48),
            ("done", 84),
        ],
        holes: &[(45, 44)],
    },
    Baseline {
        name: "copy_generic_custom_false_2",
        steps: 92,
        effects: &[
            ("receiver", 17),
            ("range", 23),
            ("destination", 29),
            ("start", 38),
            ("end", 44),
            ("committed", 54),
            ("done", 90),
        ],
        holes: &[(49, 48)],
    },
    Baseline {
        name: "copy_native_false_3",
        steps: 72,
        effects: &[
            ("receiver", 13),
            ("range", 19),
            ("destination", 25),
            ("committed", 34),
            ("done", 70),
        ],
        holes: &[(31, 30)],
    },
    Baseline {
        name: "copy_generic_false_3",
        steps: 78,
        effects: &[
            ("receiver", 13),
            ("range", 19),
            ("destination", 25),
            ("committed", 40),
            ("done", 76),
        ],
        holes: &[(35, 34)],
    },
    Baseline {
        name: "copy_custom_false_3",
        steps: 85,
        effects: &[
            ("receiver", 16),
            ("range", 22),
            ("destination", 28),
            ("start", 33),
            ("end", 39),
            ("committed", 47),
            ("done", 83),
        ],
        holes: &[(44, 43)],
    },
    Baseline {
        name: "copy_generic_custom_false_3",
        steps: 91,
        effects: &[
            ("receiver", 16),
            ("range", 22),
            ("destination", 28),
            ("start", 37),
            ("end", 43),
            ("committed", 53),
            ("done", 89),
        ],
        holes: &[(48, 47)],
    },
    Baseline {
        name: "copy_native_false_4",
        steps: 72,
        effects: &[
            ("receiver", 13),
            ("range", 19),
            ("destination", 25),
            ("committed", 34),
            ("done", 70),
        ],
        holes: &[(31, 30)],
    },
    Baseline {
        name: "copy_generic_false_4",
        steps: 78,
        effects: &[
            ("receiver", 13),
            ("range", 19),
            ("destination", 25),
            ("committed", 40),
            ("done", 76),
        ],
        holes: &[(35, 34)],
    },
    Baseline {
        name: "copy_custom_false_4",
        steps: 85,
        effects: &[
            ("receiver", 16),
            ("range", 22),
            ("destination", 28),
            ("start", 33),
            ("end", 39),
            ("committed", 47),
            ("done", 83),
        ],
        holes: &[(44, 43)],
    },
    Baseline {
        name: "copy_generic_custom_false_4",
        steps: 91,
        effects: &[
            ("receiver", 16),
            ("range", 22),
            ("destination", 28),
            ("start", 37),
            ("end", 43),
            ("committed", 53),
            ("done", 89),
        ],
        holes: &[(48, 47)],
    },
    Baseline {
        name: "copy_native_false_5",
        steps: 73,
        effects: &[
            ("receiver", 13),
            ("range", 19),
            ("destination", 25),
            ("committed", 35),
            ("done", 71),
        ],
        holes: &[(31, 30), (32, 30)],
    },
    Baseline {
        name: "copy_generic_false_5",
        steps: 79,
        effects: &[
            ("receiver", 13),
            ("range", 19),
            ("destination", 25),
            ("committed", 41),
            ("done", 77),
        ],
        holes: &[(35, 34), (36, 34)],
    },
    Baseline {
        name: "copy_custom_false_5",
        steps: 86,
        effects: &[
            ("receiver", 16),
            ("range", 22),
            ("destination", 28),
            ("start", 33),
            ("end", 39),
            ("committed", 48),
            ("done", 84),
        ],
        holes: &[(44, 43), (45, 43)],
    },
    Baseline {
        name: "copy_generic_custom_false_5",
        steps: 92,
        effects: &[
            ("receiver", 16),
            ("range", 22),
            ("destination", 28),
            ("start", 37),
            ("end", 43),
            ("committed", 54),
            ("done", 90),
        ],
        holes: &[(48, 47), (49, 47)],
    },
    Baseline {
        name: "copy_native_false_6",
        steps: 73,
        effects: &[
            ("receiver", 12),
            ("range", 18),
            ("destination", 24),
            ("committed", 35),
            ("done", 71),
        ],
        holes: &[(30, 29), (31, 29), (32, 29)],
    },
    Baseline {
        name: "copy_generic_false_6",
        steps: 79,
        effects: &[
            ("receiver", 12),
            ("range", 18),
            ("destination", 24),
            ("committed", 41),
            ("done", 77),
        ],
        holes: &[(34, 33), (35, 33), (36, 33)],
    },
    Baseline {
        name: "copy_custom_false_6",
        steps: 86,
        effects: &[
            ("receiver", 15),
            ("range", 21),
            ("destination", 27),
            ("start", 32),
            ("end", 38),
            ("committed", 48),
            ("done", 84),
        ],
        holes: &[(43, 42), (44, 42), (45, 42)],
    },
    Baseline {
        name: "copy_generic_custom_false_6",
        steps: 92,
        effects: &[
            ("receiver", 15),
            ("range", 21),
            ("destination", 27),
            ("start", 36),
            ("end", 42),
            ("committed", 54),
            ("done", 90),
        ],
        holes: &[(47, 46), (48, 46), (49, 46)],
    },
    Baseline {
        name: "copy_native_false_7",
        steps: 71,
        effects: &[
            ("receiver", 14),
            ("range", 20),
            ("destination", 26),
            ("committed", 33),
            ("done", 69),
        ],
        holes: &[],
    },
    Baseline {
        name: "copy_generic_false_7",
        steps: 77,
        effects: &[
            ("receiver", 14),
            ("range", 20),
            ("destination", 26),
            ("committed", 39),
            ("done", 75),
        ],
        holes: &[],
    },
    Baseline {
        name: "copy_custom_false_7",
        steps: 83,
        effects: &[
            ("receiver", 16),
            ("range", 22),
            ("destination", 28),
            ("start", 33),
            ("end", 39),
            ("committed", 45),
            ("done", 81),
        ],
        holes: &[],
    },
    Baseline {
        name: "copy_generic_custom_false_7",
        steps: 89,
        effects: &[
            ("receiver", 16),
            ("range", 22),
            ("destination", 28),
            ("start", 37),
            ("end", 43),
            ("committed", 51),
            ("done", 87),
        ],
        holes: &[],
    },
    Baseline {
        name: "copy_native_false_8",
        steps: 71,
        effects: &[
            ("receiver", 14),
            ("range", 20),
            ("destination", 26),
            ("committed", 33),
            ("done", 69),
        ],
        holes: &[],
    },
    Baseline {
        name: "copy_generic_false_8",
        steps: 77,
        effects: &[
            ("receiver", 14),
            ("range", 20),
            ("destination", 26),
            ("committed", 39),
            ("done", 75),
        ],
        holes: &[],
    },
    Baseline {
        name: "copy_custom_false_8",
        steps: 84,
        effects: &[
            ("receiver", 17),
            ("range", 23),
            ("destination", 29),
            ("start", 34),
            ("end", 40),
            ("committed", 46),
            ("done", 82),
        ],
        holes: &[],
    },
    Baseline {
        name: "copy_generic_custom_false_8",
        steps: 90,
        effects: &[
            ("receiver", 17),
            ("range", 23),
            ("destination", 29),
            ("start", 38),
            ("end", 44),
            ("committed", 52),
            ("done", 88),
        ],
        holes: &[],
    },
];
