// Observed at 7d2ba34 before native List join entry.
pub(super) struct Baseline {
    pub name: &'static str,
    pub steps: u64,
    pub effects: &'static [(&'static str, u64)],
    pub holes: &'static [(u64, u64)],
}
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "array_0",
        steps: 24,
        effects: &[("source", 6), ("separator", 11), ("done", 22)],
        holes: &[],
    },
    Baseline {
        name: "array_1",
        steps: 25,
        effects: &[("source", 7), ("separator", 12), ("done", 23)],
        holes: &[],
    },
    Baseline {
        name: "array_2",
        steps: 27,
        effects: &[("source", 9), ("separator", 14), ("done", 25)],
        holes: &[],
    },
    Baseline {
        name: "array_3",
        steps: 27,
        effects: &[("source", 9), ("separator", 14), ("done", 25)],
        holes: &[],
    },
    Baseline {
        name: "array_4",
        steps: 27,
        effects: &[("source", 9), ("separator", 14), ("done", 25)],
        holes: &[],
    },
    Baseline {
        name: "generic_array_0",
        steps: 28,
        effects: &[("source", 6), ("separator", 11), ("done", 26)],
        holes: &[],
    },
    Baseline {
        name: "generic_array_1",
        steps: 29,
        effects: &[("source", 7), ("separator", 12), ("done", 27)],
        holes: &[],
    },
    Baseline {
        name: "generic_array_2",
        steps: 31,
        effects: &[("source", 9), ("separator", 14), ("done", 29)],
        holes: &[],
    },
    Baseline {
        name: "generic_array_3",
        steps: 31,
        effects: &[("source", 9), ("separator", 14), ("done", 29)],
        holes: &[],
    },
    Baseline {
        name: "generic_array_4",
        steps: 31,
        effects: &[("source", 9), ("separator", 14), ("done", 29)],
        holes: &[],
    },
    Baseline {
        name: "custom_0",
        steps: 56,
        effects: &[("source", 6), ("separator", 12), ("iter", 17), ("done", 54)],
        holes: &[],
    },
    Baseline {
        name: "custom_1",
        steps: 77,
        effects: &[
            ("source", 7),
            ("separator", 13),
            ("iter", 18),
            ("item", 43),
            ("done", 75),
        ],
        holes: &[],
    },
    Baseline {
        name: "custom_2",
        steps: 119,
        effects: &[
            ("source", 9),
            ("separator", 15),
            ("iter", 20),
            ("item", 45),
            ("item", 65),
            ("item", 85),
            ("done", 117),
        ],
        holes: &[],
    },
    Baseline {
        name: "custom_3",
        steps: 119,
        effects: &[
            ("source", 9),
            ("separator", 15),
            ("iter", 20),
            ("item", 45),
            ("item", 65),
            ("item", 85),
            ("done", 117),
        ],
        holes: &[],
    },
    Baseline {
        name: "custom_4",
        steps: 119,
        effects: &[
            ("source", 9),
            ("separator", 15),
            ("iter", 20),
            ("item", 45),
            ("item", 65),
            ("item", 85),
            ("done", 117),
        ],
        holes: &[],
    },
    Baseline {
        name: "generic_custom_0",
        steps: 60,
        effects: &[("source", 6), ("separator", 12), ("iter", 20), ("done", 58)],
        holes: &[],
    },
    Baseline {
        name: "generic_custom_1",
        steps: 81,
        effects: &[
            ("source", 7),
            ("separator", 13),
            ("iter", 21),
            ("item", 46),
            ("done", 79),
        ],
        holes: &[],
    },
    Baseline {
        name: "generic_custom_2",
        steps: 123,
        effects: &[
            ("source", 9),
            ("separator", 15),
            ("iter", 23),
            ("item", 48),
            ("item", 68),
            ("item", 88),
            ("done", 121),
        ],
        holes: &[],
    },
    Baseline {
        name: "generic_custom_3",
        steps: 123,
        effects: &[
            ("source", 9),
            ("separator", 15),
            ("iter", 23),
            ("item", 48),
            ("item", 68),
            ("item", 88),
            ("done", 121),
        ],
        holes: &[],
    },
    Baseline {
        name: "generic_custom_4",
        steps: 123,
        effects: &[
            ("source", 9),
            ("separator", 15),
            ("iter", 23),
            ("item", 48),
            ("item", 68),
            ("item", 88),
            ("done", 121),
        ],
        holes: &[],
    },
    Baseline {
        name: "dynamic_array_0",
        steps: 42,
        effects: &[("source", 6), ("separator", 15), ("done", 40)],
        holes: &[],
    },
    Baseline {
        name: "dynamic_array_1",
        steps: 49,
        effects: &[("source", 7), ("separator", 16), ("done", 47)],
        holes: &[],
    },
    Baseline {
        name: "dynamic_array_2",
        steps: 63,
        effects: &[("source", 9), ("separator", 18), ("done", 61)],
        holes: &[],
    },
    Baseline {
        name: "dynamic_array_3",
        steps: 63,
        effects: &[("source", 9), ("separator", 18), ("done", 61)],
        holes: &[],
    },
    Baseline {
        name: "dynamic_array_4",
        steps: 63,
        effects: &[("source", 9), ("separator", 18), ("done", 61)],
        holes: &[],
    },
    Baseline {
        name: "dynamic_custom_0",
        steps: 60,
        effects: &[("source", 6), ("separator", 16), ("iter", 21), ("done", 58)],
        holes: &[],
    },
    Baseline {
        name: "dynamic_custom_1",
        steps: 81,
        effects: &[
            ("source", 7),
            ("separator", 17),
            ("iter", 22),
            ("item", 47),
            ("done", 79),
        ],
        holes: &[],
    },
    Baseline {
        name: "dynamic_custom_2",
        steps: 123,
        effects: &[
            ("source", 9),
            ("separator", 19),
            ("iter", 24),
            ("item", 49),
            ("item", 69),
            ("item", 89),
            ("done", 121),
        ],
        holes: &[],
    },
    Baseline {
        name: "dynamic_custom_3",
        steps: 123,
        effects: &[
            ("source", 9),
            ("separator", 19),
            ("iter", 24),
            ("item", 49),
            ("item", 69),
            ("item", 89),
            ("done", 121),
        ],
        holes: &[],
    },
    Baseline {
        name: "dynamic_custom_4",
        steps: 123,
        effects: &[
            ("source", 9),
            ("separator", 19),
            ("iter", 24),
            ("item", 49),
            ("item", 69),
            ("item", 89),
            ("done", 121),
        ],
        holes: &[],
    },
    Baseline {
        name: "mutable_array_0",
        steps: 42,
        effects: &[("source", 6), ("separator", 15), ("done", 40)],
        holes: &[],
    },
    Baseline {
        name: "mutable_array_1",
        steps: 49,
        effects: &[("source", 7), ("separator", 16), ("done", 47)],
        holes: &[],
    },
    Baseline {
        name: "mutable_array_2",
        steps: 63,
        effects: &[("source", 9), ("separator", 18), ("done", 61)],
        holes: &[],
    },
    Baseline {
        name: "mutable_array_3",
        steps: 63,
        effects: &[("source", 9), ("separator", 18), ("done", 61)],
        holes: &[],
    },
    Baseline {
        name: "mutable_array_4",
        steps: 63,
        effects: &[("source", 9), ("separator", 18), ("done", 61)],
        holes: &[],
    },
];

pub(super) fn all() -> impl Iterator<Item = &'static Baseline> {
    BASELINE.iter()
}
