// Observed at 66ea900 before native destination entries.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "collect_array_native_false_false",
        steps: 50,
        effects: &[("source", 8), ("done", 48)],
        holes: &[],
    },
    Baseline {
        name: "collect_array_native_false_true",
        steps: 53,
        effects: &[("source", 8), ("done", 51)],
        holes: &[],
    },
    Baseline {
        name: "collect_array_native_true_false",
        steps: 29,
        effects: &[("source", 5), ("done", 27)],
        holes: &[],
    },
    Baseline {
        name: "collect_array_native_true_true",
        steps: 32,
        effects: &[("source", 5), ("done", 30)],
        holes: &[],
    },
    Baseline {
        name: "collect_array_custom_false_false",
        steps: 134,
        effects: &[
            ("source", 9),
            ("next", 16),
            ("next", 47),
            ("next", 78),
            ("next", 109),
            ("done", 132),
        ],
        holes: &[],
    },
    Baseline {
        name: "collect_array_custom_false_true",
        steps: 137,
        effects: &[
            ("source", 9),
            ("next", 18),
            ("next", 49),
            ("next", 80),
            ("next", 111),
            ("done", 135),
        ],
        holes: &[],
    },
    Baseline {
        name: "collect_array_custom_true_false",
        steps: 38,
        effects: &[("source", 6), ("next", 13), ("done", 36)],
        holes: &[],
    },
    Baseline {
        name: "collect_array_custom_true_true",
        steps: 41,
        effects: &[("source", 6), ("next", 15), ("done", 39)],
        holes: &[],
    },
    Baseline {
        name: "collect_array_lazy_false_false",
        steps: 106,
        effects: &[
            ("source", 12),
            ("item", 31),
            ("item", 51),
            ("item", 71),
            ("done", 104),
        ],
        holes: &[],
    },
    Baseline {
        name: "collect_array_lazy_false_true",
        steps: 109,
        effects: &[
            ("source", 12),
            ("item", 33),
            ("item", 53),
            ("item", 73),
            ("done", 107),
        ],
        holes: &[],
    },
    Baseline {
        name: "collect_array_lazy_true_false",
        steps: 43,
        effects: &[("source", 9), ("done", 41)],
        holes: &[],
    },
    Baseline {
        name: "collect_array_lazy_true_true",
        steps: 46,
        effects: &[("source", 9), ("done", 44)],
        holes: &[],
    },
    Baseline {
        name: "collect_bag_native_false_false",
        steps: 57,
        effects: &[("source", 8), ("construct", 13), ("done", 55)],
        holes: &[],
    },
    Baseline {
        name: "collect_bag_native_false_true",
        steps: 60,
        effects: &[("source", 8), ("construct", 15), ("done", 58)],
        holes: &[],
    },
    Baseline {
        name: "collect_bag_native_true_false",
        steps: 36,
        effects: &[("source", 5), ("construct", 10), ("done", 34)],
        holes: &[],
    },
    Baseline {
        name: "collect_bag_native_true_true",
        steps: 39,
        effects: &[("source", 5), ("construct", 12), ("done", 37)],
        holes: &[],
    },
    Baseline {
        name: "collect_bag_custom_false_false",
        steps: 141,
        effects: &[
            ("source", 9),
            ("construct", 14),
            ("next", 20),
            ("next", 51),
            ("next", 82),
            ("next", 113),
            ("done", 139),
        ],
        holes: &[],
    },
    Baseline {
        name: "collect_bag_custom_false_true",
        steps: 144,
        effects: &[
            ("source", 9),
            ("construct", 16),
            ("next", 22),
            ("next", 53),
            ("next", 84),
            ("next", 115),
            ("done", 142),
        ],
        holes: &[],
    },
    Baseline {
        name: "collect_bag_custom_true_false",
        steps: 45,
        effects: &[("source", 6), ("construct", 11), ("next", 17), ("done", 43)],
        holes: &[],
    },
    Baseline {
        name: "collect_bag_custom_true_true",
        steps: 48,
        effects: &[("source", 6), ("construct", 13), ("next", 19), ("done", 46)],
        holes: &[],
    },
    Baseline {
        name: "collect_bag_lazy_false_false",
        steps: 113,
        effects: &[
            ("source", 12),
            ("construct", 17),
            ("item", 35),
            ("item", 55),
            ("item", 75),
            ("done", 111),
        ],
        holes: &[],
    },
    Baseline {
        name: "collect_bag_lazy_false_true",
        steps: 116,
        effects: &[
            ("source", 12),
            ("construct", 19),
            ("item", 37),
            ("item", 57),
            ("item", 77),
            ("done", 114),
        ],
        holes: &[],
    },
    Baseline {
        name: "collect_bag_lazy_true_false",
        steps: 50,
        effects: &[("source", 9), ("construct", 14), ("done", 48)],
        holes: &[],
    },
    Baseline {
        name: "collect_bag_lazy_true_true",
        steps: 53,
        effects: &[("source", 9), ("construct", 16), ("done", 51)],
        holes: &[],
    },
    Baseline {
        name: "collect_total_native_false_false",
        steps: 78,
        effects: &[
            ("source", 8),
            ("construct", 13),
            ("destination", 28),
            ("destination", 41),
            ("destination", 54),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "collect_total_native_false_true",
        steps: 81,
        effects: &[
            ("source", 8),
            ("construct", 15),
            ("destination", 30),
            ("destination", 43),
            ("destination", 56),
            ("done", 79),
        ],
        holes: &[],
    },
    Baseline {
        name: "collect_total_native_true_false",
        steps: 36,
        effects: &[("source", 5), ("construct", 10), ("done", 34)],
        holes: &[],
    },
    Baseline {
        name: "collect_total_native_true_true",
        steps: 39,
        effects: &[("source", 5), ("construct", 12), ("done", 37)],
        holes: &[],
    },
    Baseline {
        name: "collect_total_custom_false_false",
        steps: 162,
        effects: &[
            ("source", 9),
            ("construct", 14),
            ("next", 22),
            ("destination", 51),
            ("next", 60),
            ("destination", 89),
            ("next", 98),
            ("destination", 127),
            ("next", 136),
            ("done", 160),
        ],
        holes: &[],
    },
    Baseline {
        name: "collect_total_custom_false_true",
        steps: 165,
        effects: &[
            ("source", 9),
            ("construct", 16),
            ("next", 24),
            ("destination", 53),
            ("next", 62),
            ("destination", 91),
            ("next", 100),
            ("destination", 129),
            ("next", 138),
            ("done", 163),
        ],
        holes: &[],
    },
    Baseline {
        name: "collect_total_custom_true_false",
        steps: 45,
        effects: &[("source", 6), ("construct", 11), ("next", 19), ("done", 43)],
        holes: &[],
    },
    Baseline {
        name: "collect_total_custom_true_true",
        steps: 48,
        effects: &[("source", 6), ("construct", 13), ("next", 21), ("done", 46)],
        holes: &[],
    },
    Baseline {
        name: "collect_total_lazy_false_false",
        steps: 134,
        effects: &[
            ("source", 12),
            ("construct", 17),
            ("item", 37),
            ("destination", 47),
            ("item", 64),
            ("destination", 74),
            ("item", 91),
            ("destination", 101),
            ("done", 132),
        ],
        holes: &[],
    },
    Baseline {
        name: "collect_total_lazy_false_true",
        steps: 137,
        effects: &[
            ("source", 12),
            ("construct", 19),
            ("item", 39),
            ("destination", 49),
            ("item", 66),
            ("destination", 76),
            ("item", 93),
            ("destination", 103),
            ("done", 135),
        ],
        holes: &[],
    },
    Baseline {
        name: "collect_total_lazy_true_false",
        steps: 50,
        effects: &[("source", 9), ("construct", 14), ("done", 48)],
        holes: &[],
    },
    Baseline {
        name: "collect_total_lazy_true_true",
        steps: 53,
        effects: &[("source", 9), ("construct", 16), ("done", 51)],
        holes: &[],
    },
    Baseline {
        name: "collect_set_native_false_false",
        steps: 142,
        effects: &[
            ("source", 11),
            ("hash", 26),
            ("hash", 49),
            ("eq", 70),
            ("hash", 93),
            ("eq", 114),
            ("done", 140),
        ],
        holes: &[],
    },
    Baseline {
        name: "collect_set_native_false_true",
        steps: 145,
        effects: &[
            ("source", 11),
            ("hash", 28),
            ("hash", 51),
            ("eq", 72),
            ("hash", 95),
            ("eq", 116),
            ("done", 143),
        ],
        holes: &[],
    },
    Baseline {
        name: "collect_set_native_true_false",
        steps: 29,
        effects: &[("source", 5), ("done", 27)],
        holes: &[],
    },
    Baseline {
        name: "collect_set_native_true_true",
        steps: 32,
        effects: &[("source", 5), ("done", 30)],
        holes: &[],
    },
    Baseline {
        name: "collect_set_custom_false_false",
        steps: 226,
        effects: &[
            ("source", 12),
            ("next", 19),
            ("hash", 49),
            ("next", 67),
            ("hash", 97),
            ("eq", 118),
            ("next", 136),
            ("hash", 166),
            ("eq", 187),
            ("next", 201),
            ("done", 224),
        ],
        holes: &[],
    },
    Baseline {
        name: "collect_set_custom_false_true",
        steps: 229,
        effects: &[
            ("source", 12),
            ("next", 21),
            ("hash", 51),
            ("next", 69),
            ("hash", 99),
            ("eq", 120),
            ("next", 138),
            ("hash", 168),
            ("eq", 189),
            ("next", 203),
            ("done", 227),
        ],
        holes: &[],
    },
    Baseline {
        name: "collect_set_custom_true_false",
        steps: 38,
        effects: &[("source", 6), ("next", 13), ("done", 36)],
        holes: &[],
    },
    Baseline {
        name: "collect_set_custom_true_true",
        steps: 41,
        effects: &[("source", 6), ("next", 15), ("done", 39)],
        holes: &[],
    },
    Baseline {
        name: "collect_set_lazy_false_false",
        steps: 198,
        effects: &[
            ("source", 15),
            ("item", 34),
            ("hash", 45),
            ("item", 71),
            ("hash", 82),
            ("eq", 103),
            ("item", 129),
            ("hash", 140),
            ("eq", 161),
            ("done", 196),
        ],
        holes: &[],
    },
    Baseline {
        name: "collect_set_lazy_false_true",
        steps: 201,
        effects: &[
            ("source", 15),
            ("item", 36),
            ("hash", 47),
            ("item", 73),
            ("hash", 84),
            ("eq", 105),
            ("item", 131),
            ("hash", 142),
            ("eq", 163),
            ("done", 199),
        ],
        holes: &[],
    },
    Baseline {
        name: "collect_set_lazy_true_false",
        steps: 43,
        effects: &[("source", 9), ("done", 41)],
        holes: &[],
    },
    Baseline {
        name: "collect_set_lazy_true_true",
        steps: 46,
        effects: &[("source", 9), ("done", 44)],
        holes: &[],
    },
    Baseline {
        name: "collect_map_native_false_false",
        steps: 160,
        effects: &[
            ("source", 17),
            ("hash", 36),
            ("hash", 63),
            ("eq", 84),
            ("hash", 111),
            ("eq", 132),
            ("done", 158),
        ],
        holes: &[],
    },
    Baseline {
        name: "collect_map_native_false_true",
        steps: 163,
        effects: &[
            ("source", 17),
            ("hash", 38),
            ("hash", 65),
            ("eq", 86),
            ("hash", 113),
            ("eq", 134),
            ("done", 161),
        ],
        holes: &[],
    },
    Baseline {
        name: "collect_map_native_true_false",
        steps: 29,
        effects: &[("source", 5), ("done", 27)],
        holes: &[],
    },
    Baseline {
        name: "collect_map_native_true_true",
        steps: 32,
        effects: &[("source", 5), ("done", 30)],
        holes: &[],
    },
    Baseline {
        name: "collect_map_custom_false_false",
        steps: 244,
        effects: &[
            ("source", 18),
            ("next", 25),
            ("hash", 59),
            ("next", 77),
            ("hash", 111),
            ("eq", 132),
            ("next", 150),
            ("hash", 184),
            ("eq", 205),
            ("next", 219),
            ("done", 242),
        ],
        holes: &[],
    },
    Baseline {
        name: "collect_map_custom_false_true",
        steps: 247,
        effects: &[
            ("source", 18),
            ("next", 27),
            ("hash", 61),
            ("next", 79),
            ("hash", 113),
            ("eq", 134),
            ("next", 152),
            ("hash", 186),
            ("eq", 207),
            ("next", 221),
            ("done", 245),
        ],
        holes: &[],
    },
    Baseline {
        name: "collect_map_custom_true_false",
        steps: 38,
        effects: &[("source", 6), ("next", 13), ("done", 36)],
        holes: &[],
    },
    Baseline {
        name: "collect_map_custom_true_true",
        steps: 41,
        effects: &[("source", 6), ("next", 15), ("done", 39)],
        holes: &[],
    },
    Baseline {
        name: "collect_map_lazy_false_false",
        steps: 216,
        effects: &[
            ("source", 21),
            ("item", 40),
            ("hash", 55),
            ("item", 81),
            ("hash", 96),
            ("eq", 117),
            ("item", 143),
            ("hash", 158),
            ("eq", 179),
            ("done", 214),
        ],
        holes: &[],
    },
    Baseline {
        name: "collect_map_lazy_false_true",
        steps: 219,
        effects: &[
            ("source", 21),
            ("item", 42),
            ("hash", 57),
            ("item", 83),
            ("hash", 98),
            ("eq", 119),
            ("item", 145),
            ("hash", 160),
            ("eq", 181),
            ("done", 217),
        ],
        holes: &[],
    },
    Baseline {
        name: "collect_map_lazy_true_false",
        steps: 43,
        effects: &[("source", 9), ("done", 41)],
        holes: &[],
    },
    Baseline {
        name: "collect_map_lazy_true_true",
        steps: 46,
        effects: &[("source", 9), ("done", 44)],
        holes: &[],
    },
];
