// Observed at 66ea900 before native destination entries.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "direct_array_sequence",
        steps: 141,
        effects: &[
            ("source", 8),
            ("iter", 13),
            ("next", 23),
            ("next", 54),
            ("next", 85),
            ("next", 116),
            ("done", 139),
        ],
        holes: &[],
    },
    Baseline {
        name: "direct_array_view",
        steps: 56,
        effects: &[("source", 10), ("done", 54)],
        holes: &[],
    },
    Baseline {
        name: "direct_bag_sequence",
        steps: 148,
        effects: &[
            ("source", 8),
            ("construct", 13),
            ("iter", 17),
            ("next", 27),
            ("next", 58),
            ("next", 89),
            ("next", 120),
            ("done", 146),
        ],
        holes: &[],
    },
    Baseline {
        name: "direct_bag_view",
        steps: 63,
        effects: &[("source", 10), ("construct", 15), ("done", 61)],
        holes: &[],
    },
    Baseline {
        name: "direct_total_sequence",
        steps: 169,
        effects: &[
            ("source", 8),
            ("construct", 13),
            ("iter", 17),
            ("next", 29),
            ("destination", 58),
            ("next", 67),
            ("destination", 96),
            ("next", 105),
            ("destination", 134),
            ("next", 143),
            ("done", 167),
        ],
        holes: &[],
    },
    Baseline {
        name: "direct_total_view",
        steps: 84,
        effects: &[
            ("source", 10),
            ("construct", 15),
            ("destination", 34),
            ("destination", 47),
            ("destination", 60),
            ("done", 82),
        ],
        holes: &[],
    },
    Baseline {
        name: "direct_set_sequence",
        steps: 233,
        effects: &[
            ("source", 11),
            ("iter", 16),
            ("next", 26),
            ("hash", 56),
            ("next", 74),
            ("hash", 104),
            ("eq", 125),
            ("next", 143),
            ("hash", 173),
            ("eq", 194),
            ("next", 208),
            ("done", 231),
        ],
        holes: &[],
    },
    Baseline {
        name: "direct_set_view",
        steps: 148,
        effects: &[
            ("source", 13),
            ("hash", 32),
            ("hash", 55),
            ("eq", 76),
            ("hash", 99),
            ("eq", 120),
            ("done", 146),
        ],
        holes: &[],
    },
    Baseline {
        name: "direct_map_sequence",
        steps: 251,
        effects: &[
            ("source", 17),
            ("iter", 22),
            ("next", 32),
            ("hash", 66),
            ("next", 84),
            ("hash", 118),
            ("eq", 139),
            ("next", 157),
            ("hash", 191),
            ("eq", 212),
            ("next", 226),
            ("done", 249),
        ],
        holes: &[],
    },
    Baseline {
        name: "direct_map_view",
        steps: 166,
        effects: &[
            ("source", 19),
            ("hash", 42),
            ("hash", 69),
            ("eq", 90),
            ("hash", 117),
            ("eq", 138),
            ("done", 164),
        ],
        holes: &[],
    },
];
