// Observed at 66ea900 before native destination entries.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "fallible_option_array_empty_false",
        steps: 55,
        effects: &[("source", 7), ("done", 53)],
        holes: &[],
    },
    Baseline {
        name: "fallible_option_array_empty_true",
        steps: 71,
        effects: &[("source", 7), ("iter", 12), ("next", 22), ("done", 69)],
        holes: &[],
    },
    Baseline {
        name: "fallible_option_array_success_false",
        steps: 106,
        effects: &[("source", 13), ("done", 104)],
        holes: &[],
    },
    Baseline {
        name: "fallible_option_array_success_true",
        steps: 197,
        effects: &[
            ("source", 13),
            ("iter", 18),
            ("next", 28),
            ("next", 62),
            ("next", 96),
            ("next", 130),
            ("done", 195),
        ],
        holes: &[],
    },
    Baseline {
        name: "fallible_option_array_failure_false",
        steps: 48,
        effects: &[("source", 12), ("done", 46)],
        holes: &[],
    },
    Baseline {
        name: "fallible_option_array_failure_true",
        steps: 101,
        effects: &[
            ("source", 12),
            ("iter", 17),
            ("next", 27),
            ("next", 61),
            ("done", 99),
        ],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_array_empty_false",
        steps: 55,
        effects: &[("source", 7), ("done", 53)],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_array_empty_true",
        steps: 71,
        effects: &[("source", 7), ("iter", 12), ("next", 22), ("done", 69)],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_array_success_false",
        steps: 106,
        effects: &[("source", 13), ("done", 104)],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_array_success_true",
        steps: 197,
        effects: &[
            ("source", 13),
            ("iter", 18),
            ("next", 28),
            ("next", 62),
            ("next", 96),
            ("next", 130),
            ("done", 195),
        ],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_array_failure_false",
        steps: 50,
        effects: &[("source", 13), ("done", 48)],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_array_failure_true",
        steps: 103,
        effects: &[
            ("source", 13),
            ("iter", 18),
            ("next", 28),
            ("next", 62),
            ("done", 101),
        ],
        holes: &[],
    },
    Baseline {
        name: "fallible_option_bag_empty_false",
        steps: 62,
        effects: &[("source", 7), ("construct", 22), ("done", 60)],
        holes: &[],
    },
    Baseline {
        name: "fallible_option_bag_empty_true",
        steps: 78,
        effects: &[
            ("source", 7),
            ("iter", 12),
            ("next", 22),
            ("construct", 38),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "fallible_option_bag_success_false",
        steps: 113,
        effects: &[("source", 13), ("construct", 55), ("done", 111)],
        holes: &[],
    },
    Baseline {
        name: "fallible_option_bag_success_true",
        steps: 204,
        effects: &[
            ("source", 13),
            ("iter", 18),
            ("next", 28),
            ("next", 62),
            ("next", 96),
            ("next", 130),
            ("construct", 146),
            ("done", 202),
        ],
        holes: &[],
    },
    Baseline {
        name: "fallible_option_bag_failure_false",
        steps: 48,
        effects: &[("source", 12), ("done", 46)],
        holes: &[],
    },
    Baseline {
        name: "fallible_option_bag_failure_true",
        steps: 101,
        effects: &[
            ("source", 12),
            ("iter", 17),
            ("next", 27),
            ("next", 61),
            ("done", 99),
        ],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_bag_empty_false",
        steps: 62,
        effects: &[("source", 7), ("construct", 22), ("done", 60)],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_bag_empty_true",
        steps: 78,
        effects: &[
            ("source", 7),
            ("iter", 12),
            ("next", 22),
            ("construct", 38),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_bag_success_false",
        steps: 113,
        effects: &[("source", 13), ("construct", 55), ("done", 111)],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_bag_success_true",
        steps: 204,
        effects: &[
            ("source", 13),
            ("iter", 18),
            ("next", 28),
            ("next", 62),
            ("next", 96),
            ("next", 130),
            ("construct", 146),
            ("done", 202),
        ],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_bag_failure_false",
        steps: 50,
        effects: &[("source", 13), ("done", 48)],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_bag_failure_true",
        steps: 103,
        effects: &[
            ("source", 13),
            ("iter", 18),
            ("next", 28),
            ("next", 62),
            ("done", 101),
        ],
        holes: &[],
    },
    Baseline {
        name: "fallible_option_total_empty_false",
        steps: 62,
        effects: &[("source", 7), ("construct", 22), ("done", 60)],
        holes: &[],
    },
    Baseline {
        name: "fallible_option_total_empty_true",
        steps: 78,
        effects: &[
            ("source", 7),
            ("iter", 12),
            ("next", 22),
            ("construct", 38),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "fallible_option_total_success_false",
        steps: 134,
        effects: &[
            ("source", 13),
            ("construct", 55),
            ("destination", 71),
            ("destination", 84),
            ("destination", 97),
            ("done", 132),
        ],
        holes: &[],
    },
    Baseline {
        name: "fallible_option_total_success_true",
        steps: 225,
        effects: &[
            ("source", 13),
            ("iter", 18),
            ("next", 28),
            ("next", 62),
            ("next", 96),
            ("next", 130),
            ("construct", 146),
            ("destination", 162),
            ("destination", 175),
            ("destination", 188),
            ("done", 223),
        ],
        holes: &[],
    },
    Baseline {
        name: "fallible_option_total_failure_false",
        steps: 48,
        effects: &[("source", 12), ("done", 46)],
        holes: &[],
    },
    Baseline {
        name: "fallible_option_total_failure_true",
        steps: 101,
        effects: &[
            ("source", 12),
            ("iter", 17),
            ("next", 27),
            ("next", 61),
            ("done", 99),
        ],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_total_empty_false",
        steps: 62,
        effects: &[("source", 7), ("construct", 22), ("done", 60)],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_total_empty_true",
        steps: 78,
        effects: &[
            ("source", 7),
            ("iter", 12),
            ("next", 22),
            ("construct", 38),
            ("done", 76),
        ],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_total_success_false",
        steps: 134,
        effects: &[
            ("source", 13),
            ("construct", 55),
            ("destination", 71),
            ("destination", 84),
            ("destination", 97),
            ("done", 132),
        ],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_total_success_true",
        steps: 225,
        effects: &[
            ("source", 13),
            ("iter", 18),
            ("next", 28),
            ("next", 62),
            ("next", 96),
            ("next", 130),
            ("construct", 146),
            ("destination", 162),
            ("destination", 175),
            ("destination", 188),
            ("done", 223),
        ],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_total_failure_false",
        steps: 50,
        effects: &[("source", 13), ("done", 48)],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_total_failure_true",
        steps: 103,
        effects: &[
            ("source", 13),
            ("iter", 18),
            ("next", 28),
            ("next", 62),
            ("done", 101),
        ],
        holes: &[],
    },
    Baseline {
        name: "fallible_option_set_empty_false",
        steps: 55,
        effects: &[("source", 7), ("done", 53)],
        holes: &[],
    },
    Baseline {
        name: "fallible_option_set_empty_true",
        steps: 71,
        effects: &[("source", 7), ("iter", 12), ("next", 22), ("done", 69)],
        holes: &[],
    },
    Baseline {
        name: "fallible_option_set_success_false",
        steps: 198,
        effects: &[
            ("source", 16),
            ("hash", 69),
            ("hash", 92),
            ("eq", 113),
            ("hash", 136),
            ("eq", 157),
            ("done", 196),
        ],
        holes: &[],
    },
    Baseline {
        name: "fallible_option_set_success_true",
        steps: 289,
        effects: &[
            ("source", 16),
            ("iter", 21),
            ("next", 31),
            ("next", 65),
            ("next", 99),
            ("next", 133),
            ("hash", 160),
            ("hash", 183),
            ("eq", 204),
            ("hash", 227),
            ("eq", 248),
            ("done", 287),
        ],
        holes: &[],
    },
    Baseline {
        name: "fallible_option_set_failure_false",
        steps: 50,
        effects: &[("source", 14), ("done", 48)],
        holes: &[],
    },
    Baseline {
        name: "fallible_option_set_failure_true",
        steps: 103,
        effects: &[
            ("source", 14),
            ("iter", 19),
            ("next", 29),
            ("next", 63),
            ("done", 101),
        ],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_set_empty_false",
        steps: 55,
        effects: &[("source", 7), ("done", 53)],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_set_empty_true",
        steps: 71,
        effects: &[("source", 7), ("iter", 12), ("next", 22), ("done", 69)],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_set_success_false",
        steps: 198,
        effects: &[
            ("source", 16),
            ("hash", 69),
            ("hash", 92),
            ("eq", 113),
            ("hash", 136),
            ("eq", 157),
            ("done", 196),
        ],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_set_success_true",
        steps: 289,
        effects: &[
            ("source", 16),
            ("iter", 21),
            ("next", 31),
            ("next", 65),
            ("next", 99),
            ("next", 133),
            ("hash", 160),
            ("hash", 183),
            ("eq", 204),
            ("hash", 227),
            ("eq", 248),
            ("done", 287),
        ],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_set_failure_false",
        steps: 52,
        effects: &[("source", 15), ("done", 50)],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_set_failure_true",
        steps: 105,
        effects: &[
            ("source", 15),
            ("iter", 20),
            ("next", 30),
            ("next", 64),
            ("done", 103),
        ],
        holes: &[],
    },
    Baseline {
        name: "fallible_option_map_empty_false",
        steps: 55,
        effects: &[("source", 7), ("done", 53)],
        holes: &[],
    },
    Baseline {
        name: "fallible_option_map_empty_true",
        steps: 71,
        effects: &[("source", 7), ("iter", 12), ("next", 22), ("done", 69)],
        holes: &[],
    },
    Baseline {
        name: "fallible_option_map_success_false",
        steps: 216,
        effects: &[
            ("source", 22),
            ("hash", 79),
            ("hash", 106),
            ("eq", 127),
            ("hash", 154),
            ("eq", 175),
            ("done", 214),
        ],
        holes: &[],
    },
    Baseline {
        name: "fallible_option_map_success_true",
        steps: 307,
        effects: &[
            ("source", 22),
            ("iter", 27),
            ("next", 37),
            ("next", 71),
            ("next", 105),
            ("next", 139),
            ("hash", 170),
            ("hash", 197),
            ("eq", 218),
            ("hash", 245),
            ("eq", 266),
            ("done", 305),
        ],
        holes: &[],
    },
    Baseline {
        name: "fallible_option_map_failure_false",
        steps: 54,
        effects: &[("source", 18), ("done", 52)],
        holes: &[],
    },
    Baseline {
        name: "fallible_option_map_failure_true",
        steps: 107,
        effects: &[
            ("source", 18),
            ("iter", 23),
            ("next", 33),
            ("next", 67),
            ("done", 105),
        ],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_map_empty_false",
        steps: 55,
        effects: &[("source", 7), ("done", 53)],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_map_empty_true",
        steps: 71,
        effects: &[("source", 7), ("iter", 12), ("next", 22), ("done", 69)],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_map_success_false",
        steps: 216,
        effects: &[
            ("source", 22),
            ("hash", 79),
            ("hash", 106),
            ("eq", 127),
            ("hash", 154),
            ("eq", 175),
            ("done", 214),
        ],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_map_success_true",
        steps: 307,
        effects: &[
            ("source", 22),
            ("iter", 27),
            ("next", 37),
            ("next", 71),
            ("next", 105),
            ("next", 139),
            ("hash", 170),
            ("hash", 197),
            ("eq", 218),
            ("hash", 245),
            ("eq", 266),
            ("done", 305),
        ],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_map_failure_false",
        steps: 56,
        effects: &[("source", 19), ("done", 54)],
        holes: &[],
    },
    Baseline {
        name: "fallible_result_map_failure_true",
        steps: 109,
        effects: &[
            ("source", 19),
            ("iter", 24),
            ("next", 34),
            ("next", 68),
            ("done", 107),
        ],
        holes: &[],
    },
];
