// Observed at 66ea900 before native destination entries.
use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "partition_array_native_empty",
        steps: 70,
        effects: &[("source", 5), ("done", 68)],
        holes: &[],
    },
    Baseline {
        name: "partition_array_native_mixed",
        steps: 133,
        effects: &[
            ("source", 8),
            ("predicate", 27),
            ("predicate", 41),
            ("predicate", 55),
            ("done", 131),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_array_native_none",
        steps: 127,
        effects: &[
            ("source", 8),
            ("predicate", 27),
            ("predicate", 39),
            ("predicate", 51),
            ("done", 125),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_array_custom_empty",
        steps: 79,
        effects: &[("source", 6), ("next", 18), ("done", 77)],
        holes: &[],
    },
    Baseline {
        name: "partition_array_custom_mixed",
        steps: 217,
        effects: &[
            ("source", 9),
            ("next", 21),
            ("predicate", 50),
            ("next", 60),
            ("predicate", 89),
            ("next", 99),
            ("predicate", 128),
            ("next", 138),
            ("done", 215),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_array_custom_none",
        steps: 211,
        effects: &[
            ("source", 9),
            ("next", 21),
            ("predicate", 50),
            ("next", 58),
            ("predicate", 87),
            ("next", 95),
            ("predicate", 124),
            ("next", 132),
            ("done", 209),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_array_lazy_empty",
        steps: 84,
        effects: &[("source", 9), ("done", 82)],
        holes: &[],
    },
    Baseline {
        name: "partition_array_lazy_mixed",
        steps: 189,
        effects: &[
            ("source", 12),
            ("item", 36),
            ("predicate", 46),
            ("item", 64),
            ("predicate", 74),
            ("item", 92),
            ("predicate", 102),
            ("done", 187),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_array_lazy_none",
        steps: 183,
        effects: &[
            ("source", 12),
            ("item", 36),
            ("predicate", 46),
            ("item", 62),
            ("predicate", 72),
            ("item", 88),
            ("predicate", 98),
            ("done", 181),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_bag_native_empty",
        steps: 84,
        effects: &[
            ("source", 5),
            ("construct", 25),
            ("construct", 43),
            ("done", 82),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_bag_native_mixed",
        steps: 147,
        effects: &[
            ("source", 8),
            ("predicate", 27),
            ("predicate", 41),
            ("predicate", 55),
            ("construct", 70),
            ("construct", 100),
            ("done", 145),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_bag_native_none",
        steps: 141,
        effects: &[
            ("source", 8),
            ("predicate", 27),
            ("predicate", 39),
            ("predicate", 51),
            ("construct", 64),
            ("construct", 82),
            ("done", 139),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_bag_custom_empty",
        steps: 93,
        effects: &[
            ("source", 6),
            ("next", 18),
            ("construct", 34),
            ("construct", 52),
            ("done", 91),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_bag_custom_mixed",
        steps: 231,
        effects: &[
            ("source", 9),
            ("next", 21),
            ("predicate", 50),
            ("next", 60),
            ("predicate", 89),
            ("next", 99),
            ("predicate", 128),
            ("next", 138),
            ("construct", 154),
            ("construct", 184),
            ("done", 229),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_bag_custom_none",
        steps: 225,
        effects: &[
            ("source", 9),
            ("next", 21),
            ("predicate", 50),
            ("next", 58),
            ("predicate", 87),
            ("next", 95),
            ("predicate", 124),
            ("next", 132),
            ("construct", 148),
            ("construct", 166),
            ("done", 223),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_bag_lazy_empty",
        steps: 98,
        effects: &[
            ("source", 9),
            ("construct", 39),
            ("construct", 57),
            ("done", 96),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_bag_lazy_mixed",
        steps: 203,
        effects: &[
            ("source", 12),
            ("item", 36),
            ("predicate", 46),
            ("item", 64),
            ("predicate", 74),
            ("item", 92),
            ("predicate", 102),
            ("construct", 126),
            ("construct", 156),
            ("done", 201),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_bag_lazy_none",
        steps: 197,
        effects: &[
            ("source", 12),
            ("item", 36),
            ("predicate", 46),
            ("item", 62),
            ("predicate", 72),
            ("item", 88),
            ("predicate", 98),
            ("construct", 120),
            ("construct", 138),
            ("done", 195),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_total_native_empty",
        steps: 84,
        effects: &[
            ("source", 5),
            ("construct", 25),
            ("construct", 44),
            ("done", 82),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_total_native_mixed",
        steps: 168,
        effects: &[
            ("source", 8),
            ("predicate", 27),
            ("predicate", 41),
            ("predicate", 55),
            ("construct", 70),
            ("destination", 86),
            ("destination", 99),
            ("construct", 115),
            ("destination", 131),
            ("done", 166),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_total_native_none",
        steps: 162,
        effects: &[
            ("source", 8),
            ("predicate", 27),
            ("predicate", 39),
            ("predicate", 51),
            ("construct", 64),
            ("construct", 83),
            ("destination", 99),
            ("destination", 112),
            ("destination", 125),
            ("done", 160),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_total_custom_empty",
        steps: 93,
        effects: &[
            ("source", 6),
            ("next", 18),
            ("construct", 34),
            ("construct", 53),
            ("done", 91),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_total_custom_mixed",
        steps: 252,
        effects: &[
            ("source", 9),
            ("next", 21),
            ("predicate", 50),
            ("next", 60),
            ("predicate", 89),
            ("next", 99),
            ("predicate", 128),
            ("next", 138),
            ("construct", 154),
            ("destination", 170),
            ("destination", 183),
            ("construct", 199),
            ("destination", 215),
            ("done", 250),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_total_custom_none",
        steps: 246,
        effects: &[
            ("source", 9),
            ("next", 21),
            ("predicate", 50),
            ("next", 58),
            ("predicate", 87),
            ("next", 95),
            ("predicate", 124),
            ("next", 132),
            ("construct", 148),
            ("construct", 167),
            ("destination", 183),
            ("destination", 196),
            ("destination", 209),
            ("done", 244),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_total_lazy_empty",
        steps: 98,
        effects: &[
            ("source", 9),
            ("construct", 39),
            ("construct", 58),
            ("done", 96),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_total_lazy_mixed",
        steps: 224,
        effects: &[
            ("source", 12),
            ("item", 36),
            ("predicate", 46),
            ("item", 64),
            ("predicate", 74),
            ("item", 92),
            ("predicate", 102),
            ("construct", 126),
            ("destination", 142),
            ("destination", 155),
            ("construct", 171),
            ("destination", 187),
            ("done", 222),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_total_lazy_none",
        steps: 218,
        effects: &[
            ("source", 12),
            ("item", 36),
            ("predicate", 46),
            ("item", 62),
            ("predicate", 72),
            ("item", 88),
            ("predicate", 98),
            ("construct", 120),
            ("construct", 139),
            ("destination", 155),
            ("destination", 168),
            ("destination", 181),
            ("done", 216),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_set_native_empty",
        steps: 70,
        effects: &[("source", 5), ("done", 68)],
        holes: &[],
    },
    Baseline {
        name: "partition_set_native_mixed",
        steps: 207,
        effects: &[
            ("source", 11),
            ("predicate", 30),
            ("predicate", 45),
            ("predicate", 60),
            ("hash", 87),
            ("hash", 110),
            ("eq", 131),
            ("hash", 162),
            ("done", 205),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_set_native_none",
        steps: 219,
        effects: &[
            ("source", 11),
            ("predicate", 30),
            ("predicate", 42),
            ("predicate", 54),
            ("hash", 90),
            ("hash", 113),
            ("eq", 134),
            ("hash", 157),
            ("eq", 178),
            ("done", 217),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_set_custom_empty",
        steps: 79,
        effects: &[("source", 6), ("next", 18), ("done", 77)],
        holes: &[],
    },
    Baseline {
        name: "partition_set_custom_mixed",
        steps: 291,
        effects: &[
            ("source", 12),
            ("next", 24),
            ("predicate", 53),
            ("next", 64),
            ("predicate", 93),
            ("next", 104),
            ("predicate", 133),
            ("next", 144),
            ("hash", 171),
            ("hash", 194),
            ("eq", 215),
            ("hash", 246),
            ("done", 289),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_set_custom_none",
        steps: 303,
        effects: &[
            ("source", 12),
            ("next", 24),
            ("predicate", 53),
            ("next", 61),
            ("predicate", 90),
            ("next", 98),
            ("predicate", 127),
            ("next", 135),
            ("hash", 174),
            ("hash", 197),
            ("eq", 218),
            ("hash", 241),
            ("eq", 262),
            ("done", 301),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_set_lazy_empty",
        steps: 84,
        effects: &[("source", 9), ("done", 82)],
        holes: &[],
    },
    Baseline {
        name: "partition_set_lazy_mixed",
        steps: 263,
        effects: &[
            ("source", 15),
            ("item", 39),
            ("predicate", 49),
            ("item", 68),
            ("predicate", 78),
            ("item", 97),
            ("predicate", 107),
            ("hash", 143),
            ("hash", 166),
            ("eq", 187),
            ("hash", 218),
            ("done", 261),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_set_lazy_none",
        steps: 275,
        effects: &[
            ("source", 15),
            ("item", 39),
            ("predicate", 49),
            ("item", 65),
            ("predicate", 75),
            ("item", 91),
            ("predicate", 101),
            ("hash", 146),
            ("hash", 169),
            ("eq", 190),
            ("hash", 213),
            ("eq", 234),
            ("done", 273),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_map_native_empty",
        steps: 70,
        effects: &[("source", 5), ("done", 68)],
        holes: &[],
    },
    Baseline {
        name: "partition_map_native_mixed",
        steps: 231,
        effects: &[
            ("source", 17),
            ("predicate", 36),
            ("predicate", 53),
            ("predicate", 70),
            ("hash", 103),
            ("hash", 130),
            ("eq", 151),
            ("hash", 186),
            ("done", 229),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_map_native_none",
        steps: 237,
        effects: &[
            ("source", 17),
            ("predicate", 36),
            ("predicate", 48),
            ("predicate", 60),
            ("hash", 100),
            ("hash", 127),
            ("eq", 148),
            ("hash", 175),
            ("eq", 196),
            ("done", 235),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_map_custom_empty",
        steps: 79,
        effects: &[("source", 6), ("next", 18), ("done", 77)],
        holes: &[],
    },
    Baseline {
        name: "partition_map_custom_mixed",
        steps: 315,
        effects: &[
            ("source", 18),
            ("next", 30),
            ("predicate", 59),
            ("next", 72),
            ("predicate", 101),
            ("next", 114),
            ("predicate", 143),
            ("next", 156),
            ("hash", 187),
            ("hash", 214),
            ("eq", 235),
            ("hash", 270),
            ("done", 313),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_map_custom_none",
        steps: 321,
        effects: &[
            ("source", 18),
            ("next", 30),
            ("predicate", 59),
            ("next", 67),
            ("predicate", 96),
            ("next", 104),
            ("predicate", 133),
            ("next", 141),
            ("hash", 184),
            ("hash", 211),
            ("eq", 232),
            ("hash", 259),
            ("eq", 280),
            ("done", 319),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_map_lazy_empty",
        steps: 84,
        effects: &[("source", 9), ("done", 82)],
        holes: &[],
    },
    Baseline {
        name: "partition_map_lazy_mixed",
        steps: 287,
        effects: &[
            ("source", 21),
            ("item", 45),
            ("predicate", 55),
            ("item", 76),
            ("predicate", 86),
            ("item", 107),
            ("predicate", 117),
            ("hash", 159),
            ("hash", 186),
            ("eq", 207),
            ("hash", 242),
            ("done", 285),
        ],
        holes: &[],
    },
    Baseline {
        name: "partition_map_lazy_none",
        steps: 293,
        effects: &[
            ("source", 21),
            ("item", 45),
            ("predicate", 55),
            ("item", 71),
            ("predicate", 81),
            ("item", 97),
            ("predicate", 107),
            ("hash", 156),
            ("hash", 183),
            ("eq", 204),
            ("hash", 231),
            ("eq", 252),
            ("done", 291),
        ],
        holes: &[],
    },
];
