use kagari_common::Span;

use crate::kind::SyntaxKind;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TokenKind {
    Whitespace,
    FnKw,
    StructKw,
    EnumKw,
    LetKw,
    ReturnKw,
    IfKw,
    ElseKw,
    MatchKw,
    WhileKw,
    LoopKw,
    BreakKw,
    ContinueKw,
    TrueKw,
    FalseKw,
    Ident,
    Number,
    Float,
    String,
    LParen,
    RParen,
    LBracket,
    RBracket,
    LBrace,
    RBrace,
    Comma,
    Colon,
    Semi,
    Dot,
    Eq,
    Plus,
    Minus,
    Star,
    Slash,
    Bang,
    EqEq,
    NotEq,
    Lt,
    Gt,
    Le,
    Ge,
    AmpAmp,
    PipePipe,
    Arrow,
    FatArrow,
    Eof,
    Unknown,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}

impl TokenKind {
    pub fn is_trivia(&self) -> bool {
        matches!(self, Self::Whitespace)
    }

    pub fn to_syntax_kind(&self) -> SyntaxKind {
        match self {
            Self::Whitespace => SyntaxKind::Whitespace,
            Self::FnKw => SyntaxKind::FnKw,
            Self::StructKw => SyntaxKind::StructKw,
            Self::EnumKw => SyntaxKind::EnumKw,
            Self::LetKw => SyntaxKind::LetKw,
            Self::ReturnKw => SyntaxKind::ReturnKw,
            Self::IfKw => SyntaxKind::IfKw,
            Self::ElseKw => SyntaxKind::ElseKw,
            Self::MatchKw => SyntaxKind::MatchKw,
            Self::WhileKw => SyntaxKind::WhileKw,
            Self::LoopKw => SyntaxKind::LoopKw,
            Self::BreakKw => SyntaxKind::BreakKw,
            Self::ContinueKw => SyntaxKind::ContinueKw,
            Self::TrueKw => SyntaxKind::TrueKw,
            Self::FalseKw => SyntaxKind::FalseKw,
            Self::Ident => SyntaxKind::Ident,
            Self::Number => SyntaxKind::Number,
            Self::Float => SyntaxKind::Float,
            Self::String => SyntaxKind::String,
            Self::LParen => SyntaxKind::LParen,
            Self::RParen => SyntaxKind::RParen,
            Self::LBracket => SyntaxKind::LBracket,
            Self::RBracket => SyntaxKind::RBracket,
            Self::LBrace => SyntaxKind::LBrace,
            Self::RBrace => SyntaxKind::RBrace,
            Self::Comma => SyntaxKind::Comma,
            Self::Colon => SyntaxKind::Colon,
            Self::Semi => SyntaxKind::Semi,
            Self::Dot => SyntaxKind::Dot,
            Self::Eq => SyntaxKind::Eq,
            Self::Plus => SyntaxKind::Plus,
            Self::Minus => SyntaxKind::Minus,
            Self::Star => SyntaxKind::Star,
            Self::Slash => SyntaxKind::Slash,
            Self::Bang => SyntaxKind::Bang,
            Self::EqEq => SyntaxKind::EqEq,
            Self::NotEq => SyntaxKind::NotEq,
            Self::Lt => SyntaxKind::Lt,
            Self::Gt => SyntaxKind::Gt,
            Self::Le => SyntaxKind::Le,
            Self::Ge => SyntaxKind::Ge,
            Self::AmpAmp => SyntaxKind::AmpAmp,
            Self::PipePipe => SyntaxKind::PipePipe,
            Self::Arrow => SyntaxKind::Arrow,
            Self::FatArrow => SyntaxKind::FatArrow,
            Self::Eof => SyntaxKind::Eof,
            Self::Unknown => SyntaxKind::Unknown,
        }
    }
}
