use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "contains_scalar_empty_direct",
        steps: 38,
        effects: &[
            ("receiver", 11),
            ("query", 17),
            ("committed", 28),
            ("done", 36),
        ],
        holes: &[],
    },
    Baseline {
        name: "contains_scalar_empty_generic",
        steps: 47,
        effects: &[
            ("receiver", 12),
            ("query", 18),
            ("committed", 37),
            ("done", 45),
        ],
        holes: &[],
    },
    Baseline {
        name: "contains_scalar_empty_dynamic",
        steps: 45,
        effects: &[
            ("receiver", 14),
            ("query", 20),
            ("committed", 35),
            ("done", 43),
        ],
        holes: &[],
    },
    Baseline {
        name: "contains_scalar_present_direct",
        steps: 53,
        effects: &[
            ("receiver", 26),
            ("query", 32),
            ("committed", 43),
            ("done", 51),
        ],
        holes: &[],
    },
    Baseline {
        name: "contains_scalar_present_generic",
        steps: 62,
        effects: &[
            ("receiver", 27),
            ("query", 33),
            ("committed", 52),
            ("done", 60),
        ],
        holes: &[],
    },
    Baseline {
        name: "contains_scalar_present_dynamic",
        steps: 60,
        effects: &[
            ("receiver", 29),
            ("query", 35),
            ("committed", 50),
            ("done", 58),
        ],
        holes: &[],
    },
    Baseline {
        name: "contains_scalar_absent_direct",
        steps: 53,
        effects: &[
            ("receiver", 26),
            ("query", 32),
            ("committed", 43),
            ("done", 51),
        ],
        holes: &[],
    },
    Baseline {
        name: "contains_scalar_absent_generic",
        steps: 62,
        effects: &[
            ("receiver", 27),
            ("query", 33),
            ("committed", 52),
            ("done", 60),
        ],
        holes: &[],
    },
    Baseline {
        name: "contains_scalar_absent_dynamic",
        steps: 60,
        effects: &[
            ("receiver", 29),
            ("query", 35),
            ("committed", 50),
            ("done", 58),
        ],
        holes: &[],
    },
    Baseline {
        name: "contains_nominal_empty_direct",
        steps: 64,
        effects: &[
            ("receiver", 17),
            ("query", 25),
            ("hash", 31),
            ("committed", 54),
            ("done", 62),
        ],
        holes: &[],
    },
    Baseline {
        name: "contains_nominal_empty_generic",
        steps: 73,
        effects: &[
            ("receiver", 18),
            ("query", 26),
            ("hash", 38),
            ("committed", 63),
            ("done", 71),
        ],
        holes: &[],
    },
    Baseline {
        name: "contains_nominal_empty_dynamic",
        steps: 71,
        effects: &[
            ("receiver", 20),
            ("query", 28),
            ("hash", 37),
            ("committed", 61),
            ("done", 69),
        ],
        holes: &[],
    },
    Baseline {
        name: "contains_nominal_present_direct",
        steps: 285,
        effects: &[
            ("hash", 21),
            ("hash", 44),
            ("eq", 66),
            ("hash", 93),
            ("eq", 115),
            ("eq", 141),
            ("receiver", 164),
            ("query", 172),
            ("hash", 178),
            ("eq", 200),
            ("eq", 226),
            ("eq", 252),
            ("committed", 275),
            ("done", 283),
        ],
        holes: &[],
    },
    Baseline {
        name: "contains_nominal_present_generic",
        steps: 294,
        effects: &[
            ("hash", 21),
            ("hash", 44),
            ("eq", 66),
            ("hash", 93),
            ("eq", 115),
            ("eq", 141),
            ("receiver", 165),
            ("query", 173),
            ("hash", 185),
            ("eq", 207),
            ("eq", 233),
            ("eq", 259),
            ("committed", 284),
            ("done", 292),
        ],
        holes: &[],
    },
    Baseline {
        name: "contains_nominal_present_dynamic",
        steps: 292,
        effects: &[
            ("hash", 21),
            ("hash", 44),
            ("eq", 66),
            ("hash", 93),
            ("eq", 115),
            ("eq", 141),
            ("receiver", 167),
            ("query", 175),
            ("hash", 184),
            ("eq", 206),
            ("eq", 232),
            ("eq", 258),
            ("committed", 282),
            ("done", 290),
        ],
        holes: &[],
    },
    Baseline {
        name: "contains_nominal_absent_direct",
        steps: 289,
        effects: &[
            ("hash", 21),
            ("hash", 44),
            ("eq", 66),
            ("hash", 93),
            ("eq", 115),
            ("eq", 141),
            ("receiver", 164),
            ("query", 172),
            ("hash", 178),
            ("eq", 200),
            ("eq", 226),
            ("eq", 252),
            ("committed", 279),
            ("done", 287),
        ],
        holes: &[],
    },
    Baseline {
        name: "contains_nominal_absent_generic",
        steps: 298,
        effects: &[
            ("hash", 21),
            ("hash", 44),
            ("eq", 66),
            ("hash", 93),
            ("eq", 115),
            ("eq", 141),
            ("receiver", 165),
            ("query", 173),
            ("hash", 185),
            ("eq", 207),
            ("eq", 233),
            ("eq", 259),
            ("committed", 288),
            ("done", 296),
        ],
        holes: &[],
    },
    Baseline {
        name: "contains_nominal_absent_dynamic",
        steps: 296,
        effects: &[
            ("hash", 21),
            ("hash", 44),
            ("eq", 66),
            ("hash", 93),
            ("eq", 115),
            ("eq", 141),
            ("receiver", 167),
            ("query", 175),
            ("hash", 184),
            ("eq", 206),
            ("eq", 232),
            ("eq", 258),
            ("committed", 286),
            ("done", 294),
        ],
        holes: &[],
    },
    Baseline {
        name: "contains_tuple_empty_direct",
        steps: 82,
        effects: &[
            ("receiver", 23),
            ("query", 33),
            ("hash", 45),
            ("committed", 72),
            ("done", 80),
        ],
        holes: &[],
    },
    Baseline {
        name: "contains_tuple_present_direct",
        steps: 419,
        effects: &[
            ("hash", 33),
            ("hash", 66),
            ("eq", 101),
            ("hash", 139),
            ("eq", 174),
            ("eq", 214),
            ("receiver", 242),
            ("query", 252),
            ("hash", 264),
            ("eq", 299),
            ("eq", 339),
            ("eq", 379),
            ("committed", 409),
            ("done", 417),
        ],
        holes: &[],
    },
    Baseline {
        name: "contains_tuple_absent_direct",
        steps: 421,
        effects: &[
            ("hash", 33),
            ("hash", 66),
            ("eq", 101),
            ("hash", 139),
            ("eq", 174),
            ("eq", 214),
            ("receiver", 242),
            ("query", 252),
            ("hash", 264),
            ("eq", 299),
            ("eq", 339),
            ("eq", 379),
            ("committed", 411),
            ("done", 419),
        ],
        holes: &[],
    },
    Baseline {
        name: "contains_option_empty_direct",
        steps: 79,
        effects: &[
            ("receiver", 20),
            ("query", 29),
            ("hash", 41),
            ("committed", 69),
            ("done", 77),
        ],
        holes: &[],
    },
    Baseline {
        name: "contains_option_present_direct",
        steps: 429,
        effects: &[
            ("hash", 30),
            ("hash", 64),
            ("eq", 100),
            ("hash", 140),
            ("eq", 176),
            ("eq", 218),
            ("receiver", 248),
            ("query", 257),
            ("hash", 269),
            ("eq", 305),
            ("eq", 347),
            ("eq", 389),
            ("committed", 419),
            ("done", 427),
        ],
        holes: &[],
    },
    Baseline {
        name: "contains_option_absent_direct",
        steps: 433,
        effects: &[
            ("hash", 30),
            ("hash", 64),
            ("eq", 100),
            ("hash", 140),
            ("eq", 176),
            ("eq", 218),
            ("receiver", 248),
            ("query", 257),
            ("hash", 269),
            ("eq", 305),
            ("eq", 347),
            ("eq", 389),
            ("committed", 423),
            ("done", 431),
        ],
        holes: &[],
    },
    Baseline {
        name: "contains_choice_empty_direct",
        steps: 81,
        effects: &[
            ("receiver", 20),
            ("query", 29),
            ("hash", 43),
            ("committed", 71),
            ("done", 79),
        ],
        holes: &[],
    },
    Baseline {
        name: "contains_choice_present_direct",
        steps: 449,
        effects: &[
            ("hash", 32),
            ("hash", 68),
            ("eq", 106),
            ("hash", 148),
            ("eq", 186),
            ("eq", 230),
            ("receiver", 260),
            ("query", 269),
            ("hash", 283),
            ("eq", 321),
            ("eq", 365),
            ("eq", 409),
            ("committed", 439),
            ("done", 447),
        ],
        holes: &[],
    },
    Baseline {
        name: "contains_choice_absent_direct",
        steps: 453,
        effects: &[
            ("hash", 32),
            ("hash", 68),
            ("eq", 106),
            ("hash", 148),
            ("eq", 186),
            ("eq", 230),
            ("receiver", 260),
            ("query", 269),
            ("hash", 283),
            ("eq", 321),
            ("eq", 365),
            ("eq", 409),
            ("committed", 443),
            ("done", 451),
        ],
        holes: &[],
    },
    Baseline {
        name: "contains_identity_empty_direct",
        steps: 42,
        effects: &[
            ("receiver", 14),
            ("query", 21),
            ("committed", 32),
            ("done", 40),
        ],
        holes: &[],
    },
    Baseline {
        name: "contains_identity_present_direct",
        steps: 58,
        effects: &[
            ("receiver", 29),
            ("query", 37),
            ("committed", 48),
            ("done", 56),
        ],
        holes: &[],
    },
    Baseline {
        name: "contains_identity_absent_direct",
        steps: 57,
        effects: &[
            ("receiver", 29),
            ("query", 36),
            ("committed", 47),
            ("done", 55),
        ],
        holes: &[],
    },
];
