use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "get_scalar_empty_direct",
        steps: 38,
        effects: &[
            ("receiver", 11),
            ("query", 17),
            ("committed", 28),
            ("done", 36),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_scalar_empty_generic",
        steps: 47,
        effects: &[
            ("receiver", 12),
            ("query", 18),
            ("committed", 37),
            ("done", 45),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_scalar_empty_dynamic",
        steps: 45,
        effects: &[
            ("receiver", 14),
            ("query", 20),
            ("committed", 35),
            ("done", 43),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_scalar_present_direct",
        steps: 57,
        effects: &[
            ("receiver", 29),
            ("query", 35),
            ("committed", 47),
            ("done", 55),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_scalar_present_generic",
        steps: 66,
        effects: &[
            ("receiver", 30),
            ("query", 36),
            ("committed", 56),
            ("done", 64),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_scalar_present_dynamic",
        steps: 64,
        effects: &[
            ("receiver", 32),
            ("query", 38),
            ("committed", 54),
            ("done", 62),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_scalar_absent_direct",
        steps: 56,
        effects: &[
            ("receiver", 29),
            ("query", 35),
            ("committed", 46),
            ("done", 54),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_scalar_absent_generic",
        steps: 65,
        effects: &[
            ("receiver", 30),
            ("query", 36),
            ("committed", 55),
            ("done", 63),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_scalar_absent_dynamic",
        steps: 63,
        effects: &[
            ("receiver", 32),
            ("query", 38),
            ("committed", 53),
            ("done", 61),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_nominal_empty_direct",
        steps: 64,
        effects: &[
            ("receiver", 17),
            ("query", 25),
            ("hash", 31),
            ("committed", 54),
            ("done", 62),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_nominal_empty_generic",
        steps: 73,
        effects: &[
            ("receiver", 18),
            ("query", 26),
            ("hash", 38),
            ("committed", 63),
            ("done", 71),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_nominal_empty_dynamic",
        steps: 71,
        effects: &[
            ("receiver", 20),
            ("query", 28),
            ("hash", 37),
            ("committed", 61),
            ("done", 69),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_nominal_present_direct",
        steps: 289,
        effects: &[
            ("hash", 22),
            ("hash", 46),
            ("eq", 68),
            ("hash", 96),
            ("eq", 118),
            ("eq", 144),
            ("receiver", 167),
            ("query", 175),
            ("hash", 181),
            ("eq", 203),
            ("eq", 229),
            ("eq", 255),
            ("committed", 279),
            ("done", 287),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_nominal_present_generic",
        steps: 298,
        effects: &[
            ("hash", 22),
            ("hash", 46),
            ("eq", 68),
            ("hash", 96),
            ("eq", 118),
            ("eq", 144),
            ("receiver", 168),
            ("query", 176),
            ("hash", 188),
            ("eq", 210),
            ("eq", 236),
            ("eq", 262),
            ("committed", 288),
            ("done", 296),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_nominal_present_dynamic",
        steps: 296,
        effects: &[
            ("hash", 22),
            ("hash", 46),
            ("eq", 68),
            ("hash", 96),
            ("eq", 118),
            ("eq", 144),
            ("receiver", 170),
            ("query", 178),
            ("hash", 187),
            ("eq", 209),
            ("eq", 235),
            ("eq", 261),
            ("committed", 286),
            ("done", 294),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_nominal_absent_direct",
        steps: 292,
        effects: &[
            ("hash", 22),
            ("hash", 46),
            ("eq", 68),
            ("hash", 96),
            ("eq", 118),
            ("eq", 144),
            ("receiver", 167),
            ("query", 175),
            ("hash", 181),
            ("eq", 203),
            ("eq", 229),
            ("eq", 255),
            ("committed", 282),
            ("done", 290),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_nominal_absent_generic",
        steps: 301,
        effects: &[
            ("hash", 22),
            ("hash", 46),
            ("eq", 68),
            ("hash", 96),
            ("eq", 118),
            ("eq", 144),
            ("receiver", 168),
            ("query", 176),
            ("hash", 188),
            ("eq", 210),
            ("eq", 236),
            ("eq", 262),
            ("committed", 291),
            ("done", 299),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_nominal_absent_dynamic",
        steps: 299,
        effects: &[
            ("hash", 22),
            ("hash", 46),
            ("eq", 68),
            ("hash", 96),
            ("eq", 118),
            ("eq", 144),
            ("receiver", 170),
            ("query", 178),
            ("hash", 187),
            ("eq", 209),
            ("eq", 235),
            ("eq", 261),
            ("committed", 289),
            ("done", 297),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_tuple_empty_direct",
        steps: 82,
        effects: &[
            ("receiver", 23),
            ("query", 33),
            ("hash", 45),
            ("committed", 72),
            ("done", 80),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_tuple_present_direct",
        steps: 423,
        effects: &[
            ("hash", 34),
            ("hash", 68),
            ("eq", 103),
            ("hash", 142),
            ("eq", 177),
            ("eq", 217),
            ("receiver", 245),
            ("query", 255),
            ("hash", 267),
            ("eq", 302),
            ("eq", 342),
            ("eq", 382),
            ("committed", 413),
            ("done", 421),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_tuple_absent_direct",
        steps: 424,
        effects: &[
            ("hash", 34),
            ("hash", 68),
            ("eq", 103),
            ("hash", 142),
            ("eq", 177),
            ("eq", 217),
            ("receiver", 245),
            ("query", 255),
            ("hash", 267),
            ("eq", 302),
            ("eq", 342),
            ("eq", 382),
            ("committed", 414),
            ("done", 422),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_option_empty_direct",
        steps: 79,
        effects: &[
            ("receiver", 20),
            ("query", 29),
            ("hash", 41),
            ("committed", 69),
            ("done", 77),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_option_present_direct",
        steps: 433,
        effects: &[
            ("hash", 31),
            ("hash", 66),
            ("eq", 102),
            ("hash", 143),
            ("eq", 179),
            ("eq", 221),
            ("receiver", 251),
            ("query", 260),
            ("hash", 272),
            ("eq", 308),
            ("eq", 350),
            ("eq", 392),
            ("committed", 423),
            ("done", 431),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_option_absent_direct",
        steps: 436,
        effects: &[
            ("hash", 31),
            ("hash", 66),
            ("eq", 102),
            ("hash", 143),
            ("eq", 179),
            ("eq", 221),
            ("receiver", 251),
            ("query", 260),
            ("hash", 272),
            ("eq", 308),
            ("eq", 350),
            ("eq", 392),
            ("committed", 426),
            ("done", 434),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_choice_empty_direct",
        steps: 81,
        effects: &[
            ("receiver", 20),
            ("query", 29),
            ("hash", 43),
            ("committed", 71),
            ("done", 79),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_choice_present_direct",
        steps: 453,
        effects: &[
            ("hash", 33),
            ("hash", 70),
            ("eq", 108),
            ("hash", 151),
            ("eq", 189),
            ("eq", 233),
            ("receiver", 263),
            ("query", 272),
            ("hash", 286),
            ("eq", 324),
            ("eq", 368),
            ("eq", 412),
            ("committed", 443),
            ("done", 451),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_choice_absent_direct",
        steps: 456,
        effects: &[
            ("hash", 33),
            ("hash", 70),
            ("eq", 108),
            ("hash", 151),
            ("eq", 189),
            ("eq", 233),
            ("receiver", 263),
            ("query", 272),
            ("hash", 286),
            ("eq", 324),
            ("eq", 368),
            ("eq", 412),
            ("committed", 446),
            ("done", 454),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_identity_empty_direct",
        steps: 42,
        effects: &[
            ("receiver", 14),
            ("query", 21),
            ("committed", 32),
            ("done", 40),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_identity_present_direct",
        steps: 62,
        effects: &[
            ("receiver", 32),
            ("query", 40),
            ("committed", 52),
            ("done", 60),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_identity_absent_direct",
        steps: 60,
        effects: &[
            ("receiver", 32),
            ("query", 39),
            ("committed", 50),
            ("done", 58),
        ],
        holes: &[],
    },
];
