use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "get_or_insert_with_scalar_empty_direct",
        steps: 57,
        effects: &[
            ("receiver", 11),
            ("query", 17),
            ("callback", 23),
            ("factory", 32),
            ("committed", 47),
            ("done", 55),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_or_insert_with_scalar_empty_generic",
        steps: 68,
        effects: &[
            ("receiver", 12),
            ("query", 18),
            ("callback", 24),
            ("factory", 41),
            ("committed", 58),
            ("done", 66),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_or_insert_with_scalar_empty_dynamic",
        steps: 65,
        effects: &[
            ("receiver", 14),
            ("query", 20),
            ("callback", 26),
            ("factory", 39),
            ("committed", 55),
            ("done", 63),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_or_insert_with_scalar_present_direct",
        steps: 69,
        effects: &[
            ("receiver", 29),
            ("query", 35),
            ("callback", 41),
            ("committed", 59),
            ("done", 67),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_or_insert_with_scalar_present_generic",
        steps: 80,
        effects: &[
            ("receiver", 30),
            ("query", 36),
            ("callback", 42),
            ("committed", 70),
            ("done", 78),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_or_insert_with_scalar_present_dynamic",
        steps: 77,
        effects: &[
            ("receiver", 32),
            ("query", 38),
            ("callback", 44),
            ("committed", 67),
            ("done", 75),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_or_insert_with_scalar_absent_direct",
        steps: 75,
        effects: &[
            ("receiver", 29),
            ("query", 35),
            ("callback", 41),
            ("factory", 50),
            ("committed", 65),
            ("done", 73),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_or_insert_with_scalar_absent_generic",
        steps: 86,
        effects: &[
            ("receiver", 30),
            ("query", 36),
            ("callback", 42),
            ("factory", 59),
            ("committed", 76),
            ("done", 84),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_or_insert_with_scalar_absent_dynamic",
        steps: 83,
        effects: &[
            ("receiver", 32),
            ("query", 38),
            ("callback", 44),
            ("factory", 57),
            ("committed", 73),
            ("done", 81),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_or_insert_with_nominal_empty_direct",
        steps: 101,
        effects: &[
            ("receiver", 17),
            ("query", 25),
            ("callback", 31),
            ("hash", 38),
            ("factory", 58),
            ("hash", 65),
            ("committed", 91),
            ("done", 99),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_or_insert_with_nominal_empty_generic",
        steps: 112,
        effects: &[
            ("receiver", 18),
            ("query", 26),
            ("callback", 32),
            ("hash", 47),
            ("factory", 67),
            ("hash", 74),
            ("committed", 102),
            ("done", 110),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_or_insert_with_nominal_empty_dynamic",
        steps: 109,
        effects: &[
            ("receiver", 20),
            ("query", 28),
            ("callback", 34),
            ("hash", 45),
            ("factory", 65),
            ("hash", 72),
            ("committed", 99),
            ("done", 107),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_or_insert_with_nominal_present_direct",
        steps: 301,
        effects: &[
            ("hash", 22),
            ("hash", 46),
            ("eq", 68),
            ("hash", 96),
            ("eq", 118),
            ("eq", 144),
            ("receiver", 167),
            ("query", 175),
            ("callback", 181),
            ("hash", 188),
            ("eq", 210),
            ("eq", 236),
            ("eq", 262),
            ("committed", 291),
            ("done", 299),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_or_insert_with_nominal_present_generic",
        steps: 312,
        effects: &[
            ("hash", 22),
            ("hash", 46),
            ("eq", 68),
            ("hash", 96),
            ("eq", 118),
            ("eq", 144),
            ("receiver", 168),
            ("query", 176),
            ("callback", 182),
            ("hash", 197),
            ("eq", 219),
            ("eq", 245),
            ("eq", 271),
            ("committed", 302),
            ("done", 310),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_or_insert_with_nominal_present_dynamic",
        steps: 309,
        effects: &[
            ("hash", 22),
            ("hash", 46),
            ("eq", 68),
            ("hash", 96),
            ("eq", 118),
            ("eq", 144),
            ("receiver", 170),
            ("query", 178),
            ("callback", 184),
            ("hash", 195),
            ("eq", 217),
            ("eq", 243),
            ("eq", 269),
            ("committed", 299),
            ("done", 307),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_or_insert_with_nominal_absent_direct",
        steps: 407,
        effects: &[
            ("hash", 22),
            ("hash", 46),
            ("eq", 68),
            ("hash", 96),
            ("eq", 118),
            ("eq", 144),
            ("receiver", 167),
            ("query", 175),
            ("callback", 181),
            ("hash", 188),
            ("eq", 210),
            ("eq", 236),
            ("eq", 262),
            ("factory", 286),
            ("hash", 293),
            ("eq", 315),
            ("eq", 341),
            ("eq", 367),
            ("committed", 397),
            ("done", 405),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_or_insert_with_nominal_absent_generic",
        steps: 418,
        effects: &[
            ("hash", 22),
            ("hash", 46),
            ("eq", 68),
            ("hash", 96),
            ("eq", 118),
            ("eq", 144),
            ("receiver", 168),
            ("query", 176),
            ("callback", 182),
            ("hash", 197),
            ("eq", 219),
            ("eq", 245),
            ("eq", 271),
            ("factory", 295),
            ("hash", 302),
            ("eq", 324),
            ("eq", 350),
            ("eq", 376),
            ("committed", 408),
            ("done", 416),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_or_insert_with_nominal_absent_dynamic",
        steps: 415,
        effects: &[
            ("hash", 22),
            ("hash", 46),
            ("eq", 68),
            ("hash", 96),
            ("eq", 118),
            ("eq", 144),
            ("receiver", 170),
            ("query", 178),
            ("callback", 184),
            ("hash", 195),
            ("eq", 217),
            ("eq", 243),
            ("eq", 269),
            ("factory", 293),
            ("hash", 300),
            ("eq", 322),
            ("eq", 348),
            ("eq", 374),
            ("committed", 405),
            ("done", 413),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_or_insert_with_tuple_empty_direct",
        steps: 129,
        effects: &[
            ("receiver", 23),
            ("query", 33),
            ("callback", 39),
            ("hash", 52),
            ("factory", 76),
            ("hash", 89),
            ("committed", 119),
            ("done", 127),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_or_insert_with_tuple_present_direct",
        steps: 435,
        effects: &[
            ("hash", 34),
            ("hash", 68),
            ("eq", 103),
            ("hash", 142),
            ("eq", 177),
            ("eq", 217),
            ("receiver", 245),
            ("query", 255),
            ("callback", 261),
            ("hash", 274),
            ("eq", 309),
            ("eq", 349),
            ("eq", 389),
            ("committed", 425),
            ("done", 433),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_or_insert_with_tuple_absent_direct",
        steps: 591,
        effects: &[
            ("hash", 34),
            ("hash", 68),
            ("eq", 103),
            ("hash", 142),
            ("eq", 177),
            ("eq", 217),
            ("receiver", 245),
            ("query", 255),
            ("callback", 261),
            ("hash", 274),
            ("eq", 309),
            ("eq", 349),
            ("eq", 389),
            ("factory", 418),
            ("hash", 431),
            ("eq", 466),
            ("eq", 506),
            ("eq", 546),
            ("committed", 581),
            ("done", 589),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_or_insert_with_option_empty_direct",
        steps: 127,
        effects: &[
            ("receiver", 20),
            ("query", 29),
            ("callback", 35),
            ("hash", 48),
            ("factory", 73),
            ("hash", 86),
            ("committed", 117),
            ("done", 125),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_or_insert_with_option_present_direct",
        steps: 445,
        effects: &[
            ("hash", 31),
            ("hash", 66),
            ("eq", 102),
            ("hash", 143),
            ("eq", 179),
            ("eq", 221),
            ("receiver", 251),
            ("query", 260),
            ("callback", 266),
            ("hash", 279),
            ("eq", 315),
            ("eq", 357),
            ("eq", 399),
            ("committed", 435),
            ("done", 443),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_or_insert_with_option_absent_direct",
        steps: 610,
        effects: &[
            ("hash", 31),
            ("hash", 66),
            ("eq", 102),
            ("hash", 143),
            ("eq", 179),
            ("eq", 221),
            ("receiver", 251),
            ("query", 260),
            ("callback", 266),
            ("hash", 279),
            ("eq", 315),
            ("eq", 357),
            ("eq", 399),
            ("factory", 430),
            ("hash", 443),
            ("eq", 479),
            ("eq", 521),
            ("eq", 563),
            ("committed", 600),
            ("done", 608),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_or_insert_with_choice_empty_direct",
        steps: 131,
        effects: &[
            ("receiver", 20),
            ("query", 29),
            ("callback", 35),
            ("hash", 50),
            ("factory", 75),
            ("hash", 90),
            ("committed", 121),
            ("done", 129),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_or_insert_with_choice_present_direct",
        steps: 465,
        effects: &[
            ("hash", 33),
            ("hash", 70),
            ("eq", 108),
            ("hash", 151),
            ("eq", 189),
            ("eq", 233),
            ("receiver", 263),
            ("query", 272),
            ("callback", 278),
            ("hash", 293),
            ("eq", 331),
            ("eq", 375),
            ("eq", 419),
            ("committed", 455),
            ("done", 463),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_or_insert_with_choice_absent_direct",
        steps: 638,
        effects: &[
            ("hash", 33),
            ("hash", 70),
            ("eq", 108),
            ("hash", 151),
            ("eq", 189),
            ("eq", 233),
            ("receiver", 263),
            ("query", 272),
            ("callback", 278),
            ("hash", 293),
            ("eq", 331),
            ("eq", 375),
            ("eq", 419),
            ("factory", 450),
            ("hash", 465),
            ("eq", 503),
            ("eq", 547),
            ("eq", 591),
            ("committed", 628),
            ("done", 636),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_or_insert_with_identity_empty_direct",
        steps: 61,
        effects: &[
            ("receiver", 14),
            ("query", 21),
            ("callback", 27),
            ("factory", 36),
            ("committed", 51),
            ("done", 59),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_or_insert_with_identity_present_direct",
        steps: 74,
        effects: &[
            ("receiver", 32),
            ("query", 40),
            ("callback", 46),
            ("committed", 64),
            ("done", 72),
        ],
        holes: &[],
    },
    Baseline {
        name: "get_or_insert_with_identity_absent_direct",
        steps: 79,
        effects: &[
            ("receiver", 32),
            ("query", 39),
            ("callback", 45),
            ("factory", 54),
            ("committed", 69),
            ("done", 77),
        ],
        holes: &[],
    },
];
