use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "map_insert_scalar_empty_direct",
        steps: 38,
        effects: &[
            ("receiver", 11),
            ("query", 17),
            ("payload", 23),
            ("committed", 28),
            ("done", 36),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_insert_scalar_empty_generic",
        steps: 51,
        effects: &[
            ("receiver", 12),
            ("query", 18),
            ("payload", 24),
            ("committed", 41),
            ("done", 49),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_insert_scalar_empty_dynamic",
        steps: 47,
        effects: &[
            ("receiver", 14),
            ("query", 20),
            ("payload", 26),
            ("committed", 37),
            ("done", 45),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_insert_scalar_present_direct",
        steps: 56,
        effects: &[
            ("receiver", 29),
            ("query", 35),
            ("payload", 41),
            ("committed", 46),
            ("done", 54),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_insert_scalar_present_generic",
        steps: 69,
        effects: &[
            ("receiver", 30),
            ("query", 36),
            ("payload", 42),
            ("committed", 59),
            ("done", 67),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_insert_scalar_present_dynamic",
        steps: 65,
        effects: &[
            ("receiver", 32),
            ("query", 38),
            ("payload", 44),
            ("committed", 55),
            ("done", 63),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_insert_scalar_absent_direct",
        steps: 56,
        effects: &[
            ("receiver", 29),
            ("query", 35),
            ("payload", 41),
            ("committed", 46),
            ("done", 54),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_insert_scalar_absent_generic",
        steps: 69,
        effects: &[
            ("receiver", 30),
            ("query", 36),
            ("payload", 42),
            ("committed", 59),
            ("done", 67),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_insert_scalar_absent_dynamic",
        steps: 65,
        effects: &[
            ("receiver", 32),
            ("query", 38),
            ("payload", 44),
            ("committed", 55),
            ("done", 63),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_insert_nominal_empty_direct",
        steps: 64,
        effects: &[
            ("receiver", 17),
            ("query", 25),
            ("payload", 31),
            ("hash", 37),
            ("committed", 54),
            ("done", 62),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_insert_nominal_empty_generic",
        steps: 77,
        effects: &[
            ("receiver", 18),
            ("query", 26),
            ("payload", 32),
            ("hash", 46),
            ("committed", 67),
            ("done", 75),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_insert_nominal_empty_dynamic",
        steps: 73,
        effects: &[
            ("receiver", 20),
            ("query", 28),
            ("payload", 34),
            ("hash", 44),
            ("committed", 63),
            ("done", 71),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_insert_nominal_present_direct",
        steps: 288,
        effects: &[
            ("hash", 22),
            ("hash", 46),
            ("eq", 68),
            ("hash", 96),
            ("eq", 118),
            ("eq", 144),
            ("receiver", 167),
            ("query", 175),
            ("payload", 181),
            ("hash", 187),
            ("eq", 209),
            ("eq", 235),
            ("eq", 261),
            ("committed", 278),
            ("done", 286),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_insert_nominal_present_generic",
        steps: 301,
        effects: &[
            ("hash", 22),
            ("hash", 46),
            ("eq", 68),
            ("hash", 96),
            ("eq", 118),
            ("eq", 144),
            ("receiver", 168),
            ("query", 176),
            ("payload", 182),
            ("hash", 196),
            ("eq", 218),
            ("eq", 244),
            ("eq", 270),
            ("committed", 291),
            ("done", 299),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_insert_nominal_present_dynamic",
        steps: 297,
        effects: &[
            ("hash", 22),
            ("hash", 46),
            ("eq", 68),
            ("hash", 96),
            ("eq", 118),
            ("eq", 144),
            ("receiver", 170),
            ("query", 178),
            ("payload", 184),
            ("hash", 194),
            ("eq", 216),
            ("eq", 242),
            ("eq", 268),
            ("committed", 287),
            ("done", 295),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_insert_nominal_absent_direct",
        steps: 292,
        effects: &[
            ("hash", 22),
            ("hash", 46),
            ("eq", 68),
            ("hash", 96),
            ("eq", 118),
            ("eq", 144),
            ("receiver", 167),
            ("query", 175),
            ("payload", 181),
            ("hash", 187),
            ("eq", 209),
            ("eq", 235),
            ("eq", 261),
            ("committed", 282),
            ("done", 290),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_insert_nominal_absent_generic",
        steps: 305,
        effects: &[
            ("hash", 22),
            ("hash", 46),
            ("eq", 68),
            ("hash", 96),
            ("eq", 118),
            ("eq", 144),
            ("receiver", 168),
            ("query", 176),
            ("payload", 182),
            ("hash", 196),
            ("eq", 218),
            ("eq", 244),
            ("eq", 270),
            ("committed", 295),
            ("done", 303),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_insert_nominal_absent_dynamic",
        steps: 301,
        effects: &[
            ("hash", 22),
            ("hash", 46),
            ("eq", 68),
            ("hash", 96),
            ("eq", 118),
            ("eq", 144),
            ("receiver", 170),
            ("query", 178),
            ("payload", 184),
            ("hash", 194),
            ("eq", 216),
            ("eq", 242),
            ("eq", 268),
            ("committed", 291),
            ("done", 299),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_insert_tuple_empty_direct",
        steps: 82,
        effects: &[
            ("receiver", 23),
            ("query", 33),
            ("payload", 39),
            ("hash", 51),
            ("committed", 72),
            ("done", 80),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_insert_tuple_present_direct",
        steps: 422,
        effects: &[
            ("hash", 34),
            ("hash", 68),
            ("eq", 103),
            ("hash", 142),
            ("eq", 177),
            ("eq", 217),
            ("receiver", 245),
            ("query", 255),
            ("payload", 261),
            ("hash", 273),
            ("eq", 308),
            ("eq", 348),
            ("eq", 388),
            ("committed", 412),
            ("done", 420),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_insert_tuple_absent_direct",
        steps: 424,
        effects: &[
            ("hash", 34),
            ("hash", 68),
            ("eq", 103),
            ("hash", 142),
            ("eq", 177),
            ("eq", 217),
            ("receiver", 245),
            ("query", 255),
            ("payload", 261),
            ("hash", 273),
            ("eq", 308),
            ("eq", 348),
            ("eq", 388),
            ("committed", 414),
            ("done", 422),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_insert_option_empty_direct",
        steps: 79,
        effects: &[
            ("receiver", 20),
            ("query", 29),
            ("payload", 35),
            ("hash", 47),
            ("committed", 69),
            ("done", 77),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_insert_option_present_direct",
        steps: 432,
        effects: &[
            ("hash", 31),
            ("hash", 66),
            ("eq", 102),
            ("hash", 143),
            ("eq", 179),
            ("eq", 221),
            ("receiver", 251),
            ("query", 260),
            ("payload", 266),
            ("hash", 278),
            ("eq", 314),
            ("eq", 356),
            ("eq", 398),
            ("committed", 422),
            ("done", 430),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_insert_option_absent_direct",
        steps: 436,
        effects: &[
            ("hash", 31),
            ("hash", 66),
            ("eq", 102),
            ("hash", 143),
            ("eq", 179),
            ("eq", 221),
            ("receiver", 251),
            ("query", 260),
            ("payload", 266),
            ("hash", 278),
            ("eq", 314),
            ("eq", 356),
            ("eq", 398),
            ("committed", 426),
            ("done", 434),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_insert_choice_empty_direct",
        steps: 81,
        effects: &[
            ("receiver", 20),
            ("query", 29),
            ("payload", 35),
            ("hash", 49),
            ("committed", 71),
            ("done", 79),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_insert_choice_present_direct",
        steps: 452,
        effects: &[
            ("hash", 33),
            ("hash", 70),
            ("eq", 108),
            ("hash", 151),
            ("eq", 189),
            ("eq", 233),
            ("receiver", 263),
            ("query", 272),
            ("payload", 278),
            ("hash", 292),
            ("eq", 330),
            ("eq", 374),
            ("eq", 418),
            ("committed", 442),
            ("done", 450),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_insert_choice_absent_direct",
        steps: 456,
        effects: &[
            ("hash", 33),
            ("hash", 70),
            ("eq", 108),
            ("hash", 151),
            ("eq", 189),
            ("eq", 233),
            ("receiver", 263),
            ("query", 272),
            ("payload", 278),
            ("hash", 292),
            ("eq", 330),
            ("eq", 374),
            ("eq", 418),
            ("committed", 446),
            ("done", 454),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_insert_identity_empty_direct",
        steps: 42,
        effects: &[
            ("receiver", 14),
            ("query", 21),
            ("payload", 27),
            ("committed", 32),
            ("done", 40),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_insert_identity_present_direct",
        steps: 61,
        effects: &[
            ("receiver", 32),
            ("query", 40),
            ("payload", 46),
            ("committed", 51),
            ("done", 59),
        ],
        holes: &[],
    },
    Baseline {
        name: "map_insert_identity_absent_direct",
        steps: 60,
        effects: &[
            ("receiver", 32),
            ("query", 39),
            ("payload", 45),
            ("committed", 50),
            ("done", 58),
        ],
        holes: &[],
    },
];
