use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "set_insert_scalar_empty_direct",
        steps: 32,
        effects: &[
            ("receiver", 11),
            ("query", 17),
            ("committed", 22),
            ("done", 30),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_insert_scalar_empty_generic",
        steps: 43,
        effects: &[
            ("receiver", 12),
            ("query", 18),
            ("committed", 33),
            ("done", 41),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_insert_scalar_empty_dynamic",
        steps: 40,
        effects: &[
            ("receiver", 14),
            ("query", 20),
            ("committed", 30),
            ("done", 38),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_insert_scalar_present_direct",
        steps: 47,
        effects: &[
            ("receiver", 26),
            ("query", 32),
            ("committed", 37),
            ("done", 45),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_insert_scalar_present_generic",
        steps: 58,
        effects: &[
            ("receiver", 27),
            ("query", 33),
            ("committed", 48),
            ("done", 56),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_insert_scalar_present_dynamic",
        steps: 55,
        effects: &[
            ("receiver", 29),
            ("query", 35),
            ("committed", 45),
            ("done", 53),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_insert_scalar_absent_direct",
        steps: 47,
        effects: &[
            ("receiver", 26),
            ("query", 32),
            ("committed", 37),
            ("done", 45),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_insert_scalar_absent_generic",
        steps: 58,
        effects: &[
            ("receiver", 27),
            ("query", 33),
            ("committed", 48),
            ("done", 56),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_insert_scalar_absent_dynamic",
        steps: 55,
        effects: &[
            ("receiver", 29),
            ("query", 35),
            ("committed", 45),
            ("done", 53),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_insert_nominal_empty_direct",
        steps: 58,
        effects: &[
            ("receiver", 17),
            ("query", 25),
            ("hash", 31),
            ("committed", 48),
            ("done", 56),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_insert_nominal_empty_generic",
        steps: 69,
        effects: &[
            ("receiver", 18),
            ("query", 26),
            ("hash", 38),
            ("committed", 59),
            ("done", 67),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_insert_nominal_empty_dynamic",
        steps: 66,
        effects: &[
            ("receiver", 20),
            ("query", 28),
            ("hash", 37),
            ("committed", 56),
            ("done", 64),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_insert_nominal_present_direct",
        steps: 279,
        effects: &[
            ("hash", 21),
            ("hash", 44),
            ("eq", 66),
            ("hash", 93),
            ("eq", 115),
            ("eq", 141),
            ("receiver", 164),
            ("query", 172),
            ("hash", 178),
            ("eq", 200),
            ("eq", 226),
            ("eq", 252),
            ("committed", 269),
            ("done", 277),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_insert_nominal_present_generic",
        steps: 290,
        effects: &[
            ("hash", 21),
            ("hash", 44),
            ("eq", 66),
            ("hash", 93),
            ("eq", 115),
            ("eq", 141),
            ("receiver", 165),
            ("query", 173),
            ("hash", 185),
            ("eq", 207),
            ("eq", 233),
            ("eq", 259),
            ("committed", 280),
            ("done", 288),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_insert_nominal_present_dynamic",
        steps: 287,
        effects: &[
            ("hash", 21),
            ("hash", 44),
            ("eq", 66),
            ("hash", 93),
            ("eq", 115),
            ("eq", 141),
            ("receiver", 167),
            ("query", 175),
            ("hash", 184),
            ("eq", 206),
            ("eq", 232),
            ("eq", 258),
            ("committed", 277),
            ("done", 285),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_insert_nominal_absent_direct",
        steps: 283,
        effects: &[
            ("hash", 21),
            ("hash", 44),
            ("eq", 66),
            ("hash", 93),
            ("eq", 115),
            ("eq", 141),
            ("receiver", 164),
            ("query", 172),
            ("hash", 178),
            ("eq", 200),
            ("eq", 226),
            ("eq", 252),
            ("committed", 273),
            ("done", 281),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_insert_nominal_absent_generic",
        steps: 294,
        effects: &[
            ("hash", 21),
            ("hash", 44),
            ("eq", 66),
            ("hash", 93),
            ("eq", 115),
            ("eq", 141),
            ("receiver", 165),
            ("query", 173),
            ("hash", 185),
            ("eq", 207),
            ("eq", 233),
            ("eq", 259),
            ("committed", 284),
            ("done", 292),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_insert_nominal_absent_dynamic",
        steps: 291,
        effects: &[
            ("hash", 21),
            ("hash", 44),
            ("eq", 66),
            ("hash", 93),
            ("eq", 115),
            ("eq", 141),
            ("receiver", 167),
            ("query", 175),
            ("hash", 184),
            ("eq", 206),
            ("eq", 232),
            ("eq", 258),
            ("committed", 281),
            ("done", 289),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_insert_tuple_empty_direct",
        steps: 76,
        effects: &[
            ("receiver", 23),
            ("query", 33),
            ("hash", 45),
            ("committed", 66),
            ("done", 74),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_insert_tuple_present_direct",
        steps: 413,
        effects: &[
            ("hash", 33),
            ("hash", 66),
            ("eq", 101),
            ("hash", 139),
            ("eq", 174),
            ("eq", 214),
            ("receiver", 242),
            ("query", 252),
            ("hash", 264),
            ("eq", 299),
            ("eq", 339),
            ("eq", 379),
            ("committed", 403),
            ("done", 411),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_insert_tuple_absent_direct",
        steps: 415,
        effects: &[
            ("hash", 33),
            ("hash", 66),
            ("eq", 101),
            ("hash", 139),
            ("eq", 174),
            ("eq", 214),
            ("receiver", 242),
            ("query", 252),
            ("hash", 264),
            ("eq", 299),
            ("eq", 339),
            ("eq", 379),
            ("committed", 405),
            ("done", 413),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_insert_option_empty_direct",
        steps: 73,
        effects: &[
            ("receiver", 20),
            ("query", 29),
            ("hash", 41),
            ("committed", 63),
            ("done", 71),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_insert_option_present_direct",
        steps: 423,
        effects: &[
            ("hash", 30),
            ("hash", 64),
            ("eq", 100),
            ("hash", 140),
            ("eq", 176),
            ("eq", 218),
            ("receiver", 248),
            ("query", 257),
            ("hash", 269),
            ("eq", 305),
            ("eq", 347),
            ("eq", 389),
            ("committed", 413),
            ("done", 421),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_insert_option_absent_direct",
        steps: 427,
        effects: &[
            ("hash", 30),
            ("hash", 64),
            ("eq", 100),
            ("hash", 140),
            ("eq", 176),
            ("eq", 218),
            ("receiver", 248),
            ("query", 257),
            ("hash", 269),
            ("eq", 305),
            ("eq", 347),
            ("eq", 389),
            ("committed", 417),
            ("done", 425),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_insert_choice_empty_direct",
        steps: 75,
        effects: &[
            ("receiver", 20),
            ("query", 29),
            ("hash", 43),
            ("committed", 65),
            ("done", 73),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_insert_choice_present_direct",
        steps: 443,
        effects: &[
            ("hash", 32),
            ("hash", 68),
            ("eq", 106),
            ("hash", 148),
            ("eq", 186),
            ("eq", 230),
            ("receiver", 260),
            ("query", 269),
            ("hash", 283),
            ("eq", 321),
            ("eq", 365),
            ("eq", 409),
            ("committed", 433),
            ("done", 441),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_insert_choice_absent_direct",
        steps: 447,
        effects: &[
            ("hash", 32),
            ("hash", 68),
            ("eq", 106),
            ("hash", 148),
            ("eq", 186),
            ("eq", 230),
            ("receiver", 260),
            ("query", 269),
            ("hash", 283),
            ("eq", 321),
            ("eq", 365),
            ("eq", 409),
            ("committed", 437),
            ("done", 445),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_insert_identity_empty_direct",
        steps: 36,
        effects: &[
            ("receiver", 14),
            ("query", 21),
            ("committed", 26),
            ("done", 34),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_insert_identity_present_direct",
        steps: 52,
        effects: &[
            ("receiver", 29),
            ("query", 37),
            ("committed", 42),
            ("done", 50),
        ],
        holes: &[],
    },
    Baseline {
        name: "set_insert_identity_absent_direct",
        steps: 51,
        effects: &[
            ("receiver", 29),
            ("query", 36),
            ("committed", 41),
            ("done", 49),
        ],
        holes: &[],
    },
];
