use super::Baseline;
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "update_scalar_empty_direct",
        steps: 57,
        effects: &[
            ("receiver", 11),
            ("query", 17),
            ("callback", 23),
            ("transform", 30),
            ("committed", 47),
            ("done", 55),
        ],
        holes: &[],
    },
    Baseline {
        name: "update_scalar_empty_generic",
        steps: 68,
        effects: &[
            ("receiver", 12),
            ("query", 18),
            ("callback", 24),
            ("transform", 39),
            ("committed", 58),
            ("done", 66),
        ],
        holes: &[],
    },
    Baseline {
        name: "update_scalar_empty_dynamic",
        steps: 65,
        effects: &[
            ("receiver", 14),
            ("query", 20),
            ("callback", 26),
            ("transform", 37),
            ("committed", 55),
            ("done", 63),
        ],
        holes: &[],
    },
    Baseline {
        name: "update_scalar_present_direct",
        steps: 75,
        effects: &[
            ("receiver", 29),
            ("query", 35),
            ("callback", 41),
            ("transform", 48),
            ("committed", 65),
            ("done", 73),
        ],
        holes: &[],
    },
    Baseline {
        name: "update_scalar_present_generic",
        steps: 86,
        effects: &[
            ("receiver", 30),
            ("query", 36),
            ("callback", 42),
            ("transform", 57),
            ("committed", 76),
            ("done", 84),
        ],
        holes: &[],
    },
    Baseline {
        name: "update_scalar_present_dynamic",
        steps: 83,
        effects: &[
            ("receiver", 32),
            ("query", 38),
            ("callback", 44),
            ("transform", 55),
            ("committed", 73),
            ("done", 81),
        ],
        holes: &[],
    },
    Baseline {
        name: "update_scalar_absent_direct",
        steps: 75,
        effects: &[
            ("receiver", 29),
            ("query", 35),
            ("callback", 41),
            ("transform", 48),
            ("committed", 65),
            ("done", 73),
        ],
        holes: &[],
    },
    Baseline {
        name: "update_scalar_absent_generic",
        steps: 86,
        effects: &[
            ("receiver", 30),
            ("query", 36),
            ("callback", 42),
            ("transform", 57),
            ("committed", 76),
            ("done", 84),
        ],
        holes: &[],
    },
    Baseline {
        name: "update_scalar_absent_dynamic",
        steps: 83,
        effects: &[
            ("receiver", 32),
            ("query", 38),
            ("callback", 44),
            ("transform", 55),
            ("committed", 73),
            ("done", 81),
        ],
        holes: &[],
    },
    Baseline {
        name: "update_nominal_empty_direct",
        steps: 101,
        effects: &[
            ("receiver", 17),
            ("query", 25),
            ("callback", 31),
            ("hash", 38),
            ("transform", 56),
            ("hash", 67),
            ("committed", 91),
            ("done", 99),
        ],
        holes: &[],
    },
    Baseline {
        name: "update_nominal_empty_generic",
        steps: 112,
        effects: &[
            ("receiver", 18),
            ("query", 26),
            ("callback", 32),
            ("hash", 47),
            ("transform", 65),
            ("hash", 76),
            ("committed", 102),
            ("done", 110),
        ],
        holes: &[],
    },
    Baseline {
        name: "update_nominal_empty_dynamic",
        steps: 109,
        effects: &[
            ("receiver", 20),
            ("query", 28),
            ("callback", 34),
            ("hash", 45),
            ("transform", 63),
            ("hash", 74),
            ("committed", 99),
            ("done", 107),
        ],
        holes: &[],
    },
    Baseline {
        name: "update_nominal_present_direct",
        steps: 399,
        effects: &[
            ("hash", 22),
            ("hash", 46),
            ("eq", 68),
            ("hash", 96),
            ("eq", 118),
            ("eq", 144),
            ("receiver", 167),
            ("query", 175),
            ("callback", 181),
            ("hash", 188),
            ("eq", 210),
            ("eq", 236),
            ("eq", 262),
            ("transform", 280),
            ("hash", 291),
            ("eq", 313),
            ("eq", 339),
            ("eq", 365),
            ("committed", 389),
            ("done", 397),
        ],
        holes: &[],
    },
    Baseline {
        name: "update_nominal_present_generic",
        steps: 410,
        effects: &[
            ("hash", 22),
            ("hash", 46),
            ("eq", 68),
            ("hash", 96),
            ("eq", 118),
            ("eq", 144),
            ("receiver", 168),
            ("query", 176),
            ("callback", 182),
            ("hash", 197),
            ("eq", 219),
            ("eq", 245),
            ("eq", 271),
            ("transform", 289),
            ("hash", 300),
            ("eq", 322),
            ("eq", 348),
            ("eq", 374),
            ("committed", 400),
            ("done", 408),
        ],
        holes: &[],
    },
    Baseline {
        name: "update_nominal_present_dynamic",
        steps: 407,
        effects: &[
            ("hash", 22),
            ("hash", 46),
            ("eq", 68),
            ("hash", 96),
            ("eq", 118),
            ("eq", 144),
            ("receiver", 170),
            ("query", 178),
            ("callback", 184),
            ("hash", 195),
            ("eq", 217),
            ("eq", 243),
            ("eq", 269),
            ("transform", 287),
            ("hash", 298),
            ("eq", 320),
            ("eq", 346),
            ("eq", 372),
            ("committed", 397),
            ("done", 405),
        ],
        holes: &[],
    },
    Baseline {
        name: "update_nominal_absent_direct",
        steps: 407,
        effects: &[
            ("hash", 22),
            ("hash", 46),
            ("eq", 68),
            ("hash", 96),
            ("eq", 118),
            ("eq", 144),
            ("receiver", 167),
            ("query", 175),
            ("callback", 181),
            ("hash", 188),
            ("eq", 210),
            ("eq", 236),
            ("eq", 262),
            ("transform", 284),
            ("hash", 295),
            ("eq", 317),
            ("eq", 343),
            ("eq", 369),
            ("committed", 397),
            ("done", 405),
        ],
        holes: &[],
    },
    Baseline {
        name: "update_nominal_absent_generic",
        steps: 418,
        effects: &[
            ("hash", 22),
            ("hash", 46),
            ("eq", 68),
            ("hash", 96),
            ("eq", 118),
            ("eq", 144),
            ("receiver", 168),
            ("query", 176),
            ("callback", 182),
            ("hash", 197),
            ("eq", 219),
            ("eq", 245),
            ("eq", 271),
            ("transform", 293),
            ("hash", 304),
            ("eq", 326),
            ("eq", 352),
            ("eq", 378),
            ("committed", 408),
            ("done", 416),
        ],
        holes: &[],
    },
    Baseline {
        name: "update_nominal_absent_dynamic",
        steps: 415,
        effects: &[
            ("hash", 22),
            ("hash", 46),
            ("eq", 68),
            ("hash", 96),
            ("eq", 118),
            ("eq", 144),
            ("receiver", 170),
            ("query", 178),
            ("callback", 184),
            ("hash", 195),
            ("eq", 217),
            ("eq", 243),
            ("eq", 269),
            ("transform", 291),
            ("hash", 302),
            ("eq", 324),
            ("eq", 350),
            ("eq", 376),
            ("committed", 405),
            ("done", 413),
        ],
        holes: &[],
    },
    Baseline {
        name: "update_tuple_empty_direct",
        steps: 129,
        effects: &[
            ("receiver", 23),
            ("query", 33),
            ("callback", 39),
            ("hash", 52),
            ("transform", 74),
            ("hash", 91),
            ("committed", 119),
            ("done", 127),
        ],
        holes: &[],
    },
    Baseline {
        name: "update_tuple_present_direct",
        steps: 587,
        effects: &[
            ("hash", 34),
            ("hash", 68),
            ("eq", 103),
            ("hash", 142),
            ("eq", 177),
            ("eq", 217),
            ("receiver", 245),
            ("query", 255),
            ("callback", 261),
            ("hash", 274),
            ("eq", 309),
            ("eq", 349),
            ("eq", 389),
            ("transform", 414),
            ("hash", 431),
            ("eq", 466),
            ("eq", 506),
            ("eq", 546),
            ("committed", 577),
            ("done", 585),
        ],
        holes: &[],
    },
    Baseline {
        name: "update_tuple_absent_direct",
        steps: 591,
        effects: &[
            ("hash", 34),
            ("hash", 68),
            ("eq", 103),
            ("hash", 142),
            ("eq", 177),
            ("eq", 217),
            ("receiver", 245),
            ("query", 255),
            ("callback", 261),
            ("hash", 274),
            ("eq", 309),
            ("eq", 349),
            ("eq", 389),
            ("transform", 416),
            ("hash", 433),
            ("eq", 468),
            ("eq", 508),
            ("eq", 548),
            ("committed", 581),
            ("done", 589),
        ],
        holes: &[],
    },
    Baseline {
        name: "update_option_empty_direct",
        steps: 127,
        effects: &[
            ("receiver", 20),
            ("query", 29),
            ("callback", 35),
            ("hash", 48),
            ("transform", 71),
            ("hash", 88),
            ("committed", 117),
            ("done", 125),
        ],
        holes: &[],
    },
    Baseline {
        name: "update_option_present_direct",
        steps: 602,
        effects: &[
            ("hash", 31),
            ("hash", 66),
            ("eq", 102),
            ("hash", 143),
            ("eq", 179),
            ("eq", 221),
            ("receiver", 251),
            ("query", 260),
            ("callback", 266),
            ("hash", 279),
            ("eq", 315),
            ("eq", 357),
            ("eq", 399),
            ("transform", 424),
            ("hash", 441),
            ("eq", 477),
            ("eq", 519),
            ("eq", 561),
            ("committed", 592),
            ("done", 600),
        ],
        holes: &[],
    },
    Baseline {
        name: "update_option_absent_direct",
        steps: 610,
        effects: &[
            ("hash", 31),
            ("hash", 66),
            ("eq", 102),
            ("hash", 143),
            ("eq", 179),
            ("eq", 221),
            ("receiver", 251),
            ("query", 260),
            ("callback", 266),
            ("hash", 279),
            ("eq", 315),
            ("eq", 357),
            ("eq", 399),
            ("transform", 428),
            ("hash", 445),
            ("eq", 481),
            ("eq", 523),
            ("eq", 565),
            ("committed", 600),
            ("done", 608),
        ],
        holes: &[],
    },
    Baseline {
        name: "update_choice_empty_direct",
        steps: 131,
        effects: &[
            ("receiver", 20),
            ("query", 29),
            ("callback", 35),
            ("hash", 50),
            ("transform", 73),
            ("hash", 92),
            ("committed", 121),
            ("done", 129),
        ],
        holes: &[],
    },
    Baseline {
        name: "update_choice_present_direct",
        steps: 630,
        effects: &[
            ("hash", 33),
            ("hash", 70),
            ("eq", 108),
            ("hash", 151),
            ("eq", 189),
            ("eq", 233),
            ("receiver", 263),
            ("query", 272),
            ("callback", 278),
            ("hash", 293),
            ("eq", 331),
            ("eq", 375),
            ("eq", 419),
            ("transform", 444),
            ("hash", 463),
            ("eq", 501),
            ("eq", 545),
            ("eq", 589),
            ("committed", 620),
            ("done", 628),
        ],
        holes: &[],
    },
    Baseline {
        name: "update_choice_absent_direct",
        steps: 638,
        effects: &[
            ("hash", 33),
            ("hash", 70),
            ("eq", 108),
            ("hash", 151),
            ("eq", 189),
            ("eq", 233),
            ("receiver", 263),
            ("query", 272),
            ("callback", 278),
            ("hash", 293),
            ("eq", 331),
            ("eq", 375),
            ("eq", 419),
            ("transform", 448),
            ("hash", 467),
            ("eq", 505),
            ("eq", 549),
            ("eq", 593),
            ("committed", 628),
            ("done", 636),
        ],
        holes: &[],
    },
    Baseline {
        name: "update_identity_empty_direct",
        steps: 61,
        effects: &[
            ("receiver", 14),
            ("query", 21),
            ("callback", 27),
            ("transform", 34),
            ("committed", 51),
            ("done", 59),
        ],
        holes: &[],
    },
    Baseline {
        name: "update_identity_present_direct",
        steps: 80,
        effects: &[
            ("receiver", 32),
            ("query", 40),
            ("callback", 46),
            ("transform", 53),
            ("committed", 70),
            ("done", 78),
        ],
        holes: &[],
    },
    Baseline {
        name: "update_identity_absent_direct",
        steps: 79,
        effects: &[
            ("receiver", 32),
            ("query", 39),
            ("callback", 45),
            ("transform", 52),
            ("committed", 69),
            ("done", 77),
        ],
        holes: &[],
    },
];
