// Observed at 9a9dc93 before replacing the List query algorithms.
pub(super) struct Baseline {
    pub name: &'static str,
    pub steps: u64,
    pub effects: &'static [(&'static str, u64)],
}
pub(super) const BASELINE: &[Baseline] = &[
    Baseline {
        name: "array_false_0_first_0",
        steps: 19,
        effects: &[("done", 15)],
    },
    Baseline {
        name: "array_false_0_last_0",
        steps: 31,
        effects: &[("done", 27)],
    },
    Baseline {
        name: "array_false_0_binary_search_-1",
        steps: 36,
        effects: &[("done", 32)],
    },
    Baseline {
        name: "array_false_0_binary_search_0",
        steps: 36,
        effects: &[("done", 32)],
    },
    Baseline {
        name: "array_false_0_binary_search_3",
        steps: 36,
        effects: &[("done", 32)],
    },
    Baseline {
        name: "array_false_0_binary_search_8",
        steps: 36,
        effects: &[("done", 32)],
    },
    Baseline {
        name: "array_false_0_binary_search_9",
        steps: 36,
        effects: &[("done", 32)],
    },
    Baseline {
        name: "array_false_1_first_0",
        steps: 21,
        effects: &[("done", 17)],
    },
    Baseline {
        name: "array_false_1_last_0",
        steps: 34,
        effects: &[("done", 30)],
    },
    Baseline {
        name: "array_false_1_binary_search_-1",
        steps: 52,
        effects: &[("done", 48)],
    },
    Baseline {
        name: "array_false_1_binary_search_0",
        steps: 46,
        effects: &[("done", 42)],
    },
    Baseline {
        name: "array_false_1_binary_search_3",
        steps: 54,
        effects: &[("done", 50)],
    },
    Baseline {
        name: "array_false_1_binary_search_8",
        steps: 54,
        effects: &[("done", 50)],
    },
    Baseline {
        name: "array_false_1_binary_search_9",
        steps: 54,
        effects: &[("done", 50)],
    },
    Baseline {
        name: "array_false_5_first_0",
        steps: 25,
        effects: &[("done", 21)],
    },
    Baseline {
        name: "array_false_5_last_0",
        steps: 38,
        effects: &[("done", 34)],
    },
    Baseline {
        name: "array_false_5_binary_search_-1",
        steps: 86,
        effects: &[("done", 82)],
    },
    Baseline {
        name: "array_false_5_binary_search_0",
        steps: 80,
        effects: &[("done", 76)],
    },
    Baseline {
        name: "array_false_5_binary_search_3",
        steps: 73,
        effects: &[("done", 69)],
    },
    Baseline {
        name: "array_false_5_binary_search_8",
        steps: 67,
        effects: &[("done", 63)],
    },
    Baseline {
        name: "array_false_5_binary_search_9",
        steps: 75,
        effects: &[("done", 71)],
    },
    Baseline {
        name: "array_true_0_binary_search_-1",
        steps: 37,
        effects: &[("done", 33)],
    },
    Baseline {
        name: "array_true_0_binary_search_0",
        steps: 37,
        effects: &[("done", 33)],
    },
    Baseline {
        name: "array_true_0_binary_search_3",
        steps: 37,
        effects: &[("done", 33)],
    },
    Baseline {
        name: "array_true_0_binary_search_8",
        steps: 37,
        effects: &[("done", 33)],
    },
    Baseline {
        name: "array_true_0_binary_search_9",
        steps: 37,
        effects: &[("done", 33)],
    },
    Baseline {
        name: "array_true_1_binary_search_-1",
        steps: 62,
        effects: &[("cmp", 30), ("done", 58)],
    },
    Baseline {
        name: "array_true_1_binary_search_0",
        steps: 56,
        effects: &[("cmp", 30), ("done", 52)],
    },
    Baseline {
        name: "array_true_1_binary_search_3",
        steps: 64,
        effects: &[("cmp", 30), ("done", 60)],
    },
    Baseline {
        name: "array_true_1_binary_search_8",
        steps: 64,
        effects: &[("cmp", 30), ("done", 60)],
    },
    Baseline {
        name: "array_true_1_binary_search_9",
        steps: 64,
        effects: &[("cmp", 30), ("done", 60)],
    },
    Baseline {
        name: "array_true_5_binary_search_-1",
        steps: 116,
        effects: &[("cmp", 38), ("cmp", 61), ("cmp", 84), ("done", 112)],
    },
    Baseline {
        name: "array_true_5_binary_search_0",
        steps: 110,
        effects: &[("cmp", 38), ("cmp", 61), ("cmp", 84), ("done", 106)],
    },
    Baseline {
        name: "array_true_5_binary_search_3",
        steps: 95,
        effects: &[("cmp", 38), ("cmp", 61), ("done", 91)],
    },
    Baseline {
        name: "array_true_5_binary_search_8",
        steps: 89,
        effects: &[("cmp", 38), ("cmp", 63), ("done", 85)],
    },
    Baseline {
        name: "array_true_5_binary_search_9",
        steps: 97,
        effects: &[("cmp", 38), ("cmp", 63), ("done", 93)],
    },
    Baseline {
        name: "custom_false_0_first_0",
        steps: 27,
        effects: &[("get", 10), ("done", 23)],
    },
    Baseline {
        name: "custom_false_0_last_0",
        steps: 44,
        effects: &[("iter", 10), ("len", 20), ("done", 40)],
    },
    Baseline {
        name: "custom_false_0_binary_search_-1",
        steps: 49,
        effects: &[("iter", 11), ("len", 21), ("done", 45)],
    },
    Baseline {
        name: "custom_false_0_binary_search_0",
        steps: 49,
        effects: &[("iter", 11), ("len", 21), ("done", 45)],
    },
    Baseline {
        name: "custom_false_0_binary_search_3",
        steps: 49,
        effects: &[("iter", 11), ("len", 21), ("done", 45)],
    },
    Baseline {
        name: "custom_false_0_binary_search_8",
        steps: 49,
        effects: &[("iter", 11), ("len", 21), ("done", 45)],
    },
    Baseline {
        name: "custom_false_0_binary_search_9",
        steps: 49,
        effects: &[("iter", 11), ("len", 21), ("done", 45)],
    },
    Baseline {
        name: "custom_false_1_first_0",
        steps: 29,
        effects: &[("get", 11), ("done", 25)],
    },
    Baseline {
        name: "custom_false_1_last_0",
        steps: 54,
        effects: &[("iter", 11), ("len", 21), ("get", 32), ("done", 50)],
    },
    Baseline {
        name: "custom_false_1_binary_search_-1",
        steps: 72,
        effects: &[("iter", 12), ("len", 22), ("get", 39), ("done", 68)],
    },
    Baseline {
        name: "custom_false_1_binary_search_0",
        steps: 66,
        effects: &[("iter", 12), ("len", 22), ("get", 39), ("done", 62)],
    },
    Baseline {
        name: "custom_false_1_binary_search_3",
        steps: 74,
        effects: &[("iter", 12), ("len", 22), ("get", 39), ("done", 70)],
    },
    Baseline {
        name: "custom_false_1_binary_search_8",
        steps: 74,
        effects: &[("iter", 12), ("len", 22), ("get", 39), ("done", 70)],
    },
    Baseline {
        name: "custom_false_1_binary_search_9",
        steps: 74,
        effects: &[("iter", 12), ("len", 22), ("get", 39), ("done", 70)],
    },
    Baseline {
        name: "custom_false_5_first_0",
        steps: 33,
        effects: &[("get", 15), ("done", 29)],
    },
    Baseline {
        name: "custom_false_5_last_0",
        steps: 58,
        effects: &[("iter", 15), ("len", 25), ("get", 36), ("done", 54)],
    },
    Baseline {
        name: "custom_false_5_binary_search_-1",
        steps: 120,
        effects: &[
            ("iter", 16),
            ("len", 26),
            ("get", 43),
            ("get", 65),
            ("get", 87),
            ("done", 116),
        ],
    },
    Baseline {
        name: "custom_false_5_binary_search_0",
        steps: 114,
        effects: &[
            ("iter", 16),
            ("len", 26),
            ("get", 43),
            ("get", 65),
            ("get", 87),
            ("done", 110),
        ],
    },
    Baseline {
        name: "custom_false_5_binary_search_3",
        steps: 100,
        effects: &[
            ("iter", 16),
            ("len", 26),
            ("get", 43),
            ("get", 65),
            ("done", 96),
        ],
    },
    Baseline {
        name: "custom_false_5_binary_search_8",
        steps: 94,
        effects: &[
            ("iter", 16),
            ("len", 26),
            ("get", 43),
            ("get", 67),
            ("done", 90),
        ],
    },
    Baseline {
        name: "custom_false_5_binary_search_9",
        steps: 102,
        effects: &[
            ("iter", 16),
            ("len", 26),
            ("get", 43),
            ("get", 67),
            ("done", 98),
        ],
    },
    Baseline {
        name: "custom_true_0_binary_search_-1",
        steps: 50,
        effects: &[("iter", 12), ("len", 22), ("done", 46)],
    },
    Baseline {
        name: "custom_true_0_binary_search_0",
        steps: 50,
        effects: &[("iter", 12), ("len", 22), ("done", 46)],
    },
    Baseline {
        name: "custom_true_0_binary_search_3",
        steps: 50,
        effects: &[("iter", 12), ("len", 22), ("done", 46)],
    },
    Baseline {
        name: "custom_true_0_binary_search_8",
        steps: 50,
        effects: &[("iter", 12), ("len", 22), ("done", 46)],
    },
    Baseline {
        name: "custom_true_0_binary_search_9",
        steps: 50,
        effects: &[("iter", 12), ("len", 22), ("done", 46)],
    },
    Baseline {
        name: "custom_true_1_binary_search_-1",
        steps: 82,
        effects: &[
            ("iter", 14),
            ("len", 24),
            ("get", 41),
            ("cmp", 50),
            ("done", 78),
        ],
    },
    Baseline {
        name: "custom_true_1_binary_search_0",
        steps: 76,
        effects: &[
            ("iter", 14),
            ("len", 24),
            ("get", 41),
            ("cmp", 50),
            ("done", 72),
        ],
    },
    Baseline {
        name: "custom_true_1_binary_search_3",
        steps: 84,
        effects: &[
            ("iter", 14),
            ("len", 24),
            ("get", 41),
            ("cmp", 50),
            ("done", 80),
        ],
    },
    Baseline {
        name: "custom_true_1_binary_search_8",
        steps: 84,
        effects: &[
            ("iter", 14),
            ("len", 24),
            ("get", 41),
            ("cmp", 50),
            ("done", 80),
        ],
    },
    Baseline {
        name: "custom_true_1_binary_search_9",
        steps: 84,
        effects: &[
            ("iter", 14),
            ("len", 24),
            ("get", 41),
            ("cmp", 50),
            ("done", 80),
        ],
    },
    Baseline {
        name: "custom_true_5_binary_search_-1",
        steps: 150,
        effects: &[
            ("iter", 22),
            ("len", 32),
            ("get", 49),
            ("cmp", 58),
            ("get", 79),
            ("cmp", 88),
            ("get", 109),
            ("cmp", 118),
            ("done", 146),
        ],
    },
    Baseline {
        name: "custom_true_5_binary_search_0",
        steps: 144,
        effects: &[
            ("iter", 22),
            ("len", 32),
            ("get", 49),
            ("cmp", 58),
            ("get", 79),
            ("cmp", 88),
            ("get", 109),
            ("cmp", 118),
            ("done", 140),
        ],
    },
    Baseline {
        name: "custom_true_5_binary_search_3",
        steps: 122,
        effects: &[
            ("iter", 22),
            ("len", 32),
            ("get", 49),
            ("cmp", 58),
            ("get", 79),
            ("cmp", 88),
            ("done", 118),
        ],
    },
    Baseline {
        name: "custom_true_5_binary_search_8",
        steps: 116,
        effects: &[
            ("iter", 22),
            ("len", 32),
            ("get", 49),
            ("cmp", 58),
            ("get", 81),
            ("cmp", 90),
            ("done", 112),
        ],
    },
    Baseline {
        name: "custom_true_5_binary_search_9",
        steps: 124,
        effects: &[
            ("iter", 22),
            ("len", 32),
            ("get", 49),
            ("cmp", 58),
            ("get", 81),
            ("cmp", 90),
            ("done", 120),
        ],
    },
    Baseline {
        name: "dynamic_false_0_first_0",
        steps: 28,
        effects: &[("get", 11), ("done", 24)],
    },
    Baseline {
        name: "dynamic_false_0_last_0",
        steps: 45,
        effects: &[("iter", 11), ("len", 21), ("done", 41)],
    },
    Baseline {
        name: "dynamic_false_0_binary_search_-1",
        steps: 50,
        effects: &[("iter", 12), ("len", 22), ("done", 46)],
    },
    Baseline {
        name: "dynamic_false_0_binary_search_0",
        steps: 50,
        effects: &[("iter", 12), ("len", 22), ("done", 46)],
    },
    Baseline {
        name: "dynamic_false_0_binary_search_3",
        steps: 50,
        effects: &[("iter", 12), ("len", 22), ("done", 46)],
    },
    Baseline {
        name: "dynamic_false_0_binary_search_8",
        steps: 50,
        effects: &[("iter", 12), ("len", 22), ("done", 46)],
    },
    Baseline {
        name: "dynamic_false_0_binary_search_9",
        steps: 50,
        effects: &[("iter", 12), ("len", 22), ("done", 46)],
    },
    Baseline {
        name: "dynamic_false_1_first_0",
        steps: 30,
        effects: &[("get", 12), ("done", 26)],
    },
    Baseline {
        name: "dynamic_false_1_last_0",
        steps: 55,
        effects: &[("iter", 12), ("len", 22), ("get", 33), ("done", 51)],
    },
    Baseline {
        name: "dynamic_false_1_binary_search_-1",
        steps: 73,
        effects: &[("iter", 13), ("len", 23), ("get", 40), ("done", 69)],
    },
    Baseline {
        name: "dynamic_false_1_binary_search_0",
        steps: 67,
        effects: &[("iter", 13), ("len", 23), ("get", 40), ("done", 63)],
    },
    Baseline {
        name: "dynamic_false_1_binary_search_3",
        steps: 75,
        effects: &[("iter", 13), ("len", 23), ("get", 40), ("done", 71)],
    },
    Baseline {
        name: "dynamic_false_1_binary_search_8",
        steps: 75,
        effects: &[("iter", 13), ("len", 23), ("get", 40), ("done", 71)],
    },
    Baseline {
        name: "dynamic_false_1_binary_search_9",
        steps: 75,
        effects: &[("iter", 13), ("len", 23), ("get", 40), ("done", 71)],
    },
    Baseline {
        name: "dynamic_false_5_first_0",
        steps: 34,
        effects: &[("get", 16), ("done", 30)],
    },
    Baseline {
        name: "dynamic_false_5_last_0",
        steps: 59,
        effects: &[("iter", 16), ("len", 26), ("get", 37), ("done", 55)],
    },
    Baseline {
        name: "dynamic_false_5_binary_search_-1",
        steps: 121,
        effects: &[
            ("iter", 17),
            ("len", 27),
            ("get", 44),
            ("get", 66),
            ("get", 88),
            ("done", 117),
        ],
    },
    Baseline {
        name: "dynamic_false_5_binary_search_0",
        steps: 115,
        effects: &[
            ("iter", 17),
            ("len", 27),
            ("get", 44),
            ("get", 66),
            ("get", 88),
            ("done", 111),
        ],
    },
    Baseline {
        name: "dynamic_false_5_binary_search_3",
        steps: 101,
        effects: &[
            ("iter", 17),
            ("len", 27),
            ("get", 44),
            ("get", 66),
            ("done", 97),
        ],
    },
    Baseline {
        name: "dynamic_false_5_binary_search_8",
        steps: 95,
        effects: &[
            ("iter", 17),
            ("len", 27),
            ("get", 44),
            ("get", 68),
            ("done", 91),
        ],
    },
    Baseline {
        name: "dynamic_false_5_binary_search_9",
        steps: 103,
        effects: &[
            ("iter", 17),
            ("len", 27),
            ("get", 44),
            ("get", 68),
            ("done", 99),
        ],
    },
    Baseline {
        name: "dynamic_true_0_binary_search_-1",
        steps: 51,
        effects: &[("iter", 13), ("len", 23), ("done", 47)],
    },
    Baseline {
        name: "dynamic_true_0_binary_search_0",
        steps: 51,
        effects: &[("iter", 13), ("len", 23), ("done", 47)],
    },
    Baseline {
        name: "dynamic_true_0_binary_search_3",
        steps: 51,
        effects: &[("iter", 13), ("len", 23), ("done", 47)],
    },
    Baseline {
        name: "dynamic_true_0_binary_search_8",
        steps: 51,
        effects: &[("iter", 13), ("len", 23), ("done", 47)],
    },
    Baseline {
        name: "dynamic_true_0_binary_search_9",
        steps: 51,
        effects: &[("iter", 13), ("len", 23), ("done", 47)],
    },
    Baseline {
        name: "dynamic_true_1_binary_search_-1",
        steps: 83,
        effects: &[
            ("iter", 15),
            ("len", 25),
            ("get", 42),
            ("cmp", 51),
            ("done", 79),
        ],
    },
    Baseline {
        name: "dynamic_true_1_binary_search_0",
        steps: 77,
        effects: &[
            ("iter", 15),
            ("len", 25),
            ("get", 42),
            ("cmp", 51),
            ("done", 73),
        ],
    },
    Baseline {
        name: "dynamic_true_1_binary_search_3",
        steps: 85,
        effects: &[
            ("iter", 15),
            ("len", 25),
            ("get", 42),
            ("cmp", 51),
            ("done", 81),
        ],
    },
    Baseline {
        name: "dynamic_true_1_binary_search_8",
        steps: 85,
        effects: &[
            ("iter", 15),
            ("len", 25),
            ("get", 42),
            ("cmp", 51),
            ("done", 81),
        ],
    },
    Baseline {
        name: "dynamic_true_1_binary_search_9",
        steps: 85,
        effects: &[
            ("iter", 15),
            ("len", 25),
            ("get", 42),
            ("cmp", 51),
            ("done", 81),
        ],
    },
    Baseline {
        name: "dynamic_true_5_binary_search_-1",
        steps: 151,
        effects: &[
            ("iter", 23),
            ("len", 33),
            ("get", 50),
            ("cmp", 59),
            ("get", 80),
            ("cmp", 89),
            ("get", 110),
            ("cmp", 119),
            ("done", 147),
        ],
    },
    Baseline {
        name: "dynamic_true_5_binary_search_0",
        steps: 145,
        effects: &[
            ("iter", 23),
            ("len", 33),
            ("get", 50),
            ("cmp", 59),
            ("get", 80),
            ("cmp", 89),
            ("get", 110),
            ("cmp", 119),
            ("done", 141),
        ],
    },
    Baseline {
        name: "dynamic_true_5_binary_search_3",
        steps: 123,
        effects: &[
            ("iter", 23),
            ("len", 33),
            ("get", 50),
            ("cmp", 59),
            ("get", 80),
            ("cmp", 89),
            ("done", 119),
        ],
    },
    Baseline {
        name: "dynamic_true_5_binary_search_8",
        steps: 117,
        effects: &[
            ("iter", 23),
            ("len", 33),
            ("get", 50),
            ("cmp", 59),
            ("get", 82),
            ("cmp", 91),
            ("done", 113),
        ],
    },
    Baseline {
        name: "dynamic_true_5_binary_search_9",
        steps: 125,
        effects: &[
            ("iter", 23),
            ("len", 33),
            ("get", 50),
            ("cmp", 59),
            ("get", 82),
            ("cmp", 91),
            ("done", 121),
        ],
    },
    Baseline {
        name: "view_false_0_first_0",
        steps: 24,
        effects: &[("done", 20)],
    },
    Baseline {
        name: "view_false_0_last_0",
        steps: 38,
        effects: &[("done", 34)],
    },
    Baseline {
        name: "view_false_0_binary_search_-1",
        steps: 43,
        effects: &[("done", 39)],
    },
    Baseline {
        name: "view_false_0_binary_search_0",
        steps: 43,
        effects: &[("done", 39)],
    },
    Baseline {
        name: "view_false_0_binary_search_3",
        steps: 43,
        effects: &[("done", 39)],
    },
    Baseline {
        name: "view_false_0_binary_search_8",
        steps: 43,
        effects: &[("done", 39)],
    },
    Baseline {
        name: "view_false_0_binary_search_9",
        steps: 43,
        effects: &[("done", 39)],
    },
    Baseline {
        name: "view_false_1_first_0",
        steps: 26,
        effects: &[("done", 22)],
    },
    Baseline {
        name: "view_false_1_last_0",
        steps: 45,
        effects: &[("done", 41)],
    },
    Baseline {
        name: "view_false_1_binary_search_-1",
        steps: 63,
        effects: &[("done", 59)],
    },
    Baseline {
        name: "view_false_1_binary_search_0",
        steps: 57,
        effects: &[("done", 53)],
    },
    Baseline {
        name: "view_false_1_binary_search_3",
        steps: 65,
        effects: &[("done", 61)],
    },
    Baseline {
        name: "view_false_1_binary_search_8",
        steps: 65,
        effects: &[("done", 61)],
    },
    Baseline {
        name: "view_false_1_binary_search_9",
        steps: 65,
        effects: &[("done", 61)],
    },
    Baseline {
        name: "view_false_5_first_0",
        steps: 30,
        effects: &[("done", 26)],
    },
    Baseline {
        name: "view_false_5_last_0",
        steps: 49,
        effects: &[("done", 45)],
    },
    Baseline {
        name: "view_false_5_binary_search_-1",
        steps: 105,
        effects: &[("done", 101)],
    },
    Baseline {
        name: "view_false_5_binary_search_0",
        steps: 99,
        effects: &[("done", 95)],
    },
    Baseline {
        name: "view_false_5_binary_search_3",
        steps: 88,
        effects: &[("done", 84)],
    },
    Baseline {
        name: "view_false_5_binary_search_8",
        steps: 82,
        effects: &[("done", 78)],
    },
    Baseline {
        name: "view_false_5_binary_search_9",
        steps: 90,
        effects: &[("done", 86)],
    },
    Baseline {
        name: "view_true_0_binary_search_-1",
        steps: 44,
        effects: &[("done", 40)],
    },
    Baseline {
        name: "view_true_0_binary_search_0",
        steps: 44,
        effects: &[("done", 40)],
    },
    Baseline {
        name: "view_true_0_binary_search_3",
        steps: 44,
        effects: &[("done", 40)],
    },
    Baseline {
        name: "view_true_0_binary_search_8",
        steps: 44,
        effects: &[("done", 40)],
    },
    Baseline {
        name: "view_true_0_binary_search_9",
        steps: 44,
        effects: &[("done", 40)],
    },
    Baseline {
        name: "view_true_1_binary_search_-1",
        steps: 73,
        effects: &[("cmp", 41), ("done", 69)],
    },
    Baseline {
        name: "view_true_1_binary_search_0",
        steps: 67,
        effects: &[("cmp", 41), ("done", 63)],
    },
    Baseline {
        name: "view_true_1_binary_search_3",
        steps: 75,
        effects: &[("cmp", 41), ("done", 71)],
    },
    Baseline {
        name: "view_true_1_binary_search_8",
        steps: 75,
        effects: &[("cmp", 41), ("done", 71)],
    },
    Baseline {
        name: "view_true_1_binary_search_9",
        steps: 75,
        effects: &[("cmp", 41), ("done", 71)],
    },
    Baseline {
        name: "view_true_5_binary_search_-1",
        steps: 135,
        effects: &[("cmp", 49), ("cmp", 76), ("cmp", 103), ("done", 131)],
    },
    Baseline {
        name: "view_true_5_binary_search_0",
        steps: 129,
        effects: &[("cmp", 49), ("cmp", 76), ("cmp", 103), ("done", 125)],
    },
    Baseline {
        name: "view_true_5_binary_search_3",
        steps: 110,
        effects: &[("cmp", 49), ("cmp", 76), ("done", 106)],
    },
    Baseline {
        name: "view_true_5_binary_search_8",
        steps: 104,
        effects: &[("cmp", 49), ("cmp", 78), ("done", 100)],
    },
    Baseline {
        name: "view_true_5_binary_search_9",
        steps: 112,
        effects: &[("cmp", 49), ("cmp", 78), ("done", 108)],
    },
];
